### ISSUE TITLE
Invalid requirement

### ISSUE THREAD

**Issue by YakuzaSuske** [d8ahazard/sd_dreambooth_extension#1]
stdout: Installing requirements for Dreambooth

stderr: Traceback (most recent call last):
  File "C:\SUPER SD 2.0\stable-diffusion-webui-master\extensions\sd_dreambooth_extension-main\install.py", line 4, in <module>
    run_pip(f"install -r {reqs}", "requirements for Dreambooth")
  File "C:\SUPER SD 2.0\stable-diffusion-webui-master\launch.py", line 63, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "C:\SUPER SD 2.0\stable-diffusion-webui-master\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Dreambooth.
Command: "C:\SUPER SD 2.0\stable-diffusion-webui-master\venv\Scripts\python.exe" -m pip install -r C:\SUPER SD 2.0\stable-diffusion-webui-master\extensions\sd_dreambooth_extension-main\requirements.txt --prefer-binary
Error code: 1
stdout: <empty>
stderr: ERROR: Invalid requirement: '2.0\\stable-diffusion-webui-master\\extensions\\sd_dreambooth_extension-main\\requirements.txt'
Hint: It looks like a path. File '2.0\stable-diffusion-webui-master\extensions\sd_dreambooth_extension-main\requirements.txt' does not exist.

**Comment by d8ahazard** [comment]
I mean, the requirements file definitely exists and works, else this issue thread would be flooded with similar complaints.

As such, I'm guessing the issue is that you have spaces in the path, which generally makes Python angry. I'd try renaming "SUPER SD 2.0" to "SUPER_SD_2.0" and see how that works for you. I'll also make a not to see if I can't sanitize the path in this instance. 

Otherwise, you maybe cloned the repo wrong or something?

**Comment by YakuzaSuske** [comment]
> I mean, the requirements file definitely exists and works, else this issue thread would be flooded with similar complaints.
> 
> As such, I'm guessing the issue is that you have spaces in the path, which generally makes Python angry. I'd try renaming "SUPER SD 2.0" to "SUPER_SD_2.0" and see how that works for you. I'll also make a not to see if I can't sanitize the path in this instance.
> 
> Otherwise, you maybe cloned the repo wrong or something?

Yup renaming it fixed it.
