### ISSUE TITLE
TypeError: start_training() takes 38 positional arguments but 40 were given

### ISSUE THREAD

**Issue by Rartist** [d8ahazard/sd_dreambooth_extension#100]
`File "#\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "#\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
TypeError: start_training() takes 38 positional arguments but 40 were given`

Alright... I could bet the Error I got a few hours ago (after Updating) was the same Error with "takes 36 but 38 were given"...
thanks for Updating so fast, but looks like it wasn't solved but rather "pushed further" or something.

**Comment by d8ahazard** [comment]
Please use the issue template.  This is almost certainly related to an old version of the UI being used.

**Comment by CrazyBoyM** [comment]
Just stop the webui and restart it, everything will be fine.
