### ISSUE TITLE
merged checkpoint works but lora weights does not work with kohya-ss sd-webui-additional-networks

### ISSUE THREAD

**Issue by harrywang** [d8ahazard/sd_dreambooth_extension#1020]
I trained a model - training completed successfully. The merged model works (shows beckham):
<img width="2551" alt="Screenshot 2023-03-05 at 8 33 25 AM" src="https://user-images.githubusercontent.com/595772/222963868-8dd260e7-e166-47b0-8367-892465a87ea1.png">

however, when I use the generated Lora weights using https://github.com/kohya-ss/sd-webui-additional-networks, it has no effect:
<img width="2552" alt="Screenshot 2023-03-05 at 8 34 03 AM" src="https://user-images.githubusercontent.com/595772/222963982-dfa49fc5-5a29-409f-a696-ddbe2605ac31.png">

I used another Lora weights I got from Civitai.com and it works - to confirm the extension is working.

The files are:

<img width="259" alt="Screenshot 2023-03-05 at 9 01 07 AM" src="https://user-images.githubusercontent.com/595772/222965057-bc194776-1eb9-46ea-be7c-a0eba3553320.png">

I found the following error in the log:
```
Loading weights [1a189f0be6] from /home/hjwang/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.safetensors
Creating model from config: /home/hjwang/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Model loaded in 1.2s (create model: 0.4s, apply weights to model: 0.3s, apply half(): 0.2s, move model to device: 0.3s).
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7ff3fc4817f0>]: TypeError
Traceback (most recent call last):
  File "/home/hjwang/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/home/hjwang/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/home/hjwang/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 151, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/home/hjwang/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 83, in load_lora
    sd = sd_models.read_state_dict(filename)
  File "/home/hjwang/stable-diffusion-webui/modules/sd_models.py", line 224, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "/home/hjwang/stable-diffusion-webui/modules/sd_models.py", line 197, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
TypeError: pop expected at most 1 argument, got 2
```
I guess this is the cause but don't know why - Can anyone help? What did I miss?

BTW, I found the following two closed related issues: 

https://github.com/d8ahazard/sd_dreambooth_extension/issues/695
https://github.com/d8ahazard/sd_dreambooth_extension/issues/723

**Comment by harrywang** [comment]
I found the following error in the log:
```
Loading weights [1a189f0be6] from /home/hjwang/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.safetensors
Creating model from config: /home/hjwang/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Model loaded in 1.2s (create model: 0.4s, apply weights to model: 0.3s, apply half(): 0.2s, move model to device: 0.3s).
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7ff3fc4817f0>]: TypeError
Traceback (most recent call last):
  File "/home/hjwang/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/home/hjwang/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/home/hjwang/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 151, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/home/hjwang/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 83, in load_lora
    sd = sd_models.read_state_dict(filename)
  File "/home/hjwang/stable-diffusion-webui/modules/sd_models.py", line 224, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "/home/hjwang/stable-diffusion-webui/modules/sd_models.py", line 197, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
TypeError: pop expected at most 1 argument, got 2
```
I guess this is the cause but don't know why - hope someone can help.

**Comment by gammagoat** [comment]
The additional networks feature in a1111 was written by for kohya_ss model format. The main of this model uses the cloneofsimo implementation for LoRA and is not compatible. There is an option in dev to also have additional networks Loras for the non-extended version if you want to give it a try

**Comment by ArrowM** [comment]
Also that non-extended version should get merged to main sometime today or tomorrow

**Comment by harrywang** [comment]
> The additional networks feature in a1111 was written by for kohya_ss model format. The main of this model uses the cloneofsimo implementation for LoRA and is not compatible. There is an option in dev to also have additional networks Loras for the non-extended version if you want to give it a try

Thanks!

**Comment by harrywang** [comment]
@gammagoat @ArrowM I see a PR merge https://github.com/d8ahazard/sd_dreambooth_extension/pull/1014 did this merge "additional networks Loras for the non-extended version"? how to use/enable this? Any pointer? Thanks a lot!

**Comment by harrywang** [comment]
I pulled from dev and don't know which saving option will make lora compatible with https://github.com/kohya-ss/sd-webui-additional-networks
<img width="835" alt="Screenshot 2023-03-06 at 10 01 45 AM" src="https://user-images.githubusercontent.com/595772/223148239-9c51ad8c-de32-42c4-a385-8bcffe9853ba.png">

**Comment by harrywang** [comment]
> Generate Lora weights for extra networks will save a file in the model/lora directory that will work (as long as you don't use extended Lora). I recommend deleting or moving all the old incompatible .pt files out of there.

awesome - will try and report back! Thanks!!

**Comment by harrywang** [comment]
@gammagoat I trained again and the new lora weights work perfectly!! Thanks!
<img width="1875" alt="Screenshot 2023-03-06 at 10 52 48 AM" src="https://user-images.githubusercontent.com/595772/223161860-ab0d1fd0-8c87-472f-a712-6c1c90f202c6.png">
