### ISSUE TITLE
CPU training trying to connect to huggingface

### ISSUE THREAD

**Issue by kokakin** [d8ahazard/sd_dreambooth_extension#103]
**Have you read the Readme?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes, not the problem.

**Have you updated Dreambooth to the latest revision?**
Just did that

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is 4d9b93d439c58c85c0949632650c3bf775fbcac2
[!] Not using xformers memory efficient attention.
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

**Describe the bug**
When training with CPU, in the end or when an image or checkpoint is generated, the following error occurs:

**Provide logs**
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Scheduler Loaded
 Allocated: 0.0GB
 Reserved: 0.0GB

Steps: 100%|███████████████████████████████████████████████████████| 2/2 [01:59<00:00, 62.05s/it, loss=0.0215, lr=5e-6] Exception while training: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like C:\stable-diffusion-webui\models\dreambooth\banana\working is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
 Allocated: 0.0GB
 Reserved: 0.0GB

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 601, in _get_config_dict
    resolved_config_file = cached_path(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 300, in cached_path
    raise ValueError(f"unable to parse {url_or_filename} as a URL or as a local path")
ValueError: unable to parse C:\stable-diffusion-webui\models\dreambooth\gabi\working\config.json as a URL or as a local path

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 954, in main
    save_weights(lifetime_step, save_model, save_img)
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 810, in save_weights
    text_enc_model = CLIPTextModel.from_pretrained(args.working_dir, subfolder="text_encoder")
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 1764, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\configuration_clip.py", line 126, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 553, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 634, in _get_config_dict
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like C:\stable-diffusion-webui\models\dreambooth\gabi\working is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
 CLEANUP:
 Allocated: 0.0GB
 Reserved: 0.0GB

 Cleanup Complete.
 Allocated: 0.0GB
 Reserved: 0.0GB

Steps: 100%|███████████████████████████████████████████████████████| 2/2 [02:00<00:00, 60.13s/it, loss=0.0215, lr=5e-6]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Training completed, reloading SD Model.': '0.0/0.0GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 5

**Environment**
Windows 11, native, using a GTX1050ti 4GB, trying to run training on a i7 7th gen processor

Thanks a lot for this project, I hope I can get past this error!
I'm sorry if I missed anything concerning the bug report, I'm available to run tests

**Comment by d8ahazard** [comment]
This is a weird one. I just pushed a commit to make it so it doesn't try to use the subfolder param, please update and let me know if this addresses it.

**Comment by d8ahazard** [comment]
65a4bdf

**Comment by kokakin** [comment]
I did it, it didn't throw the error, it threw a CUDA out of memory error, I guess this specific issue is closed then. Thank you very much!
But help me understand this, shouldn't the processor do all the training, why is it trying to allocate CUDA memory? I'm a complete noob sorry
