### ISSUE TITLE
run train error

### ISSUE THREAD

**Issue by assassinLL** [d8ahazard/sd_dreambooth_extension#1032]
```st
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Pre-processing images: dest_data_db: : 0it [00:00, ?it/s]                                                          We need a total of 270 class images.
Pre-processing images: dest_data_db: : 0it [00:00, ?it/s]
Generating 270 class images for training...
Generating class images 0/270::   0%|                                                      | 0/270 [00:00<?, ?it/s]Source checkpoint: /home/Text2Image/web-ui/stable-diffusion-webui/models/Stable-diffusion/sd-v2-1_768-ema-pruned.ckpt
Model info: /home/Text2Image/web-ui/stable-diffusion-webui/models/Stable-diffusion/sd-v2-1_768-ema-pruned.ckpt
Loading model: sd-v2-1_768-ema-pruned
Loading weights [ad2a33c361] from /home/Text2Image/web-ui/stable-diffusion-webui/models/Stable-diffusion/sd-v2-1_768-ema-pruned.ckpt
Creating model from config: /home/Text2Image/web-ui/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/configs/stable-diffusion/v2-inference-v.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Applying xformers cross attention optimization.
Model loaded in 44.2s (load weights from disk: 36.0s, find config: 3.9s, create model: 0.3s, apply weights to model: 1.9s, apply half(): 0.9s, load VAE: 0.1s, move model to device: 0.6s, scripts callbacks: 0.2s).
Restored system models.
Generating class images 0/270::   0%|                                                       | 0/40 [00:00<?, ?it/s]No txt2img.
Traceback (most recent call last):
  File "/home/Text2Image/web-ui/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 691, in start_training
    result = main(use_txt2img=use_txt2img)
  File "/home/Text2Image/web-ui/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1140, in main
    return inner_loop()
  File "/home/Text2Image/web-ui/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 123, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/home/Text2Image/web-ui/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 198, in inner_loop
    count, instance_prompts, class_prompts = generate_classifiers(args, use_txt2img=use_txt2img,
  File "/home/Text2Image/web-ui/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/gen_utils.py", line 171, in generate_classifiers
    new_images = builder.generate_images(prompts, pbar)
  File "/home/Text2Image/web-ui/stable-diffusion-webui/extensions/sd_dreambooth_extension/helpers/image_builder.py", line 228, in generate_images
    with self.accelerator.autocast(), torch.inference_mode():
AttributeError: 'ImageBuilder' object has no attribute 'accelerator'
```

`
Python 3.9.6
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is latest
Diffusers version is  0.13.1
Torch version is 1.13.1
Torch vision version is 0.14.1
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
ok

**Describe the bug**

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**

What OS?
linux

If Windows - WSL or native?

What GPU are you using?

gtx1080ti

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

{
    "adamw_weight_decay": 0.01,
    "attention": "xformers",
    "cache_latents": true,
    "clip_skip": 1,
    "concepts_list": [
        {
            "class_data_dir": "",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "class_negative_prompt": "lowres,bad anatomy,bad hands,text,error,missing fingers,\nextra digit,fewer digits,cropped,worst quality,\nlow quality,normal quality,jpeg artifacts,signature,\nwatermark,username,blurry,missing arms,long neck,\nHumpbacked,missing limb,too many fingers,\nmutated,poorly drawn,out of frame,bad hands,\nowres,unclear eyes,poorly drawn,cloned face,bad face",
            "class_prompt": "masterpiece,best quality,1girl",
            "class_token": "",
            "instance_data_dir": "/home/Text2Image/web-ui/stable-diffusion-webui/train/yc_high_quality/dest_data_db",
            "instance_prompt": "masterpiece,best quality,db_yc 1girl",
            "instance_token": "db_yc",
            "is_valid": true,
            "n_save_sample": 1,
            "num_class_images_per": 5,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 20,
            "save_sample_negative_prompt": "lowres,bad anatomy,bad hands,text,error,missing fingers,\nextra digit,fewer digits,cropped,worst quality,\nlow quality,normal quality,jpeg artifacts,signature,\nwatermark,username,blurry,missing arms,long neck,\nHumpbacked,missing limb,too many fingers,\nmutated,poorly drawn,out of frame,bad hands,\nowres,unclear eyes,poorly drawn,cloned face,bad face",
            "save_sample_prompt": "masterpiece,best quality,db_yc 1girl,full body,cute,long hair",
            "save_sample_template": ""
        }
    ],
    "concepts_path": "",
    "custom_model_name": "",
    "deis_train_scheduler": false,
    "deterministic": false,
    "ema_predict": false,
    "epoch": 0,
    "epoch_pause_frequency": 0,
    "epoch_pause_time": 0,
    "freeze_clip_normalization": false,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "gradient_set_to_none": true,
    "graph_smoothing": 50,
    "half_lora": false,
    "half_model": false,
    "train_unfrozen": false,
    "has_ema": false,
    "hflip": false,
    "infer_ema": false,
    "initial_revision": 0,
    "learning_rate": 1e-05,
    "learning_rate_min": 1e-06,
    "lifetime_revision": 0,
    "lora_learning_rate": 0.0002,
    "lora_model_name": "",
    "lora_unet_rank": 4,
    "lora_txt_rank": 4,
    "lora_txt_learning_rate": 0.0002,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant_with_warmup",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "mixed_precision": "fp16",
    "model_name": "db_sd_v2_yc",
    "model_dir": "models/dreambooth/db_sd_v2_yc",
    "model_path": "models/dreambooth/db_sd_v2_yc",
    "num_train_epochs": 150,
    "offset_noise": 0,
    "optimizer": "8Bit Adam",
    "pad_tokens": true,
    "pretrained_model_name_or_path": "models/dreambooth/db_sd_v2_yc/working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_scale": false,
    "prior_loss_target": 100.0,
    "prior_loss_weight": 0.75,
    "prior_loss_weight_min": 0.1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 1,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": false,
    "save_ema": true,
    "save_embedding_every": 25,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": true,
    "save_preview_every": 5,
    "save_safetensors": true,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "scheduler": "DEISMultistep",
    "shuffle_tags": true,
    "snapshot": [],
    "split_loss": true,
    "src": "/home/Text2Image/web-ui/stable-diffusion-webui/models/Stable-diffusion/sd-v2-1_768-ema-pruned.ckpt",
    "stop_text_encoder": 1,
    "strict_tokens": false,
    "tf32_enable": false,
    "train_batch_size": 1,
    "train_imagic": false,
    "train_unet": true,
    "use_concepts": false,
    "use_ema": false,
    "use_lora": true,
    "use_lora_extended": false,
    "use_subdir": true,
    "v2": true
}

**Comment by ArrowM** [comment]
Could you please update your extension and check if that fixes your issue? If it doesn't. Please send your startup console logs that list your library versions, the bit that looks like:
```st
Python 3.9.6 Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8 Installing requirements for Web UI Skipping dreambooth installation.
```
