### ISSUE TITLE
Launch errors detected: ['Incorrect version of torch installed.', 'Incorrect version of torchvision installed.']

### ISSUE THREAD

**Issue by wilzamguerrero** [d8ahazard/sd_dreambooth_extension#1034]
Hi I hope all are really good, i have this error maybe can help me, when um run Stable Diffusion in google colab, this only appear when I try to use dreambooth

Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing gfpgan
Installing clip
Installing xformers
Installing requirements for CodeFormer
Installing requirements for Web UI

Installing sd-webui-controlnet requirement: svglib

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
Dreambooth revision: 5be87ba63f62c228cf135425e21577f70c4e3351
SD-WebUI revision: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

Checking Dreambooth requirements...
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring mediapipe-silicon: markers 'sys_platform == "darwin"' don't match your environment
Collecting accelerate==0.16.0
  Using cached accelerate-0.16.0-py3-none-any.whl (199 kB)
Collecting bitsandbytes==0.35.4
  Using cached bitsandbytes-0.35.4-py3-none-any.whl (62.5 MB)
Collecting diffusers==0.13.1
  Using cached diffusers-0.13.1-py3-none-any.whl (716 kB)
Collecting gitpython~=3.1.31
  Using cached GitPython-3.1.31-py3-none-any.whl (184 kB)
Collecting modelcards~=0.1.6
  Using cached modelcards-0.1.6-py3-none-any.whl (12 kB)
Collecting tensorflow==2.11.0
  Downloading tensorflow-2.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (588.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 2.3 MB/s eta 0:00:00
Collecting mediapipe
  Downloading mediapipe-0.9.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.0/33.0 MB 45.5 MB/s eta 0:00:00
Collecting transformers~=4.26.1
  Using cached transformers-4.26.1-py3-none-any.whl (6.3 MB)
Collecting discord-webhook~=1.1.0
  Using cached discord_webhook-1.1.0-py3-none-any.whl (12 kB)
Collecting lion-pytorch~=0.0.7
  Using cached lion_pytorch-0.0.7-py3-none-any.whl (4.3 kB)
Collecting xformers==0.0.17.dev464
  Downloading xformers-0.0.17.dev464-cp310-cp310-manylinux2014_x86_64.whl (129.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.6/129.6 MB 9.2 MB/s eta 0:00:00
Collecting keras<2.12,>=2.11.0
  Downloading keras-2.11.0-py2.py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 73.2 MB/s eta 0:00:00
Collecting tensorflow-estimator<2.12,>=2.11.0
  Downloading tensorflow_estimator-2.11.0-py2.py3-none-any.whl (439 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 kB 42.3 MB/s eta 0:00:00
Collecting tensorboard
  Downloading tensorboard-2.11.2-py3-none-any.whl (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 110.2 MB/s eta 0:00:00
Collecting opencv-contrib-python
  Downloading opencv_contrib_python-4.7.0.72-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (67.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.9/67.9 MB 11.5 MB/s eta 0:00:00
Installing collected packages: bitsandbytes, tensorflow-estimator, opencv-contrib-python, keras, gitpython, discord-webhook, transformers, modelcards, mediapipe, diffusers, xformers, tensorboard, lion-pytorch, accelerate, tensorflow
  Attempting uninstall: bitsandbytes
    Found existing installation: bitsandbytes 0.35.0
    Uninstalling bitsandbytes-0.35.0:
      Successfully uninstalled bitsandbytes-0.35.0
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.10.0
    Uninstalling tensorflow-estimator-2.10.0:
      Successfully uninstalled tensorflow-estimator-2.10.0
  Attempting uninstall: keras
    Found existing installation: keras 2.10.0
    Uninstalling keras-2.10.0:
      Successfully uninstalled keras-2.10.0
  Attempting uninstall: gitpython
    Found existing installation: GitPython 3.1.27
    Uninstalling GitPython-3.1.27:
      Successfully uninstalled GitPython-3.1.27
  Attempting uninstall: transformers
    Found existing installation: transformers 4.26.0
    Uninstalling transformers-4.26.0:
      Successfully uninstalled transformers-4.26.0
  Attempting uninstall: diffusers
    Found existing installation: diffusers 0.10.2
    Uninstalling diffusers-0.10.2:
      Successfully uninstalled diffusers-0.10.2
  Attempting uninstall: xformers
    Found existing installation: xformers 0.0.16rc425
    Uninstalling xformers-0.0.16rc425:
      Successfully uninstalled xformers-0.0.16rc425
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.10.1
    Uninstalling tensorboard-2.10.1:
      Successfully uninstalled tensorboard-2.10.1
  Attempting uninstall: accelerate
    Found existing installation: accelerate 0.15.0
    Uninstalling accelerate-0.15.0:
      Successfully uninstalled accelerate-0.15.0
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.10.1
    Uninstalling tensorflow-2.10.1:
      Successfully uninstalled tensorflow-2.10.1
Successfully installed accelerate-0.16.0 bitsandbytes-0.35.4 diffusers-0.13.1 discord-webhook-1.1.0 gitpython-3.1.31 keras-2.11.0 lion-pytorch-0.0.7 mediapipe-0.9.1.0 modelcards-0.1.6 opencv-contrib-python-4.7.0.72 tensorboard-2.11.2 tensorflow-2.11.0 tensorflow-estimator-2.11.0 transformers-4.26.1 xformers-0.0.17.dev464

[!] torch version 1.13.1 installed.
[!] torchvision version 0.14.1 installed.
[+] accelerate version 0.16.0 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.
Launch errors detected: ['Incorrect version of torch installed.', 'Incorrect version of torchvision installed.']

#######################################################################################################

**Comment by Ark-kun** [comment]
How did you get into the state where you have Cuda-less PyTorch installed?
I think this bug might be related: https://github.com/d8ahazard/sd_dreambooth_extension/issues/1056
