### ISSUE TITLE
Possible serious bug that slows down training significantly as the epoch count increases

### ISSUE THREAD

**Issue by FurkanGozukara** [d8ahazard/sd_dreambooth_extension#1035]
In the early stages of the training, it generates preview and save checkpoints very fast

As the epoch count increases, then it is almost as training freezes and no messages displayed for a long time when it comes to generate preview image part

Our guess is that, this is caused by the loss plots graphs generation

It also makes sense because as the epoch count increases, the data it has to process increases

Could you check this issue? perhaps we can disable loss plots graphs generation? 

Where should i manually disable in the code to test this? Thank you

**Comment by Arilziem** [comment]
I believe this is done in [train_dreambooth.py#L856](https://github.com/d8ahazard/sd_dreambooth_extension/blob/5be87ba63f62c228cf135425e21577f70c4e3351/dreambooth/train_dreambooth.py#L856), I commented out everything except the first line in the try block the last time I did a longer training run.

I thought this was fixed though. If not, caching previous values is probably the quickest solution so calculations don't have to be redone every time. Also incrementally reducing the number of samples might be worthwhile, as the values tend to become too dense to plot anyway.

**Comment by d8ahazard** [comment]
I'll look and see if I can't optimize parse_logs to parse less entries or something...

**Comment by FurkanGozukara** [comment]
> I'll look and see if I can't optimize parse_logs to parse less entries or something...

I am not sure if that is the primary cause. 

something making the model wait here too much as the number of epochs increases

![image](https://user-images.githubusercontent.com/19240467/223488646-7475f470-3d75-46ea-93ff-df0a71318903.png)

**Comment by d8ahazard** [comment]
> > I'll look and see if I can't optimize parse_logs to parse less entries or something...
> 
> I am not sure if that is the primary cause.
> 
> something making the model wait here too much as the number of epochs increases
> 
> ![image](https://user-images.githubusercontent.com/19240467/223488646-7475f470-3d75-46ea-93ff-df0a71318903.png)
> 
> perhaps we can print more messages?

I'm almost sure that's the issue. I've noticed it before with models I've trained for a LONG time. I'm working on a test to that theory now, where I basically make our "parse_logs" method live within a LogParser class. The LogParser class keeps track of the data already parsed from logs, and only parses changed/new logfiles. I've also updated the Accelerator to use a smaller max log file size, which should help with making it only have to deal with smaller bites.

Almost done working it out, then I'll generate some extra logs and see how it behaves.

**Comment by FurkanGozukara** [comment]
@d8ahazard thank you so much for quick update

started a new 300 epoch training with a very large dataset 127 training pictures

so lets see how it will go

may i ask something else?

when we provide 512x512x3(rgb channels) image, it is encoded into latent space as  4x64x64

so when we set training resolution to 1024x1024x3 on sd 1.5 version what happens? how it is encoded? the vector size of training changes?

thank you very much for answer

Bucket 0 (1024, 1024, 0) - Instance Images: 128 | Class Images: 0 | Max Examples/batch: 128

**Comment by minienglish1** [comment]
If you don't want to comment it out, a easy fix is to:
1) disable samples --> no samples, no graph
2) Set it to train longer than you want, then close the cmd window rather than cancel the training.  If the training completes, or or is canceled, it will generate samples, and thus a graph

**Comment by Arilziem** [comment]
@d8ahazard
> I'm working on a test to that theory now, where I basically make our "parse_logs" method live within a LogParser class. The LogParser class keeps track of the data already parsed from logs, and only parses changed/new logfiles. I've also updated the Accelerator to use a smaller max log file size, which should help with making it only have to deal with smaller bites.

Not sure if 2bcc837 was supposed to be that fix or just a WIP, but it did not really help much. It does seem to skip older logs which is nice, but that only helps with logs from previous training sessions. The current log keeps growing, and so parsing still gets really slow at some point.

**Comment by morphinapg** [comment]
Yeah I'm experiencing this right now with a long training session. Would it be possible to add an option to disable the graph, at least until this is fixed properly? I don't want to disable samples, but parsing the log seems to be taking a LONG time in my current session, which is just past 40,000 steps right now.
