### ISSUE TITLE
Memory allocation problem - xformers on 16.7 GB - xformers off 80 GB = out of memory error

### ISSUE THREAD

**Issue by FurkanGozukara** [d8ahazard/sd_dreambooth_extension#1039]
Latest dev commit of the extension - 1024 pixel resolution - 127 training instances - no classification images

When I don't use xformers it gives oop error even on 80 GB graphic card A100 runpod

When I enable xformers same settings it uses vram=16.5 and works on even 24 GB vram having GPU

The config I am using is as

![image](https://user-images.githubusercontent.com/19240467/223560189-da7cc0bb-34bb-4dc2-bafa-c2ae8668afab.png)

![image](https://user-images.githubusercontent.com/19240467/223560260-54daee0d-d41d-4f34-bee8-acb954ccfc06.png)

![image](https://user-images.githubusercontent.com/19240467/223560317-20eef921-6bc0-40ab-86d1-89a27611ecda.png)

python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: 0.0.17.dev464  •  gradio: 3.16.2  •  

here the error message

![image](https://user-images.githubusercontent.com/19240467/223560718-30801b6e-2142-409b-93cc-a69f55873264.png)

full config is attached

[db_config.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/10914188/db_config.txt)

**Comment by ArrowM** [comment]
Interesting, idk why default would be that much higher. Torch 2 is not officially released or supported by this extension yet.... but if you are going to the trouble of renting a RunPod, it might be worth giving Torch2 default attention a try. I'll copy paste the torch2 info I put in the discord:


:warning: EXPERIMENTAL :warning: (some stuff, such as fp32 precision doesn't seem to work)
2. run
```
./venv/Scripts/activate
pip install --no-deps --force-reinstall https://download.pytorch.org/whl/nightly/cu118/torch-2.0.0.dev20230220%2Bcu118-cp310-cp310-win_amd64.whl https://download.pytorch.org/whl/nightly/cu118/torchvision-0.15.0.dev20230220%2Bcu118-cp310-cp310-win_amd64.whl https://github.com/ArrowM/xformers/releases/download/xformers-0.0.17%2B836ab28.d20230222-cp310-cu118/xformers-0.0.17+836ab28.d20230222-cp310-cp310-win_amd64.whl
```
3. remove xformers from your dreambooth `requirements.txt` (it will override these 3 installs if you don't)

**Comment by FurkanGozukara** [comment]
> Interesting, idk why default would be that much higher. Torch 2 is not officially released or supported by this extension yet.... but if you are going to the trouble of renting a RunPod, it might be worth giving Torch2 default attention a try. I'll copy paste the torch2 info I put in the discord:
> 
> ## ⚠️ EXPERIMENTAL ⚠️
> (some stuff, such as fp32 precision doesn't seem to work)
> 
> 1. run
> 
> ```
> ./venv/Scripts/activate
> pip install --no-deps --force-reinstall https://download.pytorch.org/whl/nightly/cu118/torch-2.0.0.dev20230220%2Bcu118-cp310-cp310-win_amd64.whl https://download.pytorch.org/whl/nightly/cu118/torchvision-0.15.0.dev20230220%2Bcu118-cp310-cp310-win_amd64.whl https://github.com/ArrowM/xformers/releases/download/xformers-0.0.17%2B836ab28.d20230222-cp310-cu118/xformers-0.0.17+836ab28.d20230222-cp310-cp310-win_amd64.whl
> ```
> 
> 2. remove xformers from your dreambooth `requirements.txt` (it will override these 3 installs if you don't)

thanks will try. after i enabled gradient checkpoint, it started training with 45.9 GB vram

however after first model checkpoint or preview image generation the vram usage dropped to 13.9 gb. currently testing which one was the reason

something definitely not right

**Comment by FurkanGozukara** [comment]
this is currently running on another machine with gradient checkpoint enabled

![image](https://user-images.githubusercontent.com/19240467/223571150-4f24d635-00b6-4150-931d-340049ba3996.png)

**Comment by FurkanGozukara** [comment]
ok i captured the error

after first sample generated it blew up

this image just before first sample generated 

![image](https://user-images.githubusercontent.com/19240467/223574110-6bf744c6-d937-49d2-8bd7-72e5dec2e8c1.png)


this image after first sample generated

![image](https://user-images.githubusercontent.com/19240467/223574149-a9299a2d-c1d0-4b1a-ac51-a9a320f2c901.png)

here the used config

5x lesser vram
10x it speed up

[db_config (2).txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/10914649/db_config.2.txt)

**Comment by FurkanGozukara** [comment]
@ArrowM can you give commands for unix? those torch 2.0.0 is for windows :/

**Comment by FurkanGozukara** [comment]
after latest update seems like fixed

![image](https://user-images.githubusercontent.com/19240467/223589687-460aca47-3a80-42ba-aeed-742fd055f760.png)
