### ISSUE TITLE
\working is not the path to a directory containing a config.json file.

### ISSUE THREAD

**Issue by o0oradaro0o** [d8ahazard/sd_dreambooth_extension#104]
**Have you read the Readme?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is 4d9b93d439c58c85c0949632650c3bf775fbcac2
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

**Describe the bug**
Training gets to 100% but the console says it cannot find a config.json in the working directory of the model i'm training (there isn't one to find even when i create a fresh model from the create tab). it also complains about my internet connection

**Provide logs**
`To create a public link, set `share=True` in `launch()`.
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary X:\SD-Web-3\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
 Scheduler Loaded
 Allocated: 0.6GB
 Reserved: 0.7GB

Steps: 100%|██████████████████████████████████████████████████| 1000/1000 [08:37<00:00,  2.02it/s, loss=0.159, lr=5e-6] Exception while training: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like X:\SD-Web-3\stable-diffusion-webui\models\dreambooth\stainedglass\working is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
 Allocated: 5.5GB
 Reserved: 9.0GB

Traceback (most recent call last):
  File "X:\SD-Web-3\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 601, in _get_config_dict
    resolved_config_file = cached_path(
  File "X:\SD-Web-3\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 300, in cached_path
    raise ValueError(f"unable to parse {url_or_filename} as a URL or as a local path")
ValueError: unable to parse X:\SD-Web-3\stable-diffusion-webui\models\dreambooth\stainedglass\working\config.json as a URL or as a local path

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X:\SD-Web-3\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 954, in main
    save_weights(lifetime_step, save_model, save_img)
  File "X:\SD-Web-3\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 810, in save_weights
    text_enc_model = CLIPTextModel.from_pretrained(args.working_dir, subfolder="text_encoder")
  File "X:\SD-Web-3\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 1764, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "X:\SD-Web-3\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\configuration_clip.py", line 126, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "X:\SD-Web-3\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 553, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "X:\SD-Web-3\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 634, in _get_config_dict
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like X:\SD-Web-3\stable-diffusion-webui\models\dreambooth\stainedglass\working is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
 CLEANUP:
 Allocated: 5.5GB
 Reserved: 9.0GB

 Cleanup Complete.
 Allocated: 4.9GB
 Reserved: 7.3GB

Steps: 100%|██████████████████████████████████████████████████| 1000/1000 [08:37<00:00,  1.93it/s, loss=0.159, lr=5e-6]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 3.8GB

Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Training completed, reloading SD Model.': '0.0/3.8GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 1000`

Despite it saying it finished, I cannot find an output model anywhere, I assume the error prevented the creation of the model.

**Environment**
What OS?
windows 10
If Windows - WSL or native?
native
What GPU are you using?
3080 with 10 gb of vram 
for settings:
I set the save checkpoint to match the training steps at 1000, i set the image generation to 10000 (I did not want it to generate images and separate issue, if i set this to 0 i get a divide by 0 error when i try to train)

in advanced:
 I untiked "Train Text Encoder" ticked "Use 8bit Adam" and set the Mixed Precision 'fp16" 
 
 Thanks for making this tool! I really hope i can get it working!

**Comment by d8ahazard** [comment]
I just pushed 65a4bdf, please let me know if this resolves the issue.

**Comment by agcagc** [comment]
Same error with untiked "Train Text Encoder" (if ticked no error and save ckpt)

**Comment by o0oradaro0o** [comment]
pulling latest fixed this issue for me! you da best!

**Comment by FloydianSound** [comment]
This error is happening to me too, since the latest pull (about 12h ago?)
using Dreambooth extension with Web-UI, all within VisionsOfChaos

i was successfull last week with a previous version (one with the tickboxes for `use filenames` or `textfiles`
