### ISSUE TITLE
Xformers issue on PaperSpace

### ISSUE THREAD

**Issue by Maki9009** [d8ahazard/sd_dreambooth_extension#1040]
I'm trying to run the latest build of Auto1111 Stable Diffusion UI on PaperSpace, and the latest version of this dreambooth extension. 
But when I hit train I get this error:

 Exception training model: 'No such operator xformers_flash::flash_fwd - did you forget to build xformers with `python setup.py develop`?'.

Even though xformers is installed properly. so idk whats wrong, 
I'm running this on a A4000 on Paperspace... usually it works but with the latest updates something breaks like class generating and such.. this time its this xformers issue idk.

**Comment by ArrowM** [comment]
Please follow the issue template or your issue will be closed automatically.
