### ISSUE TITLE
Exception while training: integer division or modulo by zero

### ISSUE THREAD

**Issue by Slug-Cat** [d8ahazard/sd_dreambooth_extension#105]
**Have you read the Readme?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

loading Dreambooth reqs from E:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt
Checking Dreambooth requirements.
Checking torch and torchvision versions
Dreambooth revision is f33d4259f2e73fb3a1de6b2f8734e33e29691646
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.

**Describe the bug**
Training lasts for 5 or so steps on 12gb VRAM, every step produces the same division by zero error provided in logs section, then the training quits. 
Settings:
![image](https://user-images.githubusercontent.com/53411759/201177000-38c352a8-2e3d-4669-b3ce-6458f71ac928.png)

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

`Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

[bitsandbytes bug report message here]

CUDA SETUP: Loading binary E:\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
 Scheduler Loaded
 Allocated: 0.6GB
 Reserved: 0.7GB

Steps:   0%|                                                  | 1/1000 [00:16<4:34:20, 16.48s/it, loss=0.0498, lr=5e-6] Exception while training: integer division or modulo by zero
 Allocated: 5.5GB
 Reserved: 8.8GB

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 948, in main
    if training_complete:
ZeroDivisionError: integer division or modulo by zero
Steps:   0%|                                                  | 2/1000 [00:17<1:59:43,  7.20s/it, loss=0.0498, lr=5e-6] Exception while training: integer division or modulo by zero
 Allocated: 5.5GB
 Reserved: 9.0GB

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 948, in main
    if training_complete:
ZeroDivisionError: integer division or modulo by zero
Steps:   0%|▏                                                 | 3/1000 [00:17<1:10:16,  4.23s/it, loss=0.0498, lr=5e-6] Exception while training: integer division or modulo by zero
 Allocated: 5.5GB
 Reserved: 9.0GB

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 948, in main
    if training_complete:
ZeroDivisionError: integer division or modulo by zero
Steps:   0%|▏                                                   | 4/1000 [00:18<47:04,  2.84s/it, loss=0.0498, lr=5e-6] Exception while training: integer division or modulo by zero
 Allocated: 5.5GB
 Reserved: 9.0GB

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 948, in main
    if training_complete:
ZeroDivisionError: integer division or modulo by zero
Steps:   0%|▎                                                   | 5/1000 [00:19<34:11,  2.06s/it, loss=0.0498, lr=5e-6] Exception while training: integer division or modulo by zero
 Allocated: 5.5GB
 Reserved: 9.0GB

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 948, in main
    if training_complete:
ZeroDivisionError: integer division or modulo by zero
Steps:   1%|▎                                                   | 6/1000 [00:19<26:28,  1.60s/it, loss=0.0498, lr=5e-6] Exception while training: integer division or modulo by zero
 Allocated: 5.5GB
 Reserved: 9.0GB

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 948, in main
    if training_complete:
ZeroDivisionError: integer division or modulo by zero
 CLEANUP:
 Allocated: 5.5GB
 Reserved: 9.0GB

 Cleanup Complete.
 Allocated: 4.9GB
 Reserved: 8.7GB

Steps:   1%|▎                                                   | 6/1000 [00:20<55:30,  3.35s/it, loss=0.0498, lr=5e-6]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 3.8GB

Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Training completed, reloading SD Model.': '0.0/3.8GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 6`

**Environment**
What OS? Windows 10
If Windows - WSL or native? *shrug*
What GPU are you using? RTX 3060 12GB

**Comment by YakuzaSuske** [comment]
This happened t me, you have to increase the save checkpoint and image at every steps higher than your steps, it's currently a bit broken atm.
https://github.com/d8ahazard/sd_dreambooth_extension/issues/81

**Comment by Slug-Cat** [comment]
> This happened to me, you have to increase the save checkpoint and image at every steps higher than your steps, it's currently a bit broken atm. #81
Well that seems to have done the trick... how odd.

**Comment by d8ahazard** [comment]
4684f0f should fix this.
