### ISSUE TITLE
Exception with the stupid image again: [Errno 22] Invalid argument...

### ISSUE THREAD

**Issue by Jonseed** [d8ahazard/sd_dreambooth_extension#106]
**Have you read the Readme?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
no, because I'm worried it might break...

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

```
Dreambooth revision is c1702f13820984a4dbe0f5c4552a14c7833b277e
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
```

**Describe the bug**
Generating image previews doesn't work. When you have a prompt in the preview image prompt field (and negative prompt field), then during training when it goes to make the image it gives this error:

`Exception with the stupid image again: [Errno 22] Invalid argument...`

This is followed by a really long filename that is the prompt, with the step number, and .png. Then there is a note about where the weights were saved. A png is not saved, and training continues. I wonder if it has to do with the long filename? If the preview image prompt field is left blank, a preview image is made, but it is not related to the training (whatever a blank field prompt generates).

**Provide logs**
no crash, training continues

**Environment**
What OS? Windows
If Windows - WSL or native? native
What GPU are you using? 3060 12GB

**Comment by Jonseed** [comment]
I notice when I run regular txt2img, the filenames are truncated. They are not the full prompt. I wonder if something like that has to be done here as well. Maybe it is running into a long filename issue with the OS.

**Comment by Jonseed** [comment]
txt2img seems to usually truncate filenames at 145 characters.

**Comment by Jonseed** [comment]
I have confirmed that using a shorter prompt generates an image preview just fine, so I think it must have to do with the length of the filename that is causing the exception.

**Comment by d8ahazard** [comment]
Update your version of the extension, this has already been fixed.

**Comment by Jonseed** [comment]
@d8ahazard I'm now on the latest commit 4684f0f, and I still get this error with long preview prompt/filenames, so I don't think it's been fixed.

**Comment by d8ahazard** [comment]
Noted. I'll see what I can do to fix this.

**Comment by Renaldas111** [comment]
I'm getting similar error during training, training is working properly, but when it is time for a preview image generation, I receive:

Exception with the stupid image again: tensors used as indices must be long, byte or bool tensors

**Comment by Jonseed** [comment]
Hmm, I don't see the message about the tensors and indices. For me it just says "invalid argument" followed by the really long filename.

**Comment by d8ahazard** [comment]
This should be resolved...

**Comment by AmitShashi** [comment]
stable diffusion os error Invalid argument

it happens when image is generated but is not able to save image because it setting for file name pattern you may have use something like this:

__ModelName-[model_name]-[model_hash]__ __sampler-[sampler]__  __steps-[steps]__  __width x height-[width] x [height]__ __cfg-[cfg]__ __seed-[seed]__ __prompt-[prompt]__

in prompt section ,, people usually use:

 (worst quality, low quality:1.4)
 
 in above line it has ":"
 which cannot be used for saving file names
