### ISSUE TITLE
LoRA safetensors are saved under lora instead of Lora directory

### ISSUE THREAD

**Issue by initialxy** [d8ahazard/sd_dreambooth_extension#1069]
```
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
Commit hash: dfeee786f903e392dbef1519c7c246b9856ebab3
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
Dreambooth revision: bff61c6b92b79ece2e140ee240e0628dd9a4ebef
SD-WebUI revision: dfeee786f903e392dbef1519c7c246b9856ebab3

Checking Dreambooth requirements...
Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring mediapipe-silicon: markers 'sys_platform == "darwin"' don't match your environment
Collecting accelerate==0.16.0
  Using cached accelerate-0.16.0-py3-none-any.whl (199 kB)
Collecting gitpython~=3.1.31
  Using cached GitPython-3.1.31-py3-none-any.whl (184 kB)
Collecting transformers~=4.26.1
  Using cached transformers-4.26.1-py3-none-any.whl (6.3 MB)
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Installing collected packages: requests, gitpython, accelerate, transformers
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Attempting uninstall: gitpython
    Found existing installation: GitPython 3.1.30
    Uninstalling GitPython-3.1.30:
      Successfully uninstalled GitPython-3.1.30
  Attempting uninstall: accelerate
    Found existing installation: accelerate 0.12.0
    Uninstalling accelerate-0.12.0:
      Successfully uninstalled accelerate-0.12.0
  Attempting uninstall: transformers
    Found existing installation: transformers 4.25.1
    Uninstalling transformers-4.25.1:
      Successfully uninstalled transformers-4.25.1
Successfully installed accelerate-0.16.0 gitpython-3.1.31 requests-2.28.2 transformers-4.26.1

[!] torch version 1.13.1+rocm5.2 installed.
[!] torchvision version 0.14.1+rocm5.2 installed.
[+] accelerate version 0.16.0 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.
Launch errors detected: ['Incorrect version of torch installed.', 'Incorrect version of torchvision installed.']
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
YES
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
YES
**Have you updated Dreambooth to the latest revision?**
YES
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
YES
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**

When "Generate LoRA weights for extra networks." is enabled, the release note mentions that

> you should now automatically see the generated LoRA files in the native extra networks feature, or you can directly add it to your prompts using the <LoRA:modelname_steps:1> syntax

However this extension saves LoRA safetensors files under `stable-diffusion-webui/models/lora` (lower case l), instead of `stable-diffusion-webui/models/Lora` (uppper case L). It seems a1111 picks up LoRAs from Lora directory, so they don't get picked up until they are manually moved. 

**Environment**

What OS?
Arch Linux

What GPU are you using?
AMD Radeon RX 6700 XT

**Comment by ArrowM** [comment]
Weird, this issue doesn't seem to impact windows. It's an easy fix tho. Update line `extensions/sd_dreambooth_extension/dreambooth/shared.py:302` to be properly capitalized. I'll include it in a future PR to main.

**Comment by initialxy** [comment]
The directory seems to be defaulted here in a1111
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/extensions-builtin/Lora/preload.py#L6

Thanks for taking a look!

**Comment by lodinv** [comment]
Can't choose Lora
![lora](https://user-images.githubusercontent.com/8284477/228684265-6e7b0c1c-1cc2-42da-890a-fd6597fdb728.png)

**Comment by lodinv** [comment]
Невозможно выбрать Lora
![lora](https://user-images.githubusercontent.com/8284477/228684675-f0f2a701-a815-4fe3-b8e6-9fb6ebfdb389.png)

**Comment by lodinv** [comment]
Can't choose Lora

![lora](https://user-images.githubusercontent.com/8284477/228685274-0e72eb4f-85a4-4e64-afeb-1186f54d39b2.png)

**Comment by ArrowM** [comment]
The original issue of `Lora` not being capitalized was fixed ~ 2 weeks ago (we forgot to close the issue though). @lodinv please open a separate issue with the template filled out.
