### ISSUE TITLE
AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing'

### ISSUE THREAD

**Issue by CORRUPTOR2037** [d8ahazard/sd_dreambooth_extension#107]
**Have you read the Readme?**
Yes I did

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Several times

**Have you updated Dreambooth to the latest revision?**
yes

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**
Dreambooth revision is 65a4bdffc41b3ab44ec8262acce21c87d9a7fccf
Diffusers version is 0.3.0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Incorrect diffusers version for Dreambooth, running installer.: 0.3.0

(i forcibly reinstalled diffusers before launching UI to 0.8.0 with
`pip uninstall git+https://github.com/ShivamShrirao/diffusers.git#egg=diffusers`
`pip install git+https://github.com/ShivamShrirao/diffusers.git#egg=diffusers`
`Successfully installed diffusers-0.8.0.dev0`
)

**Describe the bug**
Error on training start

**Provide logs**
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "E:\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 275, in start_training
    trained_steps = main(config)
  File "E:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 640, in main
    unet.enable_gradient_checkpointing()
  File "E:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing'

**Environment**
Native Windows 10
Python 3.9.2
RTX 3060 12 GB

Model cloned from SD 1.4 downloaded from hugginface
Use CPU Only (SLOW) = false
Don't cache latents = true
Train Text Encoder = false
Use 8bit Adam = true
Mixed precision = no

**Comment by mykeehu** [comment]
Just turn off "Don't cache latents", and be Train Text Encoder = true, Mixed precision = fp16 and try again ;)

**Comment by d8ahazard** [comment]
Your diffusers version is still version 0.3.0. Restart the WebUI and try again.

**Comment by CORRUPTOR2037** [comment]
Restart WebUI does not help
Reinstall extension does not help

Diffusers 0.3.0 is always reinstalled back at WebUI launch
Maybe because it is specified as requirement in WebUI

**Comment by Giganoob23** [comment]
Same error here.

Error completing request
Arguments: ('test1', 'C:\\StableDif\\stable-diffusion-webui\\training input', '', 'tsttst', False, False, '', '', '', 1, 7.5, 40, 0, 512, False, False, 1, 1, 1, 1500, 1, True, 5e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 0, 1500, 'fp16', True, '', False, True, True) {}
Traceback (most recent call last):
  File "C:\StableDif\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\StableDif\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\StableDif\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 276, in start_training
    trained_steps = main(config)
  File "C:\StableDif\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 640, in main
    unet.enable_gradient_checkpointing()
  File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing'

**Comment by mykeehu** [comment]
Which model would you train for? SD 1.5 or 1.4 or other?

**Comment by skier233** [comment]
Same issue

**Comment by d8ahazard** [comment]
Have a look at the updated "sd-webui-user-dreambooth.bat" file. 

I've added some flags to force it to only install requirements/torch ONCE, which I think should resolve this.

Unet2DContidionalModel missing enable_gradient_checkpointing is a clear indicator that the diffusers version is too old.
