### ISSUE TITLE
Regression: not able to generate sample images after removal of optim_to

### ISSUE THREAD

**Issue by Arilziem** [d8ahazard/sd_dreambooth_extension#1075]
The removal of `optim_to` (PR #1071) has resulted in me getting OOM when generating sample images during training (and on training end). Manually adding back `optim_to` makes sample images possible again.

Windows 10 native
RTX 3080 (10GB VRAM)

Can't go lower with the training settings unless I switch to Lora (or reduce resolution below 512), so without optim_to, no sample images when doing a full(-ish) training on 10GB.

(I apologize for not filling out the template, as I think this is very straightforward. Happy to add those details of course if you feel you need them.)

**Comment by ArrowM** [comment]
Have you re-added `optim_to` to the latest commit on main and verified that it fixes your OOM issue? 

I did a test with and without `optim_to` and it didn't seem to provide any improvement on my setup. If it works for you though, we can re-add it.

**Comment by d8ahazard** [comment]
@ArrowM I was worried about this one. I have a feeling that maybe the effect is only noticeable on lower-VRAM setups. As it's not really hurting anything and was added for this specific reason, I think it'd be a wise idea to just put it back. It only runs when saving weights or previews anyway.

**Comment by ArrowM** [comment]
I'd still like you to verify that it fixes your OOM before we merge it. Here's the PR for it #1076

**Comment by Arilziem** [comment]
I will run an A/B test with that PR later to make sure the PR is the only factor. I tested with bd3fecc before and got OOM, manually added back `optim_to` and then it was fine.

**Comment by Arilziem** [comment]
Ran with bd3fecc and compared to 8f7a7d7. I can confirm it fixes the OOM.

Conditions to reproduce were interesting though. Without `optim_to`, it only triggers OOM with snapshots enabled and when creating a new model right before (not when resuming training after restarting the webui). Solid though with `optim_to` back in.

**Comment by ArrowM** [comment]
Hey, sorry we got off topic on the other thread. Would you consider #1072 fixed with the re-addition of `optim_to`?
