### ISSUE TITLE
lora train error

### ISSUE THREAD

**Issue by Vencenter** [d8ahazard/sd_dreambooth_extension#1079]
To create a public link, set `share=True` in `launch()`.
Model dir set to: D:\tools\AI_umaru\stable-diffusion\models\dreambooth\AI
Model dir set to: D:\tools\AI_umaru\stable-diffusion\models\dreambooth\AI
Model dir set to: D:\tools\AI_umaru\stable-diffusion\models\dreambooth\AI
Model dir set to: D:\tools\AI_umaru\stable-diffusion\models\dreambooth\AI
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Exception initializing accelerator: Accelerator.__init__() got an unexpected keyword argument 'project_dir'
Restored system models.
Duration: 00:00:04

**Comment by ArrowM** [comment]
Did not follow the issue template
