### ISSUE TITLE
The preview result is inconsistent with the production result.

### ISSUE THREAD

**Issue by AlamJoy** [d8ahazard/sd_dreambooth_extension#1088]
What version of Sampler is used to generate the preview image? The difference between the production result of the preview image and the normal production result of sd is too huge. This is true for all preset Samplers.

**Comment by ArrowM** [comment]
![image](https://user-images.githubusercontent.com/42418080/226124657-2cc6e9c2-7bdb-409f-ae5f-042f0fbfc9bb.png)

**Comment by AlamJoy** [comment]
I did multiple tests with the same variables and these settings did not affect the preview images output during training. The preview images output during training have better shape simulation and detail preservation than the actual results.

**Comment by AlamJoy** [comment]
In the case of Optimizer Lion, the results on both sides are close, only in the case of Optimizer Adam, this problem occurs.

**Comment by AlamJoy** [comment]
After using Lion, the effect is consistent, only in the case of Adam is there a difference.
