### ISSUE TITLE
Exception training model: 'No module named 'tensorflow.python''.

### ISSUE THREAD

**Issue by PamirSevincel** [d8ahazard/sd_dreambooth_extension#1093]
Dear friends,

I am having trouble running Dreambooth locally on webui. Stable Diffusion works perfectly but when I try to train my own images on Dreambooth using webui, I get the error:

> Exception training model: 'No module named 'tensorflow.python''.

I have tensorflow installed on my conda environment but do not know why this doesn't work.

Please help!

![image](https://user-images.githubusercontent.com/98260504/226172645-c4c26d75-4a1b-40d8-8c84-b41fd9fb39d7.png)

**Comment by pofed193** [comment]
What are the rest of the settings under model?

**Comment by PamirSevincel** [comment]
> What are the rest of the settings under model?

I am not changing any of the settings. Just specifying the image directory and the directory for regularization.

What can I share with you here to make you better understand the problem?

**Comment by pofed193** [comment]
Did you go to the 'create' tab to make a base model, then select it on the 'select' tab?

**Comment by PamirSevincel** [comment]
> Did you go to the 'create' tab to make a base model, then select it on the 'select' tab?

Yes, I create a model first and select the stable diffusion 2.1 checkpoint.

**Comment by Soumyajit** [comment]
Same problem for me as well.. I was trying with v1-5-pruned-emaonly.ckpt (My GPU is 6GB)

**Comment by Soumyajit** [comment]
I managed to solve this via:

1. Shutdown the Web UI - close terminal
2. Delete venv folder
3. Add "tensorflow==2.11.0" to the last line of  "requirements_versions.txt (https://github.com/d8ahazard/sd_dreambooth_extension/issues/751)
4. Now the above should ideally work but I found that I need to also enable LONG PATHS in windows: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry
5. Restart the Web UI

**Comment by PamirSevincel** [comment]
> I managed to solve this via:
> 
> 1. Shutdown the Web UI - close terminal
> 2. Delete venv folder
> 3. Add "tensorflow==2.11.0" to the last line of  "requirements_versions.txt ([No module named tensorflow #751](https://github.com/d8ahazard/sd_dreambooth_extension/issues/751))
> 4. Now the above should ideally work but I found that I need to also enable LONG PATHS in windows: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry
> 5. Restart the Web UI

It works!! Thank you so much 👌
