### ISSUE TITLE
DreamBooth error

### ISSUE THREAD

**Issue by crazedaimond** [d8ahazard/sd_dreambooth_extension#1095]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 0. Initial troubleshooting
I'm getting this error when starting Automatic1111

### 1. Please find the following lines in the console and paste them below.

Already up to date.
venv "C:\Stable_Diffusion_AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI

Error running install.py for extension extensions\sd_dreambooth_extension.
Command: "C:\Stable_Diffusion_AI\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout:
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision:
SD-WebUI revision: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

Successfully installed accelerate-0.17.1
Successfully installed bitsandbytes-0.35.4
Successfully installed dadaptation-1.5
Successfully installed diffusers-0.14.0
Successfully installed discord-webhook-1.1.0 requests-2.28.2
Successfully installed fastapi-0.90.1 starlette-0.23.1
Successfully installed gitpython-3.1.31
Successfully installed lion-pytorch-0.0.7

stderr: Traceback (most recent call last):
  File "C:\Stable_Diffusion_AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 64, in pip_install
    output = subprocess.check_output(
  File "C:\Users\craze\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\craze\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Stable_Diffusion_AI\\stable-diffusion-webui\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', "mediapipe; sys_platform != 'darwin'"]' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Stable_Diffusion_AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 35, in <module>
    actual_install()
  File "C:\Stable_Diffusion_AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 51, in actual_install
    install_requirements()
  File "C:\Stable_Diffusion_AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 90, in install_requirements
    pip_install([line])
  File "C:\Stable_Diffusion_AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 72, in pip_install
    error_msg = grepexc.output.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 2585: invalid start byte

Launching Web UI with arguments: --deepdanbooru --xformers --theme dark
Loading weights [fc2511737a] from C:\Stable_Diffusion_AI\stable-diffusion-webui\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
Creating model from config: C:\Stable_Diffusion_AI\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\Stable_Diffusion_AI\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(22): beautiful_mistake-6500, beautiful_mistake-8500, bukkakAI, corneo_anal, corneo_ball_gag, corneo_bound_missionary, corneo_covering_breasts_two_hands, corneo_cowgirl, corneo_pov_anal, corneo_pov_oral, corneo_side_doggy, corneo_spitroast, corneo_tentacle_sex, EasyNegative, ng_deepnegative_v1_75t, pureerosface_v1, realcumAI, spreadassms, Style-Glass, style-hamunaptra, style-princess, ulzzang-6500-v1.1
Model loaded in 5.1s (create model: 0.5s, apply weights to model: 1.3s, apply half(): 0.9s, load VAE: 0.4s, move model to device: 0.8s, load textual inversion embeddings: 1.2s).
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary C:\Stable_Diffusion_AI\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary C:\Stable_Diffusion_AI\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Exception importing xformers: Xformers version must be >= 0.0.17.dev
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 26.8s (import gradio: 2.2s, import ldm: 0.8s, other imports: 2.3s, list extensions: 0.5s, load scripts: 2.5s, load SD checkpoint: 5.5s, create ui: 12.8s).

### 2. Describe the bug

(A clear and concise description of what the bug is)

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

### 3. Provide logs

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```st
PASTE YOUR STACKTRACE HERE
```

### 4. Environment

What OS?
Windows 11
If Windows - WSL or native?

What GPU are you using?

**Comment by H722X** [comment]
also i am

**Comment by BertrandUrych** [comment]
I have the same issue... I tried reinstalling the whole Stable diffusion, reinstaling python and all of it's libraries and still nothing works.

**Comment by dr-dark-flames** [comment]
same but getting something different after the install.py error:
```
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.0
    Uninstalling protobuf-3.20.0:
      Successfully uninstalled protobuf-3.20.0
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'B:\\Apps\\Stable Diffusion\\stable-diffusion-webui\\venv\\Lib\\site-packages\\google\\~.otobuf\\internal\\_api_implementation.cp310-win_amd64.pyd'
Check the permissions.


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: B:\Apps\Stable Diffusion\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip


[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] xformers version 0.0.17.dev464 installed.

stderr: Traceback (most recent call last):
  File "B:\Apps\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 35, in <module>
    actual_install()
  File "B:\Apps\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 57, in actual_install
    check_versions()
  File "B:\Apps\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 164, in check_versions
    if req_type == "min" and Version(installed_ver) < Version(req_ver):
  File "B:\Apps\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\packaging\version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'None'
```

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
