### ISSUE TITLE
Smart PreProcess Tab

### ISSUE THREAD

**Issue by scrambled2** [d8ahazard/sd_dreambooth_extension#11]
Not an issue, but what is the smart preprocess tab in your example? Been hoping someone introduced better pre-processing settings in the Auto1111 repo.

**Comment by d8ahazard** [comment]
> Not an issue, but what is the smart preprocess tab in your example? Been hoping someone introduced better pre-processing settings in the Auto1111 repo.

Another WIP extension I'll be releasing soon. It's based on my YOLO-Crop pull request in the main repo. Uses CLIP to interrogate the image (or a user-defined prompt), then uses YOLO to find the object in the image that most likely corresponds to the prompt, finds the center, then expands from the center point to best encapsulate the subject.

Just trying to squash one new bug as a result of porting to an extension, then I'll have a repo up.

**Comment by scrambled2** [comment]
Ahh nice. That's rad. I'll try it as soon as you release it!

**Comment by d8ahazard** [comment]
I'm gonna close this for now. I have the other extension ready to go, just waiting to drop it till I get this can of worms settled. I'll drop a link here when I post it.

**Comment by d8ahazard** [comment]
> @d8ahazard Thanks man!

As promised:

https://github.com/d8ahazard/sd_smartprocess

**Comment by scrambled2** [comment]
Dude. This is genius!

**Comment by scrambled2** [comment]
Dumb suggestion #1. It appears the captions are being created before the crops. Which means that the captions sometimes might have made sense before the crops, but after they could refer to people and things that are no longer present. I would reverse the order of operations on that. Thanks!
