### ISSUE TITLE
Error when installing/restarting

### ISSUE THREAD

**Issue by eM-Krow** [d8ahazard/sd_dreambooth_extension#110]
![image](https://user-images.githubusercontent.com/87371945/201209367-a0f0371e-0415-408c-826a-dd7f155d1aa3.png)

**Comment by mykeehu** [comment]
It helped me:

- inactivate the Dreambooth extension in Automatic1111 and close it
- delete the directory of the Dreambooth extension
- start Automatic1111 and install the extension
- reactivate it (if you don't see it, restart Gradio in Settings)
- after activation, close everything and start Automatic1111
- all done, installed.

**Comment by d8ahazard** [comment]
This is now 5 days old, which is almost like a whole new extension with the number of changes made.

Please try again and update as needed, close if applicable. 

This issue will be closed if no update is provided in 24 hours for the sake of tracking current issues.
