### ISSUE TITLE
cache crash when modified image sources

### ISSUE THREAD

**Issue by yggdrasil75** [d8ahazard/sd_dreambooth_extension#1102]
### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision: (yeah, this is still empty. needs some sort of code hash put here I guess… but I updated and restarted anyway.)
SD-WebUI revision:

Checking Dreambooth requirements...
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.

#######################################################################################################
```

### 2. Describe the bug
changes to images cause cache to not update
if I add or remove an image from the source folders, the cache starts to be regenerated, but when saving it crashes. this means that if I forgot to delete the cache manually, then I just wasted 20+ minutes (depending on number of files)

### 3. Provide logs

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```st
aving cache!
Traceback (most recent call last):
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 554, in start_training
    result = main(use_txt2img=use_txt2img)
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1137, in main
    return inner_loop()
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 120, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 449, in inner_loop
    train_dataset = generate_dataset(
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\utils\gen_utils.py", line 88, in generate_dataset
    train_dataset.make_buckets_with_caching(vae, min_bucket_reso)
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\dataset\db_dataset.py", line 266, in make_buckets_with_caching
    os.remove(image_cache_file)
PermissionError: [WinError 5] Access is denied: 'D:\\creations\\imagetraining\\automatic\\models\\dreambooth\\everythingcustom\\cache\\image_cache_768.safetensors'
```

### 4. Environment

What OS?windows 10

If Windows - WSL or native? native

What GPU are you using? 3090

**Comment by ArrowM** [comment]
> yeah, this is still empty. needs some sort of code hash put here I guess… but I updated and restarted anyway.

I can tell from the startup log that your extension isn't up to date (perhaps you A1111 isn't fully updated, older versions had issues with updating extensions. Please fix that and then try again.

**Comment by yggdrasil75** [comment]
I clicked "update extension and restart" in the testing section. I then closed and reopened a1111. I copied that after I did those.
my a1111 is up to date because I have git pull in the webui-user.bat. 
what do you mean it isnt up to date? is one of the packages outdated?

**Comment by yggdrasil75** [comment]
https://gist.github.com/yggdrasil75/995bd3d2b2dd15a2d095332d01d05663

the entire startup log. perhaps you see something there I dont, but I certainly have updated.

**Comment by ArrowM** [comment]
you can look at the commit history and see that your hash is outdated https://github.com/d8ahazard/sd_dreambooth_extension/commits/main

**Comment by ArrowM** [comment]
also does the extensions update and restart output anything in the console?

**Comment by yggdrasil75** [comment]
I made 1106 so that the version number issue can be responded to and hopefully the cache crash can be responded to. is there anything related to this issue you would from me? or has there been any changes to the cache code since I did a git clone 2 weeks ago?
