### ISSUE TITLE
git clone Dreambooth installing failed 

### ISSUE THREAD

**Issue by sk8erchen** [d8ahazard/sd_dreambooth_extension#1104]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 78ca4dabe9b269b7dae25960121c58c41e6c39e1
SD-WebUI revision: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

#######################################################################################################
```

### 2. Describe the bug

I installed the AUTOMATIC1111/stable-diffusion-webui from https://github.com/AUTOMATIC1111/stable-diffusion-webui it runs successfully, then I installed Dreambooth using git pull command from the extension folder, after that, when I run webui-user.bat, it pops up erros like below and the dreambooth tab isn't showing in the webui.

![image](https://user-images.githubusercontent.com/75480055/226781188-db7dbdc6-ccb4-47a8-b53f-0138c9b1b4ab.png)

### 4. Environment

What OS?

If Windows - WSL or native?
It's native Windows 11 pro

What GPU are you using?
It's a 4090 with 24g vram

**Comment by ArrowM** [comment]
Alrighty. I'll take a stab at fixing this as it's been report many times. This is almost certainly going to be a mistake in the A1111 base project though.

**Comment by sk8erchen** [comment]
Hi, is this the solution?

**Comment by LaoniGAGA** [comment]
same problem

**Comment by ArrowM** [comment]
@sk8erchen @LaoniGAGA did either of you try checking out https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8797
If yes, please post the results.

**Comment by ArrowM** [comment]
https://www.youtube.com/watch?v=wQLFCUZKwbM

**Comment by sk8erchen** [comment]
here's what I have just done:
1. reinstall stable-diffusion using git clone
2. reinstall dreambooth using git clone
3. double check requirements_version.txt and requirements.txt
4. key in the three lines you gave below
git remote add ArrowM-master https://github.com/ArrowM/stable-diffusion-webui
git fetch ArrowM-master
git cherry-pick -m 00bd271faffbdfd2988b6cfc9117c67681ee14b7

and here is the result of the three git lines:
![Snipaste_2023-03-23_00-39-50](https://user-images.githubusercontent.com/75480055/226977774-45f6154b-1c22-4455-a5b5-ab5cc30a6f15.png)
5. now the sd loads up successfully, and dreambooth tab FINALLY shows up
6. THANK YOU SO MUCH
