### ISSUE TITLE
commit hash is blank

### ISSUE THREAD

**Issue by yggdrasil75** [d8ahazard/sd_dreambooth_extension#1106]
1. Please find the following lines in the console and paste them below.
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision: 
SD-WebUI revision:

Checking Dreambooth requirements...
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.

#######################################################################################################
2. Describe the bug
dreambooth revision is blank

https://github.com/d8ahazard/sd_dreambooth_extension/issues/1102

https://gist.github.com/yggdrasil75/995bd3d2b2dd15a2d095332d01d05663

https://gist.github.com/yggdrasil75/629b0becd69a42720977ae4e9e02fad3
all of this code shows every time I hit the button. but if I do a git pull then I have 
D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension>git pull
Already up to date.

now hopefully #1102  can have its actual issue responded to.

**Comment by ArrowM** [comment]
Follow the template
