### ISSUE TITLE
Dreambooth extension won't load - Google Colab

### ISSUE THREAD

**Issue by cosmiclantern** [d8ahazard/sd_dreambooth_extension#1108]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 0. Initial troubleshooting
Yes

### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: bd3fecc3d27d777a4e8f3206a0b16e852877dbad
SD-WebUI revision: 

[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] xformers version 0.0.17+b6be33a.d20230315 installed.
[+] accelerate version 0.17.1 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.27.1 installed.

#######################################################################################################
```

### 2. Describe the bug

Dreambooth extension won't load when starting the ui in colab.

### 3. Provide logs

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 51, in <module>
    from dreambooth.webhook import save_and_test_webhook
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/webhook.py", line 6, in <module>
    import discord_webhook
ModuleNotFoundError: No module named 'discord_webhook'

### 4. Environment

What OS? Jupyter notebook on Google Colab, https://github.com/TheLastBen/fast-stable-diffusion

**Comment by ArrowM** [comment]
Please update your extension (to da2e40415f1cb63cc4de46d6dc97eb8676c6e30c) and let me know if that fixes it. If it doesn't please include the full startup log.

**Comment by cosmiclantern** [comment]
Thank you for replying, I've updated the extension but the result is the same. Please can you tell me how to retrieve the full startup log on the google colab platform? All I get when running the code cell to start the UI is the log I pasted above. Am I missing something? I'm really thick when it comes to this stuff.

**Comment by ArrowM** [comment]
I don't use google collab. Do you have a link to the collab page you are using?

**Comment by cosmiclantern** [comment]
Yeah it's https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb  by https://github.com/TheLastBen/fast-stable-diffusion

**Comment by cosmiclantern** [comment]
Ok, I deleted the runtime and started again from thelastben's newest notebook (not the copy I saved to my google drive). Ran it all again, and now this almost identical trace:

[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 51, in <module>
    from dreambooth.webhook import save_and_test_webhook
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/webhook.py", line 6, in <module>
    import discord_webhook
ModuleNotFoundError: No module named 'discord_webhook'

********

Is there something wrong with the files scripts.py, script_loading.py, main.py & webhook.py?  I can see the lines of code it's referring to, but not knowing anything about python how do i fix it?

**Comment by DarkVioletMoonRay** [comment]
I got the extension to appear by running this script through a cell:

!pip -q install --upgrade -r /content/gdrive/MyDrive/sd/stable-diffusion-webui/requirements.txt

But, this still causes an exception to occur with the xformers when I run the cell that initiates Stablw Diffusion; the extension then seems unable to create models. Attempting to do so just causes the cell to stop running. I tried installing the appropriate xformer package, but it upgrades torch to 2.0.0, which then makes the Stable Diffusion Cell throw errors like OP states.

**Comment by ArrowM** [comment]
Yeah, xformers just unpublished the 0.0.17 wheels built with torch 1. xformers < 0.0.17 cause training errors. So you're stuck with upgrading to Torch 2 for now:
```
!pip install --force-reinstall torch torchvision --index-url https://download.pytorch.org/whl/cu118
!pip install --force-reinstall --no-deps --pre xformers
```
I made a post on the xformers repo asking them to republish the wheels built with torch 1.
