### ISSUE TITLE
Deforum reaching into txt2img and altering the resolution is not okay.

### ISSUE THREAD

**Issue by enn-nafnlaus** [d8ahazard/sd_dreambooth_extension#1109]
### 1. Startup

No startup errors from Dreambooth (it's gone now, I can't paste it)

### 2. Describe the bug

After updating, Dreambooth adjusts the resolution in txt2img, even if a person isn't using Dreambooth at all, trying to make it align to step boundaries. Try setting the resolution to 960x540.

This should go without saying, but Dreambooth should never mess with txt2img, but _**especially**_ if the person isn't using Dreambooth at all.  I was forced to delete the extension.

### 3. Provide logs

Visual only.

### 4. Environment

Linux, but it doesn't matter.

**Comment by ArrowM** [comment]
??? Dreambooth doesn't touch txt2img. Also you title says Deforum? What???

**Comment by ArrowM** [comment]
Fixed. It'll be in a future PR to main. https://github.com/d8ahazard/sd_dreambooth_extension/commit/24ece01ff04b2abdded118b09a0be35fa1bca137

**Comment by enn-nafnlaus** [comment]
LOL @ Deforum accidentally being in the title (like 80% of the bugs I encounter are with Deforum, so... force of habit  ;)  )

Thanks for the quick fix!

**Comment by 78Alpha** [comment]
I wonder if this is why my control net sliders were acting weird.

My only addition is that it happened infrequently.

**Comment by ArrowM** [comment]
#1117 was just merged and should fix it.
