### ISSUE TITLE
mac m1 cannot start webui with this extension and get a " illegal hardware instruction" error

### ISSUE THREAD

**Issue by duelgenji** [d8ahazard/sd_dreambooth_extension#1111]
### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
################################################################
Python 3.10.10 (main, Feb 16 2023, 02:58:25) [Clang 14.0.0 (clang-1400.0.29.202)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled

Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.10 (main, Feb 16 2023, 02:58:25) [Clang 14.0.0 (clang-1400.0.29.202)]
Dreambooth revision: da2e40415f1cb63cc4de46d6dc97eb8676c6e30c
SD-WebUI revision: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

Successfully installed accelerate-0.17.1
Successfully installed requests-2.28.2
Successfully installed fastapi-0.90.1 starlette-0.23.1
Successfully installed gitpython-3.1.31
Successfully installed transformers-4.27.2
Successfully installed torch-1.13.1

[!] torch version 1.13.1 installed.
[!] torchvision version 0.13.1 installed.
[!] xformers NOT installed.
[+] accelerate version 0.17.1 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.27.2 installed.
[+] bitsandbytes version 0.35.4 installed.
#######################################################################################################
```

### 2. Describe the bug
After I installed sd_dreambooth_extension, i cant use webui.sh to start, if I remove the "sd_dreambooth_extension" folder and clean the "venv" folder, i can restart  webui again(after waiting long time to redownload stuff in venv)

### 3. Provide logs

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```st
Launching Web UI with arguments: --upcast-sampling --no-half-vae --use-cpu interrogate
/Users/knight/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/knight/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIxEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  Referenced from: /Users/knight/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/image.so
  Expected in: /Users/knight/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  warn(f"Failed to load image Python extension: {e}")
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
[AddNet] Updating model hashes...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 3531.83it/s]
[AddNet] Updating model hashes...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 23172.95it/s]
[1]    41697 illegal hardware instruction  ./webui.sh
/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

### 4. Environment

What OS?
Mac M1

**Comment by ArrowM** [comment]
I'm guessing it's the tensorflow-metal library (so if you run into an issue again, just delete the 2 folders for that in `venv/Libs/sitepackage`.

Could you please try cloning the this extension into your extensions directory, then open `extensions/sd_dreambooth_extension/requirements.txt` and remove the line with `tensorflow-metal`, then start up the project.

**Comment by duelgenji** [comment]
@ArrowM  I've tried  remove the line with ''tensorflow-metal'' and restart, got the same error

**Comment by ArrowM** [comment]
Hmm, I don't have a mac so I can't do any of this testing myself. Could you please try changing the tensorflow line of the requirements file to be
```
tensorflow==2.11.1; sys_platform != 'darwin' or platform_machine != 'arm64'
```
Also this might have some info https://stackoverflow.com/questions/65383338/zsh-illegal-hardware-instruction-python-when-installing-tensorflow-on-macbook

**Comment by ArrowM** [comment]
> It seems like what you typed is not different from the original text.

OG text is removing `tensorflow-metal`, second message is removing `tensorflow`. MacOS is goofy - they have 2 of their own flavors of the tensorflow library. I'm hoping you can try this configuration of this requirements file
```
tensorflow==2.11.1; sys_platform != 'darwin' or platform_machine != 'arm64'
tensorflow-macos==2.11.0; sys_platform == 'darwin' and platform_machine == 'arm64'
tensorflow-metal; sys_platform == 'darwin' and platform_machine == 'arm64'
```
which should skip `tensorflow`, and include `tensorflow-macos` and `tensorflow-metal` on mac systems.

**Comment by duelgenji** [comment]
I tried this 
```
tensorflow==2.11.1; sys_platform != 'darwin' or platform_machine != 'arm64'
tensorflow-macos==2.11.0; sys_platform == 'darwin' and platform_machine == 'arm64'
tensorflow-metal==0.7.1; sys_platform == 'darwin' and platform_machine == 'arm64'
```
and got the above error message again

**Comment by ArrowM** [comment]
Got it. Okay, we're narrowing it down.

> It seems like what you typed is not different from the original text.
But I just removed both tensorflow and tensorflow-metal, now i can start the webui and click into the Dreambooth TAB.
and i don't know what issue will occur without the 'tensorflow' package...

Did you try running dreambooth with that configuration? If not, could you please try it and verify that it runs?

If that works. I'll update the requirements accordingly so it'll be fixed for other macos people.

**Comment by duelgenji** [comment]
the success starting requirement.txt file is like this:
```
accelerate==0.17.1
bitsandbytes==0.35.4
dadaptation==1.5.0
diffusers~=0.14.0
discord-webhook~=1.1.0
fastapi~=0.90.1
gitpython~=3.1.31
lion-pytorch~=0.0.7
tensorboard~=2.11.2
tensorflow-macos==2.11.0; sys_platform == 'darwin' and platform_machine == 'arm64'
tqdm~=4.64.1
transformers==4.27.2
```

and there is no 'tensorflow' package in venv/lib/site-packages.

**Comment by ArrowM** [comment]
Yes. Can you please try to train with that setup and verify it runs?

**Comment by duelgenji** [comment]
glad to

<img width="714" alt="image" src="https://user-images.githubusercontent.com/6143263/227243912-56fcb272-7f28-4d39-abb8-a2ec07dd5be4.png">

![image](https://user-images.githubusercontent.com/6143263/227244092-c3bea223-b435-479f-a96a-2a6a5f0eba24.png)

**Comment by ArrowM** [comment]
Does hitting "Train" start training or does it throw an error?

**Comment by ArrowM** [comment]
The model selected has revisions = 0. So I'm guessing you just hit "Create Model". Did you hit the orange "Train" button at all?

**Comment by duelgenji** [comment]
yes, Exception training model: 'No module named 'tensorflow'' occured

**Comment by ArrowM** [comment]
Ooof. Looks like you need tensorflow installed then. I'd recommend searching the web for more info about tensorflow for macos. I don't know any more about it.

**Comment by duelgenji** [comment]
ok i'll try it later, thanks for help
