### ISSUE TITLE
Can we have a way to specify lr_end for polynomial learning rate schedules?

### ISSUE THREAD

**Issue by morphinapg** [d8ahazard/sd_dreambooth_extension#1112]
It seems when using polynomial, the learning rate always ends at 1e-7, and I think there could be some benefit for longer sessions to let it drop even further by the end 

I found in the [code for optimization.py](https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/dreambooth/optimization.py) where it says:

`lr_end ('float', *optional*, defaults to 1e-7)
`

but the code itself always forces it to 1e-7, with no way for the user to modify it from the UI. I can of course modify the code to set it to what I want, but I imagine this will be replaced every time I update the extension, so it would be ideal if there was an option to set this in the UI

**Comment by myndxero** [comment]
I concur since polynomial is my preferred method of training, too.
