### ISSUE TITLE
Installed but not appreared in Tab (Mac M1 Pro)

### ISSUE THREAD

**Issue by yum1573** [d8ahazard/sd_dreambooth_extension#1125]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: bd3fecc3d27d777a4e8f3206a0b16e852877dbad
SD-WebUI revision: 

[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] xformers version 0.0.17+b6be33a.d20230315 installed.
[+] accelerate version 0.17.1 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.27.1 installed.

#######################################################################################################
```

### 2. Describe the bug
I have installed dreambooth extension on SD automatic1111 and completely restarted webUI. Everything is the latest version. However dreambooth didn't show up in the tab.

<img width="976" alt="Screenshot 2023-03-27 at 1 31 35" src="https://user-images.githubusercontent.com/128035749/227790103-94d9f75b-f148-40cf-b715-c3a5135af5d6.png">

### 4. Environment

What OS?
MacOS 13.2.1 (M1 Pro)

**Comment by ArrowM** [comment]
Please update your extension and report back

**Comment by nbdy-coder** [comment]
extension don't work on amc m1, after download it impossible to relaunch stable diffusion webui

**Comment by ArrowM** [comment]
Post the full startup log

**Comment by nbdy-coder** [comment]
> Post the full startup log

which log setup ?

If i remove the extension, automatic 1111 is working well.
if i checkout on an old commit (like 2 days ago) the extension work.
If i comeback to the last version, i have the error :

`NameError: name 'DreamboothConfig' is not defined
`

That's all.
I'm on mac m1 but the error come from one of the last version because if i rollback on a 2 day old commit it's working

**Comment by yum1573** [comment]
> Please update your extension and report back

I just updated to the lastest version, and the result is the same...
<img width="999" alt="Screenshot 2023-03-27 at 2 28 01" src="https://user-images.githubusercontent.com/128035749/227793258-ab6b0233-8950-483d-97c3-d021a1c74e45.png">

**Comment by ArrowM** [comment]
I don't know how I could be more explicit. I need the logs from the project when it starts up (before you even open a webpage).  This bit:
```
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: 00bd271faffbdfd2988b6cfc9117c67681ee14b7
Installing requirements for Web UI


If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
```

**Comment by ArrowM** [comment]
Also, please try this:
https://github.com/d8ahazard/sd_dreambooth_extension/issues/1124#issuecomment-1484164689

**Comment by Zuco-M** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/124027906/228470727-67b244a7-8f2a-4c8e-a1cc-b11822c4001c.png">
Maybe this is the reason, but I don't know how to fix it. Mac can't install xformers

**Comment by ArrowM** [comment]
> Maybe this is the reason

Nope, it's not.
