### ISSUE TITLE
Dreambooth not installing when starting Auto1111

### ISSUE THREAD

**Issue by dr-dark-flames** [d8ahazard/sd_dreambooth_extension#1126]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 0. Initial troubleshooting
Please check each of these before opening an issue. If you've checked them, **delete this section of your bug report**. Have you:
- Updated the Stable-Diffusion-WebUI to the latest version?
- Updated Dreambooth to the latest revision?
- Completely restarted the stable-diffusion-webUI, not just reloaded the UI?
- Read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?

### 1. Please find the following lines in the console and paste them below.

```
Error running install.py for extension B:\Apps\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension.
Command: "B:\Apps\Stable Diffusion\stable-diffusion-webui\venv\Scripts\python.exe" "B:\Apps\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 3324b6ab7fa661cf7d6b5ef186227dc5e8ad1878
Successfully installed accelerate-0.17.1 fastapi-0.90.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 starlette-0.23.1 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.17rc482 installed.
[+] torch version 2.0.0+cu117 installed.
[+] torchvision version 0.15.1+cu117 installed.

stderr: Traceback (most recent call last):
  File "B:\Apps\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 35, in <module>
    actual_install()
  File "B:\Apps\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 47, in actual_install
    check_versions()
  File "B:\Apps\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 169, in check_versions
    if required_comparison == "min" and Version(installed_ver) < Version(required_version):
  File "B:\Apps\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\packaging\version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'None'
```

### 2. Describe the bug

I dont even know whats the bug its just not starting as u can see above

### 3. Provide logs

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```st
PASTE YOUR STACKTRACE HERE
```

### 4. Environment

What OS?

If Windows - WSL or native?

What GPU are you using?

Windows 11, Nvidia RTX 3080ti

**Comment by ArrowM** [comment]
What version of python?

**Comment by ArrowM** [comment]
Checkout the dev branch, should be fixed:
```
cd extensions/sd_dreambooth_extension
git checkout dev
```

You're probably not using python 3.10 (which is the recommended/required version for A1111, so you might run into other issues)

**Comment by ArrowM** [comment]
I still don't understand why it isn't finding a version for your accelerate library though, very weird

**Comment by dr-dark-flames** [comment]
> Checkout the dev branch, should be fixed:
> 
> ```
> cd extensions/sd_dreambooth_extension
> git checkout dev
> ```
> 
> You're probably not using python 3.10 (which is the recommended/required version for A1111, so you might run into other issues)
my python 3.10.10

**Comment by NthKevkas** [comment]
Hey, I checked out the dev branch and got a pretty big error I'll attach it below.
As stated at the top of the error I am running python 3.10.6
I've got a 3070mobile 8GB VRAM.
Any help would be greatly appreciated!
[DreamboothError.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11144605/DreamboothError.txt)

**Comment by ArrowM** [comment]
Your on an outdated dev commit

**Comment by NthKevkas** [comment]
So just update the extension and I should be good to go?

**Comment by ArrowM** [comment]
You should probably switch back to the main branch  
```
git checkout main
```
then update the extension.
