### ISSUE TITLE
No matching distribution found for xformers==0.0.17.dev447

### ISSUE THREAD

**Issue by chouhai2018** [d8ahazard/sd_dreambooth_extension#1130]
venv "C:\ai\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 5fcd4bfa3d86c3ebf91ff993b6472a68a3a4f6ad
Installing xformers
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\launch.py", line 351, in <module>
    prepare_environment()
  File "C:\ai\stable-diffusion-webui\launch.py", line 270, in prepare_environment
    run_pip(f"install -U -I --no-deps {xformers_package}", "xformers")
  File "C:\ai\stable-diffusion-webui\launch.py", line 129, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "C:\ai\stable-diffusion-webui\launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install xformers.
Command: "C:\ai\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install -U -I --no-deps xformers==0.0.17.dev447 --prefer-binary
Error code: 1
stdout: Looking in indexes: https://mirrors.aliyun.com/pypi/simple/

stderr: ERROR: Could not find a version that satisfies the requirement xformers==0.0.17.dev447 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17.dev480, 0.0.17.dev481, 0.0.17.dev482, 0.0.17.dev483, 0.0.17.dev484, 0.0.17rc481, 0.0.17rc482)
ERROR: No matching distribution found for xformers==0.0.17.dev447

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\ai\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip

**Comment by chouhai2018** [comment]
webui-user-dreambooth.bat

@echo off
set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=  --xformers 
set "XFORMERS_PACKAGE=xformers==0.0.17.dev447"
:: Use the below argument if getting OOM extracting checkpoints
:: set COMMANDLINE_ARGS=--ckptfix
set "REQS_FILE=.\extensions\sd_dreambooth_extension\requirements.txt"
:: Uncomment below to skip trying to install automatically on launch.
:: set "DREAMBOOTH_SKIP_INSTALL=True"
:: Use this to launch with accelerate (Run 'accelerate config' first, launch once without to install dependencies)
:: set ACCELERATE="True"

call webui.bat

**Comment by MajorExe** [comment]
same

**Comment by MajorExe** [comment]
![image](https://user-images.githubusercontent.com/66012519/227940948-fa69770c-88e5-4081-b079-c9d51823aa5f.png)
![image](https://user-images.githubusercontent.com/66012519/227941003-810d065d-2b0a-4da8-8cf2-c6ce0d844df4.png)

**Comment by MajorExe** [comment]
> 

My xformers is 0.0.17rc482
Torch 2.0.0

**Comment by MajorExe** [comment]
> xformers just unpublished the 0.0.17 wheels built with torch 1. You need xformers >= 0.0.17dev because lower versions cause training errors. Your options are:
> 
> * Upgrade to torch2
> 
> ```
> !pip install --force-reinstall torch torchvision --index-url https://download.pytorch.org/whl/cu118
> !pip install --force-reinstall --no-deps --pre xformers
> ```
> 
> or
> 
> * get a torch1 xformers whl by either
>   
>   * finding a cache of the official Dev build
>   * building it yourself

My xformers 0.0.17rc482
Torch 2.0.0

**Comment by ArrowM** [comment]
Oh, remove your xformers arg in the bat file

**Comment by ArrowM** [comment]
The extension versions have already been updated.

**Comment by bartman081523** [comment]
> The extension versions have already been updated. 

Yes and not the xformers version for torch 1.

**Comment by ArrowM** [comment]
All officially hosted wheels of xformers>=0.0.17dev are built with Torch 2 meaning they are not compatible with Torch 1. da8f3fccc806586f71da6619bc2e4d0493ffef70 will print the message below, summarizing the options for xformers installation. If xformers decides to publish torch 1 wheels, I will update the code accordingly.

> Your version of xformers ({xformers_version}) is <= 0.0.17.dev. 
> Publicly hosted Torch1 wheels are no longer available for xformers >= 0.0.17.dev. So the available options are:
> 1. Proceed to use Dreambooth without xformers (you are currently doing this)
> 2. Upgrade to Torch 2 (recommended)
> 3. Build your own Torch 1 Xformers wheel

**Comment by Vigilence** [comment]
**Try the tutorial here - https://www.reddit.com/r/StableDiffusion/comments/12okzjt/installing_xformers_0017_for_dreambooth_breaks/**  

Maybe someone can add it to the extension message when its loading up and to the main page as a solutions for everyone.
