### ISSUE TITLE
UI loses connection to training after a while - new samples stop appearing in UI, as well as status/ETA

### ISSUE THREAD

**Issue by morphinapg** [d8ahazard/sd_dreambooth_extension#1139]
### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
Dreambooth revision: 3324b6ab7fa661cf7d6b5ef186227dc5e8ad1878
Successfully installed accelerate-0.17.1 fastapi-0.90.1 gitpython-3.1.31 requests-2.28.2 starlette-0.23.1 tensorboard-data-server-0.7.0 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.17.dev476 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.17.1 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
```

### 2. Describe the bug

When training, the UI will normally show the latest sample image generated, along with some info about the current progress of training, such as the step #, the current learning rate, the amount of VRAM being used, and the ETA for when it's expected to finish.

After a recent update, something either broke in the extension itself or the webui, and while the beginning of training shows these things just fine, at some point it will just stop updating eventually. The screen will be frozen with the last generated sample and training status. The training will continue in the command line, and the command line keeps updating its progress there, although I've found that the ETA in the UI was a bit better of an estimate for completion time than the command line, which seems to increase and decrease more dramatically at any given moment. 

The point at which it stops updating has been different every session, but with enough steps, it seems to always stop. Some sessions I've had it stop after the first 2 or 3 samples generated, and the most recent training session I've had it go over 13000 steps before freezing. 

Using the latest versions of the webui and dreambooth extension as of posting this. 

### 3. Provide logs

~~If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.~~

_No crash_

### 4. Environment

What OS? Windows 11

If Windows - WSL or native? native

What GPU are you using? RTX 3080 Ti (12 GB)

**Comment by eadnams22** [comment]
Since I use a remote computer a lot of the time, I just point the webui image browser at the models/dreambooth directory and can track the training progress there, including the graphs.

**Comment by ArrowM** [comment]
Can you `git checkout dev` and lmk if it's fixed for you?

**Comment by ArrowM** [comment]
Seems like Base project's upgrade of Gradio from 3.16.2 to 3.23.0 is causing some issues. We'll have to look into it.

**Comment by ArrowM** [comment]
Yeah it looks like there are multiple A1111 issues related to this. For now, the best fix is probably rolling back to an older A1111 commit.

**Comment by morphinapg** [comment]
> Yeah it looks like there are multiple A1111 issues related to this. For now, the best fix is probably rolling back to an older A1111 commit.

Okay, I had a feeling it might be something like this. For now I can work around it until they fix.
