### ISSUE TITLE
name 'DreamboothConfig' is not defined

### ISSUE THREAD

**Issue by Zuco-M** [d8ahazard/sd_dreambooth_extension#1140]
Apple M1 Pro, 16GB, 13.0 (22A380)

here is the problem

![issue](https://user-images.githubusercontent.com/124027906/228477735-6b738ad2-e95a-4635-b74f-1048ce6d2757.png)

**Comment by ArrowM** [comment]
did not follow template

**Comment by xiaowugeabide** [comment]
I have the same problem

**Comment by CarringtonCreative** [comment]
For anyone battling with this issue I `cd` into `stable-diffusion-webui\extensions\sd_dreambooth_extension` directory and ran `pip install -r requirements.txt` directly. Then I ran `pip install -r requirements.txt` in the `stable-diffusion-webui` directory. After that I reran the webui and I can now see the Dreambooth tab.
