### ISSUE TITLE
Switch to tensorflow 2.10.0

### ISSUE THREAD

**Issue by abel1502** [d8ahazard/sd_dreambooth_extension#1143]
**WHAT**
Tensorflow doesn't support gpu on windows after 2.10, so if no new features are necessary for the operation of the extension, it would be desireable to switch back to that version. While one can adjust it personally, it is reset on every extension update (due to how webui always force-updates everything).

**WHERE**
requirements.txt

**Comment by ArrowM** [comment]
> Tensorflow doesn't support gpu on windows after 2.10

It seems to be working fine for everyone I've talked to. Do you have a stacktrace?

**Comment by abel1502** [comment]
It does work, but it falls back to cpu. At least, that's what its documentation says:
https://www.tensorflow.org/install/pip#system_requirements

**Comment by ArrowM** [comment]
Good catch. I believe we only use Tensorflow and Tensorboard for graph generation, so GPU access doesn't really matter. I'd like @d8ahazard to verify though.
