### ISSUE TITLE
Too much memory used in text chunks?

### ISSUE THREAD

**Issue by sk8erchen** [d8ahazard/sd_dreambooth_extension#1145]
### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui>git pull
error: Your local changes to the following files would be overwritten by merge:
        requirements_versions.txt
Please commit your changes or stash them before you merge.
Aborting
Updating a9fed7c3..22bcc7be
venv "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI


Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: da2e40415f1cb63cc4de46d6dc97eb8676c6e30c
SD-WebUI revision: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

Successfully installed requests-2.28.2
Successfully installed gitpython-3.1.31

[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[!] xformers NOT installed.
[+] accelerate version 0.17.1 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.27.2 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
```

### 2. Describe the bug

Training stopped shortly after the Train button was hit. I'm not sure what the report meant but it seemed it was because of not enough memory?

**Screenshots/Config**
![Snipaste_2023-03-30_05-10-44](https://user-images.githubusercontent.com/75480055/228669257-d86b2ef3-fef3-48fb-859c-43de79273abc.png)

![Snipaste_2023-03-30_05-11-05](https://user-images.githubusercontent.com/75480055/228669277-1c325a8f-81b6-4c94-9b30-6a9f4d88b405.png)

![Snipaste_2023-03-30_05-11-14](https://user-images.githubusercontent.com/75480055/228669304-096b0957-c9b5-437a-8602-c0cbf3f669fb.png)

![Snipaste_2023-03-30_05-11-23](https://user-images.githubusercontent.com/75480055/228669322-942c88f2-a323-442d-b4ba-1dca6925abed.png)

[db_config.zip](https://github.com/d8ahazard/sd_dreambooth_extension/files/11105519/db_config.zip)

### 3. Provide logs
The entire cmd log as following:

D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui>git pull
error: Your local changes to the following files would be overwritten by merge:
        requirements_versions.txt
Please commit your changes or stash them before you merge.
Aborting
Updating a9fed7c3..22bcc7be
venv "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI

Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: da2e40415f1cb63cc4de46d6dc97eb8676c6e30c
SD-WebUI revision: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

Successfully installed requests-2.28.2
Successfully installed gitpython-3.1.31

[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[!] xformers NOT installed.
[+] accelerate version 0.17.1 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.27.2 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Loading weights [92970aa785] from D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\models\Stable-diffusion\dreamlikePhotoreal20_dreamlikePhotoreal20.safetensors
Creating model from config: D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Textual inversion embeddings skipped(1): cartoonish_doll
Model loaded in 1.8s (create model: 0.2s, apply weights to model: 0.3s, apply half(): 0.3s, move model to device: 0.4s, load textual inversion embeddings: 0.6s).
CUDA SETUP: Loading binary D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Exception importing xformers: No package metadata was found for xformers
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 8.1s (import gradio: 1.5s, import ldm: 0.4s, other imports: 0.9s, list extensions: 0.2s, load scripts: 1.8s, load SD checkpoint: 1.9s, create ui: 1.3s, gradio launch: 0.1s).
Model dir set to: models\dreambooth\m5icon_as_db_v002
Model dir set to: models\dreambooth\m5icon_as_db_v002
Model dir set to: models\dreambooth\m5icon_as_db_v002
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Pre-processing images: training_image:  68%|███████████████████████████▊             | 74/109 [00:00<00:00, 530.00it/s]Exception generating dataset: Too much memory used in text chunks: 201475578>MAX_TEXT_MEMORY
Traceback (most recent call last):
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils\gen_utils.py", line 97, in generate_classifiers
    prompt_dataset = ClassDataset(args.concepts(), args.model_dir, args.resolution, False)
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dataset\class_dataset.py", line 68, in __init__
    instance_prompt_buckets = sort_prompts(concept, text_getter, instance_dir, instance_images[concept_idx], bucket_resos, concept_idx, False, pbar)
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils\image_utils.py", line 113, in sort_prompts
    w, h = get_dim(img, max_dim)
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils\image_utils.py", line 31, in get_dim
    with Image.open(filename) as im:
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3268, in open
    im = _open_core(fp, filename, prefix, formats)
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3254, in _open_core
    im = factory(fp, filename)
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFile.py", line 117, in __init__
    self._open()
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\venv\lib\site-packages\PIL\PngImagePlugin.py", line 750, in _open
    s = self.png.call(cid, pos, length)
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\venv\lib\site-packages\PIL\PngImagePlugin.py", line 205, in call
    return getattr(self, "chunk_" + cid.decode("ascii"))(pos, length)
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\venv\lib\site-packages\PIL\PngImagePlugin.py", line 636, in chunk_iTXt
    self.check_text_memory(len(v))
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\venv\lib\site-packages\PIL\PngImagePlugin.py", line 385, in check_text_memory
    raise ValueError(msg)
ValueError: Too much memory used in text chunks: 201475578>MAX_TEXT_MEMORY
Pre-processing images: training_image:  68%|███████████████████████████▊             | 74/109 [00:00<00:00, 165.89it/s]
Model dir set to: models\dreambooth\m5icon_as_db_v002
Found 0 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (With Caching)
Caching latents...: 0it [00:00, ?it/s]Loading cached latents...
Total Buckets 0 - Instance Images: 0 | Class Images: 0 | Max Examples/batch: 0
Caching latents...: 0it [00:00, ?it/s]
Total images / batch: 0, total examples: 0
Caching latents...: 0it [00:00, ?it/s]
Total dataset length (steps): 0
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 0
  Num Epochs = 100
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 0
  Total optimization steps = 0
  Total training steps = 0
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Optimizer: 8bit AdamW, Prec: no
  Gradient Checkpointing: True
  EMA: False
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 2e-06
  V2: False
Steps: : 0it [00:00, ?it/s]Traceback (most recent call last):
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 724, in start_training
    result = main(class_gen_method=class_gen_method)
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1426, in main
    return inner_loop()
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "D:\Stable-Diffusion-original\SD1.5\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1178, in inner_loop
    latents = batch["images"].to(accelerator.device)
TypeError: 'NoneType' object is not subscriptable
Steps: : 0it [00:00, ?it/s]
Restored system models.
Duration: 00:00:03

### 4. Environment

What OS?
Windows11 64bit pro

If Windows - WSL or native?
native

What GPU are you using?
4090 24g vram

**Comment by ArrowM** [comment]
Weird, that's a Pillow library issue. Do you have an unusual PNG as a source image?

**Comment by sk8erchen** [comment]
I remember I converted some jpeg images into png using some third-party software, let me check

**Comment by sk8erchen** [comment]
Problem solved, one of the png images has unusual file size (192mb?!), I resaved it now the training runs smoothly, thanks!
