### ISSUE TITLE
Error running install.py for extension extensions\sd_dreambooth_extension.

### ISSUE THREAD

**Issue by cfttfc** [d8ahazard/sd_dreambooth_extension#1151]
I get this error.

`venv "D:\Yapay Zeka\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI

Error running install.py for extension extensions\sd_dreambooth_extension.
Command: "D:\Yapay Zeka\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 3324b6ab7fa661cf7d6b5ef186227dc5e8ad1878
# Requirement installation exception:
Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow-metal: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Collecting accelerate==0.17.1
Using cached accelerate-0.17.1-py3-none-any.whl (212 kB)
Collecting bitsandbytes==0.35.4
Using cached bitsandbytes-0.35.4-py3-none-any.whl (62.5 MB)
Requirement already satisfied: dadaptation==1.5.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from -r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 3)) (1.5)
Requirement already satisfied: diffusers~=0.14.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from -r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (0.14.0)
Requirement already satisfied: discord-webhook~=1.1.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from -r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (1.1.0)
Collecting fastapi~=0.90.1
Using cached fastapi-0.90.1-py3-none-any.whl (56 kB)
Collecting gitpython~=3.1.31
Using cached GitPython-3.1.31-py3-none-any.whl (184 kB)
Requirement already satisfied: lion-pytorch~=0.0.7 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from -r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.0.7)
Collecting tensorboard~=2.12.0
Using cached tensorboard-2.12.0-py3-none-any.whl (5.6 MB)
Collecting tensorflow==2.12.0
Using cached tensorflow-2.12.0-cp310-cp310-win_amd64.whl (1.9 kB)
Requirement already satisfied: tqdm~=4.64.1 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from -r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 13)) (4.64.1)
Collecting transformers==4.26.1
Using cached transformers-4.26.1-py3-none-any.whl (6.3 MB)
Requirement already satisfied: torch>=1.4.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.17.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.13.1+cu117)
Requirement already satisfied: packaging>=20.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.17.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (23.0)
Requirement already satisfied: pyyaml in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.17.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (6.0)
Requirement already satisfied: psutil in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.17.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (5.9.4)
Requirement already satisfied: numpy>=1.17 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.17.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.23.3)
Collecting tensorflow-intel==2.12.0
Using cached tensorflow_intel-2.12.0-cp310-cp310-win_amd64.whl (272.8 MB)
Requirement already satisfied: filelock in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.26.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (3.9.0)
Requirement already satisfied: regex!=2019.12.17 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.26.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2022.10.31)
Requirement already satisfied: requests in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.26.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2.25.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.26.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (0.13.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.26.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (0.13.2)
Requirement already satisfied: opt-einsum>=2.3.2 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (3.3.0)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (0.4.0)
Requirement already satisfied: setuptools in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (63.2.0)
Requirement already satisfied: h5py>=2.9.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (3.8.0)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3
Using cached protobuf-4.22.1-cp310-abi3-win_amd64.whl (420 kB)
Requirement already satisfied: typing-extensions>=3.6.6 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (4.5.0)
Collecting tensorflow-estimator<2.13,>=2.12.0
Using cached tensorflow_estimator-2.12.0-py2.py3-none-any.whl (440 kB)
Collecting keras<2.13,>=2.12.0
Using cached keras-2.12.0-py2.py3-none-any.whl (1.7 MB)
Requirement already satisfied: astunparse>=1.6.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (1.6.3)
Collecting jax>=0.3.15
Using cached jax-0.4.8-py3-none-any.whl
Requirement already satisfied: libclang>=13.0.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (15.0.6.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (0.31.0)
Requirement already satisfied: flatbuffers>=2.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (23.3.3)
Requirement already satisfied: absl-py>=1.0.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (1.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (0.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (1.51.3)
Requirement already satisfied: termcolor>=1.1.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (2.2.0)
Requirement already satisfied: six>=1.12.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (1.16.0)
Collecting wrapt<1.15,>=1.11.0
Using cached wrapt-1.14.1-cp310-cp310-win_amd64.whl (35 kB)
Requirement already satisfied: importlib-metadata in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from diffusers~=0.14.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (6.1.0)
Requirement already satisfied: Pillow in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from diffusers~=0.14.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (9.4.0)
Collecting requests
Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from fastapi~=0.90.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (1.10.6)
Collecting starlette<0.24.0,>=0.22.0
Using cached starlette-0.23.1-py3-none-any.whl (64 kB)
Requirement already satisfied: gitdb<5,>=4.0.1 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from gitpython~=3.1.31->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 7)) (4.0.10)
Requirement already satisfied: werkzeug>=1.0.1 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorboard~=2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.2.3)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorboard~=2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.4.6)
Collecting tensorboard-data-server<0.8.0,>=0.7.0
Using cached tensorboard_data_server-0.7.0-py3-none-any.whl (2.4 kB)
Requirement already satisfied: google-auth<3,>=1.6.3 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorboard~=2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.16.2)
Requirement already satisfied: wheel>=0.26 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorboard~=2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.38.4)
Requirement already satisfied: markdown>=2.6.8 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorboard~=2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (3.4.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tensorboard~=2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (1.8.1)
Requirement already satisfied: colorama in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from tqdm~=4.64.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 13)) (0.4.6)
Requirement already satisfied: smmap<6,>=3.0.1 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from gitdb<5,>=4.0.1->gitpython~=3.1.31->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 7)) (5.0.0)
Requirement already satisfied: rsa<5,>=3.1.4 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from requests->transformers==4.26.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from requests->transformers==4.26.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from requests->transformers==4.26.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from requests->transformers==4.26.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (1.26.15)
Requirement already satisfied: anyio<5,>=3.4.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from starlette<0.24.0,>=0.22.0->fastapi~=0.90.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (3.6.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.1.2)
Requirement already satisfied: zipp>=0.5 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from importlib-metadata->diffusers~=0.14.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.15.0)
Requirement already satisfied: sniffio>=1.1 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from anyio<5,>=3.4.0->starlette<0.24.0,>=0.22.0->fastapi~=0.90.1->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (1.3.0)
Collecting ml-dtypes>=0.0.3
Using cached ml_dtypes-0.0.4-cp310-cp310-win_amd64.whl (98 kB)
Requirement already satisfied: scipy>=1.7 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from jax>=0.3.15->tensorflow-intel==2.12.0->tensorflow==2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (1.10.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard~=2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in d:\yapay zeka\stable-diffusion-webui\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.12.0->-r D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (3.2.2)
Installing collected packages: bitsandbytes, wrapt, tensorflow-estimator, tensorboard-data-server, requests, protobuf, ml-dtypes, keras, starlette, jax, gitpython, accelerate, transformers, fastapi, tensorboard, tensorflow-intel, tensorflow
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'D:\\Yapay Zeka\\stable-diffusion-webui\\venv\\Lib\\site-packages\\bitsandbytes\\__init__.py'

stderr: Traceback (most recent call last):
  File "D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 35, in <module>
    actual_install()
  File "D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 41, in actual_install
    install_requirements()
  File "D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 87, in install_requirements
    raise grepexc
  File "D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 75, in install_requirements
    pip_install("-r", req_file)
  File "D:\Yapay Zeka\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 53, in pip_install
    output = subprocess.check_output(
  File "D:\Yapay Zeka\stable-diffusion-portable-main\python\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Yapay Zeka\stable-diffusion-portable-main\python\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\Yapay Zeka\\stable-diffusion-webui\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', '-r', 'D:\\Yapay Zeka\\stable-diffusion-webui\\extensions\\sd_dreambooth_extension\\requirements.txt']' returned non-zero exit status 1.

Launching Web UI with arguments: --xformers
Loading weights [d8691b4d16] from D:\Yapay Zeka\stable-diffusion-webui\models\Stable-diffusion\Deliberate.safetensors
Creating model from config: D:\Yapay Zeka\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 2.9s (create model: 0.4s, apply weights to model: 0.6s, apply half(): 0.7s, move model to device: 0.5s, load textual inversion embeddings: 0.7s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 12.7s (import gradio: 2.3s, import ldm: 2.1s, other imports: 1.2s, list extensions: 0.4s, load scripts: 1.8s, load SD checkpoint: 3.0s, create ui: 1.6s, gradio launch: 0.2s).
`

**Comment by samsamm777** [comment]
Im having the same issue

**Comment by Sayo0616** [comment]
I have met this issue too. There is a console prompt: " ModuleNotFoundError: No module named '_socket' ".

**Comment by Armingleggings** [comment]
Same problem exactly. I open the extensions tab in SD web gui, find dreambooth, click install, then close the terminal entirely and restart to a string of new errors that disappear if I delete the dreambooth extension folder. Errors include  ModuleNotFoundError: No module named '_socket' " and "AttributeError: partially initialized module 'modules.sysinfo' has no attribute 'format_exception' (most likely due to a circular import)"... I looked at the readme and saw the batch file that you can use to set environment variables to help with install, but no combination of those I can find fixed the problem. Do we just give up? I see that most of these comments were from back in may or before - did this get fixed somehow?

**Comment by uguryagarr** [comment]
Any news about solution ?
