### ISSUE TITLE
Exception training model: 'No module named 'tensorflow.python.framework.random_seed''.

### ISSUE THREAD

**Issue by highjohnconquer** [d8ahazard/sd_dreambooth_extension#1168]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 0. Initial troubleshooting
Please check each of these before opening an issue. If you've checked them, **delete this section of your bug report**. Have you:
- Updated the Stable-Diffusion-WebUI to the latest version?
- Updated Dreambooth to the latest revision?
- Completely restarted the stable-diffusion-webUI, not just reloaded the UI?
- Read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?

### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI

If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
# Your version of xformers is 0.0.16rc425.
# xformers >= 0.0.17.dev is required to be available on the Dreambooth tab.
# Torch 1 wheels of xformers >= 0.0.17.dev are no longer available on PyPI,
# but you can manually download them by going to:
https://github.com/facebookresearch/xformers/actions
# Click on the most recent action tagged with a release (middle column).
# Select a download based on your environment.
# Unzip your download
# Activate your venv and install the wheel: (from A1111 project root)
cd venv/Scripts
activate
pip install {REPLACE WITH PATH TO YOUR UNZIPPED .whl file}
# Then restart your project.
[!] xformers version 0.0.16rc425 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
```

### 2. Describe the bug

Whenever I try to train the UI gives this error: Exception training model: 'No module named 'tensorflow.python.framework.random_seed''.

**Screenshots/Config**
{
    "adamw_weight_decay": 0.01,
    "adaptation_beta1": 0,
    "adaptation_beta2": 0,
    "adaptation_d0": 1e-08,
    "adaptation_eps": 1e-08,
    "attention": "default",
    "cache_latents": false,
    "clip_skip": 1,
    "concepts_list": [
        {
            "class_data_dir": "E:\\Pictures\\Regularization Images\\woman_v1-5_mse_vae_ddim50_cfg7_n4420",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "class_negative_prompt": "(((deformed))), blurry, bad anatomy, disfigured, poorly drawn face, mutation, mutated, (extra_limb), (ugly), (poorly drawn hands), fused fingers, messy drawing",
            "class_prompt": "a photo of woman",
            "class_token": "",
            "instance_data_dir": "E:\\Documents\\khoya models\\ToniRizzo_Lora\\image\\67_ToniRizzo woman",
            "instance_prompt": "a photo of ToniRizzo woman",
            "instance_token": "",
            "is_valid": true,
            "n_save_sample": 1,
            "num_class_images_per": 0,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 20,
            "save_sample_negative_prompt": "(((deformed))), blurry, bad anatomy, disfigured, poorly drawn face, mutation, mutated, (extra_limb), (ugly), (poorly drawn hands), fused fingers, messy drawing,",
            "save_sample_prompt": "anime portrait of ToniRizzo woman",
            "save_sample_template": ""
        }
    ],
    "concepts_path": "",
    "custom_model_name": "ToniRizzo",
    "noise_scheduler": "DDPM",
    "deterministic": false,
    "ema_predict": true,
    "epoch": 0,
    "epoch_pause_frequency": 0,
    "epoch_pause_time": 0,
    "freeze_clip_normalization": false,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "gradient_set_to_none": true,
    "graph_smoothing": 50,
    "half_model": false,
    "train_unfrozen": false,
    "has_ema": false,
    "hflip": false,
    "infer_ema": true,
    "initial_revision": 0,
    "learning_rate": 2e-06,
    "learning_rate_min": 1e-06,
    "lifetime_revision": 0,
    "lora_learning_rate": 0.0001,
    "lora_model_name": "",
    "lora_unet_rank": 128,
    "lora_txt_rank": 128,
    "lora_txt_learning_rate": 5e-05,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "cosine_with_restarts",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "mixed_precision": "no",
    "model_name": "Rizzo3",
    "model_dir": "E:\\Documents\\AI\\stable-diffusion-webui\\models\\dreambooth\\Rizzo3",
    "model_path": "E:\\Documents\\AI\\stable-diffusion-webui\\models\\dreambooth\\Rizzo3",
    "num_train_epochs": 67,
    "offset_noise": 0,
    "optimizer": "8bit AdamW",
    "pad_tokens": true,
    "pretrained_model_name_or_path": "E:\\Documents\\AI\\stable-diffusion-webui\\models\\dreambooth\\Rizzo3\\working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_scale": false,
    "prior_loss_target": 100.0,
    "prior_loss_weight": 0.75,
    "prior_loss_weight_min": 0.1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 1,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": false,
    "save_ckpt_cancel": false,
    "save_ckpt_during": false,
    "save_ema": true,
    "save_embedding_every": 25,
    "save_lora_after": true,
    "save_lora_cancel": true,
    "save_lora_during": true,
    "save_lora_for_extra_net": true,
    "save_preview_every": 5,
    "save_safetensors": true,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "scheduler": "DEISMultistep",
    "shuffle_tags": true,
    "snapshot": "",
    "split_loss": true,
    "src": "E:\\Documents\\AI\\stable-diffusion-webui\\models\\Stable-diffusion\\v1-5-pruned.ckpt",
    "stop_text_encoder": 0,
    "strict_tokens": false,
    "tf32_enable": false,
    "train_batch_size": 1,
    "train_imagic": false,
    "train_unet": true,
    "use_concepts": false,
    "use_ema": false,
    "use_lora": true,
    "use_lora_extended": true,
    "use_subdir": false,
    "v2": false
}

### 3. Provide logs

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```st
venv "E:\Documents\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI

If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
# Your version of xformers is 0.0.16rc425.
# xformers >= 0.0.17.dev is required to be available on the Dreambooth tab.
# Torch 1 wheels of xformers >= 0.0.17.dev are no longer available on PyPI,
# but you can manually download them by going to:
https://github.com/facebookresearch/xformers/actions
# Click on the most recent action tagged with a release (middle column).
# Select a download based on your environment.
# Unzip your download
# Activate your venv and install the wheel: (from A1111 project root)
cd venv/Scripts
activate
pip install {REPLACE WITH PATH TO YOUR UNZIPPED .whl file}
# Then restart your project.
[!] xformers version 0.0.16rc425 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Hypernetwork-MonkeyPatch-Extension found!
Loading weights [61615d411a] from E:\Documents\AI\stable-diffusion-webui\models\Stable-diffusion\4000 Step JohanK\JKiriyoba_step_4000.ckpt
Creating model from config: E:\Documents\AI\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(58): 7dirtywords, advntr, angry512, arcan3, arcan3v2, art by Smoose2, bad-artist-anime, bad-artist, bad-hands-5, bad_prompt, bad_prompt_version2, cardstyle15, charturnerv2, clrs, corneo_spitroast, darkskin_style, defiance512, easynegative, eonn, flame_surge_style, fs2023, ghst-3000, gigaschizonegs, grin512, gustavedore, happy512, hoppagames, laugh512, magicalinterior, nervous512, ng_deepnegative_v1_75t, PlanIt, rfktr_bwmnga, RFKTR_plastic, rosalinenobodysd15, sad512, shock512, smile512, Style-Autumn, style-empire-neg, style-empire, style-hamunaptra, Style-Moana-neg, Style-Moana, Style-NebMagic, Style-Necromancy, Style-Petal-neg, Style-Petal, Style-Psycho-neg, Style-Renaissance-neg, Style-Renaissance, style-rustmagic, Style-Winter-neg, Style-Winter, tarot512, wholesomegrandpas, wholesomegrannies, _stardeaf-greenmageddon_
Textual inversion embeddings skipped(6): 21charturnerv2, InkPunk768, inksketchcolour1subtle, SDA768, UlukInkSketch2, Zootopiav4
Model loaded in 3.7s (load weights from disk: 0.8s, create model: 0.4s, apply weights to model: 0.5s, apply half(): 0.6s, move model to device: 0.5s, load textual inversion embeddings: 0.9s).
CUDA SETUP: Loading binary E:\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Startup time: 11.8s (import torch: 1.8s, import gradio: 1.4s, import ldm: 0.4s, other imports: 1.0s, load scripts: 1.7s, load SD checkpoint: 3.8s, create ui: 1.4s, gradio launch: 0.1s).
Initializing dreambooth training...
Traceback (most recent call last):
  File "E:\Documents\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 724, in start_training
    from dreambooth.train_dreambooth import main  # noqa
  File "E:\Documents\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 30, in <module>
    from tensorflow.python.framework.random_seed import set_seed as set_seed1
ModuleNotFoundError: No module named 'tensorflow.python.framework.random_seed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Documents\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 726, in start_training
    from dreambooth.train_dreambooth import main  # noqa
  File "E:\Documents\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 30, in <module>
    from tensorflow.python.framework.random_seed import set_seed as set_seed1
ModuleNotFoundError: No module named 'tensorflow.python.framework.random_seed'
Restored system models.
Duration: 00:00:01
```

### 4. Environment

What OS?

Windows

If Windows - WSL or native?

Native

What GPU are you using?
GeForce RTX 3090

**Comment by ArrowM** [comment]
Weird. Try reinstalling tensorflow `pip install --force-reinstall tensorflow`
