### ISSUE TITLE
Unable to Use Classification Images | Class Images: 0 

### ISSUE THREAD

**Issue by N0repi** [d8ahazard/sd_dreambooth_extension#1180]
### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Python 3.10.8 (main, Feb  6 2023, 18:08:25) [GCC 9.5.0]
Commit hash: a9eab236d7e8afa4d6205127904a385b2c43bb24
Installing requirements for Web UI
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
[+] xformers version 0.0.18.dev504 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.


#######################################################################################################
```

### 2. Describe the bug

I am unable to train with existing classification images/reg images. I have tried unchecking "Use Concepts List" and manually entering a concept in the UI, adding my class images path db_config.json, altering my concepts list json file, and switching to torch 2.0 and cuda-11.8. I thought that the issue might be caused by my concepts using the same "class_data_dir", but the issue occurs when only training 1 concept.

This has been an existing issue for me for quite some time. The DreamBooth extension is able to load and train with classification images using commit 4ca69a904f5ddd5651d87032b3dca515eea505ba, but it is not able to using any recent commits.

I have provided screenshots of my db_config.json and the json I am using as my concepts list. The concepts list includes 10 concepts with the same parameters, just different instance_data_dir and prompts, so I only provided 1 screenshot.

**Screenshots/Config**
![concepts_list_screenshot01](https://user-images.githubusercontent.com/29762511/231284339-5c151e88-fd8c-4518-9a01-ab7c4d258ea6.png)
![db_config_screenshot01](https://user-images.githubusercontent.com/29762511/231284342-52e1b9a9-fd05-4c6e-8bd1-a555c81e70cb.png)
![db_config_screenshot02](https://user-images.githubusercontent.com/29762511/231284344-3074fdbc-a07f-4258-9336-73d322e587b2.png)

### 3. Provide logs
```st
Pred and size are epsilon and 512, using config: /mnt/NAS/AI-ML/SD/SD_newer/working_DB_version/testing/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/../configs/v1-training-default.yaml
v1 model loaded.
Trying to load: /mnt/NAS/AI-ML/SD/SD_newer/working_DB_version/testing/stable-diffusion-webui/models/Stable-diffusion/anyv3-dream.55.yaml
Converting unet...
Converting vae...
Converting text encoder...
Saving text_encoder
Saving tokenizer
Checkpoint successfully extracted to /mnt/NAS/AI-ML/SD/SD_newer/working_DB_version/testing/stable-diffusion-webui/models/dreambooth/test_model24/working
Restored system models.
Duration: 00:01:28
Updating scheduler name to: DDIM
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Pre-processing images: forModel2: : 0it [00:00, ?it/s]                                                                      
Nothing to generate.
Found 0 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (With Caching)
Bucket  0 (512, 512, 0) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  1 (512, 512, 1) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  2 (512, 512, 2) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  3 (512, 512, 3) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  4 (512, 512, 4) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  5 (512, 512, 5) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  6 (512, 512, 6) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  7 (512, 512, 7) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  8 (512, 512, 8) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  9 (512, 512, 9) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Caching latents...: 100%|█████████████████████████████████████████████████████████████████| 300/300 [00:28<00:00, 14.73it/s]Saving cache!
Total Buckets 10 - Instance Images: 300 | Class Images: 0 | Max Examples/batch: 300                                         
Caching latents...: 100%|█████████████████████████████████████████████████████████████████| 300/300 [00:28<00:00, 14.73it/s]
Total images / batch: 300, total examples: 300
Caching latents...: 100%|█████████████████████████████████████████████████████████████████| 300/300 [00:28<00:00, 10.52it/s]
Total dataset length (steps): 300
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 300
  Num Epochs = 10
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 0
  Total optimization steps = 3000
  Total training steps = 3000
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Optimizer: 8bit AdamW, Prec: no
  Gradient Checkpointing: False
  EMA: False
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 2e-06
  V2: False
```

### 4. Environment

What OS? Linux
Ubuntu 22.04

What GPU are you using? RTX 3090

**Comment by ArrowM** [comment]
There's an option for this coming in the next update. If you want to try out the experimental branch that has it already you can use `git checkout dev` in the extension directory

**Comment by N0repi** [comment]
> There's an option for this coming in the next update. If you want to try out the experimental branch that has it already you can use `git checkout dev` in the extension directory

Thank you for your reply.  Where is the option in the experimental branch? Checking  the Concepts List box has the same results.

**Comment by N0repi** [comment]
> ![image](https://user-images.githubusercontent.com/42418080/231325402-96532203-06db-489d-a2d9-e90c3ffdf609.png)

I can't seem to get the new option to work. All of my tests still result in:

```st
Bucket  0 (512, 512, 0) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  1 (512, 512, 1) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  2 (512, 512, 2) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  3 (512, 512, 3) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  4 (512, 512, 4) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  5 (512, 512, 5) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  6 (512, 512, 6) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  7 (512, 512, 7) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  8 (512, 512, 8) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30                                  
Bucket  9 (512, 512, 9) - Instance Images:  30 | Class Images: 0 | Max Examples/batch:  30  
```

**Comment by N0repi** [comment]
@ArrowM I'm looking through dreambooth/dataset/class_dataset.py as well as dreambooth/utils/image_utils.py and trying to figure out what isn't working. What files do you recommend I look through?

**Comment by ArrowM** [comment]
`disable_class_matching` @ dreambooth/dataset/class_dataset.py:74

**Comment by ArrowM** [comment]
Also, did you set the # of class images on the concepts tab? You still need to do this 
![image](https://user-images.githubusercontent.com/42418080/232600575-76727031-ff2f-424d-a59f-f8d6e035f86b.png)

**Comment by N0repi** [comment]
> `disable_class_matching` @ dreambooth/dataset/class_dataset.py:74 . Looks like you have an ide setup; you should be able to set a breakpoint at that line and step through `sort_prompts` to see how it is collecting and processing the class pics.

Thanks for your reply. I'll give that a shot.



> Also, did you set the # of class images on the concepts tab? You still need to do this ![image](https://user-images.githubusercontent.com/42418080/232600575-76727031-ff2f-424d-a59f-f8d6e035f86b.png)

I did not set 'class images per instance image'. Do I need to set a value when using an existing class images, or only when generating images?

**Comment by ArrowM** [comment]
You always need to set that if you want to use class images. Atm. I think that behavior is fine, but you can make a PR if you want other option.

**Comment by EEWenbinWu** [comment]
the latest version cannot find disable_class_matching

**Comment by N0repi** [comment]
> You always need to set that if you want to use class images. Atm. I think that behavior is fine, but you can make a PR if you want other option.

I got it working. Thank you so much! When using a json file for concepts list, I have to enter a value with the parameter ``` "num_class_images_per" ``` for DreamBooth to use existing class images. Using the slider without specifying this parameter results the " Class Images: 0 " issue.

I'm using commit 22bcc7be428c94e9408f589966c2040187245d81 .

**Comment by EEWenbinWu** [comment]
I have 18 train images, then set num_class_images_per=45, and I prepare 18*45=810  existing class images, however, when start training , it still generate 495 class images, why?

**Comment by N0repi** [comment]
> I have 18 train images, then set num_class_images_per=45, and I prepare 18*45=810  existing class images, however, when start training , it still generate 495 class images, why?

Can you send me your log? I might have experienced the same issue while testing on one of my test_models.
By seeing your log, I can explain what is happening and how to fix it.

**Comment by allroundHim** [comment]
> 



> Also, did you set the # of class images on the concepts tab? You still need to do this ![image](https://user-images.githubusercontent.com/42418080/232600575-76727031-ff2f-424d-a59f-f8d6e035f86b.png)

Hello, I've pull the latest dev branch but still not see this in my testing tab
![image](https://user-images.githubusercontent.com/125340504/235375700-6bc98551-68d4-460c-b04f-ff4088c0492e.png)


btw, my intension is to use existing (not squared) images I found somewhere else and thrown them to the classification image folder.

**Comment by rudimytro** [comment]
Also in my case generated class images resolution is 624x416 pixels instead of 512x512, although I use the base 1.5v model and put 512x512 everywhere in the settings

**Comment by gurelkaynak** [comment]
I have the same issue, I generated 300 images under "classimages" folder but dreambooth does not detect those images and tries to create new ones.
