### ISSUE TITLE
CUDA out of memory - I tryied everything

### ISSUE THREAD

**Issue by SilveRider76** [d8ahazard/sd_dreambooth_extension#1182]
I've try everything, but I got always Cuda out of memory. I don't know but I suspect there is a problem with bitsandbytes: 
I suspect that the file: libbitsandbytes_cudaall.dll is the problem.

but it's only a suspect nothing else.

I've attacched the log, the parametres and crash.
I've already try to:
1) Restart the PC
2) Deleting and reinstall Dreambooth
3) Reinstall again Stable Diffusion
4) Changing the "model" to SD to a Realistic Vision (1.3, 1.4 and 2.0)
5) Changing the parameters of batching 

Asus DUAL -  nVidia 2060 with 12Gb of Vram
Windows 11 Pro - 64bit - 32gb ram, Intel I7, sedicated SSD 500 to Stable Diffusion.

Nothing change, always got this problem.
I'm going crazy...

#######################################################################################################
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading A111 WebUI Launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Settings file found, loading
 →   Updating Settings File  ✓
 i   Launcher Version 1.7.0
 i   Found a custom WebUI Config
 i   No Launcher launch options
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Checking requirements :
 i   Python 3.10.6150.1013 found in registry:  C:\Users\Silver\AppData\Local\Programs\Python\Python310\
 i   Clearing PATH of any mention of Python
 →   Adding python 3.10 to path  ✓
 i   Git found and already in PATH:  D:\Program Files\Git\cmd\git.exe
 i   Automatic1111 SD WebUI found:  G:\ASD1111\stable-diffusion-webui
 i   One or more checkpoint models were found
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading Complete, opening launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Arguments are now: --medvram --xformers --ckpt-dir 'G:\CKPT' --vae-path 'G:\vae-ft-ema-560000-ema-pruned.ckpt' --opt-sdp-attention --opt-sub-quad-attention
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Webui
 ✓   Done
 i   Arguments are now: --medvram --xformers --ckpt-dir 'G:\CKPT' --vae-path 'G:\vae-ft-ema-560000-ema-pruned.ckpt' --opt-sdp-attention --opt-sub-quad-attention
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  WEBUI LAUNCHING VIA EMS LAUNCHER, EXIT THIS WINDOW TO STOP THE WEBUI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 !   Any error happening after 'commit hash : XXXX' is not related to the launcher. Please report them on Automatic1111's github instead :
 ☁   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cancel
venv "G:\ASD1111\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed google-auth-oauthlib-0.4.6 requests-2.28.2
[+] xformers version 0.0.18 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --autolaunch --medvram --xformers --ckpt-dir G:\CKPT --vae-path G:\vae-ft-ema-560000-ema-pruned.ckpt --opt-sdp-attention --opt-sub-quad-attention
G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Loading weights [81086e2b3f] from G:\CKPT\realisticVisionV20_v20.ckpt
Creating model from config: G:\ASD1111\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights from commandline argument: G:\vae-ft-ema-560000-ema-pruned.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(2): L4V1c4-txt, LaVica
Model loaded in 26.2s (load weights from disk: 18.9s, create model: 1.4s, apply weights to model: 1.0s, apply half(): 2.3s, load VAE: 2.6s).
CUDA SETUP: Loading binary G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 51.7s (import torch: 13.0s, import gradio: 1.1s, import ldm: 1.7s, other imports: 3.7s, list SD models: 0.8s, setup codeformer: 0.3s, load scripts: 3.3s, load SD checkpoint: 26.4s, create ui: 0.9s, gradio launch: 0.4s).
Using CPU for extraction.
Loading model from checkpoint.
Loading ckpt...
Pred and size are epsilon and 512, using config: G:\ASD1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\..\configs\v1-training-default.yaml
v1 model loaded.
Trying to load: G:\ASD1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\..\configs\v1-training-default.yaml
Converting unet...
Converting vae...
Converting text encoder...
Saving text_encoder
Saving tokenizer
Checkpoint successfully extracted to G:\ASD1111\stable-diffusion-webui\models\dreambooth\Lucr3s14-V20-NEW\working
Restored system models.
Duration: 00:00:42
Updating scheduler name to: DDIM
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Pre-processing images: Portrait512: : 0it [00:00, ?it/s]
Nothing to generate.
Found 0 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (Without Caching)
Bucket 0 (512, 512, 0) - Instance Images: 12 | Class Images: 0 | Max Examples/batch: 12
Total Buckets 1 - Instance Images: 12 | Class Images: 0 | Max Examples/batch: 12
Processing images...: 100%|████████████████████████████████████████████████████████████████████| 12/12 [00:00<?, ?it/s]
Total images / batch: 12, total examples: 12
Processing images...: 100%|█████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 12000.87it/s]
Total dataset length (steps): 12
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 12
  Num Epochs = 300
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 210
  Total optimization steps = 3600
  Total training steps = 3600
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Optimizer: 8bit AdamW, Prec: fp16
  Gradient Checkpointing: True
  EMA: True
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 1e-06
  V2: False
Steps:   0%|                                                                                  | 0/3600 [00:00<?, ?it/s]OOM Detected, reducing batch/grad size to 0/1.
Traceback (most recent call last):
  File "G:\ASD1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "G:\ASD1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1245, in inner_loop
    ema_model.step(unet)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\ASD1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\helpers\ema_model.py", line 112, in step
    ema_param.add_(param.to(dtype=ema_param.dtype), alpha=1 - decay)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 12.00 GiB total capacity; 11.04 GiB already allocated; 0 bytes free; 11.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0%|                                                                                  | 0/3600 [00:33<?, ?it/s]
Traceback (most recent call last):
  File "G:\ASD1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 727, in start_training
    result = main(class_gen_method=class_gen_method)
  File "G:\ASD1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1371, in main
    return inner_loop()
  File "G:\ASD1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 117, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
RuntimeError: No executable batch size found, reached zero.
Restored system models.
Duration: 00:01:32

#######################################################################################################
```


### 2. Describe the bug

**Screenshots/Config**
{
    "adamw_weight_decay": 0.01,
    "adaptation_beta1": 0,
    "adaptation_beta2": 0,
    "adaptation_d0": 1e-08,
    "adaptation_eps": 1e-08,
    "attention": "xformers",
    "cache_latents": false,
    "clip_skip": 1,
    "concepts_list": [
        {
            "class_data_dir": "G:\\RegImages2",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "class_negative_prompt": "",
            "class_prompt": "photo of a young woman",
            "class_token": "",
            "instance_data_dir": "G:\\Lucresia\\Portrait512",
            "instance_prompt": "Lucr3s14 a young woman",
            "instance_token": "",
            "is_valid": true,
            "n_save_sample": 1,
            "num_class_images_per": 0,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 20,
            "save_sample_negative_prompt": "",
            "save_sample_prompt": "photo of Lucr3s14 a young woman",
            "save_sample_template": ""
        }
    ],
    "concepts_path": "",
    "custom_model_name": "",
    "noise_scheduler": "DDPM",
    "deterministic": false,
    "ema_predict": false,
    "epoch": 0,
    "epoch_pause_frequency": 0,
    "epoch_pause_time": 0,
    "freeze_clip_normalization": false,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "gradient_set_to_none": false,
    "graph_smoothing": 50,
    "half_model": false,
    "train_unfrozen": false,
    "has_ema": false,
    "hflip": false,
    "infer_ema": false,
    "initial_revision": 0,
    "learning_rate": 1e-06,
    "learning_rate_min": 1e-06,
    "lifetime_revision": 0,
    "lora_learning_rate": 0.0001,
    "lora_model_name": "",
    "lora_unet_rank": 4,
    "lora_txt_rank": 4,
    "lora_txt_learning_rate": 5e-05,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant_with_warmup",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "mixed_precision": "fp16",
    "model_name": "Lucr3s14-V20-NEW",
    "model_dir": "G:\\ASD1111\\stable-diffusion-webui\\models\\dreambooth\\Lucr3s14-V20-NEW",
    "model_path": "G:\\ASD1111\\stable-diffusion-webui\\models\\dreambooth\\Lucr3s14-V20-NEW",
    "num_train_epochs": 300,
    "offset_noise": 0,
    "optimizer": "8bit AdamW",
    "pad_tokens": true,
    "pretrained_model_name_or_path": "G:\\ASD1111\\stable-diffusion-webui\\models\\dreambooth\\Lucr3s14-V20-NEW\\working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_scale": false,
    "prior_loss_target": 100.0,
    "prior_loss_weight": 0.75,
    "prior_loss_weight_min": 0.1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 1,
    "sanity_prompt": "Lucr3s14 photo of a young woman",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": true,
    "save_ema": true,
    "save_embedding_every": 10,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": false,
    "save_lora_for_extra_net": false,
    "save_preview_every": 5,
    "save_safetensors": true,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "scheduler": "KDPM2AncestralDiscrete",
    "shuffle_tags": true,
    "snapshot": "",
    "split_loss": true,
    "src": "G:\\ASD1111\\stable-diffusion-webui\\models\\Stable-diffusion\\SD15NewVAEpruned.ckpt",
    "stop_text_encoder": 0.7,
    "strict_tokens": false,
    "tf32_enable": false,
    "train_batch_size": 1,
    "train_imagic": false,
    "train_unet": true,
    "use_concepts": false,
    "use_ema": true,
    "use_lora": false,
    "use_lora_extended": false,
    "use_subdir": true,
    "v2": false
}

### 3. Provide logs

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```st
PASTE YOUR STACKTRACE HERE
```

### 4. Environment

What OS = Windows 11 Pro - 64bit 
32gb ram, Intel I7, Dedicated SSD 500
[Log.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11210147/Log.txt)
[db_config.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11210148/db_config.txt)
[events.out.tfevents.1681293206.Phenom.6492.0.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11210149/events.out.tfevents.1681293206.Phenom.6492.0.txt)
GB for Stable Diffusion, 
[Log.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11210143/Log.txt)

What GPU are you using= Asus DUAL -  nVidia 2060 with 12Gb of Vram

**Comment by SilverRider76** [comment]
> You currently have EMA turned on. That will not work in 12GB.

I've already tryied withouth EMA (9,6gb or vram used) and still have this problem!

**Comment by SilveRider76** [comment]
this is the log withouth checking EMA
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading A111 WebUI Launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Settings file found, loading
 →   Updating Settings File  ✓
 i   Launcher Version 1.7.0
 i   Found a custom WebUI Config
 i   No Launcher launch options
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Checking requirements :
 i   Python 3.10.6150.1013 found in registry:  C:\Users\Silver\AppData\Local\Programs\Python\Python310\
 i   Clearing PATH of any mention of Python
 →   Adding python 3.10 to path  ✓
 i   Git found and already in PATH:  D:\Program Files\Git\cmd\git.exe
 i   Automatic1111 SD WebUI found:  G:\ASD1111\stable-diffusion-webui
 i   One or more checkpoint models were found
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading Complete, opening launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Arguments are now: --medvram --xformers --ckpt-dir 'G:\CKPT' --vae-path 'G:\vae-ft-ema-560000-ema-pruned.ckpt' --opt-sdp-attention --opt-sub-quad-attention
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Webui
 ✓   Done
 i   Arguments are now: --medvram --xformers --ckpt-dir 'G:\CKPT' --vae-path 'G:\vae-ft-ema-560000-ema-pruned.ckpt' --opt-sdp-attention --opt-sub-quad-attention
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  WEBUI LAUNCHING VIA EMS LAUNCHER, EXIT THIS WINDOW TO STOP THE WEBUI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 !   Any error happening after 'commit hash : XXXX' is not related to the launcher. Please report them on Automatic1111's github instead :
 ☁   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cancel
venv "G:\ASD1111\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed google-auth-oauthlib-0.4.6 requests-2.28.2
[+] xformers version 0.0.18 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --autolaunch --medvram --xformers --ckpt-dir G:\CKPT --vae-path G:\vae-ft-ema-560000-ema-pruned.ckpt --opt-sdp-attention --opt-sub-quad-attention
G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Loading weights [27a4ac756c] from G:\ASD1111\stable-diffusion-webui\models\Stable-diffusion\SD15NewVAEpruned.ckpt
Creating model from config: G:\ASD1111\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights from commandline argument: G:\vae-ft-ema-560000-ema-pruned.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(2): L4V1c4-txt, LaVica
Model loaded in 5.8s (load weights from disk: 0.9s, create model: 1.2s, apply weights to model: 0.9s, apply half(): 2.2s, load VAE: 0.5s).
CUDA SETUP: Loading binary G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 17.4s (import torch: 4.9s, import gradio: 1.0s, import ldm: 0.7s, other imports: 1.1s, setup codeformer: 0.3s, load scripts: 2.4s, load SD checkpoint: 5.9s, create ui: 0.8s, gradio launch: 0.3s).
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Pre-processing images: Portrait512: : 0it [00:00, ?it/s]
Nothing to generate.
Found 0 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (Without Caching)
Bucket 0 (512, 512, 0) - Instance Images: 12 | Class Images: 0 | Max Examples/batch: 12
Total Buckets 1 - Instance Images: 12 | Class Images: 0 | Max Examples/batch: 12
Processing images...: 100%|█████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 12020.93it/s]
Total images / batch: 12, total examples: 12
Processing images...: 100%|██████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 6006.16it/s]
Total dataset length (steps): 12
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 12
  Num Epochs = 300
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 210
  Total optimization steps = 3600
  Total training steps = 3600
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Optimizer: 8bit AdamW, Prec: fp16
  Gradient Checkpointing: True
  EMA: False
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 1e-06
  V2: False
Steps:   0%|            | 1/3600 [00:09<9:32:35,  9.55s/it, inst_loss=0.13, loss=0.13, lr=1e-6, prior_loss=0, vram=9.5]OOM Detected, reducing batch/grad size to 0/1.
Traceback (most recent call last):
  File "G:\ASD1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "G:\ASD1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1169, in inner_loop
    noise_pred = unet(
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 495, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\amp\autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 631, in forward
    sample = upsample_block(
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1805, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1798, in custom_forward
    return module(*inputs, return_dict=return_dict)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 321, in forward
    ff_output = self.ff(norm_hidden_states)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 379, in forward
    hidden_states = module(hidden_states)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 425, in forward
    hidden_states, gate = self.proj(hidden_states).chunk(2, dim=-1)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ASD1111\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 307, in lora_Linear_forward
    return torch.nn.Linear_forward_before_lora(self, input)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.10 GiB already allocated; 0 bytes free; 11.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0%|         | 1/3600 [04:02<242:15:44, 242.33s/it, inst_loss=0.13, loss=0.13, lr=1e-6, prior_loss=0, vram=9.5]
Traceback (most recent call last):
  File "G:\ASD1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 727, in start_training
    result = main(class_gen_method=class_gen_method)
  File "G:\ASD1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1371, in main
    return inner_loop()
  File "G:\ASD1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 117, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
RuntimeError: No executable batch size found, reached zero.
Restored system models.
Duration: 00:05:41
[Log2.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11210979/Log2.txt)

**Comment by butchmarshall** [comment]
I noticed you have `UNET: True` - disabling UNET makes this work for me.

**Comment by hedaoming** [comment]
disabling UNET also work for me!

**Comment by d8ahazard** [comment]
However, if you disable unet training, you will need to "alternate"
training f the unet and text encoder.

So, train for N epochs with unet disabled and "Step Ratio of Text Encoder
Training"  set to 1, and then train for the same number of epochs with Step
Ratio... set to 0 and "train Unet" enabled.

**Comment by dsalvat1** [comment]
This has not been resolved on main, dev doesn't seem to have the same problem

**Comment by mateuspestana** [comment]
I'm having the same problem. Disabling UNET works, but is there any chance we could train with it checked?
