### ISSUE TITLE
Models created aren't the same as the diffusers, safetensors end up being identical to the original model it is trained on

### ISSUE THREAD

**Issue by rodrigo-barraza** [d8ahazard/sd_dreambooth_extension#1190]
For some reason the models being outputted during a training session aren't being updated. If I manually convert the diffusers into a model myself, then everything looks good. This is annoying at the moment because the models being created during training end up being useless and there is no way to convert diffuser checkpoints into models, since they are not in the same format as the diffusers themselves.

I've tried training 1.5, 2.1 models. I've also re-enabled CKPT generation in the code instead of SAFETENSORS but regardless, the same issue persists.

```
[+] xformers version 0.0.18 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.
```

**Comment by sergiobr** [comment]
This also happens with me. The generated models are corrupted and even the last output is very bad with some models.
After a long time I found that do not tick "Extract EMA Weights" when creating the model fix it.

But I would like to know if it's possible to convert diffusers checkpoint to ckpt and if EMA really plays some difference in training.
