### ISSUE TITLE
Memory leak after using the api "start_training" endpoint

### ISSUE THREAD

**Issue by ekeric13** [d8ahazard/sd_dreambooth_extension#1198]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 3324b6ab7fa661cf7d6b5ef186227dc5e8ad1878
Successfully installed accelerate-0.17.1 fastapi-0.90.1 gitpython-3.1.31 requests-2.28.2 starlette-0.23.1 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.18.dev489 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.17.1 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
```

### 2. Describe the bug

There seems to be a memory leak after hitting the "start_endpoint".
Specifically this code:
https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/scripts/api.py#L744
Tried adding cleanup() to the very end of the method and it helped a little but not a ton.

This is the initial memory usage
<img width="611" alt="Screenshot 2023-04-25 at 2 24 39 AM" src="https://user-images.githubusercontent.com/6489651/234233959-72a0835e-7be7-4b7c-a757-4afabb6f6637.png">

After the training runs:
<img width="572" alt="Screenshot 2023-04-25 at 2 25 04 AM" src="https://user-images.githubusercontent.com/6489651/234234051-4e59c99c-5021-4e12-86da-9b1f442f2f8d.png">

After the training runs when adding the cleanup()
<img width="575" alt="Screenshot 2023-04-25 at 2 25 33 AM" src="https://user-images.githubusercontent.com/6489651/234234173-6901bc6f-09ac-4f34-aec2-5a183a3ff59a.png">

So still having issues getting back to 4.5GB memory.

### 4. Environment

What OS? - ubuntu (linux)

What GPU are you using? - CUDA Version: 11.7

**Comment by Sur3** [comment]
I can confirm I have a similar problem, I can only train for one epoch with my RTX3060 12GB  and Cuda 11.8 because the memory is not cleaned up afterwards. So I have to restart webui for every epoch so the GPU memory gets cleared after an eppoch to train the next one.

**Comment by Lalimec** [comment]
same

**Comment by kelvie** [comment]
I also ran into this, and found that it was a torch/dynamo issue with torch2: https://github.com/d8ahazard/sd_dreambooth_extension/pull/1186

so setting `TORCHDYNAMO_DISABLE=1`  before starting the webui fixed it for me

**Comment by ekeric13** [comment]
Trying this out. Let you know how it goes.

**Comment by kelvie** [comment]
@ekeric13 That's definitely a torch2 only problem. Sorry, it probably wasn't the same issue, although if you posted logs that might help others to see if they're having the same issue too!
