### ISSUE TITLE
Newly created models have pickle warning when attempting to train

### ISSUE THREAD

**Issue by dnwalkup** [d8ahazard/sd_dreambooth_extension#120]
Exception: bad file inside D:\stable-diffusion-webui\models\dreambooth\dreamboothtest\working\text_encoder\pytorch_model.bin: pytorch_model/data.pkl

The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.

**Comment by d8ahazard** [comment]
Please use the template when posting issues, this will help me better resolve problems. Thanks.
