### ISSUE TITLE
Unable to create model using this extension on Automatic1111 web ui

### ISSUE THREAD

**Issue by AnushkaBajpai31** [d8ahazard/sd_dreambooth_extension#1204]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 0. Initial troubleshooting
Please check each of these before opening an issue. If you've checked them, **delete this section of your bug report**. Have you:
- Updated the Stable-Diffusion-WebUI to the latest version? **Yes**
- Updated Dreambooth to the latest revision? **Yes**
- Completely restarted the stable-diffusion-webUI, not just reloaded the UI? **Yes**
- Read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)? **Yes**

### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:
---
Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed accelerate-0.18.0 fastapi-0.94.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 requests-2.29.0 tensorboard-data-server-0.6.1 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[!] xformers NOT installed.
[!] torch version 1.12.1 installed.
[!] torchvision version 0.13.1 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
```

### 2. Describe the bug

(A clear and concise description of what the bug is)
1. On loading the web ui, click on **Dreambooth**.
2. Select **Create Model** option.
3. Enter **Name** as **wnkc** and select **checkpoint** as **v2-1_768-ema-pruned.ckpt** (_Stable Diffusion v2.1_)
4. Click on **Create**

**Screenshots/Config**
<img width="1728" alt="Screenshot 2023-04-27 at 6 27 01 PM" src="https://user-images.githubusercontent.com/86293877/234868747-740a987a-0786-430c-bcdd-62d6b1282ba6.png">
<img width="1728" alt="Screenshot 2023-04-27 at 6 27 09 PM" src="https://user-images.githubusercontent.com/86293877/234868776-920d9235-a004-43b2-a94c-2ba12c595a76.png">

### 3. Provide logs

Snapshot attached above.

```st
PASTE YOUR STACKTRACE HERE
```

### 4. Environment

What OS? MacOS M1 Max (Monterey)

What GPU are you using?
<img width="395" alt="Screenshot 2023-04-27 at 6 31 22 PM" src="https://user-images.githubusercontent.com/86293877/234869768-88f6b9f6-2e09-47aa-a90e-a366698a12d3.png">

**Comment by koshimazaki** [comment]
Same here I keep getting this tried reinstalling multiple things, no luck... 

NameError: name 'str2optimizer8bit_blockwise' is not defined

**Comment by manugarri** [comment]
@koshimazaki here you can find suggestions to fix that issue https://github.com/d8ahazard/sd_dreambooth_extension/issues/1067

**Comment by koshimazaki** [comment]
> @koshimazaki here you can find suggestions to fix that issue #1067

thanks a lot! It worked! 
It is super sloooow. Like it did 636 steps out of 9k over night
'''
Steps:   6%|████▎                                                                  | 545/9000 [8:30:53<145:19:28, 61.88s/it, inst_loss=0.158, loss=0.158, lr=2e-6, prior_loss=0, vram=0]Steps:   7%|████▊                                                               | 637/9000 [10:21:17<161:49:36, 69.66s/it, inst_loss=0.0915, loss=0.0915, lr=2e-6, prior_loss=0, vram=0]'''

**Comment by AnushkaBajpai31** [comment]
@koshimazaki Just a follow-up, were you able to find a solution to this slowness?

**Comment by koshimazaki** [comment]
> 

not yet I am at 36% atm still same session lol I think using 90 images was a mistake. Doing it as experiment now.

```
Generating Samples: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:39<00:00, 13.02s/it]
Steps:  36%|█████████████████████████▍                                             | 3221/9000 [56:37:21<107:19:31, 66.86s/it, inst_loss=0.63, loss=0.63, lr=2e-6, prior_loss=0, vram```

**Comment by AnushkaBajpai31** [comment]
@koshimazaki 
I tried training and inference on AWS Sagemaker Jumpstart, with a train set as small as 12 images. The results were. really wonderful. Also It took around an hour to train the model. But it is expensive. Maybe you can try if you have a good budget of 50 USD. 
Meanwhile, do let me know how Google Colab works out for you. :)

**Comment by koshimazaki** [comment]
> @koshimazaki I tried training and inference on AWS Sagemaker Jumpstart, with a train set as small as 12 images. The results were really wonderful. Also It took around an hour to train the model. But it is expensive. Maybe you can try if you have a good budget of 50 USD. Meanwhile, do let me know how Google Colab works out for you. :)

Awesome, thank you, yes need to experiment with it. With 1h only google collab should be cheaper I think as you get more time with 10USD subscription + need google storage for checkpoints.

**Comment by AnushkaBajpai31** [comment]
Not stale
