### ISSUE TITLE
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-12.1/lib64/libcudart.so

### ISSUE THREAD

**Issue by dsalvat1** [d8ahazard/sd_dreambooth_extension#1209]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 0. Initial troubleshooting
Please check each of these before opening an issue. If you've checked them, **delete this section of your bug report**. Have you:
- Updated the Stable-Diffusion-WebUI to the latest version? Yes
- Updated Dreambooth to the latest revision? Yes
- Completely restarted the stable-diffusion-webUI, not just reloaded the UI? Yes
- Read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)? Yes

### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.19 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed. <=== This is the problem, my build version is 0.38.1

#######################################################################################################
```

### 2. Describe the bug

When building new bitsandbytes python module for CUDA, it is downgraded again to 0.35.4. Afterwards, training any model fails with out of memory issue.

**Screenshots/Config**
$ pip uninstall bitsandbytes

(venv) dsalvat1@leviathan:~/stable-diffusion-webui$ pip uninstall bitsandbytes
Found existing installation: bitsandbytes 0.35.4
Uninstalling bitsandbytes-0.35.4:
  Would remove:
    /home/dsalvat1/stable-diffusion-webui/venv/bin/debug_cuda
    /home/dsalvat1/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes-0.35.4.dist-info/*
    /home/dsalvat1/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/*
Proceed (Y/n)?
  Successfully uninstalled bitsandbytes-0.35.4
  
****************************Custom built bitsandbytes module************************************
Processing bitsandbytes-0.38.1-py3.10.egg
removing '/home/dsalvat1/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes-0.38.1-py3.10.egg' (and everything under it)
creating /home/dsalvat1/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes-0.38.1-py3.10.egg
Extracting bitsandbytes-0.38.1-py3.10.egg to /home/dsalvat1/stable-diffusion-webui/venv/lib/python3.10/site-packages
bitsandbytes 0.38.1 is already the active version in easy-install.pth

*********************************************************************************************************  

### 3. Provide logs

*************************Executing bash webui.sh on Automatic 1111*******************************************
Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed accelerate-0.18.0 bitsandbytes-0.35.4 fastapi-0.94.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 requests-2.29.0 transformers-4.26.1

****************************************CUDA errors*************************************************************

Model loaded in 149.5s (load weights from disk: 6.2s, create model: 1.1s, apply weights to model: 141.0s, apply half(): 0.4s, move model to device: 0.4s, load textual inversion embeddings: 0.3s).
*Deforum ControlNet support: enabled*
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Required library version not found: libbitsandbytes_cuda121_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121_nomatmul
python setup.py install
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Required library version not found: libbitsandbytes_cuda121_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121_nomatmul
python setup.py install
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so

CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Required library version not found: libbitsandbytes_cuda121_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121_nomatmul
python setup.py install
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121_nomatmul
python setup.py install
Running on local URL:  http://127.0.0.1:7860

*****************************************************************************************************************************

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 0; 11.73 GiB total capacity; 9.81 GiB already allocated; 63.75 MiB free; 10.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### 4. Environment

What OS? Ubuntu 22.04

If Windows - WSL or native? N/A

What GPU are you using? RTX 4070 12GB

**Comment by andypotato** [comment]
Same issue for me, it will cause all kinds of CUDA errors under windows:

```
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin D:\SD\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary D:\SD\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
```

**Comment by stdkoehler** [comment]
I also had an issue with bitsandbytes and ubuntu. The error log was different though. Maybe you want to try it anyways: https://github.com/d8ahazard/sd_dreambooth_extension/issues/1187

**Comment by Pedroman1** [comment]
I am having same issue in windows unsure how to fix

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
