### ISSUE TITLE
If I generate samples with the same seed (while NOT training), I get slightly different images each time

### ISSUE THREAD

**Issue by morphinapg** [d8ahazard/sd_dreambooth_extension#1210]
### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed fastapi-0.94.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 requests-2.29.0 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.17 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
```

### 2. Describe the bug

I was planning to do some experimenting on my training settings, so I wanted sample generation to follow consistent settings, so I could follow with how a specific image was changing over time during training. Looking for a good starting image to use as a base, I wanted to try different seeds, so I went to the Generate tab, set seed to 0 and clicked generate, and then I clicked it again. It generated an image that was slightly similar to the previous, but with subtle differences. I tried again and again, and still, slight differences each time. If I can't get a consistent output with the same seed, it's going to be hard to experiment with the training settings like I planned.

I also tried switching to using A1111's txt2img for generation, but that mode appears to completely ignore the seed value I set and just uses a random seed, so that wasn't useful either.

### 3. Provide logs

No crash

### 4. Environment

What OS? Windows 11

If Windows - WSL or native? native

What GPU are you using? 3080Ti

**Comment by araleza** [comment]
Are you using xformers?  That library saves memory and increases speed, but it's not entirely deterministic.

**Comment by araleza** [comment]
Also there's a Deterministic check box at the top of the Testing tab in Dreambooth, maybe that'll help

**Comment by morphinapg** [comment]
> Are you using xformers? That library saves memory and increases speed, but it's not entirely deterministic.

I use xformers but that's not how it operates in the txtimg tab. When I use the same seed in that tab, I get exactly the same image. 

> Also there's a Deterministic check box at the top of the Testing tab in Dreambooth, maybe that'll help

I figured that was like the deterministic option in the training tab, which has to do with how the sample images are processed. Personally I like that off as then you get a different random sample of the images each epoch, which I feel probably results in a better model in the end as I would imagine it would be less likely to overtrain, and may be better at adapting to other changing factors.
