### ISSUE TITLE
Adding torch.compile as an option to choose from webui

### ISSUE THREAD

**Issue by seermer** [d8ahazard/sd_dreambooth_extension#1215]
### Kindly read the entire form below and fill it out with the requested information.

**WHAT**
What is this feature of which you speak??
Currently on Linux, the model uses torch.compile with max autotune. However, compile can cause tons of problems, including but not limited to useless/meaningless debug/error messages, increased memory usage, and very long compile time. Not to mention max_autotune does not work well with all GPUs.

**WHERE**
From whence did you hear this news?? Provide a URL if possible.
From personal experience when using this extension, there are all kinds of things going wrong, and no useful message shows up. I fixed most of them, or at least know why by simply removing the torch.compile

**HOW**
I suppose that could be the same as where if you have a URL, but if there's an example, hook me up.
the code for compile is here https://github.com/d8ahazard/sd_dreambooth_extension/blob/926ae204ef5de17efca2059c334b6098492a0641/dreambooth/utils/model_utils.py#L246

add an option in the settings tab to choose whether to compile or not, which mode should be compiled with

**WHEN**
Whenever I get to it. Hold your horses...

**Comment by araleza** [comment]
This would be good.  Currently there's a slow stream of AUTOTUNE messages appearing when trying to use Dreambooth with torch 2.0.  And then, even on a 24GB 4090 card, it just says it's out of CUDA memory after that, which doesn't happen with torch 1.31.1.

I'm sure that'll get fixed at some point, but maybe the OOM wouldn't happen if the Dreambooth extension didn't attempt to use the .compile() option, so being able to disable it might be a good workaround for now.
