### ISSUE TITLE
[!] transformers NOT installed

### ISSUE THREAD

**Issue by wzgrx** [d8ahazard/sd_dreambooth_extension#1216]
[!] transformers NOT installed.

[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################

#                                       LIBRARY ISSUE DETECTED                                        #

#######################################################################################################

#

# transformers not installed.

#

# Dreambooth may not work properly.

#

# TROUBLESHOOTING

# 1. Fully restart your project (not just the webpage)

# 2. Update your A1111 project and extensions

# 3. Dreambooth requirements should have installed automatically, but you can manually install them

#    by running the following 4 commands from the A1111 project root:

cd venv/Scripts

activate

cd ../..

pip install -r ./extensions/sd_dreambooth_extension/requirements.txt

#######################################################################################################

**Comment by HomegrownExplorer** [comment]
im running into the same issue, [!] transformers NOT installed.

still searching for a solution, I'll pop back in if I find it.

**Comment by dr-dark-flames** [comment]
any update?

**Comment by swumagic** [comment]
After each update, the requirements.txt must be modified as follows.   
extensions\sd_dreambooth_extension\requirements.txt。it run ok。

accelerate~=0.18.0
bitsandbytes==0.35.4
dadaptation~=3.1
diffusers~=0.16.1
discord-webhook~=1.1.0
fastapi~=0.94.1
gitpython~=3.1.31
lion-pytorch~=0.0.7
Pillow~=9.5.0
tqdm~=4.64.1
transformers~=4.25.1 # > 4.26.x causes issues (db extension #1110)
