### ISSUE TITLE
[!] xformers version 0.0.16rc425 installed.

### ISSUE THREAD

**Issue by davehornik** [d8ahazard/sd_dreambooth_extension#1218]
### 0. Initial troubleshooting

- Updated the Stable-Diffusion-WebUI to the latest version?
yes
- Updated Dreambooth to the latest revision?
yes
- Completely restarted the stable-diffusion-webUI, not just reloaded the UI?
yes
- Read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?
nothing in there
### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed fastapi-0.94.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 requests-2.30.0 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[!] xformers version 0.0.16rc425 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
```

### 2. Describe the bug

Unable to use extension since it does not care I've got 0.0.17 automatically given by A1111. But you are forcing me to use outdated 0.0.16

### 3. Provide logs

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```st
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Pre-processing images: classifiers_0: : 0it [00:00, ?it/s]
Nothing to generate.
Traceback (most recent call last):
  File "D:\Stable WEBUI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 727, in start_training
    result = main(class_gen_method=class_gen_method)
  File "D:\Stable WEBUI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1371, in main
    return inner_loop()
  File "D:\Stable WEBUI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "D:\Stable WEBUI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 305, in inner_loop
    raise ValueError(
ValueError: xformers is not available. Make sure it is installed correctly
Restored system models.
```

**Comment by davehornik** [comment]
Was installing and trying different versions of xf, they are working great with SD but Dreambooth got problems with it no matter what.
I solved that by uninstalling your extension and found different one that works flawlessly with more features.. Thanks.

**Comment by swumagic** [comment]
After each update, the requirements.txt must be modified as follows.   
extensions\sd_dreambooth_extension\requirements.txt。it run ok。

accelerate~=0.18.0
bitsandbytes==0.35.4
dadaptation~=3.1
diffusers~=0.16.1
discord-webhook~=1.1.0
fastapi~=0.94.1
gitpython~=3.1.31
lion-pytorch~=0.0.7
Pillow~=9.5.0
tqdm~=4.64.1
transformers~=4.25.1 # > 4.26.x causes issues (db extension #1110)

**Comment by davehornik** [comment]
> After each update, the requirements.txt must be modified as follows. extensions\sd_dreambooth_extension\requirements.txt。it run ok。
> 
> accelerate~=0.18.0 bitsandbytes==0.35.4 dadaptation~=3.1 diffusers~=0.16.1 discord-webhook~=1.1.0 fastapi~=0.94.1 gitpython~=3.1.31 lion-pytorch~=0.0.7 Pillow~=9.5.0 tqdm~=4.64.1 transformers~=4.25.1 # > 4.26.x causes issues (db extension #1110)

thx for your effort, but doesn't matter.
