### ISSUE TITLE
Could not install the requirements, how to resolve the permissions, I started the webui with administrator.

### ISSUE THREAD

**Issue by lucky-yym** [d8ahazard/sd_dreambooth_extension#1224]
Error running install.py for extension extensions\sd_dreambooth_extension.
Command: "E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth

Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641

# Requirement installation exception:

WARNING: Ignoring invalid distribution -rotobuf (e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages)

WARNING: Ignoring invalid distribution -rotobuf (e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages)

Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple, https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.doubanio.com/simple

Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html

Ignoring tensorboard: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment

Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment

Ignoring tensorflow-metal: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment

Collecting accelerate~=0.18.0

Using cached https://pypi.doubanio.com/packages/e7/87/25dd46811431cfc5e8d6ba8c80758cb3131574b271fbf06cf1b691dba8d4/accelerate-0.18.0-py3-none-any.whl (215 kB)

Requirement already satisfied: bitsandbytes==0.35.4 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from -r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (0.35.4)

Requirement already satisfied: dadaptation~=1.5.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from -r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 3)) (1.5)

Requirement already satisfied: diffusers~=0.14.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from -r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (0.14.0)

Requirement already satisfied: discord-webhook~=1.1.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from -r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (1.1.0)

Collecting fastapi~=0.94.1

Using cached https://pypi.doubanio.com/packages/6b/77/c4b587e738413241b66c2715aec932e668a559e58bdc8a90cabc0fe90ff3/fastapi-0.94.1-py3-none-any.whl (56 kB)

Collecting gitpython~=3.1.31

Using cached https://pypi.doubanio.com/packages/9e/8a/d1e02cc111d65b0346f70abb83c51f8593e7134bf694a4a56d1a470caaf7/GitPython-3.1.31-py3-none-any.whl (184 kB)

Requirement already satisfied: lion-pytorch~=0.0.7 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from -r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.0.8)

Requirement already satisfied: Pillow~=9.4.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from -r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (9.4.0)

Requirement already satisfied: tqdm~=4.64.1 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from -r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (4.64.1)

Collecting transformers~=4.26.1

Using cached https://pypi.doubanio.com/packages/1e/e2/60c3f4691b16d126ee9cfe28f598b13c424b60350ab339aba81aef054b8f/transformers-4.26.1-py3-none-any.whl (6.3 MB)

Requirement already satisfied: tensorboard==2.12.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from -r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2.12.0)

Requirement already satisfied: tensorflow==2.12.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from -r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (2.12.0)

Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (1.8.1)

Requirement already satisfied: wheel>=0.26 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (0.38.4)

Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (0.7.0)

Requirement already satisfied: google-auth<3,>=1.6.3 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2.14.1)

Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (0.4.6)

Requirement already satisfied: markdown>=2.6.8 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (3.4.1)

Requirement already satisfied: protobuf>=3.19.6 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (3.20.3)

Requirement already satisfied: absl-py>=0.4 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (1.3.0)

Requirement already satisfied: setuptools>=41.0.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (65.6.0)

Requirement already satisfied: werkzeug>=1.0.1 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2.2.2)

Requirement already satisfied: requests<3,>=2.21.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2.25.1)

Requirement already satisfied: grpcio>=1.48.2 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (1.50.0)

Requirement already satisfied: numpy>=1.12.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (1.24.3)

Requirement already satisfied: tensorflow-intel==2.12.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (2.12.0)

Requirement already satisfied: typing-extensions>=3.6.6 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (4.5.0)

Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (0.31.0)

Requirement already satisfied: h5py>=2.9.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (3.8.0)

Requirement already satisfied: gast<=0.4.0,>=0.2.1 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (0.4.0)

Requirement already satisfied: google-pasta>=0.1.1 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (0.2.0)

Requirement already satisfied: jax>=0.3.15 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (0.4.9)

Requirement already satisfied: packaging in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (21.3)

Collecting numpy>=1.12.0

Using cached https://pypi.doubanio.com/packages/6a/03/ae6c3c307f9c5c7516de3df3e764ebb1de33e54e197f0370992138433ef4/numpy-1.23.5-cp310-cp310-win_amd64.whl (14.6 MB)

Requirement already satisfied: tensorflow-estimator<2.13,>=2.12.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (2.12.0)

Requirement already satisfied: termcolor>=1.1.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (2.3.0)

Requirement already satisfied: opt-einsum>=2.3.2 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (3.3.0)

Requirement already satisfied: libclang>=13.0.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (16.0.0)

Requirement already satisfied: wrapt<1.15,>=1.11.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (1.14.1)

Requirement already satisfied: six>=1.12.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (1.16.0)

Requirement already satisfied: keras<2.13,>=2.12.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (2.12.0)

Requirement already satisfied: astunparse>=1.6.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (1.6.3)

Requirement already satisfied: flatbuffers>=2.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (23.5.9)

Requirement already satisfied: pyyaml in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from accelerate~=0.18.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (6.0)

Requirement already satisfied: torch>=1.4.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from accelerate~=0.18.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (2.0.0+cu118)

Requirement already satisfied: psutil in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from accelerate~=0.18.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (5.9.4)

Requirement already satisfied: regex!=2019.12.17 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from diffusers~=0.14.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2022.10.31)

Requirement already satisfied: importlib-metadata in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from diffusers~=0.14.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (5.0.0)

Requirement already satisfied: filelock in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from diffusers~=0.14.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.8.0)

Requirement already satisfied: huggingface-hub>=0.10.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from diffusers~=0.14.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (0.11.0)

Collecting requests<3,>=2.21.0

Using cached https://pypi.tuna.tsinghua.edu.cn/packages/96/80/034ffeca15c0f4e01b7b9c6ad0fb704b44e190cde4e757edbd60be404c41/requests-2.30.0-py3-none-any.whl (62 kB)

Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from fastapi~=0.94.1->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (1.10.2)

Collecting starlette<0.27.0,>=0.26.1

Using cached https://pypi.doubanio.com/packages/12/48/f9c1ec6bee313aba264fbc2483d9070f4e4526f2538e2b55b1e4a391d938/starlette-0.26.1-py3-none-any.whl (66 kB)

Requirement already satisfied: gitdb<5,>=4.0.1 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from gitpython~=3.1.31->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 7)) (4.0.9)

Requirement already satisfied: colorama in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from tqdm~=4.64.1->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (0.4.6)

Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from transformers~=4.26.1->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 11)) (0.12.1)

Requirement already satisfied: smmap<6,>=3.0.1 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from gitdb<5,>=4.0.1->gitpython~=3.1.31->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 7)) (5.0.0)

Requirement already satisfied: rsa<5,>=3.1.4 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (4.9)

Requirement already satisfied: pyasn1-modules>=0.2.1 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (0.2.8)

Requirement already satisfied: cachetools<6.0,>=2.0.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (5.2.0)

Requirement already satisfied: requests-oauthlib>=0.7.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (1.3.1)

Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from packaging->tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (3.0.9)

Requirement already satisfied: certifi>=2017.4.17 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from requests<3,>=2.21.0->tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2022.9.24)

Requirement already satisfied: charset-normalizer<4,>=2 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from requests<3,>=2.21.0->tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2.1.1)

Requirement already satisfied: idna<4,>=2.5 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from requests<3,>=2.21.0->tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2.10)

Requirement already satisfied: urllib3<3,>=1.21.1 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from requests<3,>=2.21.0->tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (1.26.12)

Requirement already satisfied: anyio<5,>=3.4.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from starlette<0.27.0,>=0.26.1->fastapi~=0.94.1->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (3.6.2)

Requirement already satisfied: networkx in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from torch>=1.4.0->accelerate~=0.18.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (2.8.8)

Requirement already satisfied: jinja2 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from torch>=1.4.0->accelerate~=0.18.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (3.1.2)

Requirement already satisfied: sympy in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from torch>=1.4.0->accelerate~=0.18.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.12)

Requirement already satisfied: MarkupSafe>=2.1.1 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from werkzeug>=1.0.1->tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2.1.1)

Requirement already satisfied: zipp>=0.5 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from importlib-metadata->diffusers~=0.14.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.10.0)

Requirement already satisfied: sniffio>=1.1 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from anyio<5,>=3.4.0->starlette<0.27.0,>=0.26.1->fastapi~=0.94.1->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (1.3.0)

Requirement already satisfied: scipy>=1.7 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from jax>=0.3.15->tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (1.9.3)

Requirement already satisfied: ml-dtypes>=0.1.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from jax>=0.3.15->tensorflow-intel==2.12.0->tensorflow==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (0.1.0)

Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (0.4.8)

Requirement already satisfied: oauthlib>=3.0.0 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard==2.12.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (3.2.2)

Requirement already satisfied: mpmath>=0.19 in e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages (from sympy->torch>=1.4.0->accelerate~=0.18.0->-r E:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.3.0)

WARNING: Ignoring invalid distribution -rotobuf (e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages)

Installing collected packages: requests, numpy, starlette, gitpython, transformers, fastapi, accelerate

Attempting uninstall: requests

WARNING: Ignoring invalid distribution -rotobuf (e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages)

Found existing installation: requests 2.25.1

Uninstalling requests-2.25.1:

Successfully uninstalled requests-2.25.1

Attempting uninstall: numpy

WARNING: Ignoring invalid distribution -rotobuf (e:\002_programs\tablediffusion\webui\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages)

Found existing installation: numpy 1.24.3

Uninstalling numpy-1.24.3:

ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'e:\\002_programs\\tablediffusion\\webui\\novelai-webui\\novelai-webui-aki-v3\\py310\\lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll'

**Comment by davehornik** [comment]
Do not expect any help my friend.. Sadly.

But I wanted to ask, yre you running the extension on A1111 ?

**Comment by wzgrx** [comment]
This script has a lot of compatibility issues, it's time to uninstall it from SD, it's currently only suitable for standalone use

**Comment by davehornik** [comment]
> This script has a lot of compatibility issues, it's time to uninstall it from SD, it's currently only suitable for standalone use

Also zero support, I was trying to get some help for week or so now.

**Comment by jhewittdev** [comment]
Only commenting on what worked for me...

Delete the -rotobuf directory, my was named ~rotobuf, from the site-packages folder. Then delete the venv directory and restart. The standard SD started up bat, webui-user, rebuilt(?) venv and redownloaded/installed stuff and it worked just fine for me after that.

**Comment by swumagic** [comment]
After each update, the requirements.txt must be modified as follows.   
extensions\sd_dreambooth_extension\requirements.txt。it run ok。

accelerate~=0.18.0
bitsandbytes==0.35.4
dadaptation~=3.1
diffusers~=0.16.1
discord-webhook~=1.1.0
fastapi~=0.94.1
gitpython~=3.1.31
lion-pytorch~=0.0.7
Pillow~=9.5.0
tqdm~=4.64.1
transformers~=4.25.1 # > 4.26.x causes issues (db extension #1110)
