### ISSUE TITLE
No module named 'diffusers' &  name 'DreamboothConfig' is not defined

### ISSUE THREAD

**Issue by valentin0bhfr** [d8ahazard/sd_dreambooth_extension#1233]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 0. Initial troubleshooting
Please check each of these before opening an issue. If you've checked them, **delete this section of your bug report**. Have you:
- Updated the Stable-Diffusion-WebUI to the latest version?
- Updated Dreambooth to the latest revision?
- Completely restarted the stable-diffusion-webUI, not just reloaded the UI?
- Read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?

### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: bd3fecc3d27d777a4e8f3206a0b16e852877dbad
SD-WebUI revision: 

[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] xformers version 0.0.17+b6be33a.d20230315 installed.
[+] accelerate version 0.17.1 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.27.1 installed.

#######################################################################################################
```

### 2. Describe the bug

(A clear and concise description of what the bug is)

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

### 3. Provide logs
Relauncher: Launching...

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on root user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc.so.4
Python 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
Commit hash: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
Docker, returning.

Launching Web UI with arguments: -f --port 3000 --xformers --skip-install --listen --enable-insecure-extension-access
Exception importing api
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 27, in <module>
    from dreambooth.dataclasses.db_config import from_file, DreamboothConfig
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 10, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ModuleNotFoundError: No module named 'diffusers'
Error loading script: main.py
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 7, in <module>
    from dreambooth.dataclasses.db_config import (
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 10, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ModuleNotFoundError: No module named 'diffusers'

Loading weights [4c86efd062] from /workspace/stable-diffusion-webui/models/Stable-diffusion/SDv1-5.ckpt
Creating model from config: /workspace/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 19.4s (load weights from disk: 1.0s, create model: 1.6s, apply weights to model: 5.9s, apply half(): 8.8s, load VAE: 1.2s, move model to device: 0.9s).
Running on local URL:  http://0.0.0.0:3000

To create a public link, set `share=True` in `launch()`.
Error executing callback app_started_callback for /workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/modules/script_callbacks.py", line 108, in app_started_callback
    c.callback(demo, app)
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 524, in dreambooth_api
    model_cfg: DreamboothConfig = Body(description="The config to save"),
NameError: name 'DreamboothConfig' is not defined
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```st
PASTE YOUR STACKTRACE HERE
```

### 4. Environment

What OS?
 runpod.ai 
 1 x RTX 3090
32 vCPU 125 GB RAM
5 GB Disk
50 GB Pod Volume
runpod/stable-diffusion:web-automatic-6.0.1
On-Demand - Secure Cloud
If Windows - WSL or native?

What GPU are you using?

**Comment by valentin0bhfr** [comment]
I got it!


pip install -U diffusers accelerate transformers
 pip install -U discord_webhook

thats the trick :)

**Comment by rootsdub2** [comment]
this worked for me as of May 22, 2023

**Comment by XC3N** [comment]
I have the same issue and the fix doesn't work, I have tried many things (changing permissions to the whole AI folder, deleting venv and pulling again, the above fix, running pip install -r path_to:\AI\extensions\sd_dreambooth_extension\requirements.txt, etc)

any idea what is causing it? I will just give up for now

**Comment by swumagic** [comment]
After each update, the requirements.txt must be modified as follows.   
extensions\sd_dreambooth_extension\requirements.txt。it run ok。

accelerate~=0.18.0
bitsandbytes==0.35.4
dadaptation~=3.1
diffusers~=0.16.1
discord-webhook~=1.1.0
fastapi~=0.94.1
gitpython~=3.1.31
lion-pytorch~=0.0.7
Pillow~=9.5.0
tqdm~=4.64.1
transformers~=4.25.1 # > 4.26.x causes issues (db extension #1110)

**Comment by XC3N** [comment]
> After each update, the requirements.txt must be modified as follows. extensions\sd_dreambooth_extension\requirements.txt。it run ok。
> 
> accelerate~=0.18.0 bitsandbytes==0.35.4 dadaptation~=3.1 diffusers~=0.16.1 discord-webhook~=1.1.0 fastapi~=0.94.1 gitpython~=3.1.31 lion-pytorch~=0.0.7 Pillow~=9.5.0 tqdm~=4.64.1 transformers~=4.25.1 # > 4.26.x causes issues (db extension #1110)

This is the solution that ended up working for me, thanks
