### ISSUE TITLE
stderr: src/tcmalloc.cc:284] Attempt to free invalid pointer 0xad4d4b0 

### ISSUE THREAD

**Issue by starinskycc** [d8ahazard/sd_dreambooth_extension#1237]
################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc.so.4
Python 3.10.10 (main, May 24 2023, 09:49:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Version: v1.2.1
Commit hash: 89f9faa63388756314e8a1d96cf86bf5e0663045
Installing requirements

If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed astunparse-1.6.3 bitsandbytes-0.35.4 dadaptation-1.5 diffusers-0.14.0 discord-webhook-1.1.0 gast-0.4.0 gitpython-3.1.31 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 h5py-3.8.0 importlib-metadata-6.6.0 jax-0.4.10 keras-2.12.0 libclang-16.0.0 lion-pytorch-0.0.8 ml-dtypes-0.1.0 opt-einsum-3.3.0 protobuf-4.23.1 requests-2.31.0 tensorboard-2.12.0 tensorboard-plugin-wit-1.8.1 tensorflow-2.12.0 tensorflow-estimator-2.12.0 tensorflow-io-gcs-filesystem-0.32.0 wrapt-1.14.1 zipp-3.15.0
[+] xformers version 0.0.20 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.25.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --xformers
src/tcmalloc.cc:284] Attempt to free invalid pointer 0x9e554b0 
Aborted

**Comment by ngtrkhoa** [comment]
I also run into the same error

```
################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc.so.4
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0]
Version: v1.2.1
Commit hash: 89f9faa63388756314e8a1d96cf86bf5e0663045
Installing requirements
 If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed astunparse-1.6.3 bitsandbytes-0.35.4 dadaptation-1.5 diffusers-0.14.0 discord-webhook-1.1.0 flatbuffers-23.5.9 gast-0.4.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 h5py-3.8.0 importlib-metadata-6.6.0 jax-0.4.10 keras-2.12.0 libclang-16.0.0 lion-pytorch-0.0.8 ml-dtypes-0.1.0 opt-einsum-3.3.0 protobuf-4.23.1 requests-2.31.0 tensorboard-2.12.0 tensorboard-plugin-wit-1.8.1 tensorflow-2.12.0 tensorflow-estimator-2.12.0 tensorflow-io-gcs-filesystem-0.32.0 termcolor-2.3.0 tqdm-4.64.1 wrapt-1.14.1 zipp-3.15.0
[+] xformers version 0.0.17 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --port 8080
2023-05-24 21:35:23.826559: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
src/tcmalloc.cc:284] Attempt to free invalid pointer 0x562e93bf1700 
Aborted

```

**Comment by ngtrkhoa** [comment]
So it worked for me after downgrading gperftools to 2.4.8
