### ISSUE TITLE
Discord webhook not working

### ISSUE THREAD

**Issue by ashleykleynhans** [d8ahazard/sd_dreambooth_extension#1238]
### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed google-auth-oauthlib-0.4.6 requests-2.31.0
[+] xformers version 0.0.19 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
```

### 2. Describe the bug

The Discord webhook is failing to send status updates.  It works fine when sending a test message when you initially configure it, but fails to send the actual status updates.

### 3. Provide logs

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```st
Traceback (most recent call last):
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1009, in save_weights
    send_training_update(
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/webhook.py", line 67, in send_training_update
    out_imgs = [Image.open(img) for img in imgs]
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/webhook.py", line 67, in <listcomp>
    out_imgs = [Image.open(img) for img in imgs]
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/PIL/Image.py", line 3245, in open
    prefix = fp.read(16)
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/PIL/Image.py", line 528, in __getattr__
    raise AttributeError(name)
AttributeError: read
Exception parsing logz: read
```

### 4. Environment

* Ubuntu 22.04 LTS
* NVIDIA A10G GPU

**Comment by swumagic** [comment]
After each update, the requirements.txt must be modified as follows.   
extensions\sd_dreambooth_extension\requirements.txt。it run ok。

accelerate~=0.18.0
bitsandbytes==0.35.4
dadaptation~=3.1
diffusers~=0.16.1
discord-webhook~=1.1.0
fastapi~=0.94.1
gitpython~=3.1.31
lion-pytorch~=0.0.7
Pillow~=9.5.0
tqdm~=4.64.1
transformers~=4.25.1 # > 4.26.x causes issues (db extension #1110)

**Comment by ashleykleynhans** [comment]
> After each update, the requirements.txt must be modified as follows. extensions\sd_dreambooth_extension\requirements.txt。it run ok。
> 
> accelerate~=0.18.0 bitsandbytes==0.35.4 dadaptation~=3.1 diffusers~=0.16.1 discord-webhook~=1.1.0 fastapi~=0.94.1 gitpython~=3.1.31 lion-pytorch~=0.0.7 Pillow~=9.5.0 tqdm~=4.64.1 transformers~=4.25.1 # > 4.26.x causes issues (db extension #1110)

As before, please stop replying to issues if you don't know what you are talking about.
