### ISSUE TITLE
Memory Management and PYTORCH_CUDA_ALLOC_CONF

### ISSUE THREAD

**Issue by charliesdad** [d8ahazard/sd_dreambooth_extension#124]
**Have you read the Readme?**

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

**Have you updated Dreambooth to the latest revision?**

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is 3b3a8002da3a780c276934e8bcf308aa822f1e22
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

**Describe the bug**

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**
What OS?
If Windows - WSL or native?
What GPU are you using?

**Comment by charliesdad** [comment]
Dreambooth revision is 4684f0faea19c243216eac2278a42fcfcbbd756b
[!] Not using xformers memory efficient attention.
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.

i am getting the following. It seems to be asking me to manage the memory as reserve is greater than allocated, and says to refer to documentation memory management, but as yet i cant find that? 

CUDA SETUP: Loading binary C:\Users\DieselMEDIA\SuperStableDiffusion\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
Ignoring non-image file: D:\AI\photosofDIESELELKINS\20070419_0030.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC03035 - Copy.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC03666black.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08694.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08696.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08697.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08698.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08701.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08702 - Copy.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08702.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08704.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08706 - Copy.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08706.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08709.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08710 (2).JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08710 (2)picasa.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08712.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08713.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08715.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08716.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08717.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08718.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08725.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08727.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08734.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08735.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08740.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08741.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08759.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08768.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08770.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08771.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08773.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08777.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08782.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08799.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08811.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08814.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08816.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08820.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08822.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08834.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08845.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08848.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08850.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08858.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08893.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08896.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08897.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08906.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08907.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08908.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08912.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08913.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08915.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08916 - Copy.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08918.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08934.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08937.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08945.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08956.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08971.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08980.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC08996.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09001.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09004.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09059.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09070.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09074.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09087.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09088.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09096.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09099.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09100.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09118.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09120.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09151.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09200 - Copy.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09200.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09227.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09228.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09231.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09274.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09282.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09283.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09321.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09323.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09382.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09546.JPG
Ignoring non-image file: D:\AI\photosofDIESELELKINS\DSC09549.JPG
 Scheduler Loaded
 Allocated: 0.2GB
 Reserved: 0.2GB

Steps:   0%|                                                                                  | 0/1200 [00:00<?, ?it/s] Exception while training: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 12.00 GiB total capacity; 9.67 GiB already allocated; 0 bytes free; 10.37 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 8.1GB
 Reserved: 10.4GB

Traceback (most recent call last):
  File "C:\Users\DieselMEDIA\SuperStableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 923, in main
    accelerator.backward(loss)
  File "C:\Users\DieselMEDIA\SuperStableDiffusion\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 882, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "C:\Users\DieselMEDIA\SuperStableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\DieselMEDIA\SuperStableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "C:\Users\DieselMEDIA\SuperStableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "C:\Users\DieselMEDIA\SuperStableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 146, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "C:\Users\DieselMEDIA\SuperStableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 12.00 GiB total capacity; 9.67 GiB already allocated; 0 bytes free; 10.37 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 CLEANUP:
 Allocated: 7.1GB
 Reserved: 10.4GB

 Cleanup Complete.
 Allocated: 6.9GB
 Reserved: 7.7GB

Steps:   0%|                                                                                  | 0/1200 [00:16<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 7.7GB

Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Training completed, reloading SD Model.': '0.0/7.7GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 3




Windows 10 pro
WSL
palit rtx 3060 12gb

**Comment by LePrau** [comment]
The error message is "RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 12.00 GiB total capacity; 9.67 GiB already allocated; 0 bytes free; 10.37 GiB reserved in total by PyTorch)"

Basically, the process to aquire more VRAM than is available. Since 10.37 + 1 Gb would be less than 12 it seems you could still reduce the base VRAM usage on your system somehow (closing all programs except the browser).

Maybe some of the settings I used to run with a 10Gb 3080 work for you: https://github.com/d8ahazard/sd_dreambooth_extension/discussions/84#discussioncomment-4116619

**Comment by charliesdad** [comment]
> The error message is "RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 12.00 GiB total capacity; 9.67 GiB already allocated; 0 bytes free; 10.37 GiB reserved in total by PyTorch)"
> 
> Basically, the process to aquire more VRAM than is available. Since 10.37 + 1 Gb would be less than 12 it seems you could still reduce the base VRAM usage on your system somehow (closing all programs except the browser).
> 
> Maybe some of the settings I used to run with a 10Gb 3080 work for you: [#84 (comment)](https://github.com/d8ahazard/sd_dreambooth_extension/discussions/84#discussioncomment-4116619)


It seemed to work for one short session but the results were terrible 
since then its back to the same error. 
from every tutorial ive watched i thought a 12gb card would be okay?

From stuff ive read, am i right that pytorch is reserving the memory which is causing the error? 

from today -

**Comment by d8ahazard** [comment]
Sorry for the delay in response. So, it looks like you're using a 12GB GPU, which *should* work on windows if you set all of the optimizations.

I've added a wizard button to the "advanced" settings that will attempt to set the proper params for your machine so you can train. Give it a go, see if that helps.

I've linked this to the main Optimization thread, happy to continue the discussion there to help get you training.
