### ISSUE TITLE
Generated class images are not square, strange aspect ratio

### ISSUE THREAD

**Issue by rudimytro** [d8ahazard/sd_dreambooth_extension#1240]
### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Python 3.8.10 (default, Mar 14 2023, 14:51:09) 
[GCC 11.3.0]
Version: v1.2.1
Commit hash: 89f9faa63388756314e8a1d96cf86bf5e0663045
Installing requirements
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed fastapi-0.94.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 requests-2.31.0 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.21+efcd789.d20230525 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
```

### 2. Describe the bug

When generating class images 100% of the time the aspect ratio is not square. Generated class images are tall and have a slightly variable resolution (but similar aspect ratio) 
![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/13711526/fbd5c3f0-d544-49e8-932b-86db5e5ab4ab)
![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/13711526/c9237f4f-2e62-4809-aef8-af137c4a39d5)

I made sure to set 512x512 resolution where it is possible inside the extension, also to check x512 model when loading, tested multiple SD checkpoints & with/without EMA, tried different schedulers, and updated requirements - no luck.

I thought this may somehow reflect my training dataset - images there are not perfect squares at times, but my training dataset does have a square aspect ratio at times, and generated class images do not.

Additionally to that, for some runs generated class images look destroyed/corrupted significantly, but this is another issue on its own and I didn't find a way to reproduce it, as it happens randomly.

### 3. Provide logs

No crash, just a normal tqdm bar for generating class images

### 4. Environment

What OS?
Ubuntu 22.04.2

What GPU are you using?
RTX 3090 Ti

**Comment by d8ahazard** [comment]
The class images are generated to correspond with the aspect ratio of the
input images. The "resolution" field specifies the *maximum* allowed
resolution. This is intended behavior.
