### ISSUE TITLE
Access Denied when generating sample images.

### ISSUE THREAD

**Issue by vindia9** [d8ahazard/sd_dreambooth_extension#1247]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 0. Initial troubleshooting
Please check each of these before opening an issue. If you've checked them, **delete this section of your bug report**. Have you:
- Updated the Stable-Diffusion-WebUI to the latest version?
- Updated Dreambooth to the latest revision?
- Completely restarted the stable-diffusion-webUI, not just reloaded the UI?
- Read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?

### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Dreambooth revision: commit b46817bc73807848e726a3f79ef97e156e853928 (HEAD -> dev, origin/dev)
SD-WebUI revision: commit 20ae71faa8ef035c31aa3a410b707d792c8203a3 (HEAD -> master, tag: v1.3.0, origin/master, origin/HEAD)

Installing sd-webui-infinite-image-browsing requirement: python-dotenv
Installing sd-webui-infinite-image-browsing requirement: Pillow

If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: b46817bc73807848e726a3f79ef97e156e853928
Successfully installed tqdm-4.65.0 transformers-4.29.2

[+] xformers version 0.0.20 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.19.0 installed.
[+] diffusers version 0.16.1 installed.
[+] transformers version 4.29.2 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --theme light --xformers --opt-channelslast --autolaunch --server-name 0.0.0.0 --skip-install --no-hashing

#######################################################################################################
```

### 2. Describe the bug

I created a model based on "v1-5-purned.ckpt" and checked the options "Extract EMA Weights" and "Unfreeze Model". Below are the error logs and training parameters.
I deleted the cache for both the sd v1.5 model and Hugging Face and re-downloaded them to ensure that the files were not corrupted.
I found that no matter which parameters I change, I always encounter this error when generating sample images.

**Screenshots/Config**

``` json  db_config.json
{
    "weight_decay": 0.01,
    "attention": "xformers",
    "cache_latents": true,
    "clip_skip": 1,
    "concepts_list": [
        {
            "class_data_dir": "",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "class_negative_prompt": "",
            "class_prompt": "",
            "class_token": "",
            "instance_data_dir": "C:\\SD\\train_images\\images_test",
            "instance_prompt": "landscape",
            "instance_token": "",
            "is_valid": true,
            "n_save_sample": 1,
            "num_class_images_per": 0,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 20,
            "save_sample_negative_prompt": "",
            "save_sample_prompt": "landscape",
            "save_sample_template": ""
        }
    ],
    "concepts_path": "",
    "custom_model_name": "",
    "deterministic": true,
    "disable_class_matching": false,
    "disable_logging": false,
    "ema_predict": true,
    "epoch": 0,
    "epoch_pause_frequency": 0,
    "epoch_pause_time": 0,
    "freeze_clip_normalization": true,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "gradient_set_to_none": true,
    "graph_smoothing": 50,
    "half_model": false,
    "has_ema": true,
    "hflip": true,
    "infer_ema": true,
    "initial_revision": 0,
    "learning_rate": 2e-06,
    "learning_rate_min": 1e-06,
    "lifetime_revision": 0,
    "lora_learning_rate": 0.0001,
    "lora_model_name": "",
    "lora_txt_learning_rate": 5e-05,
    "lora_txt_rank": 4,
    "lora_txt_weight": 1,
    "lora_unet_rank": 4,
    "lora_weight": 1,
    "lora_use_buggy_requires_grad": false,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant_with_warmup",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "mixed_precision": "fp16",
    "model_dir": "C:\\SD\\sd-webui-aki-v4.1\\models\\dreambooth\\mymodel",
    "model_name": "mymodel",
    "model_path": "C:\\SD\\sd-webui-aki-v4.1\\models\\dreambooth\\mymodel",
    "noise_scheduler": "DDPM",
    "num_train_epochs": 100,
    "offset_noise": 0.15,
    "optimizer": "8bit AdamW",
    "pad_tokens": true,
    "pretrained_model_name_or_path": "C:\\SD\\sd-webui-aki-v4.1\\models\\dreambooth\\mymodel\\working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_scale": false,
    "prior_loss_target": 100.0,
    "prior_loss_weight": 0.75,
    "prior_loss_weight_min": 0.1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 1,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": false,
    "save_ema": true,
    "save_embedding_every": 10,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": false,
    "save_lora_for_extra_net": false,
    "save_preview_every": 1,
    "save_safetensors": true,
    "save_state_after": true,
    "save_state_cancel": false,
    "save_state_during": false,
    "scheduler": "DEISMultistep",
    "shared_diffusers_path": "",
    "shuffle_tags": false,
    "snapshot": "",
    "split_loss": true,
    "src": "C:\\SD\\sd-webui-aki-v4.1\\models\\Stable-diffusion\\v1-5-pruned.ckpt",
    "stop_text_encoder": 0.1,
    "strict_tokens": false,
    "dynamic_img_norm": false,
    "tenc_weight_decay": 0.01,
    "tenc_grad_clip_norm": 0,
    "tomesd": 0,
    "train_batch_size": 1,
    "train_imagic": false,
    "train_unet": true,
    "train_unfrozen": true,
    "txt_learning_rate": 2e-06,
    "use_concepts": false,
    "use_ema": true,
    "use_lora": false,
    "use_lora_extended": false,
    "use_shared_src": false,
    "use_subdir": true,
    "v2": false
}
```

### 3. Provide logs

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

``` log
  File "C:\SD\sd-webui-aki-v4.1\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 729, in start_training
    result = main(class_gen_method=class_gen_method)
  File "C:\SD\sd-webui-aki-v4.1\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1546, in main
    return inner_loop()
  File "C:\SD\sd-webui-aki-v4.1\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "C:\SD\sd-webui-aki-v4.1\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1500, in inner_loop
    check_save(True)
  File "C:\SD\sd-webui-aki-v4.1\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 794, in check_save
    save_weights(
  File "C:\SD\sd-webui-aki-v4.1\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1066, in save_weights
    shutil.rmtree(tmp_dir)
  File "C:\SD\sd-webui-aki-v4.1\python\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\SD\sd-webui-aki-v4.1\python\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\SD\sd-webui-aki-v4.1\python\lib\shutil.py", line 620, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\SD\sd-webui-aki-v4.1\python\lib\shutil.py", line 618, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access Denied。: 'C:\\Users\\Vindia\\AppData\\Local\\Temp\\tmp8p2y41lo\\text_encoder\\model.safetensors'
```

### 4. Environment

2 PC
Both of them use Windows 10 22H2
Native, not WSL
RTX 4090 or RTX 3090

**Comment by imuntyan** [comment]
Confirm same issue Python 3.10.11 dreambooth b396af26b7906aa82a29d8847e756396cb2c28fb

**Comment by vgaggia** [comment]
Is there a fix for it yet?

I'm getting RuntimeError: "triu_tril_cuda_template" not implemented for 'BFloat16'

Without any access denied errors

I'm on Python 3.10.9, and torch 2.0.1+cu118

**Comment by vindia9** [comment]
I fix it use #1260
But I can't use bf16 now.
Python 3.10.9, torch 2.0.1+cu118, xformers 0.0.20
In fp32 ok, in fp16, an error occurs.

``` log
No inf checks were recorded for this optimizer
```

**Comment by vgaggia** [comment]
I'm not sure what you referring to there with how you fixed yours?
But yeah i noticed fp32 works, but when it saves/generates images i get a huge dump about some keys being missing in my temp folder and it ends with:
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.
no idea if its related

**Comment by vindia9** [comment]
> 
You may modify the file based on this commit. https://github.com/d8ahazard/sd_dreambooth_extension/pull/1261/files
View the RAW file and directly replace the dreambooth/train_dreambooth.py.

As a beginner, I am uncertain where to modify the two parameters you mentioned.😂
I am attempting to conduct a training session using fp16 to see if any errors arise.

**Comment by vindia9** [comment]
> I'm not sure what you referring to there with how you fixed yours? But yeah i noticed fp32 works, but when it saves/generates images i get a huge dump about some keys being missing in my temp folder and it ends with: Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct. no idea if its related


You may modify the file based on this commit. https://github.com/d8ahazard/sd_dreambooth_extension/pull/1261/files
View the RAW file and directly replace the dreambooth/train_dreambooth.py.

As a beginner, I am uncertain where to modify the two parameters you mentioned.😂
I am attempting to conduct a training session using fp16 to see if any errors arise.

**Comment by vgaggia** [comment]
Alright, i've completely reinstalled my automatic1111 and it seems that its fixed the issue, i just backup up my models first

**Comment by DamienCz** [comment]
> 

我把dreambooth降低为了之前的版本就没问题了....试了好多办法只能暂时先这样

**Comment by DamienCz** [comment]
在新版本上确实存在数据冲突可太难过了

**Comment by DamienCz** [comment]
> > 在新版本上确实存在数据冲突可太难过了
> 
> ni hao , bu shi yi jing jie jue le ma ?

事实上，我并没有解决，我只是将最新的dreambooth降级到了上一个版本，你是说新的版本也可以使用bp16了吗？

**Comment by DamienCz** [comment]
> > > > 在新版本上确实存在数据冲突可太难过了
> > > 
> > > 
> > > ni hao , bu shi yi jing jie jue le ma ?
> > 
> > 
> > 事实上，我并没有解决，我只是将最新的dreambooth降级到了上一个版本，你是说新的版本也可以使用bp16了吗？
> 
> 哈哈哈憋不住了我也说中文 是解决了 花了了我一天的时间来弄这个 你练lora还是大模型啊，一般练大模型才会用到这个啊 我现在就在用fp16练

我在练大模型公司自用的来着，捣鼓了一天快气死了最后只能退版本

**Comment by vindia9** [comment]
> > > > > 在新版本上确实存在数据冲突可太难过了
> > > > 
> > > > 
> > > > ni hao , bu shi yi jing jie jue le ma ?
> > > 
> > > 
> > > 事实上，我并没有解决，我只是将最新的dreambooth降级到了上一个版本，你是说新的版本也可以使用bp16了吗？
> > 
> > 
> > 哈哈哈憋不住了我也说中文 是解决了 花了了我一天的时间来弄这个 你练lora还是大模型啊，一般练大模型才会用到这个啊 我现在就在用fp16练
> 
> 我在练大模型公司自用的来着，捣鼓了一天快气死了最后只能退版本

公司还缺人吗哈哈哈
我之前想回退的，但是想想觉得不至于啊

**Comment by DamienCz** [comment]
动漫公司来着要不加个v哈哈哈

**Comment by vindia9** [comment]
> 动漫公司来着要不加个v哈哈哈

我ID去掉数字就是哈哈哈哈
