### ISSUE TITLE
[Bug]: All ckpts saved during training produce the same results as base model

### ISSUE THREAD

**Issue by alcool91** [d8ahazard/sd_dreambooth_extension#1284]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I trained for 150 epochs using 8bit Adamw optimizer. When I tried to use the checkpoint in text2img none of the concepts were remembered and they matched each other for every saved ckpt. This is in contrast to the sample images produced during training, where the images closely matched concepts in the training data.

Later I loaded the selected the model and used the generate ckpt button. After doing that, the final generation model produced the right output. I was not able to figure out how to do this for earlier snapshots, although I did save them. When I select an earlier checkpoint, the generate ckpt button still applies to the latest snapshot.

![00052-7](https://github.com/d8ahazard/sd_dreambooth_extension/assets/7366322/15636863-a285-4e4c-9b15-160f7de0147d)

The top one is the latest ckpt which overrode the automatically saved ckpt when i pushed the save ckpt button. The others are various ckpts saved during training, extracted weights from model convert (both ema-only and non-ema), and the base model. 

I think that for some reason the automatically saved ckpts are not saving the correct weights. But I'm not sure about this because when I check the md5 hash it is different for the different ckpts.

### Steps to reproduce the problem

1. Train Model 
    - Using EMA
    - 8 bit AdamW
    - 0.65 Text Encoder step ratio
    - save ema weights to ckpt
    - NOT use EMA for inference
    - NOT use EMA for prediction

### Commit and libraries

Initializing Dreambooth
Dreambooth revision: dc413a14379b165355502d9f65856c40a4bb5b6f
Successfully installed accelerate-0.19.0 fastapi-0.94.1 gitpython-3.1.31 transformers-4.29.2

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.17 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.19.0 installed.
[+] diffusers version 0.16.1 installed.
[+] transformers version 4.29.2 installed.
[+] bitsandbytes version 0.35.4 installed.

### Command Line Arguments

```Shell
--autolaunch --xformers --api
```

### Console logs

```Shell
https://pastebin.com/avRQ8cyP
```

### Additional information

To address the permissionerror that kept recurring for me I used the method presented [here](https://github.com/d8ahazard/sd_dreambooth_extension/issues/1269#issuecomment-1584998667), I do not know if that is relevant since I do not understand what the temp folders are used for.

**Comment by Dwuuds** [comment]
Try to generate samples in the dreambooth settings. Are they different from the base model? I think I'm having this problem as well, its very strange. 

Essentially, the samples I generate within the DB "generate" menu _are_ accurate and show the model progressing, but the actual CKPT it generates doesn't seem to be any different from the base training model.

**Comment by alcool91** [comment]
This issue is ongoing as of July 3rd for me. Does anybody have any suggestions?
