### ISSUE TITLE
[Bug]: Doesnt install

### ISSUE THREAD

**Issue by ElMouse** [d8ahazard/sd_dreambooth_extension#1317]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

SD webgui celan install, everyting working properly. Different models generte normally.
Install from webgui as per instruction, getting error. googling and asking chatgpt didnt help.
Error log in console log.

### Steps to reproduce the problem

1. install SD webgui
2. check its working
3. try to install dreambooth from webgui
4. get the error log

### Commit and libraries

Starting at `Initializing Dreambooth` and ending several lines below at `[+] bitsandbytes version 0.35.4 installed.`.

### Command Line Arguments

```Shell
default
```

### Console logs

```Shell
*** Error running install.py for extension D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension.it/s]
*** Command: "D:\myProjects\StableDiffWebUI\system\python\python.exe" "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\install.py"
*** Error code: 1
*** stdout: no module 'xformers'. Processing without...
*** no module 'xformers'. Processing without...
*** No module 'xformers'. Proceeding without it.
*** If submitting an issue on github, please provide the full startup log for debugging purposes.
***
*** Initializing Dreambooth
*** Dreambooth revision: c2a5617c587b812b5a408143ddfb18fc49234edf
*** # Requirement installation exception:
*** Ignoring tensorboard: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
*** Collecting accelerate~=0.19.0 (from -r D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 1))
*** Using cached accelerate-0.19.0-py3-none-any.whl (219 kB)
*** Collecting bitsandbytes==0.35.4 (from -r D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 2))
*** Using cached bitsandbytes-0.35.4-py3-none-any.whl (62.5 MB)
*** Collecting dadaptation==3.1 (from -r D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 3))
*** Using cached dadaptation-3.1.tar.gz (13 kB)
*** Installing build dependencies: started
*** Installing build dependencies: finished with status 'done'
*** Getting requirements to build wheel: started
*** Getting requirements to build wheel: finished with status 'done'
*** ERROR: Exception:
*** Traceback (most recent call last):
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
*** status = run_func(*args)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
*** return func(self, options, args)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
*** requirement_set = resolver.resolve(
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
*** result = self._result = resolver.resolve(
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
*** state = resolution.resolve(requirements, max_rounds=max_rounds)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
*** self._add_to_criteria(self.state.criteria, r, parent=None)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
*** if not criterion.candidates:
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
*** return bool(self._sequence)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
*** return any(self)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
*** return (c for c in iterator if id(c) not in self._incompatible_ids)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
*** candidate = func()
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
*** self._link_candidate_cache[link] = LinkCandidate(
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
*** super().__init__(
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
*** self.dist = self._prepare()
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
*** dist = self._prepare_distribution()
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
*** return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 538, in prepare_linked_requirement
*** return self._prepare_linked_requirement(req, parallel_builds)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 653, in _prepare_linked_requirement
*** dist = _get_prepared_distribution(
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
*** abstract_dist.prepare_distribution_metadata(
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 48, in prepare_distribution_metadata
*** self._install_build_reqs(finder)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 118, in _install_build_reqs
*** build_reqs = self._get_build_requires_wheel()
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 95, in _get_build_requires_wheel
*** return backend.get_requires_for_build_wheel()
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\utils\misc.py", line 697, in get_requires_for_build_wheel
*** return super().get_requires_for_build_wheel(config_settings=cs)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
*** return self._call_hook('get_requires_for_build_wheel', {
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
*** raise BackendUnavailable(data.get('traceback', ''))
*** pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
*** obj = import_module(mod_path)
*** File "importlib\__init__.py", line 126, in import_module
*** File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
*** File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
*** File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
*** File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
*** File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
*** File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
*** File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
*** File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
*** File "<frozen importlib._bootstrap_external>", line 883, in exec_module
*** File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
*** File "C:\Users\rusan\AppData\Local\Temp\pip-build-env-9x5hqq4r\overlay\Lib\site-packages\setuptools\__init__.py", line 15, in <module>
*** import setuptools.version
*** File "C:\Users\rusan\AppData\Local\Temp\pip-build-env-9x5hqq4r\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
*** from ._importlib import metadata
*** File "C:\Users\rusan\AppData\Local\Temp\pip-build-env-9x5hqq4r\overlay\Lib\site-packages\setuptools\_importlib.py", line 44, in <module>
*** import importlib.metadata as metadata  # noqa: F401
*** File "importlib\metadata\__init__.py", line 17, in <module>
*** File "importlib\metadata\_adapters.py", line 3, in <module>
*** File "email\message.py", line 15, in <module>
*** File "email\utils.py", line 29, in <module>
*** File "socket.py", line 51, in <module>
*** ModuleNotFoundError: No module named '_socket'
***
*** stderr: D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
***   rank_zero_deprecation(
*** loading stable diffusion model: ImportError
*** Traceback (most recent call last):
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\install.py", line 33, in <module>
***     from postinstall import actual_install
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\postinstall.py", line 14, in <module>
***     from dreambooth import shared
***   File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 434, in <module>
***     is_auto = load_auto_settings()
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 46, in load_auto_settings
***     sd_model = ws.sd_model
***   File "D:\myProjects\StableDiffWebUI\webui\modules\shared.py", line 754, in sd_model
***     return modules.sd_models.model_data.get_sd_model()
***   File "D:\myProjects\StableDiffWebUI\webui\modules\sd_models.py", line 439, in get_sd_model
***     load_model()
***   File "D:\myProjects\StableDiffWebUI\webui\modules\sd_models.py", line 465, in load_model
***     from modules import lowvram, sd_hijack
***   File "D:\myProjects\StableDiffWebUI\webui\modules\sd_hijack.py", line 5, in <module>
***     import modules.textual_inversion.textual_inversion
***   File "D:\myProjects\StableDiffWebUI\webui\modules\textual_inversion\textual_inversion.py", line 16, in <module>
***     from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint, errors, hashes
***   File "D:\myProjects\StableDiffWebUI\webui\modules\processing.py", line 18, in <module>
***     from modules.sd_hijack import model_hijack
*** ImportError: cannot import name 'model_hijack' from partially initialized module 'modules.sd_hijack' (most likely due to a circular import) (D:\myProjects\StableDiffWebUI\webui\modules\sd_hijack.py)
***
***
*** Stable diffusion model failed to load
*** loading stable diffusion model: ImportError
*** Traceback (most recent call last):
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\install.py", line 33, in <module>
***     from postinstall import actual_install
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\postinstall.py", line 14, in <module>
***     from dreambooth import shared
***   File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 436, in <module>
***     load_vars()
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 352, in load_vars
***     is_auto = load_auto_settings()
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 46, in load_auto_settings
***     sd_model = ws.sd_model
***   File "D:\myProjects\StableDiffWebUI\webui\modules\shared.py", line 754, in sd_model
***     return modules.sd_models.model_data.get_sd_model()
***   File "D:\myProjects\StableDiffWebUI\webui\modules\sd_models.py", line 439, in get_sd_model
***     load_model()
***   File "D:\myProjects\StableDiffWebUI\webui\modules\sd_models.py", line 465, in load_model
***     from modules import lowvram, sd_hijack
***   File "D:\myProjects\StableDiffWebUI\webui\modules\sd_hijack.py", line 5, in <module>
***     import modules.textual_inversion.textual_inversion
***   File "D:\myProjects\StableDiffWebUI\webui\modules\textual_inversion\textual_inversion.py", line 16, in <module>
***     from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint, errors, hashes
***   File "D:\myProjects\StableDiffWebUI\webui\modules\processing.py", line 18, in <module>
***     from modules.sd_hijack import model_hijack
*** ImportError: cannot import name 'model_hijack' from partially initialized module 'modules.sd_hijack' (most likely due to a circular import) (D:\myProjects\StableDiffWebUI\webui\modules\sd_hijack.py)
***
***
*** Stable diffusion model failed to load
*** Traceback (most recent call last):
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\install.py", line 35, in <module>
***     actual_install()
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\postinstall.py", line 41, in actual_install
***     install_requirements()
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\postinstall.py", line 87, in install_requirements
***     raise grepexc
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\postinstall.py", line 75, in install_requirements
***     pip_install("-r", req_file)
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension\postinstall.py", line 53, in pip_install
***     output = subprocess.check_output(
***   File "subprocess.py", line 420, in check_output
***   File "subprocess.py", line 524, in run
*** subprocess.CalledProcessError: Command '['D:\\myProjects\\StableDiffWebUI\\system\\python\\python.exe', '-m', 'pip', 'install', '-r', 'D:\\myProjects\\StableDiffWebUI\\webui\\extensions\\sd_dreambooth_extension\\requirements.txt']' returned non-zero exit status 2.
```

**Comment by ElMouse** [comment]
windows 11, rtx 2080 mobile, i7-8750H if it makes any difference

**Comment by jonatalamantes** [comment]
Try to install the release version and not the version from MAIN

**Comment by ElMouse** [comment]
did you mean 1.0.14?
Doesnt install either

`*** Error running install.py for extension D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14.
*** Command: "D:\myProjects\StableDiffWebUI\system\python\python.exe" "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\install.py"
*** Error code: 1
*** stdout: no module 'xformers'. Processing without...
*** no module 'xformers'. Processing without...
*** No module 'xformers'. Proceeding without it.
*** If submitting an issue on github, please provide the full startup log for debugging purposes.
***
*** Initializing Dreambooth
*** Dreambooth revision:
*** # Requirement installation exception:
*** Ignoring tensorboard: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
*** Collecting accelerate~=0.19.0 (from -r D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\requirements.txt (line 1))
*** Using cached accelerate-0.19.0-py3-none-any.whl (219 kB)
*** Collecting bitsandbytes==0.35.4 (from -r D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\requirements.txt (line 2))
*** Using cached bitsandbytes-0.35.4-py3-none-any.whl (62.5 MB)
*** Collecting dadaptation==3.1 (from -r D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\requirements.txt (line 3))
*** Using cached dadaptation-3.1.tar.gz (13 kB)
*** Installing build dependencies: started
*** Installing build dependencies: finished with status 'done'
*** Getting requirements to build wheel: started
*** Getting requirements to build wheel: finished with status 'done'
*** ERROR: Exception:
*** Traceback (most recent call last):
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
*** status = run_func(*args)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
*** return func(self, options, args)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
*** requirement_set = resolver.resolve(
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
*** result = self._result = resolver.resolve(
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
*** state = resolution.resolve(requirements, max_rounds=max_rounds)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
*** self._add_to_criteria(self.state.criteria, r, parent=None)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
*** if not criterion.candidates:
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
*** return bool(self._sequence)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
*** return any(self)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
*** return (c for c in iterator if id(c) not in self._incompatible_ids)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
*** candidate = func()
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
*** self._link_candidate_cache[link] = LinkCandidate(
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
*** super().__init__(
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
*** self.dist = self._prepare()
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
*** dist = self._prepare_distribution()
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
*** return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 538, in prepare_linked_requirement
*** return self._prepare_linked_requirement(req, parallel_builds)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 653, in _prepare_linked_requirement
*** dist = _get_prepared_distribution(
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
*** abstract_dist.prepare_distribution_metadata(
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 48, in prepare_distribution_metadata
*** self._install_build_reqs(finder)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 118, in _install_build_reqs
*** build_reqs = self._get_build_requires_wheel()
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 95, in _get_build_requires_wheel
*** return backend.get_requires_for_build_wheel()
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_internal\utils\misc.py", line 697, in get_requires_for_build_wheel
*** return super().get_requires_for_build_wheel(config_settings=cs)
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
*** return self._call_hook('get_requires_for_build_wheel', {
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
*** raise BackendUnavailable(data.get('traceback', ''))
*** pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
*** File "D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
*** obj = import_module(mod_path)
*** File "importlib\__init__.py", line 126, in import_module
*** File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
*** File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
*** File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
*** File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
*** File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
*** File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
*** File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
*** File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
*** File "<frozen importlib._bootstrap_external>", line 883, in exec_module
*** File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
*** File "C:\Users\rusan\AppData\Local\Temp\pip-build-env-46j_waml\overlay\Lib\site-packages\setuptools\__init__.py", line 15, in <module>
*** import setuptools.version
*** File "C:\Users\rusan\AppData\Local\Temp\pip-build-env-46j_waml\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
*** from ._importlib import metadata
*** File "C:\Users\rusan\AppData\Local\Temp\pip-build-env-46j_waml\overlay\Lib\site-packages\setuptools\_importlib.py", line 44, in <module>
*** import importlib.metadata as metadata  # noqa: F401
*** File "importlib\metadata\__init__.py", line 17, in <module>
*** File "importlib\metadata\_adapters.py", line 3, in <module>
*** File "email\message.py", line 15, in <module>
*** File "email\utils.py", line 29, in <module>
*** File "socket.py", line 51, in <module>
*** ModuleNotFoundError: No module named '_socket'
***
*** stderr: D:\myProjects\StableDiffWebUI\system\python\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
***   rank_zero_deprecation(
*** loading stable diffusion model: ImportError
*** Traceback (most recent call last):
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\install.py", line 33, in <module>
***     from postinstall import actual_install
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\postinstall.py", line 14, in <module>
***     from dreambooth import shared
***   File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\dreambooth\shared.py", line 434, in <module>
***     is_auto = load_auto_settings()
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\dreambooth\shared.py", line 46, in load_auto_settings
***     sd_model = ws.sd_model
***   File "D:\myProjects\StableDiffWebUI\webui\modules\shared.py", line 754, in sd_model
***     return modules.sd_models.model_data.get_sd_model()
***   File "D:\myProjects\StableDiffWebUI\webui\modules\sd_models.py", line 439, in get_sd_model
***     load_model()
***   File "D:\myProjects\StableDiffWebUI\webui\modules\sd_models.py", line 465, in load_model
***     from modules import lowvram, sd_hijack
***   File "D:\myProjects\StableDiffWebUI\webui\modules\sd_hijack.py", line 5, in <module>
***     import modules.textual_inversion.textual_inversion
***   File "D:\myProjects\StableDiffWebUI\webui\modules\textual_inversion\textual_inversion.py", line 16, in <module>
***     from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint, errors, hashes
***   File "D:\myProjects\StableDiffWebUI\webui\modules\processing.py", line 18, in <module>
***     from modules.sd_hijack import model_hijack
*** ImportError: cannot import name 'model_hijack' from partially initialized module 'modules.sd_hijack' (most likely due to a circular import) (D:\myProjects\StableDiffWebUI\webui\modules\sd_hijack.py)
***
***
*** Stable diffusion model failed to load
*** loading stable diffusion model: ImportError
*** Traceback (most recent call last):
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\install.py", line 33, in <module>
***     from postinstall import actual_install
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\postinstall.py", line 14, in <module>
***     from dreambooth import shared
***   File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\dreambooth\shared.py", line 436, in <module>
***     load_vars()
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\dreambooth\shared.py", line 352, in load_vars
***     is_auto = load_auto_settings()
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\dreambooth\shared.py", line 46, in load_auto_settings
***     sd_model = ws.sd_model
***   File "D:\myProjects\StableDiffWebUI\webui\modules\shared.py", line 754, in sd_model
***     return modules.sd_models.model_data.get_sd_model()
***   File "D:\myProjects\StableDiffWebUI\webui\modules\sd_models.py", line 439, in get_sd_model
***     load_model()
***   File "D:\myProjects\StableDiffWebUI\webui\modules\sd_models.py", line 465, in load_model
***     from modules import lowvram, sd_hijack
***   File "D:\myProjects\StableDiffWebUI\webui\modules\sd_hijack.py", line 5, in <module>
***     import modules.textual_inversion.textual_inversion
***   File "D:\myProjects\StableDiffWebUI\webui\modules\textual_inversion\textual_inversion.py", line 16, in <module>
***     from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint, errors, hashes
***   File "D:\myProjects\StableDiffWebUI\webui\modules\processing.py", line 18, in <module>
***     from modules.sd_hijack import model_hijack
*** ImportError: cannot import name 'model_hijack' from partially initialized module 'modules.sd_hijack' (most likely due to a circular import) (D:\myProjects\StableDiffWebUI\webui\modules\sd_hijack.py)
***
***
*** Stable diffusion model failed to load
*** Traceback (most recent call last):
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\install.py", line 35, in <module>
***     actual_install()
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\postinstall.py", line 41, in actual_install
***     install_requirements()
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\postinstall.py", line 87, in install_requirements
***     raise grepexc
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\postinstall.py", line 75, in install_requirements
***     pip_install("-r", req_file)
***   File "D:\myProjects\StableDiffWebUI\webui\extensions\sd_dreambooth_extension-1.0.14\postinstall.py", line 53, in pip_install
***     output = subprocess.check_output(
***   File "subprocess.py", line 420, in check_output
***   File "subprocess.py", line 524, in run
*** subprocess.CalledProcessError: Command '['D:\\myProjects\\StableDiffWebUI\\system\\python\\python.exe', '-m', 'pip', 'install', '-r', 'D:\\myProjects\\StableDiffWebUI\\webui\\extensions\\sd_dreambooth_extension-1.0.14\\requirements.txt']' returned non-zero exit status 2.`

**Comment by ElMouse** [comment]
Installed without any problems throught interface on SD clean insatalled with https://github.com/EmpireMediaScience/A1111-Web-UI-Installer.
Suppose has to do with venv. My standart install of SD web ui previosuly was working without venv
