### ISSUE TITLE
Add loaded VAE model training

### ISSUE THREAD

**Issue by mutucc** [d8ahazard/sd_dreambooth_extension#132]
If want to train animate model, vae model is indispensable. There is a "-- pretrained_vae_name_or_path" judgment in "train_dreambooth. py". How to enable it in dreambooth on the webui
Please see if you can implement this function.
thank
![ce393c1589b662b3ec685347bf2185b](https://user-images.githubusercontent.com/56072810/201400433-42115bfa-261a-4604-8e4a-032a346073af.png)

**Comment by d8ahazard** [comment]
It'd just have to be added in the UI. I can probably do this sometime today
or tomorrow.

**Comment by d8ahazard** [comment]
Implemented with d15cbc9
