### ISSUE TITLE
[Bug]: Missing model directory, removing model

### ISSUE THREAD

**Issue by alesys** [d8ahazard/sd_dreambooth_extension#1325]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After this last update it is not possible to do Model / Create / Create Model. 

### Steps to reproduce the problem

Update to the latest version.
Go to Dreambooth tab.
Attempt to create a new Model. 

### Commit and libraries

Initializing Dreambooth
Dreambooth revision: b4053defa6ae018b2ea56ac243aa55063f76fe0e
Successfully installed accelerate-0.21.0 diffusers-0.19.3 fastapi-0.94.1 gitpython-3.1.32 transformers-4.30.2

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.20 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.21.0 installed.
[+] diffusers version 0.19.3 installed.
[+] transformers version 4.30.2 installed.
[+] bitsandbytes version 0.35.4 installed.

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
https://pastebin.com/TkdechPQ
```

**Comment by AlexMcCown** [comment]
I had this same issue, i had to change line 1278 in sd_to_diff.py from `vae.load_state_dict(converted_vae_checkpoint)` to `vae.load_state_dict(converted_vae_checkpoint, strict=False)` 
However as a result i have had some model issues, i have had to start up with --disable-nan-check to get txt2img to work and img2img no longer works on the trained model so i would not call this a fix; however it does in a pinch

**Comment by mcgrimm** [comment]
same issue above 
just fyi , i think my turnarround solution is try reinstall other version streambooth by

git checkout https://github.com/d8ahazard/sd_dreambooth_extension/commit/dc413a14379b165355502d9f65856c40a4bb5b6f

then pip install -r requirments.txt underneath the dreambooth folder.

**Comment by desper327** [comment]
> 可以确认同样的问题。我通过手动添加扩散模型的部分来使其工作。创建模型时，它只会转换unet和调度程序，但会在给出上述问题的vae处停止。为了让它工作，我必须在 models/dreambooth = " tty/working" 中添加文件夹/子文件夹，然后添加 model_index.json、vae、text_encoder、feature_extractor 和 tokenizer 文件夹和内容，然后再次创建模型“tty”

It's really worked for me ,thank you !
