### ISSUE TITLE
[Bug]: python3: undefined symbol: cudaRuntimeGetVersion

### ISSUE THREAD

**Issue by Cinderella-Man** [d8ahazard/sd_dreambooth_extension#1326]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I updated my extensions today and dreambooth extension is causing the whole A1111 to fail on startup

### Steps to reproduce the problem

1. Starting ./webui
2. Crashed upon startup

### Commit and libraries

b4053defa6ae018b2ea56ac243aa55063f76fe0e

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
https://pastebin.com/27cCRsKY
```

**Comment by wrapss** [comment]
same

**Comment by GNU-Linuxer** [comment]
same

**Comment by mateuspestana** [comment]
Same here.

**Comment by sbersier** [comment]
Same here:
I can launch (and run) automatic1111 without dreambooth. But, as soon as sd_dreambooth (revision: cf086c536b141fc522ff11f6cffc8b7b12da04b9) is installed (in the extensions folder)  webui.sh and launch.py crashes with the same message as @Cinderella-Man

**Comment by sbersier** [comment]
In my case, I found that the `bitsandbytes` module version was the problem.

NOTE: I tested the following on linux Ubuntu 22.04 with CUDA 12.2

Here is how I solved it:

**A)** 
Activate the venv:
`source /venv/bin/activate`

`pip uninstall bitsandbytes`

delete any bitsandbytes related folders:

`rm -rf stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes*`



**B)** 
Edit the `stable-diffusion-webui/extensions/sd_dreambooth_extension/requirements.txt` file:

I replaced (line 2):

`bitsandbytes==0.35.4`

with:

`bitsandbytes==0.41.1`



**C)** 
I needed to specify the CUDA version to use.

c.1) To get the cuda version:

`nvcc --version`

In my case, it returns:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jul_11_02:20:44_PDT_2023
Cuda compilation tools, release 12.2, V12.2.128
Build cuda_12.2.r12.2/compiler.33053471_0
```


c.2) So, I added the following line to my `.bashrc `file in my $HOME folder (note the absence of decimal point in the version):

`export BNB_CUDA_VERSION=122 ` (put here your cuda version)

Save your `.bashrc` file

Then, in the terminal:
`
source ~/.bashrc`

Test with:

`echo $BNB_CUDA_VERSION`

It should return your cuda version. In my case it returns;  `122`


D) Finally:

`./webui.sh --xformers`

It launches correctly and the Dreambooth tab is there.

Note that I haven't tried yet to train a Lora with this new configuration but everything seems OK...

**Comment by Mte90** [comment]
I changed also the `postinstall.py` that check the package version.

**Comment by sbersier** [comment]
@Mte90 Indeed a good idea. And it could also be a good idea to set the environment variable  DREAMBOOTH_SKIP_INSTALL=True (in the bashrc file) in order not to put a mess in the install again.

**Comment by Mte90** [comment]
well the issue is still there so closing doesn't make so much sense...
