### ISSUE TITLE
Not using xformers memory efficient attention

### ISSUE THREAD

**Issue by codestuff001** [d8ahazard/sd_dreambooth_extension#133]
**Have you read the Readme?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**
```
loading Dreambooth reqs from C:\Apps\stable-diffusion\extensions\sd_dreambooth_extension\requirements.txt
Checking Dreambooth requirements.
Checking torch and torchvision versions
Dreambooth revision is 4684f0faea19c243216eac2278a42fcfcbbd756b
[!] Not using xformers memory efficient attention.
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.
```

**Describe the bug**
Xformers doesn't seem to be loading correctly (see xformers notification above). The Dreambooth tab appears in the webui fine, but when I go to train, I get a CUDA out of memory error. I'm not sure the cause of the issue, but I know xformers is important.

Here's the out of memory CUDA error:
```
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 12.00 GiB total capacity; 9.34 GiB already allocated; 0 bytes free; 10.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Provide logs**

**Environment**
Windows 10 (native)
3080ti

**Comment by d8ahazard** [comment]
You need to use the -xformers command line argument, and either be running Python 3.10 or install/build xformers manually first:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Xformers
