### ISSUE TITLE
[Bug]: Black Classification Images are being generated

### ISSUE THREAD

**Issue by commander443** [d8ahazard/sd_dreambooth_extension#1330]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

black images when training

### Steps to reproduce the problem

Dreambooth
type in nude or naked for class images
results are black squares 
SFW is fine 

### Commit and libraries

Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a
[+] xformers version 0.0.20 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.21.0 installed.
[+] diffusers version 0.19.3 installed.
[+] transformers version 4.30.2 installed.
[+] bitsandbytes version 0.35.4 installed.

Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?
Yes
Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?
Yes
Have you updated Dreambooth to the latest revision?
Yes
Have you updated the Stable-Diffusion-WebUI to the latest version?
Yes
No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.
OK
<img width="588" alt="Screenshot 2023-08-21 021549" src="https://github.com/d8ahazard/sd_dreambooth_extension/assets/66979958/bdc931f7-e5e0-4c75-ba48-064025fd3bb6">

### Command Line Arguments

```Shell
--xformers
```

### Console logs

```Shell
nothing on log
```

**Comment by commander443** [comment]
@d8ahazard Any idea why I get this ?

**Comment by LDYang694** [comment]
I also meet this problem,
![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/62846124/96a80b1c-b5e4-4764-ae28-533de803c0be)

**Comment by Prometheus3D** [comment]
Perhaps it's an NSFW filter perhaps?

Look at the outputs of the black images and see what the differences are compared the ones that generated.

**Comment by Prometheus3D** [comment]
Work around here: https://github.com/d8ahazard/sd_dreambooth_extension/discussions/1350

**Comment by madrooky** [comment]
Got the same issue. Not yet tried the workaround but thanks for pointing that out!

**Comment by levicki** [comment]
@commander443 You are getting those black images because of NSFW filter (see details in https://github.com/d8ahazard/sd_dreambooth_extension/issues/1352).

Considering that manual workaround is needed for every training and that Extended LoRA training is broken for a while, Dreambooth has become unusable. Just uninstall it and use something else because the author doesn't seem to give a damn.
