### ISSUE TITLE
[Bug]: GradioDeprecationWarning: The `style` method is deprecated.

### ISSUE THREAD

**Issue by illuculent** [d8ahazard/sd_dreambooth_extension#1355]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

WARNING:py.warnings:C:\stable-diffusion\Packages\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py:257: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):

### Steps to reproduce the problem

On Load

### Commit and libraries

Starting at `Initializing Dreambooth` and ending several lines below at `[+] bitsandbytes version 0.35.4 installed.`.

### Command Line Arguments

```Shell
N/A
```

### Console logs

```Shell
N/A
```

### Additional information

N/A

**Comment by d8ahazard** [comment]
This is fixed in the /dev branch
