### ISSUE TITLE
Train button does nothing when pressed

### ISSUE THREAD

**Issue by deezee999** [d8ahazard/sd_dreambooth_extension#136]
**Have you read the Readme?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is 3b3a8002da3a780c276934e8bcf308aa822f1e22
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`
 Yes
**Describe the bug**
I followed all the steps, pressing the train button does nothing, even the console doesn't display any new info.

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.
No logs to be found
**Environment**
Windows 10 
What GPU are you using?
RTX 2070 Super 8GB

**Comment by sparkle-motion-2** [comment]
Same for me....

**Comment by d8ahazard** [comment]
Can you post a screenshot of your training settings?

**Comment by deezee999** [comment]
![Stable-Diffusion (1)](https://user-images.githubusercontent.com/68804033/201444937-f6ef9d54-953f-4153-b6ad-396e004749b0.jpg)
![Stable-Diffusion (2)](https://user-images.githubusercontent.com/68804033/201444941-79b04129-f9cc-4afd-b482-6df588d4daa6.jpg)

I left the prompt and directories blank cause I deleted the folder earlier. But the rest of the settings is what I used. I did try it without things like 8bit adam on, but didn't get any changes.

**Comment by deezee999** [comment]
![Stable-Diffusion (3)](https://user-images.githubusercontent.com/68804033/201445193-25c668fc-7efa-4790-803f-a36783036fd4.jpg)
also, I don't have the blue checkmark button that I do for txt2img, img2img, inpaint, etc.

**Comment by d8ahazard** [comment]
You need to first create a model, then select the model in the dropdown at the top, and then - at the very least, specify a directory with instance data ("Instance directory"). Please refer to the readme for further info on setup.

**Comment by deezee999** [comment]
No I did exactly that already earlier, I just deleted the models after I tried that.

**Comment by sparkle-motion-2** [comment]
<img width="524" alt="Screenshot 2022-11-11 172250" src="https://user-images.githubusercontent.com/30934429/201447158-c7915ed9-8e42-423a-8ee6-c2c04eae07f9.png">

Same as deezee999. 

Why did you close this. It is not fixed.
