### ISSUE TITLE
dreambooth tab not showing up[Bug]: 

### ISSUE THREAD

**Issue by varianwrynn0198** [d8ahazard/sd_dreambooth_extension#1368]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I installed Stable Diffusion DreamBooth but the menu does not appear. I think I'm the only person having this problem and I've been trying to solve it for two days. I tried uninstalling and reinstalling but it still doesn't work. It appears installed but is not added to the menu. I can't find a solution. What should I do

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...
a

### Commit and libraries

Starting at `Initializing Dreambooth` and ending several lines below at `[+] bitsandbytes version 0.35.4 installed.`.a

### Command Line Arguments

```Shell
dreambooth_api
        model_cfg: DreamboothConfig = Body(description="The config to save"),
    NameError: name 'DreamboothConfig' is not defined
```

### Console logs

```Shell
dreambooth_api
        model_cfg: DreamboothConfig = Body(description="The config to save"),
    NameError: name 'DreamboothConfig' is not defined
```

**Comment by StrikeLines** [comment]
Can confirm i am having this same problem.

**Comment by valentindiehl** [comment]
I'm encountering the same issue

**Comment by EgeTy** [comment]
Same issue for me, any solutions?

**Comment by FurkanHuman** [comment]
I'm having a similar problem with "SD-v2-1_512-nonema-pruned" as well. When I press the Generate Class Images button, when I say yyada train, it creates the same flat image with a noisy cream-colored "sand-like" slight smear. creating the same images.
![69e09f995dc2745a1a7c0e69406816d48bba2183](https://github.com/d8ahazard/sd_dreambooth_extension/assets/77467154/e2fb1d2b-2814-4cc3-a5ec-64ade71c7293)

**Comment by Emrex3507** [comment]
+1

**Comment by MustafaErenBozkurt** [comment]
+1
