### ISSUE TITLE
CPU training fails

### ISSUE THREAD

**Issue by chrisparkernz** [d8ahazard/sd_dreambooth_extension#14]
On Windows 11 when attempting CPU training I get this error:

`Error an illegal memory access was encountered at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu`

Look like it's got a hardcoded reference?

Also it looks like when 'Mixed Precision' is set to 'FP16', CPU training also fails due to: 

`RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'`

Don't think CPU training supports FP16.

**Comment by hugostranger** [comment]
Ran this a second time and encountered slightly different error:

`Error an illegal memory access was encountered at line 89 in file D:\ai\tool\bitsandbytes\csrc\ops.cu`

**Comment by d8ahazard** [comment]
I think this might be a symptom of not running with accelerate launch.

If you wanted to test this, you could open a command-prompt in the SD directory, then do:
.\venv\Scripts\activate.bat
accelerate config (enter the following when prompted, needed once)
- 0
- 0
- NO
- NO
- All
- fp16
accelerate launch .\launch.py

**Comment by hugostranger** [comment]
Ran the accelerate config and added the accelerate settings to the webui.bat as mentioned in https://github.com/d8ahazard/sd_dreambooth_extension/issues/13 however that didn't resolve the issue.

Did some further testing and I think it's because 8bit adam was enabled.  So 8bit adam and cpu training look mutually exclusive.

**Comment by hugostranger** [comment]
By the way really appreciate this project.  Dreambooth on Windows in the WebUI is amazing!

**Comment by d8ahazard** [comment]
> Ran the accelerate config and added the accelerate settings to the webui.bat as mentioned in #13 however that didn't resolve the issue.
> 
> Did some further testing and I think it's because 8bit adam was enabled. So 8bit adam and cpu training look mutually exclusive.

I'll note that in the readme. Closing, unless there's something else I missed.
