### ISSUE TITLE
Train button does nothing when clicked

### ISSUE THREAD

**Issue by sparkle-motion-2** [d8ahazard/sd_dreambooth_extension#142]
Have you read the Readme?
Yes

Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?
Yes

Have you updated Dreambooth to the latest revision?
Yes

Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth
Dreambooth revision is 7fd5da13c6459ea08f7ed0bf194b6467e9ea3a9b
[!] Not using xformers memory efficient attention.
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.

Describe the bug
I followed all the steps, pressing the train button does nothing, even the console doesn't display any new info.

Provide logs
If a crash has occurred, please provide the entire stack trace from the log, including the last few log messages before the crash occurred.
No logs

Environment
Windows 10
What GPU are you using?
RTX 3090

**Comment by sparkle-motion-2** [comment]
<img width="524" alt="Screenshot 2022-11-11 172250" src="https://user-images.githubusercontent.com/30934429/201447589-9ebd37d7-62c7-4e9b-ac4f-3a5fc70b7a8a.png">
Here is a screenshot of the settings.

**Comment by Slowly-Grokking** [comment]
You need to add a dataset directory

when that gives you an error, you probably need to uncheck the gradient checkpoints, and set mixed precision to f16.

**Comment by d8ahazard** [comment]
Please post the contents of your concepts_list.json file and a full console output when you start training.

**Comment by seihoukei** [comment]
Having the same issue. 

Not using json file, not using class images. Tried various combinations of settings. 

Console does not report anything. I click train, progress bar appears for a second, then disappears. No messages anywhere.

**Comment by ocdwolf** [comment]
Same issue here as well.
Trained in dreambooth with no problems the last few days, but today it won't work.
Same workflow, everything's up to date, did all the basic troubleshooting, but now when I click "train", the progress bar pops up for a quick second and disappears, no information reported in console.

**Comment by lustfeind** [comment]
Same issue here: My machine is a Apple Silicon M1 Pro

**Comment by seihoukei** [comment]
Okay, in my case it starts to work if I tick "Uses the image's filename as the image labels instead of the instance prompt". Neither kind of Instance prompt (with [filewords] and without) works otherwise.

**Comment by ocdwolf** [comment]
> Okay, in my case it starts to work if I tick "Uses the image's filename as the image labels instead of the instance prompt". Neither kind of Instance prompt (with [filewords] and without) works otherwise.

Yup that started the training for me, weird, I haven't had to check that box at all for training the last few times.

**Comment by lustfeind** [comment]
Same here: Check "Uses the image's filename as the image labels instead of the instance prompt" and Training starts.

**Comment by d8ahazard** [comment]
So this is 4x days old now, half the mentioned options don't even exist any more, and I've added a bunch of nags to indicate when params are missing. 

As such, I'm closing this. Feel free to re-open or create a new issue if you want to yell at me more about something.
