### ISSUE TITLE
Support AMD with 2 lines of code

### ISSUE THREAD

**Issue by jolyons123** [d8ahazard/sd_dreambooth_extension#1424]
### Kindly read the entire form below and fill it out with the requested information.

**WHAT**
AMD compatibility can be achieved by commenting out two lines.

**HOW**
1. During setup, skip the bitsandbytes check. Comment out https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/postinstall.py#L45 
2. During class image generation, xformers is used by default. Comment out https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/helpers/image_builder.py#L109

The above listed lines could be executed whenever NVIDIA GPU is detected (similar to https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/webui.sh#L126)

**Comment by d8ahazard** [comment]
Suggested changes implemented with a1f5a5442cc92d89a60dfa247faeade6c023ac52. Please try and let me know if you have issues.
