### ISSUE TITLE
Can't install dreambooth during start-up.

### ISSUE THREAD

**Issue by B-getty** [d8ahazard/sd_dreambooth_extension#144]
**Have you read the Readme?**

Yes.

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

Repeatedly.

**Have you updated Dreambooth to the latest revision?**

I think it's failing to do so in the script for automatic1111.

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is 3b3a8002da3a780c276934e8bcf308aa822f1e22
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

I don't see these lines.  See bleow.

**Describe the bug**

When starting up I get these errors:

---- venv "C:\stable-diffusion-webui - 1111\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 7ba3923d5b494b7756d0b12f33acb3716d830b9a
Installing requirements for Web UI
Error running install.py for extension sd_dreambooth_extension.
Command: "C:\stable-diffusion-webui - 1111\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: Installing Requirements for Dreambooth

stderr: Traceback (most recent call last):
  File "C:\stable-diffusion-webui - 1111\extensions\sd_dreambooth_extension\install.py", line 11, in <module>
    run(f'{python} -m pip install -r "{reqs}"', desc=f"Installing Requirements for {name}", errdesc=f"Couldn't install {name} requirements.")
  File "C:\stable-diffusion-webui - 1111\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install Dreambooth requirements..
Command: C:\stable-diffusion-webui - 1111\venv\Scripts\python.exe -m pip install -r "C:\stable-diffusion-webui - 1111\extensions\sd_dreambooth_extension\requirements.txt"
Error code: 1
stdout: <empty>
stderr: 'C:\stable-diffusion-webui' is not recognized as an internal or external command,
operable program or batch file.

Launching Web UI with arguments: --xformers
Error loading script: main.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui - 1111\modules\scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui - 1111\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "C:\stable-diffusion-webui - 1111\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 26, in <module>
    from dreambooth.dreambooth import get_db_models
  File "C:\stable-diffusion-webui - 1111\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "C:\stable-diffusion-webui - 1111\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 20, in <module>
    from accelerate import Accelerator
ModuleNotFoundError: No module named 'accelerate'

---

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**
What OS?
If Windows - WSL or native?
What GPU are you using?

Windows, native. 3090.

**Comment by CrazyBoyM** [comment]
Hi, I think you should just run:
```
pip install accelerate
```
then:
```
accelerate config
```
config the train env.

**Comment by B-getty** [comment]
Ok I did that and it seemed to go fine.  But when I run the bat file I get errors again.

--------------------

Installing requirements for Web UI
Error running install.py for extension sd_dreambooth_extension.
Command: "C:\stable-diffusion-webui - 1111\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: Installing Requirements for Dreambooth

stderr: Traceback (most recent call last):
  File "C:\stable-diffusion-webui - 1111\extensions\sd_dreambooth_extension\install.py", line 11, in <module>
    run(f'{python} -m pip install -r "{reqs}"', desc=f"Installing Requirements for {name}", errdesc=f"Couldn't install {name} requirements.")
  File "C:\stable-diffusion-webui - 1111\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install Dreambooth requirements..
Command: C:\stable-diffusion-webui - 1111\venv\Scripts\python.exe -m pip install -r "C:\stable-diffusion-webui - 1111\extensions\sd_dreambooth_extension\requirements.txt"
Error code: 1
stdout: <empty>
stderr: 'C:\stable-diffusion-webui' is not recognized as an internal or external command,
operable program or batch file.




Launching Web UI with arguments: --xformers
Error loading script: main.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui - 1111\modules\scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui - 1111\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "C:\stable-diffusion-webui - 1111\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 26, in <module>
    from dreambooth.dreambooth import get_db_models
  File "C:\stable-diffusion-webui - 1111\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "C:\stable-diffusion-webui - 1111\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 20, in <module>
    from accelerate import Accelerator
ModuleNotFoundError: No module named 'accelerate'

-----------------------


Thank you for your time.  Sorry if the solution is simple.  I'm out of my element here.

Is this about the location of the files?

**Comment by CrazyBoyM** [comment]
May you have a conda envirment (or other env.)
and the accelerate package is not installled to where env the webui in (just a guess)

**Comment by YakuzaSuske** [comment]
I think it's because you have spaces in you folder `stable-diffusion-webui - 1111` you can't have spaces in the SD folder or else it wont install. Try renaming the SD folder.

**Comment by B-getty** [comment]
@CrazyBoyM - I moved my SD folder to my user path and everything went fine.  Up and running!

@YakuzaSuske - thanks for the suggestion, which seems logical, but I got it installed and working by moving my entire SD install from my root drive up to my user folder in Win10.  Everything seems fine so far.

Thanks you guys!
