### ISSUE TITLE
[Bug]: GitcommandError: Cmd('git) failed due to: exit code(128)  please help

### ISSUE THREAD

**Issue by CForCloudyy** [d8ahazard/sd_dreambooth_extension#1445]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

GitcommandError: Cmd('git) failed due to: exit code(128) cmdline: git clone -v -filter=blob:none --https://github.com/volotat/SD-CN-Animation.git E:VAlgiuyelsd-webui-aki-v4.5lsd-webui-aki-v4.51tmpISD-CN-Animation stderr:'cloning into"EAVANgiuyelsd-webui-aki-v4.5lsd-webui-aki-
V4.5\tmp\SD-CN-Animation'... fatal: unable to access "https://github.com/volotat/SD-CN-Animation.git/': Failed to connect to github.com port 443 after 21057 ms: Couldn't connect to server'
扩展
Temporal
脚本,动画
描述
A "loopback on steroids" that allows either processing images in a slightly more advanced way, or making the morphing animations out of them.
Update: 2024-01-15 Added: 2023-11-04 Created: 2023-10-16
操作
stars: 17
SD-CN-Animation
选项卡,动画
Allows users to create video2video and text2video animations using any SD models as a backbone. Please, make sure that 'sd-webui-controlnet' extension is also installed.
Update: 2023-11-22 Added: 2023-05-06 Created: 2023-03-17
stars: 777
3D Model&Po: e Loader
Load your 3D model/animation inside webui, or edit model pose as well, then send screenshot to txt2img or img2img to ControlNet.
选项卡
Update: 2023-09-12 Added: 2023-03-11 Created: 2023-03-06
stars: 219
Steps Animation
动画
Create animation sequence from denoised intermediate steps.
Update: 2023-06-30 Added: 2023-01-21 Created: 2023-01-15
stars: 133
Deforum
选项卡，动画
The official port of Deform, an extensive script for 2D and 3D animations, supporting keyframable sequences, dynamic math parameters (even inside the prompts), dynamic masking, depth estimation and warping.
Update: 2023-11-16 Added: 2022-11-01 Created: 2022-10-15
stars: 2370
Extension hidden: 275
<img width="1210" alt="1841b5dfc861a8864952c2db7a1f93db" src="https://github.com/d8ahazard/sd_dreambooth_extension/assets/157479004/751659c6-205e-4c98-8442-880cd757a633">

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### Commit and libraries

Starting at `Initializing Dreambooth` and ending several lines below at `[+] bitsandbytes version 0.35.4 installed.`.

### Command Line Arguments

```Shell
‘
```

### Console logs

```Shell
‘
```

### Additional information

anyone can help

**Comment by cryptobotany** [comment]
This is the github for dreambooth, you might try cn-animation's. You can try deleting the cn-animation folder form your extensions folder and re-install using https://github.com/volotat/SD-CN-Animation/ in the "install form URL section" of webui extensions.
