### ISSUE TITLE
Changed location webUI looks for checkpoints

### ISSUE THREAD

**Issue by silverrowan** [d8ahazard/sd_dreambooth_extension#145]
**Have you read the Readme?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes - only just tried to install for the first time.
**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**
 just tried to instal but revision is: d15cbc9d7293a61a39fab9533d1120722de26abc not the one below....
`Dreambooth revision is 3b3a8002da3a780c276934e8bcf308aa822f1e22
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

**Describe the bug**
Changed location Automatic1111 is looking for checkpoint files, from: C:\Users\[user]\stable-diffusion-webui\modules\models\Stable-diffusion
to
C:\Users\[user]\stable-diffusion-webui\modules\models\Stable-diffusion
dropped the modules folder.

It did not move the models from their old location, so couldn't start the webUI, resolvable by moving the chkpts manually, but potential to cause issues with other extensions.
At first I thought an A1111 update caused this, but github says the last revision was 14hrs ago, and I'd checked for updates more recently than that. Plus, last time A1111 changed model location it moved the models.

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.
I fixed the bug-causing problem, but folder should probably still be the default for the ui?

**Environment**
What OS?
If Windows - WSL or native?
What GPU are you using?

Win10, rtx3060

**Comment by d8ahazard** [comment]
Maybe it's early, but this is confusing.

Models should go to C:\users\[user]\stable-diffusion-webui\Models\Stable-diffusion not C:\users\[user]\stable-diffusion-webui\modules\Models\Stable-diffusion

The paths you have in your issue are identical.
