### ISSUE TITLE
RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: c10::Half key.dtype: float and value.dtype: float instead.

### ISSUE THREAD

**Issue by kmlcnclk** [d8ahazard/sd_dreambooth_extension#1458]
**RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: c10::Half key.dtype: float and value.dtype: float instead.**

I am getting an error like above when ı train dreambooth modal on Stable Diffusion.

Can you help me about that?

**Comment by vanangelov** [comment]
I have the same issue on a M1 Mac. Neither using the  "Upcast cross attention layer to float32" SD option, nor "--no-half" seem to fix it.

**Comment by kmlcnclk** [comment]
> I have the same issue on a M1 Mac. Neither using the  "Upcast cross attention layer to float32" SD option, nor "--no-half" seem to fix it.

I am using Mac M1 too.

**Comment by vanangelov** [comment]
Changing  Settings > Performance > Mixed Precision to NO seems to fix this

**Comment by malcolmacronis** [comment]
Using M1 Pro 32gb ram, nothing from above fixes this.
