### ISSUE TITLE
[Bug]: Dreambooth (input tab) not showing correctly

### ISSUE THREAD

**Issue by POPSCHEN** [d8ahazard/sd_dreambooth_extension#1468]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Dreambooth (input tab) not showing correctly
![i-need-help-dreambooth-input-tab-not-showing-correctly-v0-54bwke36d77c1](https://github.com/d8ahazard/sd_dreambooth_extension/assets/51813683/009390ce-6799-4b1d-b37d-72745c2003e4)

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### Commit and libraries

Starting at `Initializing Dreambooth` and ending several lines below at `[+] bitsandbytes version 0.35.4 installed.`.

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
No
```

**Comment by ObeseWanCannoli** [comment]
Same issue, have seen this for a while and yet to find a resolution.

**Comment by boshng95** [comment]
Same, happen to me as well.
Using WSL environment to run SD.
Using `sd_dreambooth_extension` with commit `45a12fe5`

**Comment by yildirimatcioglu** [comment]
same issue here still no update.

**Comment by arnediehm** [comment]
same issue here on two systems (Notebook and Server). Input tab missing.

**Comment by bhavana-kedari** [comment]
the UI/UX has been updated, I've been scratching my head over trying to figure out what happened or whether it was some dependency mismatch issue and what not, but the UI/UX has simple been updated. you can follow this YouTube tutorial to get a hang of using the updated interface: https://www.youtube.com/watch?v=gDFEtFohMFI
