### ISSUE TITLE
[Feature Request] Generate classification dataset automatically

### ISSUE THREAD

**Issue by ShinkoNet** [d8ahazard/sd_dreambooth_extension#15]
Shiv's repo does this where it makes a set of 50 images of the classification prompt if the class folder is empty.
Right now in the webui I have to generate the prompt manually in txt2img and then move them to a new folder that I feed into the extension.
Would be good if that process can be automated.

**Comment by YakuzaSuske** [comment]
> Shiv's repo does this where it makes a set of 50 images of the classification prompt if the class folder is empty. Right now in the webui I have to generate the prompt manually in txt2img and then move them to a new folder that I feed into the extension. Would be good if that process can be automated.

So lets say i want to train an anime girl, do i just search up anime girls and download them and set those as my class images? or do i have to do something else? i think thats why im getting bad results, because i don't have class images.

**Comment by d8ahazard** [comment]
> Shiv's repo does this where it makes a set of 50 images of the classification prompt if the class folder is empty. Right now in the webui I have to generate the prompt manually in txt2img and then move them to a new folder that I feed into the extension. Would be good if that process can be automated.

This does this as well, you just specify the number of class images and prompt, and it will generate the images.

**Comment by ShinkoNet** [comment]
> > Shiv's repo does this where it makes a set of 50 images of the classification prompt if the class folder is empty. Right now in the webui I have to generate the prompt manually in txt2img and then move them to a new folder that I feed into the extension. Would be good if that process can be automated.
> 
> This does this as well, you just specify the number of class images and prompt, and it will generate the images.

"Total number of classification images to use. Set to 0 to disable." right?
Oops. You can close this then. Thanks for the info

**Comment by YakuzaSuske** [comment]
when training with classification images, i get CUDA out of memory.
