### ISSUE TITLE
Feature Request: Add option to clone Huggingface diffusers instead of converting .ckpt to diffusers for users with low system RAM

### ISSUE THREAD

**Issue by Miraculix200** [d8ahazard/sd_dreambooth_extension#152]
Free Google Colab and SageMaker Studio Lab have low system RAM, which causes to webui to crash when the Dreambooth extension converts a .ckpt to diffusers.

Suggestion: Add a tab to clone a Huggingface model, to enable users with little system RAM to start the training. 

Tab content could be:
* Huggingface URL (or profile name / model name)
* Name the trained model should have
* Huggingface token

That doesn't solve the crash after the training, when the extension tries to convert the diffusers to a .ckpt file. But that can't be fixed from the extension. Users would have to manually use a script for conversion, while the webui is not running, like I do here:
https://colab.research.google.com/github/Miraculix200/StableDiffusionUI_Colab/blob/main/StableDiffusionUI_Colab.ipynb#scrollTo=j5_IGbmKPQhu

**Comment by d8ahazard** [comment]
That's not a terrible idea. On first read over this, I thought you wanted
to re-incorporate all this stuff to the main UI, which is a bit more of a
PITA. Just a stand-alone tab with an isolated function, that I can get
behind.

I'm a bit busy today, but I'll see what I can do.

**Comment by Miraculix200** [comment]
Yes, I thought of it as an alternative to the "Create Model" tab

**Comment by d8ahazard** [comment]
Implemented with a9bbe70

You'll need to tell me if this still kills RAM for you. Unfortunately, I can't do a direct clone of the directory because then we also have to download the .ckpt files which takes forever, but I'm hoping that saving the pretrained model when loading from URL should be enough.

![image](https://user-images.githubusercontent.com/1633844/201733580-374ba396-482e-41ec-afee-e876e0c2a1f5.png)

**Comment by Miraculix200** [comment]
It works without crashing, if I enter something into the Model Path textbox. The way it is now, it looks like it would automatically use runwayml/stable-diffusion-v1-5 when clicking create. But I had to enter it manually. Otherwise it loaded the .ckpt file which is selected in the "Stable diffusion checkpoint" selector and crash.

Also, for some reason it doesn't start the training, and there is no error message in the console. But I can select the cloned model

**Comment by Miraculix200** [comment]
The webui doesn't crash when starting the training btw. I just shows a progress bar for a second which then disappears again. Can I activate debug messages for the plugin somehow?

**Comment by Miraculix200** [comment]
Training now works after starting a new session on Colab

**Comment by Miraculix200** [comment]
Training now works, after starting a new session on Colab

**Comment by d8ahazard** [comment]
> Training now works, after starting a new session on Colab. So this issue can be closed, I guess.
> 
> Though I suggest making it actually use the ghosted path in the Model Path textbox ("runwayml/stable-diffusion-v1-5"), instead of requiring the user to enter it manually. It looks like it is a default value, but it doesn't act as default value

Good suggestion - added. I've also hidden the "offline" settings when cloning from online to prevent confusion.
