### ISSUE TITLE
Error after updating to newest version

### ISSUE THREAD

**Issue by dragoriano** [d8ahazard/sd_dreambooth_extension#160]
Error running install.py for extension extensions\sd_dreambooth_extension.
Command: "C:\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: loading Dreambooth reqs from C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt
Checking Dreambooth requirements.
Checking torch and torchvision versions

stderr: Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 21, in <module>
    run(f'"{sys.executable}" -m {torch_cmd}', "Checking torch and torchvision versions", "Couldn't install torch")
  File "C:\stable-diffusion-webui\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install torch.
Command: "C:\stable-diffusion-webui\venv\Scripts\python.exe" -m "pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"
Error code: 1
stdout: <empty>
stderr: C:\stable-diffusion-webui\venv\Scripts\python.exe: Error while finding module specification for 'pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116' (ModuleNotFoundError: No module named 'pip install torch==1')

**Comment by d8ahazard** [comment]
Please refer to the issue template for submitting a bug report, do all the things, and re-submit using the template if you're still having issues.

https://github.com/d8ahazard/sd_dreambooth_extension/issues/new?assignees=&labels=&template=bug_report.md&title=
