### ISSUE TITLE
Training become extremely slow after update using  768 resolution on V100S (32GB)

### ISSUE THREAD

**Issue by nekoyama32767** [d8ahazard/sd_dreambooth_extension#163]
**Describe the bug**

Training become extremely slow after update.
V100S has 32GB memory. 
Before update training can use 28GB memory and let GPU work on full power all the time use 768 resolution. 
After update, it only can use 17GB memory and become extremely slow (5 times slower)
Set batch size to 8 makes it to use 30GB memory can not solve problem. Still extremely slow.
Set resolution to 512 can use 18GB memory on normal speed.
I think memory reduce strategy is too intense which can not use all large GPU memory.

**Environment**
What OS?
Ubuntu 22.04LTS
What GPU are you using?
V100S

**Comment by sgsdxzy** [comment]
I suspect it's the problem with ShivamShrirao's version of diffuser and xformers. Can you try the following:
edit requirements.txt and change `git+https://github.com/ShivamShrirao/diffusers.git#egg=diffusers` to another (stable) version of diffusers and try the speed again?

**Comment by sgsdxzy** [comment]
I did the experiment on 3080Ti, using the following settings and batch size=1
![image](https://user-images.githubusercontent.com/1655353/201667038-02b979d8-db71-44a8-ad56-9616972361b0.png)
On git+https://github.com/ShivamShrirao/diffusers.git#egg=diffusers: 2it/s, 10.5/12G VRAM usage;
On diffusers==0.7.2: 2.5it/s, 12/12G VRAM usage.
So ShivamShrirao's version of diffuser is indeed slower but saves VRAM. I think it has something to do with ShivamShrirao's automatic enabling of xformers. But I have never successfully enabled xformers on stable diffusers though, and the memory saving is too nice to miss, as it allows large batch size.
@d8ahazard any other good reason to ShivamShrirao's version? It seems to also cause https://github.com/d8ahazard/sd_dreambooth_extension/issues/48#issuecomment-1310648992

**Comment by d8ahazard** [comment]
> I did the experiment on 3080Ti, using the following settings and batch size=1 ![image](https://user-images.githubusercontent.com/1655353/201667038-02b979d8-db71-44a8-ad56-9616972361b0.png) On git+https://github.com/ShivamShrirao/diffusers.git#egg=diffusers: 2it/s, 10.5/12G VRAM usage; On diffusers==0.7.2: 2.5it/s, 12/12G VRAM usage. So ShivamShrirao's version of diffuser is indeed slower but saves VRAM. I think it has something to do with ShivamShrirao's automatic enabling of xformers. But I have never successfully enabled xformers on stable diffusers though, and the memory saving is too nice to miss, as it allows large batch size. @d8ahazard any other good reason to ShivamShrirao's version? It seems to also cause [#48 (comment)](https://github.com/d8ahazard/sd_dreambooth_extension/issues/48#issuecomment-1310648992)

Really, I'm just using that version because I read in one of his comments that he recommended using it. For certain, he has hooks in it to disable bitching about the safety_checker being disabled, which I've managed to skirty by replacing it with the dumb_safety method.

If you can demonstrate that we don't need it, at all, and using the "stable" version from pypi is better, I'm happy to use whatever.

**Comment by nekoyama32767** [comment]
> I suspect it's the problem with ShivamShrirao's version of diffuser and xformers. Can you try the following: edit requirements.txt and change `git+https://github.com/ShivamShrirao/diffusers.git#egg=diffusers` to another (stable) version of diffusers and try the speed again?

Using same webui's diffuser (0.7.2)  works normally on 768 resolution. And can use 28GB VRAM.

**Comment by sgsdxzy** [comment]
OK, so the remaining problem is how to enable xformers on 0.7.2...
I cannot get `unet.set_use_memory_efficient_attention_xformers(True)` to work, reporting tons of cuda error.

**Comment by nekoyama32767** [comment]
> OK, so the remaining problem is how to enable xformers on 0.7.2... I cannot get `unet.set_use_memory_efficient_attention_xformers(True)` to work, reporting tons of cuda error.

https://github.com/huggingface/diffusers/pull/1270
This issue maybe help.
ShivamShrirao's diffusers has done the same tings

**Comment by d8ahazard** [comment]
> > OK, so the remaining problem is how to enable xformers on 0.7.2... I cannot get `unet.set_use_memory_efficient_attention_xformers(True)` to work, reporting tons of cuda error.
> 
> [huggingface/diffusers#1270](https://github.com/huggingface/diffusers/pull/1270) This issue maybe help. ShivamShrirao's diffusers has done the same tings

So, I hacked in support for this in 0.7.2. I think you may be good to go if you update and try again.

**Comment by nekoyama32767** [comment]
@d8ahazard Origin 0.7.2 works normally. But hack version still can not large VRAM (768*768 only use 17G VRAM and slow)

**Comment by sgsdxzy** [comment]
> @d8ahazard Origin 0.7.2 works normally. But hack version still can not large VRAM (768*768 only use 17G VRAM and slow)

You need to turn off xformers. Remove --xformers in startup script of webui.

**Comment by nekoyama32767** [comment]
> > @d8ahazard Origin 0.7.2 works normally. But hack version still can not large VRAM (768*768 only use 17G VRAM and slow)
> 
> You need to turn off xformers. Remove --xformers in startup script of webui.

After disable xformers, speed back to normal.

**Comment by sgsdxzy** [comment]
I made a comparison in #230

**Comment by d8ahazard** [comment]
> > > @d8ahazard Origin 0.7.2 works normally. But hack version still can not large VRAM (768*768 only use 17G VRAM and slow)
> > 
> > 
> > You need to turn off xformers. Remove --xformers in startup script of webui.
> 
> After disable xformers, speed back to normal.

Closing.
