### ISSUE TITLE
dreambooth extension installed but not appear on the tab.

### ISSUE THREAD

**Issue by hungrydog666** [d8ahazard/sd_dreambooth_extension#164]
Preloading Dreambooth!
Error loading script: main.py
Traceback (most recent call last):
  File "D:\stable_diffusion\stable-diffusion-webui\modules\scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\stable_diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\stable_diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "D:\stable_diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 26, in <module>
    from dreambooth.dreambooth import get_db_models
  File "D:\stable_diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "D:\stable_diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 20, in <module>
    from accelerate import Accelerator
ModuleNotFoundError: No module named 'accelerate'

**Comment by hungrydog666** [comment]
i dont i dont understand coding, but if you can reply i am grateful for that. but if you can please reply as if you talk to a 5 year old, i dont understand what all of this means. thank you very much.

**Comment by aIt3r** [comment]
Run into the same issue as of the time of this post. I think I solved it by deactivating all the extensions except for Dreambooth (you can re-activate them and reload after), then completely rebooting Stable Diffusion (close everything). And you might want to update it to the latest by running the "git pull" command before re-launching. Hope that helps.

**Comment by d8ahazard** [comment]
Copy the contents of this file and paste it into webui-user.bat, close sd-web-ui entirely and relaunch.

https://raw.githubusercontent.com/d8ahazard/sd_dreambooth_extension/main/webui-user-dreambooth.bat

**Comment by watahboy** [comment]
I had this same issue and followed d8ahazard's advice above and didn't fix the issue, I then ran a cmd window in the directory and ran a python update. On the next restart I had the dreambooth tab.

**Comment by d8ahazard** [comment]
Please refer to the issue template for submitting a bug report, do all the things, and re-submit using the template if you're still having issues.

https://github.com/d8ahazard/sd_dreambooth_extension/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by emirkustirika** [comment]
@d8ahazard  you are the king! i am trying for this 1 whole day... thanks man! Now morning 4:15 :D

**Comment by Krittrr** [comment]
@d8ahazard you legend!

**Comment by Rauzage7** [comment]
I think I did the webui-user.bat update that @d8ahazard on 2022-11-13, but I am not confident that I did it correctly and that it is part of how webui-user is launching - and the tab does not appear in the browser. The cmd window seems to show that Dreambooth extension loads (and Dreamworks appears in the list of extensions on the Extensions tab), but no Dreambooth tab. Can I get any further guidance, please?

**Comment by Rauzage7** [comment]
I did the webui-user.bat update that @d8ahazard provided on 2022-11-13, but the Dreambooth tab does not appear in the browser. The cmd window seems to show that Dreambooth extension loads (and Dreambooth appears in the list of installed extensions on the Extensions tab), but there is no Dreambooth tab in the browser. Can I get any further guidance, please?

**Comment by NikTatishvili** [comment]
> I did the webui-user.bat update that @d8ahazard provided on 2022-11-13, but the Dreambooth tab does not appear in the browser. The cmd window seems to show that Dreambooth extension loads (and Dreambooth appears in the list of installed extensions on the Extensions tab), but there is no Dreambooth tab in the browser. Can I get any further guidance, please?

I have got the same issue, trying to do something but nothing workes
