### ISSUE TITLE
Add capability to train new models via the API 

### ISSUE THREAD

**Issue by TheFlyingPirate** [d8ahazard/sd_dreambooth_extension#167]
**WHAT**
The ability to upload the training set and parameters through an API to create a new model

**Comment by d8ahazard** [comment]
Not opposed to implementing this, but I will need more info. 

LIke, is the API even extensible to extensions? If so, how? Find me some docs, I'll take a look.

**Comment by TheFlyingPirate** [comment]
I've found the following issue mentioning accessing the api through an extension:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4005

**Comment by TheFlyingPirate** [comment]
https://github.com/TheFlyingPirate/sd_dreambooth_extension_with_api/blob/main/scripts/api.py
I coded up the api endpoint to create a model:
https://github.com/TheFlyingPirate/sd_dreambooth_extension_with_api/blob/main/scripts/api.py

**Comment by TheFlyingPirate** [comment]
Exactly, I think there are three main steps for the start_training we should take into account
1) General Functionality, just like the UI
2) Ability to provide images in the api call, either as a link or form encoded
3) Add a callback url So we can notify the caller of the api that the model has finished training

**Comment by d8ahazard** [comment]
> Exactly, I think there are three main steps for the start_training we should take into account
> 
> 1. General Functionality, just like the UI
> 2. Ability to provide images in the api call, either as a link or form encoded
> 3. Add a callback url So we can notify the caller of the api that the model has finished training

Feels like the "callback URL" should almost rely on the "shared.state" params - possibly incorporating some extra field that can be specifically fetched/set by anything to indicate what the app is doing. Or, make it a dict so that if someone has an insane GPU and is doing multiple things at once, a "job_id" can be used to query the state of any given process at any time.

if job_key in shared.state.job_dict:
    job_status = shared.state.job_dict[job_key]
    print(f"My job is currently {job_status}")

**Comment by d8ahazard** [comment]
So, we've already got some of the API implemented, I think any other features can just be added, and don't require this issue to remain open.
