### ISSUE TITLE
Error when Generate a preview image every N steps set to 0

### ISSUE THREAD

**Issue by hugostranger** [d8ahazard/sd_dreambooth_extension#17]
One of the things that throws me a Cuda out of memory error is when the training attempts to run a sample image.  However when I set the 'Generate a preview image every N steps' to '0' to disable it I receive this error when starting training:

`Error completing request...
  File "C:\stable-diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 786, in main
    save_img = not global_step % args.save_preview_every and global_step != 0
ZeroDivisionError: integer division or modulo by zero`

**Comment by hugostranger** [comment]
Sorry, duplicate of https://github.com/d8ahazard/sd_dreambooth_extension/issues/16

**Comment by d8ahazard** [comment]
This has been resolved.
