### ISSUE TITLE
Cuda error on 3070RTX

### ISSUE THREAD

**Issue by JeanBagarre01** [d8ahazard/sd_dreambooth_extension#178]
**Have you read the Readme?**

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

**Have you updated Dreambooth to the latest revision?**

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is 3b3a8002da3a780c276934e8bcf308aa822f1e22
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

**Describe the bug**
when i create my model and launch my train i got this message :

**Provide logs**

Error completing request
Arguments: ('lenalena', '', 'C:\\Users\\marvi\\Desktop\\img\\potes\\lena quignette\\rezize', 'D:\\regulazation images\\REGULARIZATION-IMAGES-SD-main\\person', 'photo of lenalena person', False, False, 'photo of a person', '1500', '', 1, 7.5, 40, 1500, 512, False, True, 1, 1, 1, 200, 1, True, 1e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 1500, 0, 'fp16', True, '', False, True, True) {}
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\ai\stable-diffusion-webui\webui.py", line 51, in f
    shared.state.begin()
  File "C:\ai\stable-diffusion-webui\modules\shared.py", line 189, in begin
    devices.torch_gc()
  File "C:\ai\stable-diffusion-webui\modules\devices.py", line 47, in torch_gc
    torch.cuda.empty_cache()
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\memory.py", line 121, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Environment**
windows 10 with RTX3070 portable version
64g ram

**Comment by d8ahazard** [comment]
Are you using xformers?

**Comment by YakuzaSuske** [comment]
> Are you using xformers?

is xformers a problem? i've been using Dreambooth with xformers all the time and i have no issues at all with it.

**Comment by d8ahazard** [comment]
> > Are you using xformers?
> 
> is xformers a problem? i've been using Dreambooth with xformers all the time and i have no issues at all with it.

I've seen this one before, I just can't recall what the issue was. I'd try disabling xformers, and or maybe installing the CUDA 11.6 toolkit, which installs CUDA specific drivers.

**Comment by YakuzaSuske** [comment]
> > > Are you using xformers?
> > 
> > 
> > is xformers a problem? i've been using Dreambooth with xformers all the time and i have no issues at all with it.
> 
> I've seen this one before, I just can't recall what the issue was. I'd try disabling xformers, and or maybe installing the CUDA 11.6 toolkit, which installs CUDA specific drivers.

I'm good, i have no issues with xformers on Dreambooth or nothing, tho OP probably might have some issues with it.

**Comment by d8ahazard** [comment]
> **Have you read the Readme?**
> 
> **Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
> 
> **Have you updated Dreambooth to the latest revision?**
> 
> **Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**
> 
> `Dreambooth revision is 3b3a8002da3a780c276934e8bcf308aa822f1e22 Diffusers version is 0.8.0.dev0. Torch version is 1.12.1+cu116. Torch vision version is 0.13.1+cu116.`
> 
> **Describe the bug** when i create my model and launch my train i got this message :
> 
> **Provide logs**
> 
> Error completing request Arguments: ('lenalena', '', 'C:\Users\marvi\Desktop\img\potes\lena quignette\rezize', 'D:\regulazation images\REGULARIZATION-IMAGES-SD-main\person', 'photo of lenalena person', False, False, 'photo of a person', '1500', '', 1, 7.5, 40, 1500, 512, False, True, 1, 1, 1, 200, 1, True, 1e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 1500, 0, 'fp16', True, '', False, True, True) {} Traceback (most recent call last): File "C:\ai\stable-diffusion-webui\modules\ui.py", line 185, in f res = list(func(*args, **kwargs)) File "C:\ai\stable-diffusion-webui\webui.py", line 51, in f shared.state.begin() File "C:\ai\stable-diffusion-webui\modules\shared.py", line 189, in begin devices.torch_gc() File "C:\ai\stable-diffusion-webui\modules\devices.py", line 47, in torch_gc torch.cuda.empty_cache() File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\memory.py", line 121, in empty_cache torch._C._cuda_emptyCache() RuntimeError: CUDA error: an illegal memory access was encountered CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> 
> **Environment** windows 10 with RTX3070 portable version 64g ram

Hello, please do an update and install the CUDA toolkit if you're still getting errors:

https://developer.nvidia.com/cuda-11-6-0-download-archive

**Comment by dathide** [comment]
I fixed one of my CUDA errors by installing cuda, then rerunning the commands on this page: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Xformers

**Comment by d8ahazard** [comment]
@JeanBagarre01 - Haven't heard from you in a week. Please give an update, else this will be closed in the next day or so.
