### ISSUE TITLE
DreamboothConfig' object has no attribute 'pretrained_vae_name_or_path'

### ISSUE THREAD

**Issue by daniel5984** [d8ahazard/sd_dreambooth_extension#182]
Arguments: ('mydisco640px', None, '/notebooks/disco_init', '/notebooks/disco_class', '', False, False, '', '', '', 1, 7.5, 40, 200, 640, False, True, 1, 1, 1, 5000, 1, True, 5e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 500, 500, 'fp16', False, '/notebooks/concepts_list.json', False, True, True) {}
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/notebooks/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 291, in start_training
    if isset(config.pretrained_vae_name_or_path) and not os.path.exists(pretrained_vae_name_or_path):
AttributeError: 'DreamboothConfig' object has no attribute 'pretrained_vae_name_or_path'

**Comment by rrweller** [comment]
+1

**Comment by Ohhhboyyy** [comment]
may I ask what you commented out exactly? I'm getting this exact error message and not having any luck yet

**Comment by d8ahazard** [comment]
Just fixed with a9bbe70
