### ISSUE TITLE
Attribute Error while running on runpod webUI

### ISSUE THREAD

**Issue by filliptm** [d8ahazard/sd_dreambooth_extension#189]
<img width="1201" alt="Screen Shot 2022-11-14 at 2 33 31 PM" src="https://user-images.githubusercontent.com/55672949/201749537-cbaf394a-0c19-4d42-beba-e6ab0b29cf01.png">

**Comment by dx777** [comment]
update the stable diffusion webUI

**Comment by d8ahazard** [comment]
Yep. You need to be on the latest(ish) version of the webUI, tag_drop out was added somewhat recently.
