### ISSUE TITLE
Exception generating checkpoint: 'bool' object has no attribute 'flush'

### ISSUE THREAD

**Issue by svankirk** [d8ahazard/sd_dreambooth_extension#191]
**Requirements output**
Installing requirements for Web UI
[auto-sd-paint-ext] Attempting auto-update...
[auto-sd-paint-ext] Fetch upstream.
[auto-sd-paint-ext] Pull upstream.

loading Dreambooth reqs from M:\AI\StableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt
Checking Dreambooth requirements.
Checking torch and torchvision versions
Dreambooth revision is 6af0ac04084c2bb4b40dad12cde673e8dd446a1a
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.

Launching Web UI with arguments: --api --port 33333 --cors-allow-origins=https://www.painthua.com

**Describe the bug**
I start dreambooth with the following bat file in windows10:

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --api  --port 33333 --cors-allow-origins=https://www.painthua.com 
set "TORCH_COMMAND=pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"
set "REQS_FILE=.\extensions\sd_dreambooth_extension\requirements.txt"
git pull
call webui.bat
 tab
I run automatic1111. when trying to define a style in dreambooth based upon art by wlop with the following settings:
![image](https://user-images.githubusercontent.com/3734797/201758249-6c66f0bc-e3d2-4d49-8840-a741aeb61cde.png)

**Provide logs**
I don't know where I might find crash logs, but the cmd console only gives me:

**Exception generating checkpoint: 'bool' object has no attribute 'flush'**
press any key to continue...

then webui closes.

**Environment**
Windows native with  3090 GPU

**Comment by d8ahazard** [comment]
Yeah, this was a typo on my part, fixed with the latest versions.

**Comment by svankirk** [comment]
Thanks! That was easy.  For me at least :)   I really appreciate you making all your hard work open with this.  Thanks again!
