### ISSUE TITLE
Dreambooth training immediately stops

### ISSUE THREAD

**Issue by iradeyal2** [d8ahazard/sd_dreambooth_extension#193]
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth:**
Dreambooth revision is 7e184a6cb95df776c2a1d86eea29321bff999899
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.

**Describe the bug**
Not sure if its a bug or me. I just installed the Dreambooth extension for the first time. Restarted several times before there were no errors listed at launch. When I hit "train" the blue progress bar appears for a moment, then disappears immediately.

**Provide Logs**
No errors appear in the log. Nothing happens in the log. 

**Environment**
What OS? Windows 10
If Windows - WSL or native? native
What GPU are you using? 2080 Ti 12gb

![Dreamboothsettings_doesntwork](https://user-images.githubusercontent.com/54294736/201770159-6514dca6-114a-405c-80d7-5fa7622abf31.jpeg)

**Comment by d8ahazard** [comment]
Try updating Dreambooth again and then hitting F5 to refresh the webpage for the UI. You're missing some settings in the latest version.
