### ISSUE TITLE
Fix typo in DreamboothConfig

### ISSUE THREAD

**Issue by red1939** [d8ahazard/sd_dreambooth_extension#194]
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is *****************************************
Diffusers version is ********.
Torch version is *********.
Torch vision version is ********.`

**Describe the bug**
Please take a look at `db_config.py@79`:
`                "pretrained_vae_name_or_path,": pretrained_vae_name_or_path,`
Remove the comma

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**
Ubuntu 22.04
Pytorch 1.13 + rocm 5.2

**Comment by d8ahazard** [comment]
Fixed with 4647d85. Thank you.
