### ISSUE TITLE
If you use a JSON config file, the load params still shows a new nonexistent "classifiers" path for class images

### ISSUE THREAD

**Issue by Jonseed** [d8ahazard/sd_dreambooth_extension#196]
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is d4c0312d22033fd0550e0ab51f08789b56966138
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

**Describe the bug**
If you use a JSON config file, and leave the UI lines blank, then after a training session and clicking "Load Params" it fills in the config file in the first field, but it also puts a new "classifiers" folder on the Classification Dataset Directory line, even though that folder doesn't exist. If I understand right, that folder is only created if classification images are generated during training. Otherwise, it doesn't get created, and that line should remain blank.

**Provide logs**
No crash

**Environment**
What OS? Windows 10
If Windows - WSL or native? native
What GPU are you using? 3060 12GB

**Comment by d8ahazard** [comment]
Technically, the folder is always created. It's just never utilized if you
don't specify a number of classification images to use.

**Comment by Jonseed** [comment]
The folder didn't get created for me. It is a nonexistent path. I specified a number of classification images, but also a different path where they are located in the JSON file.

**Comment by d8ahazard** [comment]
I think I fixed this with the latest commit. Please update and confirm/deny and close if applicable. ;)
