### ISSUE TITLE
Instance prompt no longer has option for using Filenames/txts

### ISSUE THREAD

**Issue by Slowly-Grokking** [d8ahazard/sd_dreambooth_extension#197]
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes
**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

Dreambooth revision is 60ef742dcdd791876a683ddd415576ec273d5c8e
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.

**Describe the bug**
Can't train from filenames/txt files.

labels as txt files removed
file names as labels removed
https://github.com/d8ahazard/sd_dreambooth_extension/commit/a6db4cdc345b4326ffcb92d1b43c89634cf4a4bd

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**
What OS? windows
If Windows -  native
What GPU are you using?
3090

**Comment by Jonseed** [comment]
Just use [filewords] in the instance prompt, or in the JSON file, as noted in the Readme.

`You can use [filewords] as placeholder for reading caption from the image filename or a seprarte .txt file containing caption, for example, [filewords], in the style of zymkyr. This syntax is the same as textual inversion templates.`

**Comment by Slowly-Grokking** [comment]
> Just use [filewords] in the instance prompt, or in the JSON file, as noted in the Readme.
> 
> `You can use [filewords] as placeholder for reading caption from the image filename or a seprarte .txt file containing caption, for example, "[filewords], in the style of zymkyr". This syntax is the same as textual inversion templates.`

Thank you.   I missed it in the ReadMe because this wasn't forced until today, and today's readme commit did not mention it.

**Comment by rabidcopy** [comment]
I'm not sure if I'm doing something wrong but when I try to use [filewords] in the instance/preview prompt, preview images saved are just the step count (`100.png 200.png 300.png and so on`) with no prompt attached to them and it appears to not be processing any text as training input. Not even the text put into the instance outside of [filewords] Images and text files containing the tags/prompts are formatted like this; `123456789.png 123456789.txt`. No letters in the filenames.

**Comment by Jonseed** [comment]
Do you have anything in the preview prompt field? That's what's used to generate the previews, and how it names the files, along with the step count.

**Comment by rabidcopy** [comment]
The instance prompt is supposed to be used for previews when preview prompt is left blank, but either way, in both instances of using just the instance prompt with [filewords] and manually putting [filewords] in the preview prompt, training nor previews seem to actually be using the [filewords]. If I use a prompt without [filewords] it works as expected, but with [filewords] it makes the resulting training and preview a blank prompt.

**Comment by Jonseed** [comment]
I'm not sure [filewords] can be used in the preview prompt. Which file is it supposed to choose to generate a preview? Just pick one at random?

I just did some training with [filewords] in the instance prompt, and the training surely seems to have used my [filewords].

**Comment by d8ahazard** [comment]
Use [Filewords]. I've also added sample_prompt and sample_negative prompt as options for concepts_list, so training multiple concepts will still generate samples appropriately.

**Comment by Jonseed** [comment]
@d8ahazard does the F in filewords have to be capitalized? Or does that not matter?
