### ISSUE TITLE
Specifying more than 1 sample image for previews does not generate more than 1

### ISSUE THREAD

**Issue by Jonseed** [d8ahazard/sd_dreambooth_extension#198]
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is 60ef742dcdd791876a683ddd415576ec273d5c8e
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

**Describe the bug**
If you specify more than 1 sample image to be generated for preview, it does not generate that number. It still only generates 1 image. I specified 2, and it still only generated 1.

**Provide logs**
No crash

**Environment**
What OS? Windows 10
If Windows - WSL or native? native
What GPU are you using? 3060 12GB

**Comment by d8ahazard** [comment]
This has been (re)implemented with 4647d85.
