### ISSUE TITLE
8bit adam not in requirements.txt

### ISSUE THREAD

**Issue by ShinkoNet** [d8ahazard/sd_dreambooth_extension#2]
When clicking train with adam ticked:
`Exception importing 8bit adam: No module named 'bitsandbytes'`
` CPU: False Adam: False, Prec: fp16, Prior: False, Grad: True, TextTr: True`

add 'bitsandbytes' to requirements.txt to fix the issue.

**Comment by d8ahazard** [comment]
Added with 159a336
