### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by wuchanghui5220** [d8ahazard/sd_dreambooth_extension#202]
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

**Have you updated Dreambooth to the latest revision?**

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is *****************************************
Diffusers version is ********.
Torch version is *********.
Torch vision version is ********.`

**Describe the bug**
(A clear and concise description of what the bug is)

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**
Windows 10 21H2
If Windows - WSL or native? native
What GPU are you using? A40

## RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([2, 1920, 32, 32], dtype=torch.half, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(1920, 640, kernel_size=[3, 3], padding=[1, 1], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().half()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
memory_format = Contiguous
data_type = CUDNN_DATA_HALF
padding = [1, 1, 0]
stride = [1, 1, 0]
dilation = [1, 1, 0]
groups = 1
deterministic = false
allow_tf32 = true
input: TensorDescriptor 00000173B7B95F90
type = CUDNN_DATA_HALF
nbDims = 4
dimA = 2, 1920, 32, 32,
strideA = 1966080, 1024, 32, 1,
output: TensorDescriptor 00000173B7B96FC0
type = CUDNN_DATA_HALF
nbDims = 4
dimA = 2, 640, 32, 32,
strideA = 655360, 1024, 32, 1,
weight: FilterDescriptor 0000017372B01B70
type = CUDNN_DATA_HALF
tensor_format = CUDNN_TENSOR_NCHW
nbDims = 4
dimA = 640, 1920, 3, 3,
Pointer addresses:
input: 00000002C7F00000
output: 0000000291A00000
weight: 000000026FA00000
Time taken: 52.59sTorch active/reserved: 41875/42034 MiB, Sys VRAM: 0/0 MiB (0.0%)

**Comment by d8ahazard** [comment]
Please fill out the whole template...
