### ISSUE TITLE
cannot generate ckpt - "Exception generating checkpoint: 'bool' object has no attribute 'flush'"

### ISSUE THREAD

**Issue by ethansmith2000** [d8ahazard/sd_dreambooth_extension#203]
`Dreambooth revision is 6af0ac04084c2bb4b40dad12cde673e8dd446a1a
Diffusers version is 0.7.2
Torch version is 1.12.1+cu116
Torch vision version is 1.13.1+cu116

**Describe the bug**
hitting "Generate CKPT" immediately results in exception "Exception generating checkpoint: 'bool' object has no attribute 'flush'" which is the only message in the console. 

**Provide logs**
---------
loading Dreambooth reqs from C:\Users\ethan\Desktop\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt
Checking Dreambooth requirements.
WARNING: overwriting existing torch/torchvision installation!
Checking torch and torchvision versions
Dreambooth revision is 6af0ac04084c2bb4b40dad12cde673e8dd446a1a
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.

Launching Web UI with arguments:
Preloading Dreambooth!
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [81761151] from C:\Users\ethan\Desktop\stable-diffusion-webui\models\Stable-diffusion\model.ckpt
Global Step: 840000
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 1 textual inversion embeddings.
Embeddings: Tristan
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://80f65717bef6bd15.gradio.app

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Exception generating checkpoint: 'bool' object has no attribute 'flush'
---------

**Environment**
What OS? - Windows 10
If Windows - WSL or native? - native 
What GPU are you using? - 3090

**Comment by d8ahazard** [comment]
Please update to the latest version and try again.
