### ISSUE TITLE
On google colab , Automatic 1111 : 

### ISSUE THREAD

**Issue by darth2602** [d8ahazard/sd_dreambooth_extension#207]
On google colab , Automatic 1111 : 

error message (step : Start stable-diffusion)

Preloading Dreambooth!
Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 30, in <module>
    from dreambooth import xattention
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 6, in <module>
    from diffusers.models.attention import xformers
ImportError: cannot import name 'xformers' from 'diffusers.models.attention' (/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py)

**Comment by sophieDataroots** [comment]
I got the same error

**Comment by wilzamguerrero** [comment]
> On google colab , Automatic 1111 :
> 
> error message (step : Start stable-diffusion)
> 
> Preloading Dreambooth! Error loading script: main.py Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 164, in load_scripts module = script_loading.load_module(scriptfile.path) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module exec(compiled, module.**dict**) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in from dreambooth import conversion, dreambooth File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 30, in from dreambooth import xattention File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 6, in from diffusers.models.attention import xformers ImportError: cannot import name 'xformers' from 'diffusers.models.attention' (/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py)



i used !pip install diffusers==0.7.2 for fix this problem
but now i have this message [!] Not using xformers memory efficient attention.
someone can help me.
