### ISSUE TITLE
Feature request: Preview image prompt for each concept when training multiple

### ISSUE THREAD

**Issue by Jonseed** [d8ahazard/sd_dreambooth_extension#208]
**WHAT**
You could add a preview prompt for each concept that you are training, so that you can see the progress on training each concept. Currently you can only see a preview for one of the concepts being trained, unless you add them both to the same prompt.

**HOW**
Perhaps these could be added to the JSON config file, a field for "preview_prompt" that could be added to each concept?

**Comment by d8ahazard** [comment]
Implemented with the latest commit, as well as adding "sample_prompt" and "sample_negative_prompt" to the concepts_list.
