### ISSUE TITLE
Dreambooth tab is missing

### ISSUE THREAD

**Issue by pandasonic-collective** [d8ahazard/sd_dreambooth_extension#212]
I just pulled the most recent version and the dreambooth tab is no longer displaying. 
I also uninstalled and reinstalled and it's still not there. 

Any ideas?

**Comment by ulysse-gen** [comment]
Same, getting this in console: 
`Closing server running on port: 7860
Reloading extensions
Reloading custom scripts
Dreambooth API layer loaded
Reloading modules: modules.ui
Refreshing Model List
Restarting Gradio
Error executing callback ui_tabs_callback for /notebooks/extensions/sd_dreambooth_extension/scripts/main.py
Traceback (most recent call last):
  File "/notebooks/modules/script_callbacks.py", line 93, in ui_tabs_callback
    res += c.callback() or []
  File "/notebooks/extensions/sd_dreambooth_extension/scripts/main.py", line 153, in on_ui_tabs
    fn=dreambooth.performance_wizard,
AttributeError: module 'dreambooth.dreambooth' has no attribute 'performance_wizard'`

**Comment by pandasonic-collective** [comment]
> Same, getting this in console:
> 
> ```
> Closing server running on port: 7860
> Reloading extensions
> Reloading custom scripts
> Dreambooth API layer loaded
> Reloading modules: modules.ui
> Refreshing Model List
> Restarting Gradio
> Error executing callback ui_tabs_callback for /notebooks/extensions/sd_dreambooth_extension/scripts/main.py
> Traceback (most recent call last):
>   File "/notebooks/modules/script_callbacks.py", line 93, in ui_tabs_callback
>     res += c.callback() or []
>   File "/notebooks/extensions/sd_dreambooth_extension/scripts/main.py", line 153, in on_ui_tabs
>     fn=dreambooth.performance_wizard,
> AttributeError: module 'dreambooth.dreambooth' has no attribute 'performance_wizard'
> ```

I didn't notice this at first, but I am getting the same there too

**Comment by d8ahazard** [comment]
Not to be a grump, but please, please, *PLEASE* use the template when submitting issues. I'm asking for pertinent information in there to help me fix things faster, and every issue submitted without it only takes me that much longer to resolve.
