### ISSUE TITLE
Error loading script: main.py

### ISSUE THREAD

**Issue by darth2602** [d8ahazard/sd_dreambooth_extension#214]
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
>yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
>Yes

**Have you updated Dreambooth to the latest revision?**
>yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
>yes

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is *****************************************
Diffusers version is 0.7.2
Torch version is *********.
Torch vision version is ********.`
> il will look for

**Describe the bug**
(A clear and concise description of what the bug is)

On google colab , Automatic 1111 :
error message (step : Start stable-diffusion)

Preloading Dreambooth!
Error loading script: main.py
Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 164, in load_scripts
module = script_loading.load_module(scriptfile.path)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
exec(compiled, module.dict)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in
from dreambooth import conversion, dreambooth
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 30, in
from dreambooth import xattention
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 6, in
from diffusers.models.attention import xformers
ImportError: cannot import name 'xformers' from 'diffusers.models.attention' (/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py)

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.
>no crash

**Environment**
What OS? 
>google colab

If Windows - WSL or native?
-
What GPU are you using?
>Google colab's gpus

**Comment by dathide** [comment]
I fixed this error by deleting `stable-diffusion-webui/extensions/sd_dreambooth_extension` and opening the webui again. However, now there is a different error stating `ModuleNotFoundError: No module named 'launch'`. I am using https://github.com/AbdBarho/stable-diffusion-webui-docker

**Comment by darth2602** [comment]
I fixed the error (thanks to Ben !) 

i added  at the END  "!pip install -U diffusers"   (without "")  in cell Installing Requirements ...

BEFORE
xformers()
cleanup()

AFTER
xformers()
cleanup()
!pip install -U diffusers

**Comment by d8ahazard** [comment]
So, this is not necessarily an issue, just a warning:

[!] Not using xformers memory efficient attention.

Installing xformers, especially on colab, is not presently something I support or do. Feel free to open a new issue if you have some other problem.
