### ISSUE TITLE
Running on "CPU only" generates CUDA out of memory error if Nvidia GPU present and generates runtime error if no Nvidia GPU is present

### ISSUE THREAD

**Issue by kokakin** [d8ahazard/sd_dreambooth_extension#219]
edit: I forgot the greeting, I'm sorry

Greetings dev, thanks for making this absolute gem and thanks for giving me ear (or eye)!
I hope you are well and can help me on this issue!
Thanks again for the overwhelming support you have been giving to everyone who has an issue, you're an example to be followed!

`
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
[auto-sd-paint-ext] Attempting auto-update...
[auto-sd-paint-ext] Fetch upstream.
[auto-sd-paint-ext] Pull upstream.

Installing requirements for Dreambooth
Checking Dreambooth requirements.
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is d9820bbaecf8242af554c26e007cc9775b3ac163
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.

Launching Web UI with arguments: --api
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yup

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes.

**Have you updated Dreambooth to the latest revision?**
Yes.

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes.

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

I am trying to run training on "CPU only" on a laptop with both dedicated and integrated GPU. The training runs to the point of 100%, but when saving the weights the error occurs. 

I guess that the function is calling the main torch/cuda device (which is not the CPU) regardless of the "CPU only" check. It probably has to do with the fact that the laptop has the option to run programs on CPU or on the GPU, not really both and, since SD starts using the GPU, it's probably having an issue trying to run on the CPU (I don't really know but I want to help as much as I can from this perspective).

The error also occurs during generation of ckpt via training checkpoints frequency as well as generating images. 

**Provide logs**

**Training to 100%:**

Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Scheduler Loaded
 Allocated: 0.0GB
 Reserved: 0.0GB

***** Running training *****
  Num examples = 21
  Num batches each epoch = 21
  Num Epochs = 1
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 4
  Gradient Accumulation steps = 4
  Total optimization steps = 2
Steps: 100%|███████████████████████████████████████████████████████| 2/2 [02:24<00:00, 72.64s/it, loss=0.0858, lr=5e-6] Exception while training: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.41 GiB already allocated; 0 bytes free; 3.52 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 3.4GB
 Reserved: 3.5GB

Error completing request
Arguments: ('G', None, 'C:\\stable-diffusion-webui\\temp\\ga', '', 'GPL', '', '', '', 1, 0, 10, 40, 0, 512, False, True, 1, 1, 1, 2, 4, True, 5e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 100000, 100000, 'no', True, "[{'instance_prompt': 'GPL', 'class_prompt': '', 'instance_data_dir': 'C:\\\\stable-diffusion-webui\\\\temp\\\\ga', 'class_data_dir': 'C:\\\\stable-diffusion-webui\\\\models\\\\dreambooth\\\\G\\\\classifiers'}]", True, False, 75, False, None) {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1004, in main
    save_weights(args.revision, save_model, save_img)
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 842, in save_weights
    pipeline = pipeline.to("cuda")
  File "C:\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipeline_utils.py", line 220, in to
    module.to(torch_device)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.41 GiB already allocated; 0 bytes free; 3.52 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 377, in start_training
    config, mem_record = main(config, mem_record)
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1027, in main
    traceback.logger.debug_exc()
AttributeError: module 'traceback' has no attribute 'logger'

Steps: 100%|███████████████████████████████████████████████████████| 2/2 [02:27<00:00, 73.87s/it, loss=0.0858, lr=5e-6]

**Environment**

Using Windows 11 on a GTX1050ti,  i7-7700HQ CPU @ 2.80GHz   2.80 GHz, 16.0 GB RAM, 500GB SSD 

What OS?

Windows 11

If Windows - WSL or native?

Native

What GPU are you using?

Should be none since only using CPU, but there is a Nvidia GTX1050ti present in the system along integrated graphics.

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json
![image](https://user-images.githubusercontent.com/85350285/202028524-fa879dc0-7840-4e6e-9b27-b054f3ea6045.png)
![image](https://user-images.githubusercontent.com/85350285/202028647-da6b3dbe-6d87-4d0c-bea8-af82336c5b6b.png)
![image](https://user-images.githubusercontent.com/85350285/202028718-d7429ae4-3240-4ccb-9816-7f95d2e669a2.png)

**Comment by kokakin** [comment]
**Generating checkpoint after 1 step**


Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Scheduler Loaded
 Allocated: 0.0GB
 Reserved: 0.0GB

***** Running training *****
  Num examples = 21
  Num batches each epoch = 21
  Num Epochs = 1
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 4
  Gradient Accumulation steps = 4
  Total optimization steps = 2
Steps:  50%|███████████████████████████▌                           | 1/2 [01:17<01:17, 77.90s/it, loss=0.0858, lr=5e-6] Exception while training: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 4.00 GiB total capacity; 3.42 GiB already allocated; 0 bytes free; 3.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 3.4GB
 Reserved: 3.5GB

Error completing request
Arguments: ('G', None, 'C:\\stable-diffusion-webui\\temp\\ga', '', 'GPL', '', '', '', 1, 0, 10, 40, 0, 512, False, True, 1, 1, 1, 2, 4, True, 5e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 100000, 1, 'no', True, "[{'instance_prompt': 'GPL', 'class_prompt': '', 'instance_data_dir': 'C:\\\\stable-diffusion-webui\\\\temp\\\\ga', 'class_data_dir': 'C:\\\\stable-diffusion-webui\\\\models\\\\dreambooth\\\\G\\\\classifiers'}]", True, False, 75, False, None) {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1004, in main
    save_weights(args.revision, save_model, save_img)
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 842, in save_weights
    pipeline = pipeline.to("cuda")
  File "C:\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipeline_utils.py", line 220, in to
    module.to(torch_device)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 615, in _apply
    grad_applied = fn(param.grad)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 4.00 GiB total capacity; 3.42 GiB already allocated; 0 bytes free; 3.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 377, in start_training
    config, mem_record = main(config, mem_record)
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1027, in main
    traceback.logger.debug_exc()
AttributeError: module 'traceback' has no attribute 'logger'

Steps:  50%|███████████████████████████▌                           | 1/2 [01:36<01:36, 96.76s/it, loss=0.0858, lr=5e-6]

**Comment by kokakin** [comment]
** Generating image after 1 step**

Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Scheduler Loaded
 Allocated: 0.0GB
 Reserved: 0.0GB

***** Running training *****
  Num examples = 21
  Num batches each epoch = 21
  Num Epochs = 1
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 4
  Gradient Accumulation steps = 4
  Total optimization steps = 2
Steps:  50%|███████████████████████████▌                           | 1/2 [00:57<00:57, 57.81s/it, loss=0.0858, lr=5e-6] Exception while training: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 4.00 GiB total capacity; 3.42 GiB already allocated; 0 bytes free; 3.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 3.4GB
 Reserved: 3.5GB

Error completing request
Arguments: ('G', None, 'C:\\stable-diffusion-webui\\temp\\ga', '', 'GPL', '', '', '', 1, 0, 10, 40, 0, 512, False, True, 1, 1, 1, 2, 4, True, 5e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 1, 100000, 'no', True, "[{'instance_prompt': 'GPL', 'class_prompt': '', 'instance_data_dir': 'C:\\\\stable-diffusion-webui\\\\temp\\\\ga', 'class_data_dir': 'C:\\\\stable-diffusion-webui\\\\models\\\\dreambooth\\\\G\\\\classifiers'}]", True, False, 75, False, None) {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1004, in main
    save_weights(args.revision, save_model, save_img)
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 842, in save_weights
    pipeline = pipeline.to("cuda")
  File "C:\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipeline_utils.py", line 220, in to
    module.to(torch_device)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 615, in _apply
    grad_applied = fn(param.grad)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 4.00 GiB total capacity; 3.42 GiB already allocated; 0 bytes free; 3.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 377, in start_training
    config, mem_record = main(config, mem_record)
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1027, in main
    traceback.logger.debug_exc()
AttributeError: module 'traceback' has no attribute 'logger'

Steps:  50%|███████████████████████████▌                           | 1/2 [00:59<00:59, 59.60s/it, loss=0.0858, lr=5e-6]

**Comment by xhost007** [comment]
I did not get that error. I tried a run with 2 training steps like you. My learning rate was at 1E-6; I had train text encoder unchecked and my CFG Scale was at 7.5. I used the "auto adjust" button. My VRAM is 8GB though.

**Comment by kokakin** [comment]
I ran exactly as you did, 2 steps, learning rate 1E-6, train text encoder unchecked and my CFG Scale was set to 7.5. I also used the "auto adjust" button, but the same error occurs :,(

**Comment by kokakin** [comment]
Update: After getting the errors mentioned in the thread, if I try to generate an image in the txt2img tab it triggers the following error:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)

I really do think this problem has to do with the fact that my laptop has both integrated and dedicated GPU, and while stable diffusion sets the dedicated GPU, dreambooth tries to use the CPU and ends up getting dedicated GPU references and pointers. 

I hope you guys can help me solve this issue! I really want this bird to fly, even if it takes 3+ days on the CPU!

**Comment by xhost007** [comment]
I just ran a 1200 iterations last night in CPU mode and no error (except results suck so I'll have to try again). I noticed I did my training with classification images and you did not. My gradient accumulation steps was 1 (default) I believe.
My PC also has an integrated GPU and an external RTX3070. If you haven't already, try to do a git pull on the webui folder to clean everything up, maybe it'll help? 
Looks like it's a common error when running in low VRAM.

**Comment by kokakin** [comment]
> I just ran a 1200 iterations last night in CPU mode and no error (except results suck so I'll have to try again). I noticed I did my training with classification images and you did not. My gradient accumulation steps was 1 (default) I believe. My PC also has an integrated GPU and an external RTX3070. If you haven't already, try to do a git pull on the webui folder to clean everything up, maybe it'll help? Looks like it's a common error when running in low VRAM.

I congratulate you on running 1200 iterations on CPU, that must have taken some time (like a long time). As far as I am aware you should be able to run dreambooth without classifcation images, I might be wrong though. Nevertheless i have an update:

I ran the exact same configuration on a i5-1135G7 2.40GHz, 16GB RAM, Intel Iris X GPU laptop and the same error happened again, latest Web UI from automatic1111, latest dreambooth version, no xformers, CPU only checked, gradient checkpointing checked, the rest unchecked.

So I am ruling out the possibility of it being a problem with my main laptop having both integrated and dedicated GPU.

If you guys can at least point me in the right direction of solving the issue with the "save weights" function on line 1004 of the file train_dreambooth.py, which seems to be the function that is triggering the CUDA error, that would be mighty helpful.

I am now aware that training on the CPU works thanks for the comments, they give me hope, but I tried many things now and no success whatsoever, is 16GB RAM not enough to train on the CPU?

**Comment by kokakin** [comment]
> I just ran a 1200 iterations last night in CPU mode and no error (except results suck so I'll have to try again). I noticed I did my training with classification images and you did not. My gradient accumulation steps was 1 (default) I believe. My PC also has an integrated GPU and an external RTX3070. If you haven't already, try to do a git pull on the webui folder to clean everything up, maybe it'll help? Looks like it's a common error when running in low VRAM.

I suppose you're not getting this error because you've got a decent GPU that can handle the ckpt/image generation, so in reality you are training your model on the CPU but the function that saves the model is using your GPU, can you check if during saving your GPU usage spikes in the resource manager? that would mean your GPU is being used to do the finishing touches of the training

**Comment by d8ahazard** [comment]
Whoops, didn't mean to close this, was just trying to tag it in the commit.

But, as the mentioned commit indicates, I *think* I maybe fixed this one. I replaced the casts in training from cuda to the accelerator, which doesn't seem to hurt performance on my 24GB rig, and should fix the above. Feel free to re-open if I'm wrong.

**Comment by kokakin** [comment]
Will check asap and let you know! thanks for the attention!

**Comment by kokakin** [comment]
Sorry for the delay, my CPU was toasting an egg :p
Did it! It trained, generated ckpt, generated the image and everything, you're a legend! best of all? both my laptops are training at the same time! thank you very very much!!!
