### ISSUE TITLE
installing requirements fails when parent directory contains a space

### ISSUE THREAD

**Issue by LePrau** [d8ahazard/sd_dreambooth_extension#22]
Issue posted for automatic1111:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4472

Not sure if this issue related to automatic1111 or sd_dreamboot_extension,
my assumption was that there is a general "install requirements" in auto1111 hence I posted there.
If I was mistaken please tell me and maybe them.

**Comment by LePrau** [comment]
I simply removed the space, and it worked. My path was not particularly long (E:\Stable Diffusion\stable-diffusion-webui)

Issue is that the path name is not quoted/escaped correctly, so certain special characters aside from space might introduce that problem as well.

As a workaround, you can open a cmd prompt in the \sd_dreambooth_extension directory, and run
`pip install -r requirements.txt`

**Comment by JonDadley** [comment]
I also saw this issue. Manually installing via the command prompt didn't seem to fix this for me, in the end I had to copy the entire directory to a folder with no spaces in the filepath. It does feel like the installer script should handle spaces more gracefully.

**Comment by d8ahazard** [comment]
This is now resolved.
