### ISSUE TITLE
Please re-implement "use filename" checkbox for instance/class

### ISSUE THREAD

**Issue by mike4llison** [d8ahazard/sd_dreambooth_extension#221]
Hi, first off thank you so much for this repo, it's awesome. Secondly, there was a previous implementation of using the filename for class or instance. I know you can use the Concepts List .json file, in the vein of simplification, this would be a great asset.

Thanks,

M.

**Comment by d8ahazard** [comment]
You can just use [filewords] for your instance prompt in lieu of using the check boxes, this will do the exact same thing.

**Comment by mike4llison** [comment]
@d8ahazard Awesome thank you :)
