### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Franzinator** [d8ahazard/sd_dreambooth_extension#222]
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
Dreambooth revision is 59f93b3bf5b8540d3ecbae96133099f2e6ad180e
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**
After updating the UI and the extension, a "ModuleNotFoundError" is thrown as soon as I try to train a model. Reinstalling the extension does not help, neither does running with/without the recommended flags. I also tried deleting/reinstalling the venv with no luck.

**Provide logs**

Arguments: ('newTrue', '', 'G:\\Coding_Projects\\stableDiffusion\\stable-diffusion-webui\\dreambooth\\set', '', 'test style', '', '', '', 1, 0, 7.5, 40, 0, 512, False, True, 2, 4, 1, 3200, 1, False, 2e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 500, 500, 'fp16', False, '', False, True, '75', True, True) {}
Traceback (most recent call last):
  File "G:\Coding_Projects\stableDiffusion\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "G:\Coding_Projects\stableDiffusion\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "G:\Coding_Projects\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 376, in start_training
    from dreambooth.train_dreambooth import main
ModuleNotFoundError: No module named 'dreambooth.train_dreambooth'

**Environment**

Windows 10 native
RTX 3090

**Comment by Franzinator** [comment]
To provide further context: replacing the module path as if the script was running from the root of the webui (both in line 376 of "dreambooth.py" and in line 26 of "train_dreambooth.py") seems to fix the issue. Not sure if that is a bug or if my environment got messed up somehow. Let me know if further testing could be useful.

Line 376 in "dreambooth.py"
`from extensions.sd_dreambooth_extension.dreambooth.train_dreambooth import main`

Line 27 in "train_dreambooth.py"
`from extensions.sd_dreambooth_extension.dreambooth.finetune_utils import FilenameTextGetter, EMAModel, encode_hidden_state`

**Comment by d8ahazard** [comment]
> dreambooth.train_dreambooth

This is a good one. I wasn't really sure the proper way to import the extensions, as sd-webui does some odd stuff in loading things to the path. If I can just do "extensions.sd_dreambooth_extension.dreambooth.train_dreambooth" all the time consistently, then I'd be happy to just incorporate the changes across the board for this project.

My only concern is that users can provide custom names for extensions, which would then break these hard-coded paths.

**Comment by d8ahazard** [comment]
Pushed an update to use this. If installing from the UI without a URL, this will work fine.
