### ISSUE TITLE
Black outputs

### ISSUE THREAD

**Issue by ArrowM** [d8ahazard/sd_dreambooth_extension#223]
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
Dreambooth revision is 59f93b3bf5b8540d3ecbae96133099f2e6ad180e
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116
```

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK.

**Describe the bug**
I've produced a few models and all of them produce all-black outputs 10-40% of the time (which only seem to be fixed by turning on `--precision full --no-half` in the webui settings, which destroys performance). I previously trained a couple models using WSL and the ShivamShrirao repo and I didn't have this issue. Any thoughts?

**Environment**
Windows 11 22H2, native (not WSL).
RTX 3080ti

**Comment by d8ahazard** [comment]
> ```
> Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
> Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
> Installing requirements for Web UI
> Dreambooth revision is 59f93b3bf5b8540d3ecbae96133099f2e6ad180e
> Diffusers version is 0.7.2.
> Torch version is 1.12.1+cu116.
> Torch vision version is 0.13.1+cu116
> ```
> 
> **No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.** OK.
> 
> **Describe the bug** I've produced a few models and all of the outputs models have been producing all-black outputs 10-40% of the time (which only seemed to be fixed by turning on `--precision full --no-half` in the webui settings). I previously trained a couple models using WSL and the ShivamShrirao repo and I didn't have this issue. Any thoughts?
> 
> **Environment** Windows 11 22H2, native (not WSL). RTX 3080ti

Generally, black outputs mean the safety checker is hitting on some NSFW content, I believe. The log should usually confirm this.

**Comment by ArrowM** [comment]
Sorry for my ignorance, where can I check that. I don't see anything in /log/ and I couldn't find it on the A111 wiki.

**Comment by 78Alpha** [comment]
The black outputs of a filter block can still happen. In AnythingV3.0 it still happens with the filter off. What model do you have for the base?

**Comment by ArrowM** [comment]
I am using Anything-V3.0.ckpt from https://huggingface.co/Linaqruf/anything-v3.0/tree/main (the full 7gb) one. Is there another one without the filter?

**Comment by d8ahazard** [comment]
> I am using Anything-V3.0.ckpt from https://huggingface.co/Linaqruf/anything-v3.0/tree/main (the full 7gb) one. Is there another one without the filter?

For funsies, try creating a checkpoint by checking the "import model from huggingface hub" checkbox once, then popping in a token and using "Linaqruf/anything-v3.0" for the model URL.

**Comment by ArrowM** [comment]
> For funsies, try creating a checkpoint by checking the "import model from huggingface hub" checkbox once, then popping in a token and using "Linaqruf/anything-v3.0" for the model URL.

Training a new one with this method now. Here's some additional info:
I've noticed more black results when using High Res. I've reproduce the issue with xformers on and off. I'm using the follow settings
![image](https://user-images.githubusercontent.com/42418080/202089917-bd3ba072-2618-491b-9e8b-8e8ce8188a79.png)

**Comment by mykeehu** [comment]
I also got black squares regardless of the xformer. NSFW filter is not turned on. They weren't a few days ago and I can't figure out why it generates them, either locally or on colab.

**Comment by ArrowM** [comment]
I notice this message when it saves checkpoints.
> You have passed `None` for safety_checker to disable its functionality in <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'>. Note that this might lead to problems when using <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> and is not recommended.
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254

**Comment by ArrowM** [comment]
Update: This doesn't seem to be a training issue, I'm getting this result with the vanilla 1.5 model now. I recently upgraded to a 3080ti, I'm wondering if this is an issue with the card. I'll leave this open for now in case any has suggestions for further investigation...

**Comment by ArrowM** [comment]
I think I figured out my issue, I had updated a couple of the dependencies like transformers, timm, and fairscale. After reverting them, everything seems to be working fine. I should have thought of this early, whoops. Thanks for your work on this repo d8hazard.

**Comment by ArrowM** [comment]
I think I found a fix to my problem! Enabling ` --no-half-vae`, It's great because that doesn't kill performance like `--no-half --precision full`. @mykeehu please let me know if that fixes your issue too.

**Comment by mykeehu** [comment]
@ArrowM I will check it out, thank you! It came up on colab and on local machine, but I'm generating on colab, so as soon as I have access, I'll make two sets. If it doesn't have a black image in it, it might be a solution.
