### ISSUE TITLE
Unable to load concepts as JSON

### ISSUE THREAD

**Issue by GiusTex** [d8ahazard/sd_dreambooth_extension#24]
I have created a concepts_list.json and have put its directory in the first box, but dreambooth doesn't load it.
![image](https://user-images.githubusercontent.com/112352961/200545476-aa3eb105-b06c-4fc4-b591-3fc2d0b2b03a.png)
(Don't mind the low training steps in the photo, this is a test to see if it works).
My json file has custom directories to image folders, here my concepts_list.json contents:

[
    {
        "instance_prompt": "true-full-body",
        "class_prompt": "1girl, full body",
        "instance_data_dir": "Train\dreambooth\images\Instance\true-full-body_5",
        "class_data_dir": "Train\dreambooth\images\Class\true-full-body_migliori"
    }
]

(The image folders are in the stable diffusion webui root directory, this is why i use the short path, and yesterday with my personal ShivamShrirao's Repo it was warking).
I have tried path\to\json, path\\to\\json, path/to/json and path/to/images and all don't work. I don't know why cause yesterday i was using my personal ShivamShrirao's Repo and the same path was warking.

Log:
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

Trying to parse: C:\Users\wgius\Desktop\stable-diffusion-webui\Train\dreambooth\concepts_list.json
Unable to load concepts as JSON, trying as file: 'str' object has no attribute 'read'
 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary C:\Users\wgius\Desktop\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
 Scheduler Loaded
 Allocated: 0.2GB
 Reserved: 0.2GB

  Total target lifetime optimization steps = 5
 CPU: False Adam: True, Prec: fp16, Prior: True, Grad: True, TextTr: True
 Allocated: 3.8GB
 Reserved: 3.9GB

Steps:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]Error completing request
Arguments: ('truefullbodytest', '', '', '*', '*', '1girl, true-full-body', '', 1.0, 7.5, 40.0, 55, 512, False, True, 1, 1, 1, 5, 1, True, 5e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 0, 0, 'fp16', True, 'C:\\Users\\wgius\\Desktop\\stable-diffusion-webui\\Train\\dreambooth\\concepts_list.json', False) {}
Traceback (most recent call last):
  File "C:\Users\wgius\Desktop\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\wgius\Desktop\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\Users\wgius\Desktop\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 256, in start_training
    trained_steps = main(config)
  File "C:\Users\wgius\Desktop\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 715, in main
    for step, batch in enumerate(train_dataloader):
  File "C:\Users\wgius\Desktop\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 348, in __iter__
    current_batch = next(dataloader_iter)
  File "C:\Users\wgius\Desktop\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Users\wgius\Desktop\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\wgius\Desktop\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\wgius\Desktop\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\wgius\Desktop\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 356, in __getitem__
    class_image = Image.open(class_path)
  File "C:\Users\wgius\Desktop\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Users\\wgius\\Desktop\\stable-diffusion-webui\\webui.sh'

Steps:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]

This is not related, but on my rtx 3060 12 gb ShivamShrirao's Repo with --gradient_checkpointing and --use_8bit_adam dreambooth works, while in webui for some reason not; i think the rest of the parameters are more or less the same, and shouldn't affect memory usage too much anyway

**Comment by H256** [comment]
Hi @GiusTex , I had the same problem. The instructions in the extension repo are a little unclear 😉 ,as I am also on Windows, here's what solved it for me:
1. Put the absolute path into the gui, Train Model -> Settings -> Concept Lists: `X:\dreambooth\concepts\concepts_list.json` 
2. inside the JSON file, use the following format for the path entries:
```
{
		"instance_prompt": "photo of blah woman",
		"class_prompt": "photo of a woman",
		"instance_data_dir": "X:/dreambooth/path_to_instance_dir/subfolder",
		"class_data_dir": "X:/dreambooth/path_to_class_regularization_dir/woman"
	},
```

With these settings, training runs even with multiple concepts. At least for me. :)

**Comment by GiusTex** [comment]
> 

It doesn't work for me, I tried "X:\path\to\concepts_list.json", "C:\path\to\concepts_list.json", "C:\\path\to\\concepts_list.json" and "C:/path/to/concepts_list.json", all them with the absolute paths inside the json file with {[...]} and also with {...} as in your example, but I keep getting error

**Comment by d8ahazard** [comment]
> > 
> 
> It doesn't work for me, I tried "X:\path\to\concepts_list.json", "C:\path\to\concepts_list.json", "C:\ \path\ \to\ \concepts_list.json" (without the spaces, it's just to make them appear in the comment), and "C:/path/to/concepts_list.json", all them with the absolute paths inside the json file with {[...]} and also with {...} as in your example, but I keep getting error

With JSON, you need to either use forward slashes "/", or escape your backslashes by doubling them "\\".

So, for your example, it should be "X:\\path\\to\\concepts_list.json".

**Comment by GiusTex** [comment]
> > > 
> > 
> > 
> > It doesn't work for me, I tried "X:\path\to\concepts_list.json", "C:\path\to\concepts_list.json", "C:\ \path\ \to\ \concepts_list.json" (without the spaces, it's just to make them appear in the comment), and "C:/path/to/concepts_list.json", all them with the absolute paths inside the json file with {[...]} and also with {...} as in your example, but I keep getting error
> 
> With JSON, you need to either use forward slashes "/", or escape your backslashes by doubling them "\\".
> 
> So, for your example, it should be "X:\\path\\to\\concepts_list.json".
> 
> Edit, Ironically, even on github, I have to type 4 backslashes to get it to print 2.

I already did it (X:\\path\\json and also X:/path/json), as I wrote above, and it didn't work..

**Comment by d8ahazard** [comment]
This should be resolved, both with spaces in the path and loading JSON from the UI. Please open a new issue if you have further problems.

**Comment by Jonseed** [comment]
> Hi @GiusTex , I had the same problem. The instructions in the extension repo are a little unclear 😉 ,as I am also on Windows, here's what solved it for me:
> 
> 1. Put the absolute path into the gui, Train Model -> Settings -> Concept Lists: `X:\dreambooth\concepts\concepts_list.json`
> 2. inside the JSON file, use the following format for the path entries:
> 
> ```
> {
> 		"instance_prompt": "photo of blah woman",
> 		"class_prompt": "photo of a woman",
> 		"instance_data_dir": "X:/dreambooth/path_to_instance_dir/subfolder",
> 		"class_data_dir": "X:/dreambooth/path_to_class_regularization_dir/woman"
> 	},
> ```
> 
> With these settings, training runs even with multiple concepts. At least for me. :) The trick here was to use absolute paths in JSON.

Does the JSON file need an opening and closing square bracket? That's what the example shows in the Readme.

**Comment by GiusTex** [comment]
> > Hi @GiusTex , I had the same problem. The instructions in the extension repo are a little unclear 😉 ,as I am also on Windows, here's what solved it for me:
> > 
> > 1. Put the absolute path into the gui, Train Model -> Settings -> Concept Lists: `X:\dreambooth\concepts\concepts_list.json`
> > 2. inside the JSON file, use the following format for the path entries:
> > 
> > ```
> > {
> > 		"instance_prompt": "photo of blah woman",
> > 		"class_prompt": "photo of a woman",
> > 		"instance_data_dir": "X:/dreambooth/path_to_instance_dir/subfolder",
> > 		"class_data_dir": "X:/dreambooth/path_to_class_regularization_dir/woman"
> > 	},
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With these settings, training runs even with multiple concepts. At least for me. :) The trick here was to use absolute paths in JSON.
> 
> Does the JSON file need an opening and closing square bracket? That's what the example shows in the Readme.

I already tried with the square brackets (it's in my first comment) and it didn't work, i tried again now and still it doesn't work. I've left for now dreambooth inside webui also beacuse it gives me cuda out of memory (optimized with 8 bit adam), while using normal dreambooth (not the one inside webui) i don't have those errors
