### ISSUE TITLE
"Error no file named diffusion_pytorch_model.bin found in directory"

### ISSUE THREAD

**Issue by Andreilys** [d8ahazard/sd_dreambooth_extension#240]
Hey I seem to be running into this error when trying to train my model.

It seems like after I created the model, the /notebooks/stable-diffusion-webui/models/dreambooth/miamodel/ directory has two empty folders and a db_config.json file, should there be additional files in here when I begin training?

"Error no file named diffusion_pytorch_model.bin found in directory"

![Screenshot 2022-11-16 at 8 04 58 PM](https://user-images.githubusercontent.com/8299248/202352444-5f27daa2-722a-4390-8d72-b27066654f34.jpg)

![Screenshot 2022-11-16 at 8 03 47 PM](https://user-images.githubusercontent.com/8299248/202352333-3398e132-5a3d-4e37-b567-73d31fbbd753.jpg)

**Comment by Andreilys** [comment]
Seems like when I create a new model, I get this error
*RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory*

![Screenshot 2022-11-16 at 9 18 24 PM](https://user-images.githubusercontent.com/8299248/202362497-4559a828-457b-465a-a12d-654d24a19f3c.jpg)

**Comment by d8ahazard** [comment]
What base checkpoint are you using to create the model?

**Comment by viktorsec** [comment]
Had the same issue starting from sd-v1-5-inpainting, but not with 1.4.

**Comment by Andreilys** [comment]
I was using a custom .ckpt model, this seems to work with generic stable diffusion.

Now getting this error, thanks in advance for your help!

![Screenshot 2022-11-17 at 4 03 47 PM](https://user-images.githubusercontent.com/8299248/202585950-a07c8318-3a2b-471a-8c9f-83a52df6ba4e.jpg)

**Comment by d8ahazard** [comment]
This should be fixed with the latest commit.
