### ISSUE TITLE
Using NovelAi model as Source Checkpoint causing CUDA

### ISSUE THREAD

**Issue by YakuzaSuske** [d8ahazard/sd_dreambooth_extension#247]
`Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
Installing requirements for Dreambooth
Checking Dreambooth requirements.
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is 725d85ca5485246a430d2f31f624646d061e8104
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

Trying to use the NovelAi leaked model as a source checkpoint results in `CUDA out of memory`.
Is there a way to use it as a source checkpoint without causing CUDA?

**Provide logs**
`
Creating dreambooth model folder: test
State dict not found in the usual spot, trying something else.
Checkpoint loaded from CheckpointInfo(filename='C:\\SUPER_SD_2.0\\stable-diffusion-webui-master\\models\\Stable-diffusion\\NovelAI.ckpt', title='NovelAI.ckpt [e6e8e1fc]', hash='e6e8e1fc', model_name='NovelAI', config='C:\\SUPER_SD_2.0\\stable-diffusion-webui-master\\repositories\\stable-diffusion\\configs/stable-diffusion/v1-inference.yaml')
Exception converting state_dict, using alt method.
Traceback (most recent call last):
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 927, in extract_checkpoint
    pipe = pipe.to(shared.device)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\diffusers\pipeline_utils.py", line 220, in to
    module.to(torch_device)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 12.00 GiB total capacity; 11.15 GiB already allocated; 0 bytes free; 11.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`

What OS?
`Windows`

What GPU are you using?
`RTX 3080Ti`

**Screenshots/Config**
![image](https://user-images.githubusercontent.com/63294141/202529512-3762ec71-c686-493a-b66c-5acf0346f817.png)
![image](https://user-images.githubusercontent.com/63294141/202529754-63b406dc-bd45-405b-990e-3dedd493161d.png)

**Comment by d8ahazard** [comment]
So more than likely, the NovelAI checkpoint uses some other layout than the standard one, which means that when the script tries to extract it, it grabs the wrong section and winds up OOMing because it's converting the wrong data. Or something like that.

I'm not really an expert on the construction of these models, but I do know that they're really just a zip file. How to enumerate the structure would take some work, but that would be the key to sorting this out.

If you can link me to the checkpoint, I can try my best to see if I can figure out how it's assembled, but again, I'm just taking shots in the dark for now. ;)

**Comment by YakuzaSuske** [comment]
> So more than likely, the NovelAI checkpoint uses some other layout than the standard one, which means that when the script tries to extract it, it grabs the wrong section and winds up OOMing because it's converting the wrong data. Or something like that.
> 
> I'm not really an expert on the construction of these models, but I do know that they're really just a zip file. How to enumerate the structure would take some work, but that would be the key to sorting this out.
> 
> If you can link me to the checkpoint, I can try my best to see if I can figure out how it's assembled, but again, I'm just taking shots in the dark for now. ;)

Sure i can send you a drive link since it would be faster than downloading from a torrent and safer. I'm Uploading the file to my drive, 1 sec.

**Comment by YakuzaSuske** [comment]
> So more than likely, the NovelAI checkpoint uses some other layout than the standard one, which means that when the script tries to extract it, it grabs the wrong section and winds up OOMing because it's converting the wrong data. Or something like that.
> 
> I'm not really an expert on the construction of these models, but I do know that they're really just a zip file. How to enumerate the structure would take some work, but that would be the key to sorting this out.
> 
> If you can link me to the checkpoint, I can try my best to see if I can figure out how it's assembled, but again, I'm just taking shots in the dark for now. ;)

Okay here is the link.
https://drive.google.com/file/d/1SfdEM3VJeG8gELXAwsKpJq4DsGXhHKRe/view?usp=sharing

**Comment by sgsdxzy** [comment]
You are using the 7G model right? The 4G one works after the state dict try except, while I cannot get the 7G one to work. 
I know the 7G one contains both full weight and ema weight, and I really want to load these two weights separately to unet and unet_ema, but I know nothing about ckpt structure. If @d8ahazard can find out, please tell me how to get these two weights.

**Comment by d8ahazard** [comment]
> > You are using the 7G model right? The 4G one works after the state dict try except, while I cannot get the 7G one to work. I know the 7G one contains both full weight and ema weight, and I really want to load these two weights separately to unet and unet_ema, but I know nothing about ckpt structure. If @d8ahazard can find out, please tell me how to get these two weights.
> 
> Yhea im using the 7GB model and not the 4Gb one.

Downloading now. 

My guess is, I'll need to try and optimize the extraction routine if it's *just* OOMing. I'll throw some logging in and see if I can't find what's breaking and how we can get around it. Maybe just forcing to CPU or something could work.

**Comment by d8ahazard** [comment]
![image](https://user-images.githubusercontent.com/1633844/202550995-e48e548c-aec8-4c9f-973d-380e32d5634e.png)

Shifting the checkpoint to CPU when loading seems to work, I just need to know how much VRAM you have so I know the approximate "high water mark" to look for when deciding if it's necessary to move it to CPU.

**Comment by YakuzaSuske** [comment]
> 

i have 12Gb

**Comment by d8ahazard** [comment]
Do an update and give it a go now, I think you should be set. I've made it so if the checkpoint is larger than half the available VRAM, it'll be shifted to CPU. Resulting VRAM usage is only 2GB, tested on my 8GB GPU.

60fbee0

**Comment by YakuzaSuske** [comment]
> Do an update and give it a go now, I think you should be set. I've made it so if the checkpoint is larger than half the available VRAM, it'll be shifted to CPU. Resulting VRAM usage is only 2GB, tested on my 8GB GPU.
> 
> [60fbee0](https://github.com/d8ahazard/sd_dreambooth_extension/commit/60fbee088a03a0c6aeb4892e128b4b62a23a3668)

Yup that made it work, created model successfully, trained it to 10 steps as test and successfully converted to CKPT.

**Comment by d8ahazard** [comment]
> > Do an update and give it a go now, I think you should be set. I've made it so if the checkpoint is larger than half the available VRAM, it'll be shifted to CPU. Resulting VRAM usage is only 2GB, tested on my 8GB GPU.
> > [60fbee0](https://github.com/d8ahazard/sd_dreambooth_extension/commit/60fbee088a03a0c6aeb4892e128b4b62a23a3668)
> 
> Yup that made it work, created model successfully, trained it to 10 steps as test and successfully converted to CKPT.

Sweet. I was worried it might OOM on re-compiling the checkpoint, but I guess not.

**Comment by YakuzaSuske** [comment]
> > > Do an update and give it a go now, I think you should be set. I've made it so if the checkpoint is larger than half the available VRAM, it'll be shifted to CPU. Resulting VRAM usage is only 2GB, tested on my 8GB GPU.
> > > [60fbee0](https://github.com/d8ahazard/sd_dreambooth_extension/commit/60fbee088a03a0c6aeb4892e128b4b62a23a3668)
> > 
> > 
> > Yup that made it work, created model successfully, trained it to 10 steps as test and successfully converted to CKPT.
> 
> Sweet. I was worried it might OOM on re-compiling the checkpoint, but I guess not.

Yhea it worked tho the ckpt is 2gb in size compared to the original ckpt which is 7gb i don't think it matters tho right?

**Comment by d8ahazard** [comment]
@YakuzaSuske - Sooo...this fix seems to be causing [other issues](https://github.com/d8ahazard/sd_dreambooth_extension/issues/252), so I've pushed c439bc9, which, instead of doing magic when extracting the checkpoint and adjusting to CPU, instead only does so when you set the --medvram or --lowvram command-line args. 

Please try the new release, and let me know if this works for you. If not, feel free to re-open this issue.

c439bc9
