### ISSUE TITLE
Total step count trained not saved when saving weights

### ISSUE THREAD

**Issue by Jonseed** [d8ahazard/sd_dreambooth_extension#249]
```
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is 725d85ca5485246a430d2f31f624646d061e8104
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

So I force-quit one of my trainings in the middle, and when I started the training back up, the total step count had not been saved, and reverted back to the number at the beginning of my last training. I know the weights were saved at each image preview because I could tell from the previews (and inferencing with the intermediate ckpts), but the total step count didn't match the training. Can you save the total step count at the same time you save the weights, so they match in case training stops mid-session?

**Provide logs**

No crash

**Environment**

What OS? Windows 10

If Windows - WSL or native? native

What GPU are you using? 3060 12GB

**Comment by d8ahazard** [comment]
Good call. Fixed with 6bd2277.
