### ISSUE TITLE
Sample prompts in JSON config file not used during training

### ISSUE THREAD

**Issue by Jonseed** [d8ahazard/sd_dreambooth_extension#250]
```
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is efb70649da409b395321aaa9e0f38e9ff1b93123
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

I set up two concepts in my JSON config file, with sample prompts (and negative prompts), but they were not used in generating previews during training. I only got 1 image, and it appears to have been a blank prompt (the filename was only my step count). Perhaps it was getting the info from the UI and not my JSON file? In the UI I left these fields blank. Do I need to specify 2 samples in the UI, or is that per concept? What do I put in the UI if I want it to use the sample prompts from the JSON file?

**Provide logs**

No crash

**Environment**

What OS? Windows 10

If Windows - WSL or native? native

What GPU are you using? 3060 12GB

**Comment by Jonseed** [comment]
So I'm doing more training, and watching the samples directory closely, and it seems to generate one image that looks like it **is** one of my sample prompts, but then that file is quickly overwritten by the second sample that does **not** look like it is from one of my sample prompts in the JSON file. Both had the same filename, which may be part of the problem, one is overwriting the other? The filename is just the step count, followed by "-0". Are they supposed to be -0 and -1? Should the file include the prompt in the filename, or was that removed?

**Comment by Jonseed** [comment]
It also appears to be using the very same seed(s) each time it generates samples. Is that intentional? Not sure if the seed for each concept are the same though.

**Comment by d8ahazard** [comment]
Give it a go now, I've updated the way prompts are handled, I think you should be OK now. 

I'll have to look at the quotes bit, I don't use any punctuation in my prompts aside from commas and underscore. IMHO, they should probably just be omitted or stripped from the prompt.

Also, there are some new fields for concepts.json if you are using [filewords] that you should look at.
