### ISSUE TITLE
drembooth not 

### ISSUE THREAD

**Issue by arturstudioro** [d8ahazard/sd_dreambooth_extension#253]
**WHAT**
What is this feature of which you speak??

**WHERE**
From whence did you hear this news?? Provide a URL if possible.

**HOW**
I suppose that could be the same as where if you have a URL, but if there's an example, hook me up.

**WHEN**
Whenever I get to it. Hold your horses...

**Comment by YakuzaSuske** [comment]
This dude just seriously made an account to post 'drembooth not" and he didn't even used good grammar.

**Comment by d8ahazard** [comment]
Dreambooth do.
