### ISSUE TITLE
Is posible retraining the session in colab

### ISSUE THREAD

**Issue by wilzamguerrero** [d8ahazard/sd_dreambooth_extension#259]
And if this is possible which is the step to do this, thank yo so much

**Comment by sgsdxzy** [comment]
I think you can just upload the entire models/dreambooth/your_model_name to the ocrresponding location in colab.

**Comment by d8ahazard** [comment]
It is. As @sgsdxzy said, just keep the directory from models/dreambooth for the model you're training, and you should be set. If it doesn't show up because you started the collab before uploading, you can go to extensions and reload the UI to find it. ;)

**Comment by wilzamguerrero** [comment]
Well i think that is not working for me, i stop the training and later i try to resume, i have the folder for train in the folder models/dreambooth, and later i press load parameters and yes this charge all of this, i put the steps for training exactly the same and, i press train, but begin again in 0
