### ISSUE TITLE
Black image output after recent update

### ISSUE THREAD

**Issue by HenkDz** [d8ahazard/sd_dreambooth_extension#261]
I used to train with the previous version with great results, Today I was testing the newest version of this extension and trained as usual. After using the model in text2image it renders a black image no matter what I input.
Steps to produce:
1. Create a unique model using DDIM
![image](https://user-images.githubusercontent.com/17301927/202850045-ee8c349f-9af0-4142-a31c-c942eb0cc834.png)

2. I setup dreambooth with same settings I used to do before (I got RTX3090)
![image](https://user-images.githubusercontent.com/17301927/202850124-dc1cac4f-81e1-4bd5-bbc6-1d02d6d10096.png)

3. Wiat till training finishes in 23 minutes.
![image](https://user-images.githubusercontent.com/17301927/202850156-1556adb7-c225-4ec0-a59a-3e091d26a804.png)

4. Use the new model to get Black images everytime
![image](https://user-images.githubusercontent.com/17301927/202850183-f31819ec-22bd-4a5a-aed6-84fffca63833.png)

**Comment by art-phony** [comment]
Did you try " --no-half --precision full" arguments?

**Comment by HenkDz** [comment]
> Did you try " --no-half --precision full" arguments when webui bootup?

No, why would I? Is it needed for DB to work?
I've got RTX3090 and RAM of 64GB

**Comment by HenkDz** [comment]
> --no-half --precision full

So if you meant these args can fix the black images, they didn't. But if you mean I restart training with these args, I can try

![image](https://user-images.githubusercontent.com/17301927/202854746-6ae1c140-9e03-4dd2-9e60-c666aeb2bd2e.png)

**Comment by art-phony** [comment]
> So if you meant these args can fix the black images
Oh, it's sad. I wondered about actually your training is fine, but maybe generating image part is wrong. I think these options not helps while DB training.

**Comment by d8ahazard** [comment]
Think I found the issue. I bumped the Transformers version yesterday to the .24 release, which seems to have caused the problem. 

Reverting to the .21 release seemed to fix it, but models trained with the broken version are useless. Sorry. 

Please update to 3c0f0a3, this will fix the issue.
