### ISSUE TITLE
Can you supply your own preservation images instead of generating them?

### ISSUE THREAD

**Issue by differentprogramming** [d8ahazard/sd_dreambooth_extension#265]
The average generated image for some prompts is not good, small faces turn into nonsense (though they'd look fine if you generated higher than 512x512).

If I have a classification directory that's already full of images will it use them instead of generating new ones?

If I set the Classification Prompt to [filewords] will it take the definition of the image from its filename?

**Comment by sgsdxzy** [comment]
Yes

**Comment by d8ahazard** [comment]
> Yes

So, this is a bit of a vague answer. :P

Can you supply your own preservation images? "Yes...but they should be generated by your source checkpoint." The point of the preservation images is that they exist as an example of what the model generated before it was trained. At least, that's my understanding of it. 

As such, I don't think it especially matters if the class images are perfect or not.

I did just switch the scheduler for generating class images from ddim to euler A with the hopes that it improves output quality of generated images across the board. You can also mess with negative prompts and the number of gen steps, but again, I don't know that it really matters. 

I could be entirely wrong, but that's my understanding of it from what I've read and experimented with.

**Comment by differentprogramming** [comment]
I think it matters if the "preservation images" have extra limbs and bad hands.  

I notice that after dreambooth, the dreamboothed images have much better hands than SD makes normally.
I think the bad hands are caused by so many images in the database being cut off, but since it IS learning when doing the preservation images, its making its problems worse or better, so you want to pick images that don't have problems.
