### ISSUE TITLE
Question: How to use the new "Existing Prompt Contets" option and "Instance token to swap"

### ISSUE THREAD

**Issue by trihardseven** [d8ahazard/sd_dreambooth_extension#266]
Basically I want to know how those options work exactly.

 In my case I'm using [filewords] for a txt file with danbooru tags and one made up tag. An example of said file would be: testmodel, 1boy, 1girl, sfw, smiling, etc... Which Existing Prompt Contents option should I pick in this case? It's a style dreambooth.

 I'd also like to know when to use the other options as well. And lastly what does intance token swap does and when to use it. Thanks.

**Comment by d8ahazard** [comment]
Check out the readme, I've updated it with a few examples of how [filewords] should work. 

If "testmodel" is your subject, then you would use [filewords] for all prompts, existing prompt contents of "Instance Token + Description" if 1boy or 1girl is your class, then it would be "Instance Token + Class Token + Description". 

Instance token would be "testmodel", class token, if not 1boy or 1girl, would probably be "person" or "man" or "woman", etc.

What this gets you would be:

Instance prompt stays the same, or possibly has class appended if not 1boy/1girl: "testmodel, woman, 1boy, 1girl, sfw, smiling"
Class prompt gets generated as: "woman, 1boy, 1girl, sfw, smiling"
Sample prompt would also be "testmodel, woman, 1boy, 1girl, sfw, smiling"

**Comment by d8ahazard** [comment]
I'm going to close this as it's more usage-related than an issue, but feel free to ask any additional questions, I'll be happy to answer them.

**Comment by trihardseven** [comment]
Dreambooth stopped appearing in my webui. I think you jinxed me...

Here is the error that I'm getting: 

Command: "H:\stable-diffusion-webui\venv\Scripts\python.exe" "H:\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "H:\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 14, in <module>
    from diffusers.utils.import_utils import is_xformers_available
ImportError: cannot import name 'is_xformers_available' from 'diffusers.utils.import_utils' (H:\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py)
