### ISSUE TITLE
Checkpoint generation for older step?

### ISSUE THREAD

**Issue by mykeehu** [d8ahazard/sd_dreambooth_extension#271]
I don't understand the technical background, but is it possible to create a checkpoint for a previous step? 
It may be that I have adjusted the model too much and don't want to start again from scratch, if it is technically possible, maybe keeping the previous states in the model. Is there such a thing when creating a model?

**Comment by d8ahazard** [comment]
> I don't understand the technical background, but is it possible to create a checkpoint for a previous step? It may be that I have adjusted the model too much and don't want to start again from scratch, if it is technically possible, maybe keeping the previous states in the model. Is there such a thing when creating a model?

It's not possible *now*. Currently, the /working directory is where the "lifetime" weights and stuff are stored. So, every time a checkpoint is generated, the existing weights in /working are overwritten.

If you have a generated checkpoint from the step count you want to revert back to, I *think* you can just use that as your base checkpoint, then import config from the previous model.
