### ISSUE TITLE
Suggestion/feature request: option to create ckps in a folder

### ISSUE THREAD

**Issue by seihoukei** [d8ahazard/sd_dreambooth_extension#279]
WebUI looks into folders, and populates model list recursively. It would be nice if it was possible to specify ckpt output subfolder for model to have all WIP models in one place and not scattered around.

Ex. I always end up with something like

```
Anime/model1
Anime/model2
BBB_1000
BBB_2000
Original/sd1.5
Original/sd1.4
RRR_1000
RRR_2000
Style/model1
Style/model2
```

and it would be cool to be able to force outputs to be 

```
Anime/model1
Anime/model2
Original/sd1.5
Original/sd1.4
Style/model1
Style/model2
WIP/BBB_1000
WIP/BBB_2000
WIP/RRR_1000
WIP/RRR_2000
```

**Comment by FloydianSound** [comment]
+1

maybe i would suggest to organize them by `batch_name\model-xxxx.ckpt` ?

**Comment by d8ahazard** [comment]
Added with the latest revision. :D
