### ISSUE TITLE
Disable ckpt save after cancel

### ISSUE THREAD

**Issue by fredconex** [d8ahazard/sd_dreambooth_extension#290]
There's any chance to disable the ckpt auto saving after canceling the training? sometimes after training like 1000-1500 steps I'm happy with the result, so I wait for it to save at 1500 and cancel, but it ends saving two files one with 1500 and another with small amount of steps on top of it due to time used to cancel

**Comment by seihoukei** [comment]
Expanding the idea, as I also have some griefs with cancelling.

Dropdown menu for canceling would be great with options to
- Cancel without creating ckpt
- Cancel a the end of current epoch
- Cancel at next generated checkpoint

While we are at this, I also wanted to ask - if I have hundreds of images and use cancel, some images are gonna be shown more times than others. If I continue later, does it finish the last sequence, or does it start a new one, keeping the balance off? I it's the latter, second option is important to me.

**Comment by d8ahazard** [comment]
> 

So, I've had similar thoughts regarding canceling, and haven't come up with a super-clean idea yet that I want to implement. My initial thought is to just replace the "train" button with the normal cancel button (cancel asap), and add another that cancels after the next checkpoint step...or something like that. I think I can do two different types of cancel, three might require more work.

Regarding canceling and re-starting, and heck, epochs in general, I'm working on a new Dataset class for dreambooth training that will enumerate items over multiple concepts for a varied amount of training steps (more instance images for one concept than another), as well as ensure that enumerating over each set of instance and class images is *always* random.

So, wait for the next commit, and that should be there.

**Comment by seihoukei** [comment]
WebUI itsel has dropdown menus on cancel button (right-click generate for menu with option to start infinite generation, right-click interrupt so stop ininite process). I think that would be the cleanest solution for alternative cancelling options - a right click dropdown menu with alternative variants.

**Comment by d8ahazard** [comment]
So, I'm a big liar, and this hasn't been implemented in the newest release, but it's still on my radar.

**Comment by d8ahazard** [comment]
Implemented with the latest release.
