### ISSUE TITLE
REQUEST: Amount of training steps per concept

### ISSUE THREAD

**Issue by mrgreaper** [d8ahazard/sd_dreambooth_extension#299]
**WHAT**
an argument in the concepts json to set either how many steps it trains that concept for or at what step in the training steps it starts that concept.
`"training steps": "800"`

**WHERE**
it came from my brain

**HOW**
This form is odd...

**WHEN**
Whenever I get to it. Hold your horses...

gonna add one:
**WHY**
It is rare we will have the same amount of training images when adding friends to a model (come on thats what most of us are doing lol). This would allow us to give concepts we have more training images for more time to cook while not overcooking the ones with less images.

Thanks in advance

**Comment by d8ahazard** [comment]
Not opposed to any good idea, but this one will take a bit of re-working in order to make it a reality, as presently, I believe the "training dataset" just becomes one big set of images to process, versus training one subject, then the next, etc.

Might be possible to just rework the training dataloader to remove images after N steps, but it'll still take some work.

**Comment by d8ahazard** [comment]
LOL, so, this apparently isn't nearly as trick as I thought, and it's a nice way to start building support for #176. :D 

Should have a commit implementing this tonight or tomorrow.

**Comment by mrgreaper** [comment]
Awesome :)

**Comment by d8ahazard** [comment]
This has been implemented with 083b4d2

You can either set the max steps for a concept to -1 to use the "global" number of training steps, or a specific value, after which, the subject will no longer be trained. This is also implemented in the wizards.

**Comment by mrgreaper** [comment]
Awesome thank you!
Is it compatible with 2.0 as well as 1.5 now? I know 2.0 support in
automatic1111 only happened today so guessing not but figure it can't hurt
to ask.

**Comment by d8ahazard** [comment]
Working on 2.0 support, but I don't think it's even officially supported
yet. *maybe* using the new 2.0 diffusers model from the hub, but I can't
extract the .ckpt file for now, at least.

Haven't tried with the hub version.

**Comment by mrgreaper** [comment]
I know that one model has been trained with dreambooth on 2.0 but I dont
know if it was a custom fork.
At work and reddit seems to be mostly censored lol
(3) New Release: SD 2.0 Dreambooth model - Future-Diffusion :
StableDiffusion (reddit.com)
<https://www.reddit.com/r/StableDiffusion/comments/z42idl/new_release_sd_20_dreambooth_model_futurediffusion/?utm_source=BD&utm_medium=Search&utm_name=Bing&utm_content=PSR1>

I have no idea if that link is even remotely helpful though.

As an aside, thank you for the extension, having a lot of fun putting
myself and mates into the system... still need to learn how to use it more
effectively for more abstract stuff...specially how bare bone 2.0 is. But,
with out tools like this we would all be out of luck. The work you and
people like you do for us all is appreciated.
