### ISSUE TITLE
8bit adam does not work on Windows.

### ISSUE THREAD

**Issue by ShinkoNet** [d8ahazard/sd_dreambooth_extension#3]
ShivShiram's repo bypassed this issue by using WSL2 and a docker container for bitsandbytes's required CUDA libraries.
With Windows, the following error occurs upon training:

```
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary C:\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary C:\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Exception importing 8bit adam:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs aboveto fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
The config attributes {'set_alpha_to_one': False, 'skip_prk_steps': True, 'steps_offset': 1} were passed to DDPMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
 Scheduler Loaded
 Allocated: 0.2GB
 Reserved: 0.2GB
  Total target lifetime optimization steps = 1000
 CPU: False Adam: False, Prec: fp16, Prior: False, Grad: True, TextTr: True

**Comment by ShinkoNet** [comment]
There's this writeup/tutorial here to use windows binaries of these libraries without resorting to WSL:
https://gist.github.com/geocine/e51fcc8511c91e4e3b257a0ebee938d0
maybe something similar can be done for this extension?

**Comment by d8ahazard** [comment]
> There's this writeup/tutorial here to use windows binaries of these libraries without resorting to WSL: https://gist.github.com/geocine/e51fcc8511c91e4e3b257a0ebee938d0 maybe something similar can be done for this extension?

Yes, theoretically, this wouldn't be too hard to schlep into the install.py script with a check for the OS. I'll see what time I have to tinker with this today. I don't particularly need 8bit adam, but happy to include it for those that want it.

**Comment by d8ahazard** [comment]
I've now added a bit to the installer that checks if running on windows, and if so, checks for the .dll file specified in the gist. If they're not found, they will be copied to venv, similar to the other script.

159a336

**Comment by ShinkoNet** [comment]
ok. I'll test this. Last time I did this manually and it couldn't import cudasetup in the cextensions py though. 
I'll have to test tomorrow though since it's 2am here

**Comment by sgsdxzy** [comment]
I think the dlls only work for pytorch+cu116, and by default you will get pytorch+cu113 when installing webui. Manual upgrading might be required.
I am looking for a way to compile these dlls, but I know nothing about Windows, or marchine learning pipelines or tools in the first place. Can we check if these dlls are safe?

**Comment by sgsdxzy** [comment]
> > I think the dlls only work for pytorch+cu116, and by default you will get pytorch+cu113 when installing webui. Manual upgrading might be required. I am looking for a way to compile these dlls, but I know nothing about Windows, or marchine learning pipelines or tools in the first place. Can we check if these dlls are safe?
> 
> I can force it to install specific version of pytorch with the extension - we just need to confirm that updating to cu116 won't break anything else.

I did the upgrade and haven't notice anything broken. Further tests needed.

**Comment by sgsdxzy** [comment]
But it is still better if we can compile our own version of these dlls, for any cuda version the user has installed.

**Comment by d8ahazard** [comment]
> But it is still better if we can let the users compile their own versions of these dlls, for any cuda version they have installed.

Well, the one used natively by SD is cu113, so I think I'd rather precompile and distribute as many versions as possible, then select based on the right CUDA toolkit. Building is probably going to take some backflips, which is why I'm not leaning that way.

**Comment by d8ahazard** [comment]
I'm going to close this and link it up with #7, as they're the same issue.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
