### ISSUE TITLE
Error while trying to use concepts list from json file.

### ISSUE THREAD

**Issue by mixbag** [d8ahazard/sd_dreambooth_extension#304]
![g1](https://user-images.githubusercontent.com/116809710/203561599-04d8a9b0-213f-410d-81a9-9582c444d322.png)
![g2](https://user-images.githubusercontent.com/116809710/203561626-f8b9f76a-7540-4b8c-9505-59a1b81aff55.png)
![g3](https://user-images.githubusercontent.com/116809710/203561661-03625739-ac18-4840-958a-c78943f2b278.png)
![g4](https://user-images.githubusercontent.com/116809710/203561675-f6c52129-056c-45dc-9fad-85122481417a.png)
Hello, I tried to do multiple concepts with editing the example concepts_list.json file , but it is giving me unable to load concepts error.
Plz help.

**Comment by d8ahazard** [comment]
Double the slashes in your paths "\\" not "\"

**Comment by mixbag** [comment]
hi, thanks for replaying. i changed the path from C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\concepts_list.json to C:\\stable-diffusion-webui\\extensions\\sd_dreambooth_extension\\dreambooth\\concepts_list.json but still getting the error. i also tried addind "\\" in "\" withing the json file.
