### ISSUE TITLE
Dreambooth failing with Tokenizer paths, as well as not creating subdirectories in working directory after updating

### ISSUE THREAD

**Issue by auraria** [d8ahazard/sd_dreambooth_extension#309]
`
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]

Commit hash: 8eb0a97278d074d32d4d777ab19c4413d4ce2af6

Installing requirements for Web UI

Installing requirements for Dreambooth

Checking Dreambooth requirements.

Checking/upgrading existing torch/torchvision installation

Checking torch and torchvision versions

Dreambooth revision is c589a3596ade64228de8a7851f50c2470c7a76aa

Args: ['extensions\\sd_dreambooth_extension\\install.py']

[*] Diffusers version is 0.7.2.

[*] Torch version is 1.12.1+cu116.

[*] Torch vision version is 0.13.1+cu116.

[*] Transformers version is 4.21.0.

[*] Xformers
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes, multiple times, including system reboot.

**Have you updated Dreambooth to the latest revision?**
Yes, this is when I experience the issue, didn't have an issue prior when I made my last model on the 12th.

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
As far as I'm aware of, through Automatic1111 yes.

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

OK

**Describe the bug**

Post updates, after creating a new model with OR without checkpoint(I've tried SD1.5/Anythingv3/none), I get an error regardless of what settings I select in the training section about Tokenizer files. However, it didn't create any of the subdirectory/folders under working after model creation. I've tried multiple restarts and model creations. 

Additionally it did try loading a local path as a huggingface url path a few times but I haven't seen that pop back up after additional close/starts.

EDIT: Think I found the folder/file creation issue leading up to this:

```
Creating dreambooth model folder: Petermohrbacherv2
Exception with the conversion: 'Namespace' object has no attribute 'ckptfix'
Traceback (most recent call last):
  File "C:\Users\david\Desktop\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 847, in extract_checkpoint
    if shared.cmd_opts.ckptfix or shared.cmd_opts.medvram or shared.cmd_opts.lowvram:
AttributeError: 'Namespace' object has no attribute 'ckptfix'
 Extraction completed.
 Allocated: 2.0GB
 Reserved: 2.0GB
```
It's odd that it's mentioning the ckptfix in context of lowvram/medvram here's my full startup params:

Launching Web UI with arguments: --xformers --precision autocast

Removing --precision autocast did not resolve the issue either, this occurs with both specifying a checkpoint as well as not specifying a checkpoint during model creation
![image](https://user-images.githubusercontent.com/53339284/203641044-2a64c609-7890-44eb-a649-b94e5f79127b.png)

```
Traceback (most recent call last):
  File "C:\Users\david\Desktop\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\david\Desktop\stable-diffusion-webui\webui.py", line 55, in f
    res = func(*args, **kwargs)
  File "C:\Users\david\Desktop\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 527, in start_training
    config, mem_record = main(config, mem_record)
  File "C:\Users\david\Desktop\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 717, in main
    tokenizer = CLIPTokenizer.from_pretrained(
  File "C:\Users\david\Desktop\stable-diffusion-webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1789, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'C:\Users\david\Desktop\stable-diffusion-webui\models\dreambooth\Petermohrbacherv1\working'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'C:\Users\david\Desktop\stable-diffusion-webui\models\dreambooth\Petermohrbacherv1\working' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
```
![image](https://user-images.githubusercontent.com/53339284/203635720-177266f5-f9a4-4b37-8cc1-cf89b7f704d7.png)
![image](https://user-images.githubusercontent.com/53339284/203635756-44b651e9-e2c4-40c5-bd69-34dad558f843.png)

Examples of local path being assigned as a hugging face url:
![image](https://user-images.githubusercontent.com/53339284/203635478-f1615675-1eef-41bd-8edd-f9e3f73084dc.png)
![image](https://user-images.githubusercontent.com/53339284/203635528-eb49b8c7-c718-4441-96e3-7716c0f1a5fe.png)

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS? Windows 10 : Microsoft Windows [Version 10.0.19045.2251]

If Windows - WSL or native? : WSL

What GPU are you using? RTX 3080 FE

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

Config file:

`{
    "max_token_length": "75",
    "model_dir": "C:\\Users\\david\\Desktop\\stable-diffusion-webui\\models\\dreambooth\\Petermohrbacherv1",
    "pretrained_model_name_or_path": "C:\\Users\\david\\Desktop\\stable-diffusion-webui\\models\\dreambooth\\Petermohrbacherv1\\working",
    "class_guidance_scale": 7.5,
    "class_negative_prompt": "",
    "class_infer_steps": 40,
    "use_concepts": false,
    "half_model": false,
    "file_prompt_contents": "Description",
    "instance_token": "",
    "class_token": "",
    "shuffle_after_epoch": false,
    "db_attention": "default",
    "model_name": "Petermohrbacherv1",
    "scheduler": "ddim",
    "src": "Anything-V3.0.ckpt [6569e224]",
    "total_steps": 0,
    "revision": 0,
    "pretrained_vae_name_or_path": null,
    "instance_data_dir": "E:\\pics\\taining\\petermohrbacher\\out",
    "class_data_dir": "",
    "instance_prompt": "cosmicangel",
    "class_prompt": "",
    "save_sample_prompt": "masterpiece, 4k, cosmicangel",
    "save_sample_negative_prompt": "lowres, bad anatomy, bad hands, text, error, missing fingers,extra fingers, extra body, extra head, extra face, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, ((signature)), ((watermark)), username, blurry, artist name, mutations, bad proportions, extra head, ugly, imperfections, disfigured,((multiple angles)), (( multiple shots)), (divided images:1.3),robot eyes, censored, mouth mask, mask,hairy armpits,(hands:0.3), cross eyed",
    "n_save_sample": 1,
    "seed": 0,
    "save_guidance_scale": 7.5,
    "save_infer_steps": 40,
    "with_prior_preservation": false,
    "num_class_images": 0,
    "output_dir": "C:\\Users\\david\\Desktop\\stable-diffusion-webui\\models\\dreambooth\\Petermohrbacherv1",
    "resolution": 512,
    "center_crop": false,
    "train_text_encoder": true,
    "train_batch_size": 1,
    "sample_batch_size": 1,
    "num_train_epochs": 1,
    "max_train_steps": 27300,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "learning_rate": 1.72e-06,
    "scale_lr": false,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "attention": "default",
    "use_8bit_adam": true,
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_weight_decay": 0.01,
    "adam_epsilon": 1e-08,
    "max_grad_norm": 1,
    "save_preview_every": 500,
    "save_embedding_every": 500,
    "mixed_precision": "fp16",
    "not_cache_latents": true,
    "concepts_list": [
        {
            "instance_prompt": "cosmicangel",
            "class_prompt": "",
            "instance_data_dir": "E:\\pics\\taining\\petermohrbacher\\out",
            "class_data_dir": "C:\\Users\\david\\Desktop\\stable-diffusion-webui\\models\\dreambooth\\Petermohrbacherv1\\classifiers_concept_0",
            "instance_token": "",
            "class_token": ""
        }
    ],
    "use_cpu": false,
    "pad_tokens": true,
    "hflip": false,
    "use_ema": false,
    "prior_loss_weight": 1
}`

**Comment by leppie** [comment]
The webui is probably outdated (commit seems about 20 days old).

**Comment by auraria** [comment]
> The webui is probably outdated (commit seems about 20 days old).

I did a gitpull and seems to have the same issues, going to reinstall it entirely and try again

**Comment by wyattnewhall** [comment]
Same eventual issue here, but for me the error comes from not having enough memory on my 3070

`Traceback (most recent call last):
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 944, in extract_checkpoint
    pipe = pipe.to(map_location)
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipeline_utils.py", line 220, in to
    module.to(torch_device)
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "C:\Users\12078\Desktop\SD\stable_diff\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 7.17 GiB already allocated; 0 bytes free; 7.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by leppie** [comment]
> `"train_text_encoder": true`

Only noticed this now. Not going to work on anything less than 16GB VRAM I believe. 

I only have 10GB, so I cant use text encoder either which I believe makes your instance prompt useless. 

Still testing this, and a possible workaround (by hijacking 'unused' tokens).

**Comment by d8ahazard** [comment]
So, the original issue is related to an outdated webUI, the subsequent discussion seems to be related to OOM issues and may be resolved, and a new version has been pushed that should hopefully address issues when extracting checkpoints.
