### ISSUE TITLE
Not creating working folder for the inpainting model.

### ISSUE THREAD

**Issue by dx777** [d8ahazard/sd_dreambooth_extension#312]
It works fine with the defaultd SD 1.5 model, but when I try to create using checkpoint from this [repo](https://huggingface.co/runwayml/stable-diffusion-inpainting/tree/main), then it gives me a normal status:
`Created working directory for pinkDressNoBG at /workspace/stable-diffusion-webui/models/dreambooth/pinkDressNoBG/working.
`
But that working directory is completely empty.

**Comment by d8ahazard** [comment]
Training the inpainting model is currently not implemented.
