### ISSUE TITLE
Question about [filewords]

### ISSUE THREAD

**Issue by ppkppk8520** [d8ahazard/sd_dreambooth_extension#328]
first of all, sorry for my poor english.

i wonder how can i use [filewords].
does only .txt file affect [filewords]? or does file name also affect [filewords]?

so, suppose following situation:
dbartist1 (1).png, dbartist1 (1).txt, dbartist1 (2).png, dbartist1 (2).txt ...
each .txt file consist of some tags like 1girl, solo, ...

then, if i use [filewords] as instance prompt option, what will be a real instance prompt?
only tags in .txt files? or file name + tags?
i'm not sure because there is no "file name" like things mentioned in readme.
please let me know.

thank you for advance.

**Comment by d8ahazard** [comment]
If txt files exist, they will be used as the source for caption/tags, otherwise, it will try to parse the filename.

**Comment by ppkppk8520** [comment]
Thanks!

**Comment by Ladypoly** [comment]
> How toes the txt file work?
Is there a example how it should be structured?
Where do we have to put the txt file?
