### ISSUE TITLE
Possible Unicode pasted text have problems with default charmap on startup

### ISSUE THREAD

**Issue by leppie** [d8ahazard/sd_dreambooth_extension#334]
```
stderr: Traceback (most recent call last):
  File "G:\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 80, in <module>
    check_versions()
  File "G:\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 56, in check_versions
    print(f"{status} {check} version {check_ver} installed.")
  File "C:\Users\leppie\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2713' in position 1: character maps to <undefined>
```

It seems is passing Unicode where and ANSI encoding is expected. 

This typically happens from pasted text (in my case, MS Word).

Edit: See the `checkmark` in https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/install.py#L47 , replacing with an `x` fixes the issue. 

Windows does support Unicode output on console, but it seems it is not configured in this case.

**Comment by d8ahazard** [comment]
Dammit. That checkmark is so neat.

One moment, please.

**Comment by d8ahazard** [comment]
Fixed with a66a2d6

**Comment by leppie** [comment]
> That checkmark is so neat.

You probably want to the stick to the default `*` instead of the random `X` I put in :D

**Comment by leppie** [comment]
It could just be the file needs the correct Unicode BOM.

**Comment by d8ahazard** [comment]
> > That checkmark is so neat.
> 
> You probably want to the stick to the default `*` instead of the random `X` I put in :D

LOL, I used an X. Without the check, X felt like the next best option. Open to suggestions for a simple way to differentiate between "required and met", "required and not met", and "this is just for the developer's information"

**Comment by leppie** [comment]
> It could just be the file needs the correct Unicode BOM.

Well that does not work :| Worth a try :D

**Comment by leppie** [comment]
> if you know the proper fix, I'd love to keep the checkmark.

Would be nice, but I have zero experience with Python. Could easliy tell you how it works with .NET however :D

**Comment by leppie** [comment]
> Open to suggestions for a simple way to differentiate between "required and met", "required and not met", and "this is just for the developer's information"

Maybe `o` for OK ? `x` just feels like an error.

**Comment by d8ahazard** [comment]
That checkmark really tied the room together...

**Comment by leppie** [comment]
> Test and toss a line in here or submit a PR. ;)

Got it working in a simple test file, the `coding` comment should do it.

```
# coding=utf-8

print("[✓]")
```

Save file as UTF8 in editor. 

See: https://peps.python.org/pep-0263/  (which was helpful from Python to point me there when I tested it :D )

**Comment by leppie** [comment]
Tried to fix, but it seems Automatic1111 needs to spawn the installer process with some extra flags perhaps?

I even tried saving the file with UTF8 BOM. No luck :(
