### ISSUE TITLE
Give it a go now, I've released the new dataloader. Might not fix the problem, but at the very least, I know how to debug it now. ;)

### ISSUE THREAD

**Issue by noxiouscardiumdimidium** [d8ahazard/sd_dreambooth_extension#337]
Give it a go now, I've released the new dataloader. Might not fix the problem, but at the very least, I know how to debug it now. ;)

_Originally posted by @d8ahazard in https://github.com/d8ahazard/sd_dreambooth_extension/issues/302#issuecomment-1328101679_
it broke EVERYTHING... can't load previously trained models - still get the too many values error. cant load previously trained model parameters - all entry fields turn to "error" and have to relaunch to clear (will store and load params from a newly created model, if set post-update) . checking or unchecking use concepts list tick-box throws assorted errors. attempting to use json config, or 1-some-or-all manually set concepts all throw the same "please configure some concepts" and/or max-steps error regarless of any and all other params (spent hours trying every combination of settings including ones that made no sense). even with sample prompt in json and all concepts sample image fileds, clicking "generate sample image" posts vram alloc info and freezes with no output. attempting to export newly created vanilla model produces "missing 2 required positianl arguments: vae_path and half_checkpoint" error

**Comment by d8ahazard** [comment]
Please update, and if you're still having issues, use the proper issue template to submit problems. No logs, no version info == I can't help you.
