### ISSUE TITLE
ImportError: cannot import name 'save_config'

### ISSUE THREAD

**Issue by seoeaa** [d8ahazard/sd_dreambooth_extension#338]
Just updated now won't open

ImportError: cannot import name 'save_config' from 'extensions.sd_dreambooth_extension.dreambooth.db_config' (/home/aleks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/db_config.py)

**Comment by Bendito999** [comment]
Mine did this once after the most recent update. I then exited and relaunched Stable Diffustion (am running on Ubuntu) and the second time this error no longer appeared, and the Dreambooth tab is now back.

**Comment by d8ahazard** [comment]
Please update and try again. If you are still having issues, use the proper issue template so I can more effectively diagnose the problem.
