### ISSUE TITLE
classification images saved to root folder

### ISSUE THREAD

**Issue by dx777** [d8ahazard/sd_dreambooth_extension#346]
`
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
Commit hash: bb11bee22ab02aa2fb5b96baa9be8103fff19e6a
Dreambooth revision is a66a2d6bca536207ca3154324f73a5cd43a65cb4
diffusers version 0.8.1 installed.
torch version 1.12.1 installed.
torchvision version 0.13.1 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**
I'm on the latest commit (a66a2d6bca536207ca3154324f73a5cd43a65cb4).

For some reason classification files are added to the root folder, where sd is installed. No path was provided for clasification images in wizard and was chosen to generate them. Now I have to delete them before the next training, otherwise it thinks that it can reuse the old one, and that they are belong to the new class as well. 

Also, for some reason, it generates only 26 images, when I put 30.  (And showing */26 in the progress, so it's expected).

**Environment**

Runpod linux

What GPU are you using?
A5000

**Screenshots/Config**
<img width="599" alt="Screenshot 2022-11-28 at 01 05 54" src="https://user-images.githubusercontent.com/25134157/204165712-439c5dc6-eeaa-423c-bb40-a7c1439cb0c1.png">
<img width="1167" alt="Screenshot 2022-11-28 at 01 34 42" src="https://user-images.githubusercontent.com/25134157/204165726-7e60267a-20fe-43ce-b941-aa6b99c79d71.png">
<img width="632" alt="Screenshot 2022-11-28 at 01 35 09" src="https://user-images.githubusercontent.com/25134157/204165727-664313fd-5d32-40bc-9a78-baee3bb81929.png">

**Comment by d8ahazard** [comment]
This should be resolved with 1913bc7

**Comment by dali99** [comment]
Additionally, If you set the file path manually now, the txt files won't have the full prompt that generated them, often with just a `a` as their contents
