### ISSUE TITLE
Use txt2img for regularization image generation

### ISSUE THREAD

**Issue by dali99** [d8ahazard/sd_dreambooth_extension#355]
**WHAT**
Instead of reimplementing txt2img for regularization it'd be nice if this could be outsourced to txt2img directly.

**WHY**
On my system the speed difference is huge (and has always been), with the dreambooth extension doing ~10s/it and txt2img doing ~5it/s (50x faster!)

**ALTERNATIVES CONSIDERED**
Alternatively itd be possible to fix whatever causes the dreambooth extension to be slower
But assuming the larger ecosystem can make speed improvements, itd be nice if that could be automatically leveraged

**DOWNSIDES**
Even more linking to the chaos that is automatics webui
Fancy settings elsewhere in the program might mess with the accuracy of the generated regularization output?

**Comment by d8ahazard** [comment]
This isn't really that tough to implement. Add a flag on "start training" that tells it whether to use the checkpoint for class gen, or the pipeline.

Only trick would be if the user created a model from huggingface hub, then I have no base checkpoint to load in the UI to use for txt2image. I could always generate a base checkpoint, but that's only good as long as it's not deleted.

And yes, of course, the massive headache that would probably result from trying to use txt2img if anything ever changed in the main app. 

I've thought about it, but haven't come up with something elegant and future-proof to make me want to do this yet.

**Comment by leppie** [comment]
Tagging onto this, I tried to generate more classification images just now on an existing model with > 4000 steps and it just spat out images from the trained model. IMO, it should use the base model.

**Comment by leppie** [comment]
> On my system the speed difference is huge (and has always been), with the dreambooth extension doing ~10s/it and txt2img doing ~5it/s (50x faster!)

Quick hack (not as fast as txt2img), but you can set the class batch size higher (4 worked in my case). Then cancel after it generated the images. And revert to class batch size of 1 or whatever you use.

**Comment by d8ahazard** [comment]
Class batch size *only* controls the speed of class image generation, fwiw.
;)

**Comment by d8ahazard** [comment]
Implemented with the latest release.
