### ISSUE TITLE
Epochs always set to 101

### ISSUE THREAD

**Issue by chakalakasp** [d8ahazard/sd_dreambooth_extension#361]
Here's another fun bug with the latest release: training epochs is hard coded to 101 no matter what I input.  I put in 1 or 2 or 5 -- no matter.  It goes to 101.  Which seems a little excessive on a 12000 step run on 120 images.  

Not sure if it matters, but here are the settings.  
![image](https://user-images.githubusercontent.com/52117179/204438847-3941383e-473d-4bb3-9329-b46359471292.png)

![image](https://user-images.githubusercontent.com/52117179/204439236-1aa0cefb-7bdf-401a-af61-96fd32a95609.png)

**Comment by dx777** [comment]
For me, it's just a random number (251), when I come back to train a model for a second step, from 1000 steps.

**Comment by d8ahazard** [comment]
The number of epochs is just mathed out based on the bath size, number of steps, and number of instance image.

An epoch is literally just one iteration over the full dataset.

Also, if you hover over the label for any input value, you'll see a hint that tries to tell you more about it.

In this case, the hint is:

![image](https://user-images.githubusercontent.com/1633844/204638911-5acbaf98-ebbb-4c28-8841-0455e7d89bb9.png)

**Comment by chakalakasp** [comment]
A 12000 step run needs a 101 epochs? Literally no other implementation I’ve used (including the old school python scripts you had to run in terminal) behaved this way. If I remember correctly, every other version I’ve used would use 5050 steps per epoch for a 50 image dataset, 2020 for a 20 image dataset, 1919 for a 19 image dataset. My 119 image dataset would have had 11919 iteration epochs I assume. Yours is running 119 image epochs, a good 2 orders of magnitude difference.

I guess if it all works the same I don’t care, other than the reduced speed. Last version didn’t work at all and trained up nothing after hours of GPU time — I’m running a batch now, if it works it works, I suppose.

**Comment by chakalakasp** [comment]
Ya, just poked around — by default epoch size is usully 101x number of dataset images. Yours is set to 1x number of dataset images. If that’s intentional, then ok, as long as it works and you know what you’re doing. In your previous versions the trainer did not behave this way and had more typical size epochs.
