### ISSUE TITLE
Cant install from GUI

### ISSUE THREAD

**Issue by grljjj** [d8ahazard/sd_dreambooth_extension#363]
After install in cmd
stderr: ERROR: Could not install packages due to an OSError: [WinError 5]   : 'C:\\Users\\GRLJ\\stable-diffusion-webui\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'         Check the permissions.
What should i do?

**Comment by d8ahazard** [comment]
See the example bat file "webui-user-dreambooth.bat". Try adding the line 

`
set "REQS_FILE=.\extensions\sd_dreambooth_extension\requirements.txt"
`

to your bat file and restart the webUI.

**Comment by d8ahazard** [comment]
Also, please use the issue template, as it asks pertinent questions like "Is your UI up-to-date" and "Have you restarted the UI"?

**Comment by grljjj** [comment]
Thanks
