### ISSUE TITLE
Issues with Dont cache latents enabled

### ISSUE THREAD

**Issue by leppie** [d8ahazard/sd_dreambooth_extension#364]
Note using this patch allowing me to increase batch size now (and disable Dont cache latents) on 3080 10GB 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/5165

If I disable Dont cache latents, it works. (can do batch 3 with it disabled, more when enabled, edit: tried 4 wants to but it fails, 3 is safe for me though in either case).

If I cancel the training before steps divided batch_size, it saves the checkpoint correctly. It always fails at this point. So 30 steps and batch of 3, will fail on 10th step.

Also, I removed the 2 cleanup calls in `cache_latents(...)` and it runs a lot faster now with out the expensive cleanup/gc. 
Update:  Seems it is also safe to remove cleanup call at 
https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/dreambooth/train_dreambooth.py#L961

![image](https://user-images.githubusercontent.com/127666/204541839-b7320551-9971-4898-b562-b2a35bb1db52.png)

```
***** Running training *****
  Num examples = 14
  Num batches each epoch = 14
  Num Epochs = 2
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 25
   Training settings: CPU: False Adam: True, Prec: fp16, Grad: True, TextTr: False EM: False, LR: 1.72e-06
```

```
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 981, in main
    for step, batch in enumerate(train_dataloader):
  File "G:\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 384, in __iter__
    next_batch = next(dataloader_iter)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "G:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "G:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "G:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "G:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\SuperDataset.py", line 193, in __getitem__
    self.class_dict.pop(concept_key)
```

Attempted fix by me:

```
            if concept_key in self.class_dict:
                self.class_dict.pop(concept_key)
```

Just leads to this :( 

```
raceback (most recent call last):
  File "G:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 981, in main
    for step, batch in enumerate(train_dataloader):
  File "G:\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 384, in __iter__
    next_batch = next(dataloader_iter)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "G:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "G:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "G:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "G:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\SuperDataset.py", line 156, in __getitem__
    concept_key = list(self.instance_dict)[c_index]
IndexError: list index out of range
```

**Comment by leppie** [comment]
When using prior classification, I can still keep Dont cache latents disabled, but need to drop batch size to 1.

**Comment by d8ahazard** [comment]
Do an update and try now, please. I've reworked the dataset to be less finnicky.

**Comment by leppie** [comment]
> Do an update and try now, please. I've reworked the dataset to be less finnicky.

Was already on it :D Working now both cases. 

I reapplied my removal of cleanup calls as above as I have seen no side-effects, except the pauses caused by it. Once the training starts it stays pretty solid. 

Still good with batch size of 3 if I dont use prior. Not sure why I have to revert to 1 when using prior. Perhaps the values to be compared can be computed before a batch and then moved to RAM, and retrieved as needed? Or is that what cache latents does?

**Comment by leppie** [comment]
> Grab me a fresh error log when it breaks using a batch size > than one with prior enabled, please.

It is an OOM. Sorry if I did not mention it before :D 

With luck I had it running at batch size 2 just now with 26 images. But even taking it down to 1 image, still fails with OOM.  

Still works fine with batch size = 1 in all scenarios. 

Was just feeling there might be an optimization scenario here, probably feeling incorrect :D

**Comment by d8ahazard** [comment]
> > Grab me a fresh error log when it breaks using a batch size > than one with prior enabled, please.
> 
> It is an OOM. Sorry if I did not mention it before :D
> 
> With luck I had it running at batch size 2 just now with 26 images. But even taking it down to 1 image, still fails with OOM.
> 
> Still works fine with batch size = 1 in all scenarios.
> 
> Was just feeling there might be an optimization scenario here, probably feeling incorrect :D
> 
> Edit: Correct me if I am wrong, a latent set for an image should just be 768x8 bytes, right? So even a 100 should bare take up space.

I'm far from an expert on this stuff, but I think it's more than 768x8 bytes. Each image gets transformed to a tensor, has it's pixel values and input id's loaded to vram, and their latents converted and cached. 

![image](https://user-images.githubusercontent.com/1633844/204648585-76fe21c9-85b3-4b02-978c-02c88f5a7e28.png)

**Comment by leppie** [comment]
> I'm far from an expert on this stuff, but I think it's more than 768x8 bytes.

I think I might have confused it with embeddings/token space. 🤡 

Marking this as closed now. Will do so more testing without the cleanup calls and submit a PR.

Thanks for fixing.
