### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by entmike** [d8ahazard/sd_dreambooth_extension#37]
Another bug here.  When setting preview images to something higher (since that is still bugged out), I get this error on the first checkpoint progress save:

```
Traceback (most recent call last):
  File "/home/stable/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/home/stable/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/home/stable/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "/home/stable/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 763, in main
    encoder_hidden_states = text_encoder(batch["input_ids"])[0]
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 722, in forward
    return self.text_model(
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 643, in forward
    encoder_outputs = self.encoder(
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 567, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 563, in custom_forward
    return module(*inputs, output_attentions)
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 317, in forward
    hidden_states, attn_weights = self.self_attn(
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 257, in forward
    attn_output = torch.bmm(attn_probs, value_states)
RuntimeError: expected scalar type Half but found Float
```

**Comment by entmike** [comment]
> i have the same error with the latest version - using a custom 1.5 with updated VAE though.

I am using updated VAE 86400 whatever it's called and vanilla SD 1.5.  I had to modify those lines I mentioned for it to work at all.

**Comment by Dawgmastah** [comment]
> It appears these 2 lines in `train_dreambooth.py` cause this problem for me:
> 
> ```python
>                             unet=accelerator.unwrap_model(unet).to(torch.float16),
>                             text_encoder=text_enc_model.to(torch.float16),
> ```
> 
> If I remove `to(torch.float16`, the problem stops. My model was initially created from the SD 1.5 checkpoint, which I do not know if it is fp16 or not, or if that's even part of the root cause. Anyways, just wanted to report it.

Can confirm doing these changes at least allows for the training to continue , even though error in console is still:

Exception saving preview: tensors used as indices must be long, byte or bool tensors

Testing on vanilla 1.4 as base

**Comment by patrickmros** [comment]
> It appears these 2 lines in `train_dreambooth.py` cause this problem for me:
> 
> ```python
>                             unet=accelerator.unwrap_model(unet).to(torch.float16),
>                             text_encoder=text_enc_model.to(torch.float16),
> ```
> 
> If I remove `to(torch.float16`, the problem stops. My model was initially created from the SD 1.5 checkpoint, which I do not know if it is fp16 or not, or if that's even part of the root cause. Anyways, just wanted to report it.

In the current version the lines are already changed to 

```python
unet=accelerator.unwrap_model(unet),`
`text_encoder=text_enc_model,
 ```

Still got the "RuntimeError: expected scalar type Half but found Float" problem" in Line 257 of modeling_clip.py on my RTX3060.

**Comment by sgsdxzy** [comment]
I think the problem is here in train_dreambooth.py:
```
    # Move text_encode and vae to gpu.
    # For mixed precision training we cast the text_encoder and vae weights to half-precision
    # as these models are only used for inference, keeping weights in full precision is not required.
    vae.to(accelerator.device, dtype=weight_dtype)
    if not args.train_text_encoder:
        text_encoder.to(accelerator.device, dtype=weight_dtype)
```
you need to change `text_encoder.to(accelerator.device, dtype=weight_dtype)` to `text_encoder.to(accelerator.device)`
It is safe to use fp32 here: if you need to train encoder, it is not converted to fp16 anyhow; if you use mixed precision, do not train encoder and cache latents, the encoder is unloaded immediately after latents are calculated anyhow so the vram usage is not a concern.

**Comment by patrickmros** [comment]
> you need to change `text_encoder.to(accelerator.device, dtype=weight_dtype)` to `text_encoder.to(accelerator.device)` It is safe to use fp32 here: if you need to train encoder, it is not converted to fp16 anyhow; if you use mixed precision, do not train encoder and cache latents, the encoder is unloaded immediately after latents are calculated anyhow so the vram usage is not a concern.

This creates the next error:

`RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same`

**Comment by sgsdxzy** [comment]
> > you need to change `text_encoder.to(accelerator.device, dtype=weight_dtype)` to `text_encoder.to(accelerator.device)` It is safe to use fp32 here: if you need to train encoder, it is not converted to fp16 anyhow; if you use mixed precision, do not train encoder and cache latents, the encoder is unloaded immediately after latents are calculated anyhow so the vram usage is not a concern.
> 
> This creates the next error:
> 
> `RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same`

Do you check do not cache latents? Another fix might be required if not caching latents.

**Comment by patrickmros** [comment]
> > > you need to change `text_encoder.to(accelerator.device, dtype=weight_dtype)` to `text_encoder.to(accelerator.device)` It is safe to use fp32 here: if you need to train encoder, it is not converted to fp16 anyhow; if you use mixed precision, do not train encoder and cache latents, the encoder is unloaded immediately after latents are calculated anyhow so the vram usage is not a concern.
> > 
> > 
> > This creates the next error:
> > `RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same`
> 
> Do you check do not cache latents? Another fix might be required if not caching latents.

I have checked:

[ ] Use CPU only
[x] Don't cache latents
[ ] Train Text Encoder
[x] Use 8bit Adam
[ ] Center Crop
[x] Gradient Checkpointing
[ ] Scale Learning Rate

**Comment by sgsdxzy** [comment]
> > > > you need to change `text_encoder.to(accelerator.device, dtype=weight_dtype)` to `text_encoder.to(accelerator.device)` It is safe to use fp32 here: if you need to train encoder, it is not converted to fp16 anyhow; if you use mixed precision, do not train encoder and cache latents, the encoder is unloaded immediately after latents are calculated anyhow so the vram usage is not a concern.
> > > 
> > > 
> > > This creates the next error:
> > > `RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same`
> > 
> > 
> > Do you check do not cache latents? Another fix might be required if not caching latents.
> 
> I have checked:
> 
> [ ] Use CPU only [x] Don't cache latents [ ] Train Text Encoder [x] Use 8bit Adam [ ] Center Crop [x] Gradient Checkpointing [ ] Scale Learning Rate

Uncheck Don't cache latents, at least that works for now.

**Comment by patrickmros** [comment]
> Uncheck Don't cache latents, at least that works for now.

I already tried this, it's not working either. I don't know what to do anymore since it seems like nobody than me is having this problem.

**Comment by sgsdxzy** [comment]
> > Uncheck Don't cache latents, at least that works for now.
> 
> I already tried this, it's not working either. I don't know what to do anymore since it seems like nobody except me is having this problem.

Are you using a 10xx graphics card or earlier? I think some of the code only run on 20xx and later series, but don't have the time/card to check.

**Comment by patrickmros** [comment]
No, i'm using a RTX3060 with 12GB RAM. Everything should be working...

**Comment by Jonseed** [comment]
I also have RTX3060 12GB, and I'm seeing the same error about the expected scalar type... I haven't tried editing any files.

**Comment by patrickmros** [comment]
> > No, i'm using a RTX3060 with 12GB RAM. Everything should be working...
> 
> ![image](https://user-images.githubusercontent.com/1655353/200870071-9554c390-84f0-46bc-b8c0-5e1d9da9890c.png) Yeah, strange, you should be using the same config as me, right?

yes, exactly this! 





> I also have RTX3060 12GB, and I'm seeing the same error about the expected scalar type... I haven't tried editing any files.

that's strange. but now I know that I'm not the only one.

**Comment by Jonseed** [comment]
Does the server need a restart after editing the files?

**Comment by sgsdxzy** [comment]
Yes, try completely restrart webui.
Also try activate the virtual env, run accelerate-config.exe and answer the questions, especially the one to use fp16.

**Comment by Jonseed** [comment]
After editing the file to delete the dtype=weight_dtype part, and restarting the webui server, it cached latents fine, but then when it got to the training part it threw a divide by zero error:

```
train_dreambooth.py", line 871, in main
    save_img = not global_step % args.save_preview_every
ZeroDivisionError: integer division or modulo by zero
```

**Comment by sgsdxzy** [comment]
> After editing the file to delete the dtype=weight_dtype part, and restarting the webui server, it cached latents fine, but then when it got to the training part it threw a divide by zero error:
> 
> ```
> train_dreambooth.py", line 871, in main
>     save_img = not global_step % args.save_preview_every
> ZeroDivisionError: integer division or modulo by zero
> ```

That the image preview bug, just set "Generate a preview image every N steps, 0 to disable" to some really large value, before it is fixed.

**Comment by patrickmros** [comment]
> 



> After editing the file to delete the dtype=weight_dtype part, and restarting the webui server, it cached latents fine, but then when it got to the training part it threw a divide by zero error:
> 
> ```
> train_dreambooth.py", line 871, in main
>     save_img = not global_step % args.save_preview_every
> ZeroDivisionError: integer division or modulo by zero
> ```

oh jeah! i forgot about that!

I solved it by setting "Save a checkpoint every N steps, 0 to disable" to my "training steps" size.

**Comment by Jonseed** [comment]
running through accelerate-config... do I want to use DeepSpeed?

**Comment by sgsdxzy** [comment]
No, I think deepspeed is not working yet. On the other hand once we figure out how to use it, it can reduce vram usage to 8G by offloading model to ram, enabing more cards to train.

**Comment by Jonseed** [comment]
> > 
> 
> > After editing the file to delete the dtype=weight_dtype part, and restarting the webui server, it cached latents fine, but then when it got to the training part it threw a divide by zero error:
> > ```
> > train_dreambooth.py", line 871, in main
> >     save_img = not global_step % args.save_preview_every
> > ZeroDivisionError: integer division or modulo by zero
> > ```
> 
> oh jeah! i forgot about that!
> 
> I solved it by setting "Save a checkpoint every N steps, 0 to disable" to my "training steps" size.

Still gives me a divide by zero error when setting this to the same as the training steps size...

**Comment by patrickmros** [comment]
> > > 
> > 
> > 
> > > After editing the file to delete the dtype=weight_dtype part, and restarting the webui server, it cached latents fine, but then when it got to the training part it threw a divide by zero error:
> > > ```
> > > train_dreambooth.py", line 871, in main
> > >     save_img = not global_step % args.save_preview_every
> > > ZeroDivisionError: integer division or modulo by zero
> > > ```
> > 
> > 
> > oh jeah! i forgot about that!
> > I solved it by setting "Save a checkpoint every N steps, 0 to disable" to my "training steps" size.
> 
> Still gives me a divide by zero error when setting this to the same as the training steps size...

Wait - maybe it's not the exact error. try setting your preview image count to something high like sgsdxzy mentioned before.

**Comment by Jonseed** [comment]
That was it... It's finally training!

**Comment by zark119** [comment]
> That was it... It's finally training!

could you please share the settings? I also have a 3060 12gb card..

**Comment by Jonseed** [comment]
@zark119 I made the file edit noted to delete "dtype=weight_dtype", restarted server, and unchecked don't cache latents, unchecked train text encoder, and switched mixed precision to fp16, and set generate preview to a really high number, it's finally training. Ask me about any other setting, and I'll let you know.

**Comment by Jonseed** [comment]
I also set it to save a checkpoint at the same number as my training steps.

**Comment by Jonseed** [comment]
It's not ideal Dreambooth training, since I won't get intermediate checkpoints, and can't see previews along the way, but it is at least working...

**Comment by Jonseed** [comment]
Not training the text encoder might also degrade quality, I don't know...

**Comment by zark119** [comment]
It works! Thank you! 
![image](https://user-images.githubusercontent.com/113127641/200889021-a8536f5f-68e9-4ef0-8d1f-e9127bd13cd6.png)

**Comment by mykeehu** [comment]
> I think the problem is here in train_dreambooth.py:
> 
> ```
>     # Move text_encode and vae to gpu.
>     # For mixed precision training we cast the text_encoder and vae weights to half-precision
>     # as these models are only used for inference, keeping weights in full precision is not required.
>     vae.to(accelerator.device, dtype=weight_dtype)
>     if not args.train_text_encoder:
>         text_encoder.to(accelerator.device, dtype=weight_dtype)
> ```
> 
> you need to change `text_encoder.to(accelerator.device, dtype=weight_dtype)` to `text_encoder.to(accelerator.device)` It is safe to use fp32 here: if you need to train encoder, it is not converted to fp16 anyhow; if you use mixed precision, do not train encoder and cache latents, the encoder is unloaded immediately after latents are calculated anyhow so the vram usage is not a concern.

Please make a Pull request to include it in the patch, otherwise git won't update it if I manually change the file! Thanks in advance and solution!

**Comment by Jonseed** [comment]
Ok, once it got to the end of training I got this error:

```
Traceback (most recent call last):
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 601, in _get_config_dict
    resolved_config_file = cached_path(
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 300, in cached_path
    raise ValueError(f"unable to parse {url_or_filename} as a URL or as a local path")
ValueError: unable to parse F:\repos\auto111\stable-diffusion-webui\models\dreambooth\training1\working\config.json as a URL or as a local path

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\repos\auto111\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "F:\repos\auto111\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 909, in main
    save_weights(lifetime_step, save_model, save_img)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 766, in save_weights
    text_enc_model = CLIPTextModel.from_pretrained(args.working_dir, subfolder="text_encoder")
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 1764, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\configuration_clip.py", line 126, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 553, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 634, in _get_config_dict
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like F:\repos\auto111\stable-diffusion-webui\models\dreambooth\training1\working is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

Steps: 100%|██████████| 2000/2000 [32:19<00:00,  1.03it/s, loss=0.188, lr=5e-6]
```

What does that mean? Did it not save the checkpoint at the end?

**Comment by Jonseed** [comment]
I tried creating a config.json file with the appropriate values that matched what I put into the UI, and restart training, and I get this error:

```Trying to parse: F:\repos\auto111\stable-diffusion-webui\models\dreambooth\training1\working\config.json
Unable to load concepts as JSON, trying as file: Expecting value: line 1 column 1 (char 0)```

**Comment by Jonseed** [comment]
do Windows paths need to be entered a certain way in the config.json file?

**Comment by Jonseed** [comment]
It's just one error after another, isn't it? So, after making a valid config.json file, and redoing the training, I got this error at the end of training:

```
Traceback (most recent call last):
  File "F:\repos\auto111\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "F:\repos\auto111\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 909, in main
    save_weights(lifetime_step, save_model, save_img)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 766, in save_weights
    text_enc_model = CLIPTextModel.from_pretrained(args.working_dir, subfolder="text_encoder")
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 1764, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\configuration_clip.py", line 129, in from_pretrained
    if config_dict.get("model_type") == "clip":
AttributeError: 'list' object has no attribute 'get'

Steps: 100%|██████████| 2000/2000 [32:10<00:00,  1.04it/s, loss=0.188, lr=5e-6]
```

Looks like it might be something about the text encoder, but I did not select to train the text encoder...

**Comment by sgsdxzy** [comment]
I think we should split different issues to different threads, allowing to focus on and fix one at a time.

**Comment by zark119** [comment]
It looks like some ppl with 3060 12gb card maked it works.
https://www.reddit.com/r/StableDiffusion/comments/yqm9xv/how_to_use_dreambooth_in_automatic1111_in_10/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button
