### ISSUE TITLE
Error loading script: api.py THE SOLUTION

### ISSUE THREAD

**Issue by wilzamguerrero** [d8ahazard/sd_dreambooth_extension#375]
Hi thansk for this extension i have this problem

Error loading script: api.py
Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
module = script_loading.load_module(scriptfile.path)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
compiled = compile(text, path, 'exec')
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 14
db_half_model: bool = False,
^
SyntaxError: invalid syntax

the problem is in the file api adn have an error in the api script the solution is this thanks

this 

class DreamboothParameters(BaseModel):
    db_half_model: bool = False,
    db_use_concepts: bool = False,
    db_pretrained_model_name_or_path: str

for

class DreamboothParameters(BaseModel):
    db_half_model: bool = False
    db_use_concepts: bool = False
    db_pretrained_model_name_or_path: str

**Comment by unnamedplugins** [comment]
Please create an issue using the issue template, or if you wish to suggest a solution to the problem please create a pull request to the repository.

To properly create a bug report:
![image](https://user-images.githubusercontent.com/79282950/205079752-b3a8700b-bf2c-4aed-8396-7c22883706d2.png)

**Comment by d8ahazard** [comment]
> Please create an issue using the issue template, or if you wish to suggest a solution to the problem please create a pull request to the repository.
> 
> To properly create a bug report: ![image](https://user-images.githubusercontent.com/79282950/205079752-b3a8700b-bf2c-4aed-8396-7c22883706d2.png)

Bless your heart. Want me to make you a contributor so you can close issues like this for me as well? :P

**Comment by unnamedplugins** [comment]
> > Please create an issue using the issue template, or if you wish to suggest a solution to the problem please create a pull request to the repository.
> > To properly create a bug report: ![image](https://user-images.githubusercontent.com/79282950/205079752-b3a8700b-bf2c-4aed-8396-7c22883706d2.png)
> 
> Bless your heart. Want me to make you a contributor so you can close issues like this for me as well? :P

I'd be fine with that - wouldn't mind getting in touch on discord or something as well to discuss some code changes.  You can find me on the official stablediffusion discord using the same username (but with an underscore between the words) if that sounds good.

**Comment by wilzamguerrero** [comment]
> Please create an issue using the issue template, or if you wish to suggest a solution to the problem please create a pull request to the repository.
> 
> To properly create a bug report: ![image](https://user-images.githubusercontent.com/79282950/205079752-b3a8700b-bf2c-4aed-8396-7c22883706d2.png)


well was working but know dont work again with other problems i try to fix
