### ISSUE TITLE
Says the packages not installed while they are

### ISSUE THREAD

**Issue by anastasiuspernat** [d8ahazard/sd_dreambooth_extension#379]
On my end on start the dream booth extension displays that ``diffusers`` and ``xformers`` have the wrong version. But I do have ``diffusers 0.9.0`` and ``xformers 0.0.14.dev0``. 

So I checked the code - in ``requirements.txt`` the line says `diffusers[torch]` so the parser in ``install.py`` doesn't parse it as just ``diffusers``.
Also ``xformers`` are added later in the ``install.py`` so they don't have their required version set.

Maybe I'm wrong why it happens! Just tried to pinpoint the problem. I definitely have all the packages installed.

**Comment by d8ahazard** [comment]
I blame the windows console.

Originally, I had a lovely checkbox to indicate "right version installed", I think an asterisk for "version installed is OK/doesn't matter", and an exclaimation point for "This is wrong and bad things will happen". 

Your versions are fine, I just haven't figured out how to make it show a + with diffusers. But unless you see a !, you're good.
