### ISSUE TITLE
Request: Backup db_config.json when training is (re)started

### ISSUE THREAD

**Issue by leppie** [d8ahazard/sd_dreambooth_extension#392]
I have trying to recreate a model I did a while back, but I know I made various changes when I was making as I was just messing around. 

Bad part is that it came out really well, and I cannot for the life of me get anywhere near it again.

Maybe something like `db_config.revision.json` in the `logging` or a `backup` dir.

**Comment by d8ahazard** [comment]
Another one I've been thinking of as being potentially useful...

**Comment by d8ahazard** [comment]
Implemented with e5908ab.
