### ISSUE TITLE
AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing'

### ISSUE THREAD

**Issue by entmike** [d8ahazard/sd_dreambooth_extension#40]
After your latest commit (try...except preview wrapping), now when I try to start training, I get this one:

```
Traceback (most recent call last):
  File "/home/stable/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/home/stable/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/home/stable/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "/home/stable/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 563, in main
    unet.enable_gradient_checkpointing()
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing'
```

**Comment by entmike** [comment]
Update, it appears https://github.com/d8ahazard/sd_dreambooth_extension/commit/edcae967576b2bc892b26602a5a05f7b214187a7 broke this because of the `diffusers` change in `requirements.txt`.  If I change it back to `diffusers==0.7.2`, this error goes away.

**Comment by rehaldinho64** [comment]
Changing the diffusers version didn't work for me. Switching from Python version 3.10 to 3.9 worked.

**Comment by Jonseed** [comment]
I'm also seeing this error on the latest commit 2eb125e, which installs diffusers 0.3.0. Going to try to change diffusers back to 0.7.2

**Comment by d8ahazard** [comment]
I'm going to close this, as I believe this was related to issues with installing the plugin. Feel free to open a new issue with the Template if not so I can better diagnose the issue. Tx.

**Comment by phutngo** [comment]
So what's the solution to this problem then? 

`Returning` result: Exception training model: 'UNet2DConditionModel' object has no attribute 'params'`

**Comment by travisbeard** [comment]
I am getting this as well.   Using Python 3.10

**Comment by harrywang** [comment]
> Changing the diffusers version didn't work for me. Switching from Python version 3.10 to 3.9 worked.

I ran into the same problem with Python 3.8.x and 3.9.11 worked.

**Comment by threewood1** [comment]
I also got somthing wrong like this:

AttributeError: 'UNetModel' object has no attribute 'enable_gradient_checkpointing'. Did you mean: '_return_value'? 

and I changed python3.10.0 to python3.9.11, but it didn't work

**Comment by whcjb** [comment]
DSUNet object has no attribute 'add_embedding' in diffusers/stable-diffusion-xl-1.0-inpainting-0.1
