### ISSUE TITLE
Pytorch should be exclude from requirements.txt

### ISSUE THREAD

**Issue by OedoSoldier** [d8ahazard/sd_dreambooth_extension#400]
I'm using torch 1.13 and this will cause uninstall torch 1.13 and install 1.12.1 instead.

**Comment by unnamedplugins** [comment]
Please create an issue using the issue template, or if you wish to suggest a solution to the problem please create a pull request to the repository.  You need to include information that describes why this is a problem and negative the effect it has.  The code in this repository may require torch 1.12.1 for particular reasons so just saying "it should do this" doesn't provide sufficient rationale for why this ticket should be worked on.  If you have tried the change in requirements.txt in your local system and it is working fine, you can submit a pull request to be reviewed.

If you'd like to properly create a bug report:
![image](https://user-images.githubusercontent.com/79282950/205079752-b3a8700b-bf2c-4aed-8396-7c22883706d2.png)

**Comment by OrochiZ** [comment]
大江户战士?
8bit adam must use 1.12

**Comment by d8ahazard** [comment]
Fixed with [e7b2754](https://github.com/d8ahazard/sd_dreambooth_extension/commit/e7b2754a6c1917e1934256e9b4bb37464a80d67c)
