### ISSUE TITLE
Initializing dreambooth training... errors

### ISSUE THREAD

**Issue by wilzamguerrero** [d8ahazard/sd_dreambooth_extension#401]
Sorry i remove the messaje, i hope all are fine, i have this problem, at the moment to run dreambooth in automatic in colab, maybe can help me with this problem.

Python 3.8.15 (default, Oct 12 2022, 19:14:39) 
[GCC 7.5.0]
Commit hash: 46b0d230e7c13e247eabb22e1103ce512e7ed6b1
Installing requirements for Web UI

Checking Dreambooth requirements...
Dreambooth revision is c2fc683ebcf4db23cfce22626aa6a7b565994c96
[+] bitsandbytes version 0.35.0 installed.
[ ] diffusers version 0.9.0 installed.
[+] transformers version 4.21.0 installed.
[ ] torch version 1.12.1+cu116 installed.
[ ] torchvision version 0.13.1+cu116 installed.
[ ] xformers version 0.0.13 installed.

Launching Web UI with arguments: --ckpt-dir=/content/sample_data --xformers --theme=dark --ckpt=/content/sample_data/v1-5-fp16.ckpt --share --api 
WARNING:root:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [a2a802b2] from /content/sample_data/v1-5-fp16.ckpt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://77abf464e56cf0af.gradio.app/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Returning [0.9, 0.999, 1e-08, 0.01, 'default', False, '', 1, True, False, None, True, 1.72e-06, 'constant', 0, 1, 75, 1000, 'fp16', '/content/sample_data/stable-diffusion-webui/models/dreambooth/zaumarzz/working', True, 1, True, '', 1, 512, 0, 1, 500, 500, False, 'euler-ancestral', 'v1-5-fp16.ckpt [a2a802b2]', 1, True, True, False, False, False, False, '', 7.5, 40, '', '', '', 'Description', '/content/sample_data/zaumarzz', 'zaumarzz', '', -1, 1, 0, -1, 7.5, 40, '', '', '', '', 7.5, 60, '', '', '', 'Description', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', '', 7.5, 60, '', '', '', 'Description', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', 'Loaded config.']
Concept 0 class dir is /content/sample_data/stable-diffusion-webui/models/dreambooth/zaumarzz/classifiers_0
Starting Dreambooth training...
 Cleanup completed. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

 Allocated 0.0/2.0GB 
 Reserved: 0.0/2.0GB 

Initializing dreambooth training...
Patching transformers to fix kwargs errors.
Error completing request
Arguments: ('zaumarzz', False) {}
Traceback (most recent call last):
  File "/content/sample_data/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/sample_data/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/sample_data/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 509, in start_training
    from extensions.sd_dreambooth_extension.dreambooth.train_dreambooth import main
  File "/content/sample_data/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 432, in <module>
    def main(args: DreamboothConfig, memory_record) -> tuple[DreamboothConfig, dict, str]:
TypeError: 'type' object is not subscriptable

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

**Comment by SaimanSndl** [comment]
the same problem..

**Comment by jackdjent123** [comment]
![image](https://user-images.githubusercontent.com/103981007/205477782-87027db3-b460-418b-bde9-645e54457b4d.png)
Me too, im furious that i cant get it too work

**Comment by telemole** [comment]
same issue - my first time trying to run dreambooth so I'm glad I just wasn't failing to read the instructions etc ;) Hope some smart folks here have the answer - would love to try this method vs text inversion - such cool stuff.

**Comment by Benrflanders** [comment]
@wilzamguerrero I was also having this problem and I was able to solve it by upgrading my python from 3.8.5 to 3.10.6 

You can check your python version by running `python --version` 

I'm using anaconda, so upgrading python for a single environment worked as follows:
1. activate your environment
`conda activate [name of your conda environment]`
2. upgrade python
`conda install -c anaconda python=3.10.6`

**Comment by d8ahazard** [comment]
Try with the newest version, please. I've fixed a bunch of things, at the very least, the log should tell you what the actual problem is now.

**Comment by pacient** [comment]
@d8ahazard After the update the Dreambooth completely disappeared from the toolbar
![Screenshot 2022-12-06 at 09 45 40](https://user-images.githubusercontent.com/19490170/205863487-c515350b-ef80-4ab0-aec0-b3c92b4d47d0.png)

**Comment by wilzamguerrero** [comment]
> @wilzamguerrero I was also having this problem and I was able to solve it by upgrading my python from 3.8.5 to 3.10.6
> 
> You can check your python version by running `python --version`
> 
> I'm using anaconda, so upgrading python for a single environment worked as follows:
> 
> 1. activate your environment
>    `conda activate [name of your conda environment]`
> 2. upgrade python
>    `conda install -c anaconda python=3.10.6`
> 
> EDIT: This fix pertains to the error line `TypeError: 'type' object is not subscriptable` It looks like Python subscribable type definitions were added in version 3.10. If you don't see the error `TypeError: 'type' object is not subscriptable` in your log, then this solution seems unlikely to help. I'll keep looking at the log @jackdjent123 posted and see if I can find a separate solution.

Hi i install this version of python in colab and all looks great but when i run sd dont let me install xformers
ERROR: xformers-0.0.15.dev0+cu11.2-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.
ERROR: xformers-0.0.15.dev0_4c06c79.d20221201-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by wilzamguerrero** [comment]
> Try with the newest version, please. I've fixed a bunch of things, at the very least, the log should tell you what the actual problem is now.

Python 3.8.15 (default, Oct 12 2022, 19:14:39) 
[GCC 7.5.0]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Installing gfpgan
Installing clip
Installing open_clip
Installing xformers
Cloning Stable Diffusion into repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories/taming-transformers...
Cloning K-diffusion into repositories/k-diffusion...
Cloning CodeFormer into repositories/CodeFormer...
Cloning BLIP into repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI
Cloning midas into repositories/midas...


#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.8.15 (default, Oct 12 2022, 19:14:39) 
[GCC 7.5.0]
Dreambooth revision: 88cc50ace470580842b519115545b9a08ebe115e
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers[torch] version 0.10.0.dev0 installed.
[+] transformers version 4.21.0 installed.
[ ] xformers version 0.0.13 installed.
[ ] torch version 1.13.0+cu116 installed.
[ ] torchvision version 0.14.0+cu116 installed.
#######################################################################################################

Launching Web UI with arguments: --share --api --xformers --ckpt-dir= --ckpt= --cors-allow-origins=https://www.painthua.com --theme=dark
/usr/local/lib/python3.8/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
WARNING:root:WARNING: /usr/local/lib/python3.8/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
WARNING:root:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Checkpoint in --ckpt argument not found (Possible it was moved to /content/sample_data/stable-diffusion-webui/models/Stable-diffusion: 
Dreambooth API layer loaded
Error loading script: main.py
Traceback (most recent call last):
  File "/content/sample_data/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/sample_data/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/sample_data/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 5, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.diff_to_sd import compile_checkpoint
  File "/content/sample_data/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 214, in <module>
    def convert_text_enc_state_dict_v20(text_enc_dict: dict[str, torch.Tensor]):
TypeError: 'type' object is not subscriptable

Checkpoint v1-5-fp16.ckpt [a2a802b2] not found; loading fallback content/sample_data/stable-diffusion-webui/models/Stable-diffusion/v1-5-fp16.ckpt [a2a802b2]
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading vocab.json: 100% 939k/939k [00:00<00:00, 1.86MB/s]
Downloading merges.txt: 100% 512k/512k [00:00<00:00, 1.23MB/s]
Downloading special_tokens_map.json: 100% 389/389 [00:00<00:00, 330kB/s]
Downloading tokenizer_config.json: 100% 905/905 [00:00<00:00, 717kB/s]
Downloading config.json: 100% 4.41k/4.41k [00:00<00:00, 3.72MB/s]
Downloading pytorch_model.bin: 100% 1.59G/1.59G [00:27<00:00, 61.6MB/s]
Loading weights [a2a802b2] from /content/sample_data/stable-diffusion-webui/models/Stable-diffusion/v1-5-fp16.ckpt
Applying xformers cross attention optimization.
Model loaded.
Checkpoint v1-5-fp16.ckpt [a2a802b2] not found; loading fallback content/sample_data/stable-diffusion-webui/models/Stable-diffusion/v1-5-fp16.ckpt [a2a802b2]
Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://e7a36b98549562bb.gradio.app

---------------------------------------------------------

the same wiht xformers 0.0.15

Python 3.8.15 (default, Oct 12 2022, 19:14:39) 
[GCC 7.5.0]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Cloning Stable Diffusion into repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories/taming-transformers...
Cloning K-diffusion into repositories/k-diffusion...
Cloning CodeFormer into repositories/CodeFormer...
Cloning BLIP into repositories/BLIP...
Installing requirements for Web UI
Cloning midas into repositories/midas...


#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.8.15 (default, Oct 12 2022, 19:14:39) 
[GCC 7.5.0]
Dreambooth revision: 88cc50ace470580842b519115545b9a08ebe115e
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers[torch] version 0.10.0.dev0 installed.
[+] transformers version 4.21.0 installed.
[ ] xformers version 0.0.15.dev0+1515f77.d20221130 installed.
[ ] torch version 1.13.0+cu116 installed.
[ ] torchvision version 0.14.0+cu116 installed.
#######################################################################################################

Launching Web UI with arguments: --share --api --force-enable-xformers --ckpt-dir= --ckpt=/content/sample_data/v1-5-fp16.ckpt --cors-allow-origins=https://www.painthua.com/ --theme=dark
/usr/local/lib/python3.8/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
WARNING: /usr/local/lib/python3.8/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
Need to compile C++ extensions to get sparse attention support. Please run python setup.py build develop
Dreambooth API layer loaded
Error loading script: main.py
Traceback (most recent call last):
  File "/content/sample_data/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/sample_data/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/sample_data/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 5, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.diff_to_sd import compile_checkpoint
  File "/content/sample_data/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 214, in <module>
    def convert_text_enc_state_dict_v20(text_enc_dict: dict[str, torch.Tensor]):
TypeError: 'type' object is not subscriptable

**Comment by d8ahazard** [comment]
Tupleindex out of range when using the training wiiiizard has been fixed.
