### ISSUE TITLE
About using mount path in dreambooth extension

### ISSUE THREAD

**Issue by nekoyama32767** [d8ahazard/sd_dreambooth_extension#42]
Like other models in webui, if there is a setting or command line options which make "modes/dreambooth" to another path would be pleased.

**Comment by d8ahazard** [comment]
Working on it. I have a PR submitted for the main repo to allow this, you can follow the progress here: 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4488

Once implemented, you can use the same format as the other model paths.

**Comment by d8ahazard** [comment]
Closed, implemented with #169
