### ISSUE TITLE
OOM problem with latest version

### ISSUE THREAD

**Issue by mykeehu** [d8ahazard/sd_dreambooth_extension#437]
`
Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: cb7fc3b591fc5b49d8423518d2062c4f388e71d8
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers[torch] version 0.10.0.dev0 installed.
[+] transformers version 4.21.0 installed.
[ ] xformers version 0.0.14.dev0 installed.
[ ] torch version 1.12.1+cu116 installed.
[ ] torchvision version 0.13.1+cu116 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**
I can't continue training my model because any optimization I choose, I get an OOM error. Replacing the cuda may cause problems or there is no xformers loading. I cannot continue the previous training because 12 GB of memory seems to be insufficient. The parameters are the **same as I trained with before** (see json below).

**Provide logs**

Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Using magick windows DLL!
CUDA SETUP: Loading binary H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
 Cleanup completed.
 Allocated: 0.2GB
 Reserved: 0.2GB

 Scheduler, EMA Loaded.
 Allocated: 7.1GB
 Reserved: 7.2GB

***** Running training *****
  Num examples = 10
  Num batches each epoch = 10
  Num Epochs = 4
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 40
   Training settings: CPU: False Adam: True, Prec: fp16, Grad: True, TextTr: True EM: True, LR: 5e-06
 Allocated: 7.1GB
 Reserved: 7.2GB

Steps:   0%|                                            | 0/40 [00:00<?, ?it/s] Exception while training: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 12.00 GiB total capacity; 11.17 GiB already allocated; 0 bytes free; 11.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 11.2GB
 Reserved: 11.3GB

Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 975, in main
    optimizer.step()
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\accelerate\optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\optim\lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\optim\optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\optim\optimizer.py", line 263, in step
    self.init_state(group, p, gindex, pindex)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\optim\optimizer.py", line 401, in init_state
    state["state2"] = torch.zeros_like(
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 12.00 GiB total capacity; 11.17 GiB already allocated; 0 bytes free; 11.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 CLEANUP:
 Allocated: 11.2GB
 Reserved: 11.3GB

 Cleanup completed.
 Allocated: 11.2GB
 Reserved: 11.3GB

 Cleanup Complete.
 Allocated: 11.2GB
 Reserved: 11.3GB

Steps:   0%|                                            | 0/40 [00:05<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 7.8GB

Memory output: {}
 Restored system models.
 Allocated: 2.0GB
 Reserved: 7.8GB

Returning result: Training finished. Total lifetime steps: 660

**Environment**

What OS? Windows 10

If Windows - WSL or native? Native

What GPU are you using? RTX 3060 12 GB

**Screenshots/Config**
{
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_epsilon": 1e-08,
    "adam_weight_decay": 0.01,
    "attention": "xformers",
    "center_crop": false,
    "concepts_path": "",
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "half_model": true,
    "hflip": false,
    "learning_rate": 5e-06,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "max_grad_norm": 1,
    "max_token_length": 75,
    "max_train_steps": 40,
    "mixed_precision": "fp16",
    "model_dir": "H:\\Stable-Diffusion-Automatic\\stable-diffusion-webui\\models\\dreambooth\\1style",
    "model_name": "1style",
    "not_cache_latents": false,
    "num_train_epochs": 1,
    "pad_tokens": true,
    "pretrained_model_name_or_path": "H:\\Stable-Diffusion-Automatic\\stable-diffusion-webui\\models\\dreambooth\\1style\\working",
    "pretrained_vae_name_or_path": null,
    "prior_loss_weight": 1,
    "resolution": 512,
    "revision": 660,
    "sample_batch_size": 1,
    "save_class_txt": false,
    "save_embedding_every": 500,
    "save_preview_every": 500,
    "scale_lr": false,
    "src": "model-v1-5-pruned-emaonly.ckpt [81761151]",
    "train_batch_size": 1,
    "train_text_encoder": true,
    "use_8bit_adam": true,
    "use_concepts": false,
    "use_cpu": false,
    "use_ema": true,
    "scheduler": "ddim",
    "v2": false,
    "has_ema": "True",
    "concepts_list": [
        {
            "max_steps": -1,
            "instance_data_dir": "H:\\Stable-Diffusion-Automatic\\Dreambooth\\style10",
            "class_data_dir": "H:\\Stable-Diffusion-Automatic\\Dreambooth\\!classification\\photo style",
            "file_prompt_contents": "Description",
            "instance_prompt": "1style style",
            "class_prompt": "photo style",
            "save_sample_prompt": "1style, a babe in white wedding dress in a restaurant",
            "save_sample_template": "",
            "instance_token": "",
            "class_token": "",
            "num_class_images": 200,
            "class_negative_prompt": "",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "save_sample_negative_prompt": "blurry, fat",
            "n_save_sample": 1,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 40
        }
    ],
    "lifetime_revision": 660
}

**Comment by mykeehu** [comment]
xformers, flas_attention, default optimizer no helped. :( 
I'm happy with the news, but not with the cuda replacement, so I'll have to wait to train again.

**Comment by mykeehu** [comment]
@d8ahazard didn't help :( 
I suspect that the Scheduler is writing 2 GB more than before, something is eating up the VRAM before. Here is the modification log, which is the same as in my post above:

 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Using magick windows DLL!
CUDA SETUP: Loading binary H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
 Cleanup completed.
 Allocated: 0.2GB
 Reserved: 0.2GB

 Scheduler, EMA Loaded.
 Allocated: 7.1GB
 Reserved: 7.2GB

***** Running training *****
  Num examples = 10
  Num batches each epoch = 10
  Num Epochs = 10
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 100
   Training settings: CPU: False Adam: True, Prec: fp16, Grad: True, TextTr: True EM: True, LR: 5e-06
 Allocated: 7.1GB
 Reserved: 7.2GB

Steps:   0%|                                           | 0/100 [00:00<?, ?it/s] Exception while training: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 12.00 GiB total capacity; 11.15 GiB already allocated; 0 bytes free; 11.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 11.2GB
 Reserved: 11.3GB

Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 976, in main
    optimizer.step()
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\accelerate\optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\optim\lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\optim\optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\optim\optimizer.py", line 263, in step
    self.init_state(group, p, gindex, pindex)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\optim\optimizer.py", line 393, in init_state
    state["state1"] = torch.zeros_like(
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 12.00 GiB total capacity; 11.15 GiB already allocated; 0 bytes free; 11.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 CLEANUP:
 Allocated: 11.2GB
 Reserved: 11.3GB

 Cleanup completed.
 Allocated: 11.2GB
 Reserved: 11.3GB

 Cleanup Complete.
 Allocated: 11.2GB
 Reserved: 11.3GB

**Comment by d8ahazard** [comment]
Does it work without EMA? I swapped the model a few days ago for the "official" one, I wonder if that could be it.

**Comment by leppie** [comment]
> I suspect that the Scheduler is writing 2 GB more than before, something is eating up the VRAM before

Do you have 'Show image after N steps' set to anything but 0? I been getting a lot of OOM's due to that lately.

**Comment by mykeehu** [comment]
@leppie I didn't have a problem with that until about a month ago, it's been fixed since then...

**Comment by d8ahazard** [comment]
Just pushed a change reverting the EMA stuff, please try now with it enable and LMK.

**Comment by mykeehu** [comment]
Looks good at a glance, but I missed something in the EMA writeback because I got an error:

Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Using magick windows DLL!
CUDA SETUP: Loading binary H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
 Cleanup completed.
 Allocated: 0.2GB
 Reserved: 0.2GB

 Scheduler, EMA Loaded.
 Allocated: 5.5GB
 Reserved: 5.6GB

***** Running training *****
  Num examples = 10
  Num batches each epoch = 10
  Num Epochs = 5
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 50
   Training settings: CPU: False Adam: True, Prec: fp16, Grad: True, TextTr: True EM: True, LR: 5e-06
 Allocated: 5.5GB
 Reserved: 5.6GB

Steps:   0%|                                            | 0/50 [00:00<?, ?it/s] Exception while training: 'UNet2DConditionModel' object is not iterable
 Allocated: 7.3GB
 Reserved: 11.2GB

Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 987, in main
    ema_unet.step(unet)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 132, in step
    parameters = list(parameters)
TypeError: 'UNet2DConditionModel' object is not iterable

**Comment by d8ahazard** [comment]
One more update, plz. Missed a param.

**Comment by mykeehu** [comment]
@d8ahazard Super, now it seems to be working fine! Thank you!

Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Using magick windows DLL!
CUDA SETUP: Loading binary H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
 Cleanup completed.
 Allocated: 0.2GB
 Reserved: 0.2GB

 Scheduler, EMA Loaded.
 Allocated: 5.5GB
 Reserved: 5.6GB

***** Running training *****
  Num examples = 10
  Num batches each epoch = 10
  Num Epochs = 20
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 200
   Training settings: CPU: False Adam: True, Prec: fp16, Grad: True, TextTr: True EM: True, LR: 5e-06
 Allocated: 5.5GB
 Reserved: 5.6GB

Steps:   0%|     | 0/200 [00:11<?, ?it/s, loss=0.0766, lr=5e-6, vram=7.3/9.5GB] Step 0 completed.
 Allocated: 7.3GB
 Reserved: 9.5GB

Steps:   2%| | 5/200 [00:17<07:41,  2.37s/it, loss=0.0766, lr=5e-6, vram=7.3/9. Step 5 completed.
 Allocated: 7.3GB
 Reserved: 9.5GB
