### ISSUE TITLE
Black Classification Images are being generated

### ISSUE THREAD

**Issue by NagashSzarekh** [d8ahazard/sd_dreambooth_extension#438]
`
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: cb7fc3b591fc5b49d8423518d2062c4f388e71d8
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers[torch] version 0.10.0.dev0 installed.
[+] transformers version 4.21.0 installed.
[!] xformers NOT installed.
[ ] torch version 1.12.1+cu116 installed.
[ ] torchvision version 0.13.1+cu116 installed.
#######################################################################################################
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

After the latest update when generating Class images sometimes solid black images are created. You can see below it created three. May be related to #427 as someone referenced it there. Going to test this by manually making those edits and seeing if the problem still happens.

![image](https://user-images.githubusercontent.com/36505807/205983257-56957900-6862-4b82-ae97-b45ca84aa4d5.png)

**Environment**

What OS?
Windows 10 Pro
If Windows - WSL or native?
native
What GPU are you using?
Titan Xp
**Screenshots/Config**
[db_config.zip](https://github.com/d8ahazard/sd_dreambooth_extension/files/10168926/db_config.zip)

**Comment by Janca** [comment]
I made a patch for this issue, but was closed, I believe it needs to be reopened and merged. #427

**Comment by trihardseven** [comment]
Meanwhile I get all black images lol

**Comment by NagashSzarekh** [comment]
Just an update from my testing. So far after manually making the change from #427 I have created 230 class images with no black squares, during my test before the change I had three black square in 230 class images.

**Comment by NagashSzarekh** [comment]
I am up to 500+ good images now so I am thinking this is fixed with the latest commit
