### ISSUE TITLE
Training finishes at 0 steps

### ISSUE THREAD

**Issue by Joedog6503** [d8ahazard/sd_dreambooth_extension#444]
I don't exactly know if this is a bug of just a failure on my end, sorry for being incompetent...

DiffusionWrapper has 859.52 M params.
Loading weights [a2a802b2] from C:\Users\josep\Desktop\stable-diffusion-webui-master\models\Stable-diffusion\CaeraDenoir.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
auto-sd-paint-ext:INFO: Add --listen to COMMANDLINE_ARGS to enable usage as a remote backend.
Concept 0 class dir is C:\Users\josep\Desktop\stable-diffusion-webui-master\models\dreambooth\CaeraV7\classifiers_0
Starting Dreambooth training...
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Allocated 0.0/2.0GB
 Reserved: 0.0/2.0GB

Initializing dreambooth training...
Patching transformers to fix kwargs errors.
Replace CrossAttention.forward to use default
Checking concept: {'max_steps': -1, 'instance_data_dir': 'C:\\Users\\josep\\Desktop\\stable-diffusion-webui-master\\models\\dreambooth\\CaeraV7', 'class_data_dir': '', 'file_prompt_contents': 'Description', 'instance_prompt': 'CaeraDen', 'class_prompt': 'CaeraDen', 'save_sample_prompt': '', 'save_sample_template': '', 'instance_token': '', 'class_token': '', 'num_class_images': 0, 'class_negative_prompt': '', 'class_guidance_scale': 7.5, 'class_infer_steps': 40, 'save_sample_negative_prompt': '', 'n_save_sample': 1, 'sample_seed': -1, 'save_guidance_scale': 7.5, 'save_infer_steps': 40}
Concept requires 0 images.
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Cleanup completed.
 Allocated: 0.3GB
 Reserved: 0.3GB

 Scheduler, EMA Loaded.
 Allocated: 4.0GB
 Reserved: 4.1GB

***** Running training *****
  Num examples = 17
  Num batches each epoch = 17
  Num Epochs = 471
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 8000
   Training settings: CPU: False Adam: False, Prec: no, Grad: True, TextTr: True EM: False, LR: 1.72e-06
 Allocated: 4.0GB
 Reserved: 4.1GB

Steps:   0%|                                                                                  | 0/8000 [00:00<?, ?it/s] Exception while training: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.09 GiB already allocated; 0 bytes free; 11.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 11.1GB
 Reserved: 11.3GB

Traceback (most recent call last):
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 975, in main
    optimizer.step()
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\accelerate\optimizer.py", line 140, in step
    self.optimizer.step(closure)
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\torch\optim\lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\torch\optim\optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\torch\optim\adamw.py", line 146, in step
    state['exp_avg'] = torch.zeros_like(p, memory_format=torch.preserve_format)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.09 GiB already allocated; 0 bytes free; 11.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 CLEANUP:
 Allocated: 11.1GB
 Reserved: 11.3GB

 Cleanup completed.
 Allocated: 11.1GB
 Reserved: 11.3GB

 Cleanup Complete.
 Allocated: 11.1GB
 Reserved: 11.3GB

Steps:   0%|                                                                                  | 0/8000 [00:05<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Memory output: {}
 Restored system models.
 Allocated: 2.0GB
 Reserved: 2.0GB

Returning result: Training finished. Total lifetime steps: 0

**Comment by VERMANs** [comment]
CUDA out of memory,you should use more memory GPU,I think.

**Comment by leppie** [comment]
Use fp16 and xformers options as well as Adam.

**Comment by Joedog6503** [comment]
neither of these worked

**Comment by mpmo10** [comment]
I have the same issue and my gpu is a 3090 with 24 gb vram..

**Comment by ShakedBaws** [comment]
same issue with 3080 rtx

**Comment by seoeaa** [comment]
Steps:   0%|                                                                                                                                                                                                                                                              | 0/4176 [00:00<?, ?it/s] Exception while training: HIP out of memory. Tried to allocate 26.00 MiB (GPU 0; 15.98 GiB total capacity; 11.35 GiB already allocated; 4.29 GiB free; 11.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_HIP_ALLOC_CONF 
 Allocated: 11.4GB 
 Reserved: 11.6GB

**Comment by d8ahazard** [comment]
> 00<?, ?it/s] Exception while training: HIP out of memory. Tried to allocate 26.00 MiB (GPU 0; 15.98 GiB total capacity; 11.35 GiB already allocated; 4.29 GiB free; 11.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_HIP_ALLOC_CONF
> Allocated: 11.4GB

Try again with the newest version, please. You should be able to train with text encoder on a 12GB GPU, provided you're using 8bit adam, fp16 or bf16 precision, and xformers or flash-attention for memory attention.

**Comment by ffdown** [comment]
4090 KARL! 8bit adam, fp16, and xformers ON and what? everytime..
`RuntimeError: CUDA out of memory. Tried to allocate 9.00 GiB (GPU 0; 23.99 GiB total capacity; 4.22 GiB already allocated; 12.46 GiB free; 8.68 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

![image](https://user-images.githubusercontent.com/95547131/207467185-1c7adf47-d886-4aa6-8c76-1e1f2176d88d.png)

**Comment by entmike** [comment]
I don't think that Dreambooth is unloading the A1111 checkpoint that is autoloaded when starting up.  I placed an empty 0 byte sized .ckpt file in `models/Stable-diffusion` to prevent it from loading stuff into VRAM (there's maybe a better way than that) and that's the only way that I can train on 3090.  If I use image preview, it goes OOM lol.

Linux running headless RTX 3090
128GB RAM
`--xformers` set in CLI, Memory attention set at Default, `bf16` and Use 8bit Adam are enabled.

**Comment by ffdown** [comment]
```
 Actual steps: 10000
   Training settings: CPU: False Adam: True, Prec: fp16, Grad: True, TextTr: True EM: False, LR: 2.1e-06 LORA:False
```
CPU????? where i can change this??

**Comment by KabetzuriBoii** [comment]
i think this is a lost cause, some can use it some can't and the biggest claim is that it has something to do with your windows version. they say you need windows 11 for it to work ;|

**Comment by Thomas-MMJ** [comment]
"windows version. they say you need windows 11 for it to work ;|" - there is a limit on "memory pinning" that is only fixed in windows 11 WSL2 but not windows 10 WSL2, not sure if that is a related bug for this.

**Comment by erikjara** [comment]
@entmike How can I make A1111 recognize an empty .ckpt file? Could you provide the steps to do so? Thank you.

**Comment by d8ahazard** [comment]
So, this is an OOM issue, for which I've done everything possible to fix in the latest revision.

The subsequent comments and discussion are all over the place. 

As such, I'm closing this to tidy things up. @Thomas-MMJ - If you want to discuss/PR memory pinning stuff with checks for the proper windows version, I'd be happy to incorporate.

**Comment by swathi-kumar-github** [comment]
does dreambooth work without a GPU?
