### ISSUE TITLE
terminates on "create model"

### ISSUE THREAD

**Issue by realenuf** [d8ahazard/sd_dreambooth_extension#451]
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Installing requirements for Web UI

Installing requirements for scikit_learn

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
Dreambooth revision: 88cc50ace470580842b519115545b9a08ebe115e
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers[torch] version 0.10.0.dev0 installed.
[+] transformers version 4.21.0 installed.
[ ] xformers version 0.0.15.dev0+189828c.d20221207 installed.
[ ] torch version 1.12.1+cu113 installed.
[ ] torchvision version 0.13.1+cu113 installed.
#######################################################################################################

Launching Web UI with arguments: 
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [81761151] from /media/iwoolf/BigDrive/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading model from checkpoint.
Loading checkpoint...
v1 model loaded.
Creating scheduler...
Converting unet...
Terminated

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes. I can see that the command" pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116" didn't work, so its still cu113.
I uncommented the lines in webui-user-dreambooth.sh
# install command for torch
 export TORCH_COMMAND="pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes, several times. The program terminates, so I don't even have a choice.
**Have you updated Dreambooth to the latest revision?**
git pull says its up to date
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
gut pull says its the latest
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**
I am following instructions from this video, https://www.youtube.com/watch?v=HahKXY7AQ8c
Which match the instructions in the docs https://github.com/d8ahazard/sd_dreambooth_extension#readme
I select Dreambooth, in "Create Model", I type the name "iwoolf3".
I select the source model v1-5-pruned-emaonly.ckpt, and scheduler ddim.
Then I click on "create".

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

There's nothing in /var/crash

**Environment**

What OS?
Ubuntu 22.04.1LTS
If Windows - WSL or native?
not Windows
What GPU are you using?
rtx 3060 12gb

I suspect if I can get help in how to install the correct version of torch with cu116 without conflicts, that this will be fixed.

**Comment by d8ahazard** [comment]
I think the torch version is a red herring, as it's no longer required to use a specific version.

Please try running with the --ckptfix flag, this will tell the extraction routine to use the CPU only.

**Comment by realenuf** [comment]
xformers has disappeared.

./webui.sh --ckptfix
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on iwoolf user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Installing requirements for Web UI

Installing requirements for scikit_learn


#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Dreambooth revision: 88cc50ace470580842b519115545b9a08ebe115e
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[!] diffusers[torch] version 0.11.0.dev0 installed.
[+] transformers version 4.21.0 installed.
[!] xformers NOT installed.
[ ] torch version 1.12.1+cu113 installed.
[ ] torchvision version 0.13.1+cu113 installed.
#######################################################################################################

Launching Web UI with arguments: --ckptfix

WARNING: 
Need to compile C++ extensions to get sparse attention support. Please run python setup.py build develop
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Terminated

**Comment by realenuf** [comment]
The nvidia driver updated in the last system update, and now I can't log in!

**Comment by d8ahazard** [comment]
I'd start from scratch, re-install xformers following the official Auto1111 instructions, and ensure you're on the latest version of the extension.

**Comment by BrahRah** [comment]
I have the same issue with linux mint 21 and the same gpu. My steps are:

-conda create --name automatic python==3.10.6
-conda start automatic
-cd "/home/r2d2/anaconda3/envs/automatic/bin"
-pip install -r "/media/r2d2/4TB/stable-diffusion-webui"/requirements.txt
-pip install open_clip :
ERROR: Could not find a version that satisfies the requirement open_clip (from versions: none)
ERROR: No matching distribution found for open_clip

-pip install open-clip-torch
-pip install clip

-cd SD dir
-python webui.py --xformers
-install dreambooth from extensions tab (checked if uptodate with git pull)
-give name, select 1.5 mode, select euler-ancestral
-press create model : killed

The log:
https://paste.ofcode.org/6uSCLp9k7JZz8XikKz2qb9
