### ISSUE TITLE
Regularization/Class images generator button?

### ISSUE THREAD

**Issue by mykeehu** [d8ahazard/sd_dreambooth_extension#452]
**WHAT** 
I was thinking that at the bottom of the Concepts tabs there should be a button Generate reg./class images so that we could generate such images in advance outside of training.

**WHERE** 
An extra button at the bottom of the Concepts tabs

**HOW** 
This would be a useful solution, because then we could generate regularization/class images without any extra parameters, even outside of training. There would be an extra button on the tab to Generate reg./class images (or similar), and then you could generate such images outside of training into training folders regardless of txt2img parameters.

**Comment by NagashSzarekh** [comment]
I would also like to see a feature like this as I normally like to review the Class images before training starts so I can remove any images that are bad (head cut off, face not visible, etc.). Then I  go in and have it generate them again to bring the total what to what it should be.

**Comment by d8ahazard** [comment]
@mykeehu Yep, on my radar.

Only question is - should there be one button to generate all class images, or make a button within each concept, or...

**Comment by mykeehu** [comment]
I thought of the bottom of the Concept page because each collection may be different. So there can be a button, but you have to take into account which Concept tab is active.

**Comment by NagashSzarekh** [comment]
I would like to be able to generate all Class images for all concepts. Then if I wanted to let it run overnight, I could use the multiple concept tabs to "queue" up multiple classes to be done even if I did not intend really intend on training with them all together.

**Comment by mykeehu** [comment]
Then the solution is simpler: a button, for example, next to Generate ckpt. When you press this button, it checks which tabs are filled with the class images path, the class prompt, and the number of class images greater than zero. If these criteria are met, the images for each tab are generated based on the parameters.

**Comment by d8ahazard** [comment]
Related to #355

**Comment by d8ahazard** [comment]
Added to the latest revision!

**Comment by mykeehu** [comment]
Yes, I saw it, thank you very much! :) I still have to get familiar with the new layout and how it works. :)
