### ISSUE TITLE
Error when trying to install/initialize Dreambooth

### ISSUE THREAD

**Issue by lipepin** [d8ahazard/sd_dreambooth_extension#457]
`
venv "C:\StableDiffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision:
SD-WebUI revision:

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[!] diffusers[torch] version 0.10.0 installed.
[+] transformers version 4.21.0 installed.
[ ] xformers version 0.0.14.dev0 installed.
[ ] torch version 1.12.1+cu113 installed.
[ ] torchvision version 0.13.1+cu113 installed.
#######################################################################################################

Launching Web UI with arguments: --xformers
Error loading script: api.py
Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension-main\scripts\api.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import dreambooth
ModuleNotFoundError: No module named 'extensions.sd_dreambooth_extension'

Error loading script: main.py
Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension-main\scripts\main.py", line 3, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import dreambooth
ModuleNotFoundError: No module named 'extensions.sd_dreambooth_extension'

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [7460a6fa] from C:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\model.ckpt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?** 
Yes.

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?** 
Yes.

**Have you updated Dreambooth to the latest revision?** 
Yes.

**Have you updated the Stable-Diffusion-WebUI to the latest version?** 
Yes.

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug** 
I tried to install Dreambooth on Automatic1111 via the webui itself as manually downloading and placing it in the "C:\StableDiffusion\stable-diffusion-webui\extensions" folder, but none of these ways worked.

I think the problem is here [!] diffusers[torch] version 0.10.0 installed. , but I don't know how to solve it

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS? 
Windows 11 Pro 
Build: 22621.819
Version: 22H2

If Windows - WSL or native?
Native

What GPU are you using?
GTX 1660 Galax

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by d8ahazard** [comment]
Rename the extension folder:

![image](https://user-images.githubusercontent.com/1633844/206928411-38dbcd59-6855-4ac7-86c8-faae0fd3ffe1.png)


Or install using the extensions tab: 

![image](https://user-images.githubusercontent.com/1633844/206928439-e5c517da-6b56-40a8-9f61-321fb4e5699e.png)
