### ISSUE TITLE
Training stop at random step before max steps reached if set separated Maximum Training Steps for concepts

### ISSUE THREAD

**Issue by LaikaSa** [d8ahazard/sd_dreambooth_extension#458]
`
Python revision: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Dreambooth revision: 88cc50ace470580842b519115545b9a08ebe115e
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers[torch] version 0.10.0.dev0 installed.
[+] transformers version 4.21.0 installed.
[ ] xformers version 0.0.14.dev0 installed.
[ ] torch version 1.12.1+cu116 installed.
[ ] torchvision version 0.13.1+cu116 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**
- First time:
In the interval tab, I set the max steps to 1200. In the concept tabs, set the X concept max step to 1200 and Y concept steps to 800 thinking that it will train both simultaneously but will stop for the Y concept at step 800 and only continue with X to 1200 since Y is more simple to train. But the training abruptly stops at step 1008 and announces finish, but only checkpoint models from previous steps at 300, 600, 900 were saved as I set frequently to save every 300 steps, with no final model at step 1008 it stops at.
![image](https://user-images.githubusercontent.com/112873279/206622811-815b4f9c-f996-4db7-999d-b77aa3eab070.png)

- Second time: 
I set up the training again but this time with a maximum of 1500 steps in the interval tab for the 2 same concepts. Set the Maximum steps for X at -1 steps and 800 for the Y concept. the same thing happen and It stops the training at step 1430
![image](https://user-images.githubusercontent.com/112873279/206623986-d4f5f2d3-205c-4f77-a496-b3c5f2054ce0.png)

-To ensure this is the issue that specifically happens if separated max steps were set for each concept, I run another training again but this time both max steps in the concept tab at -1. This time the training finally run full 1500/1500 steps as set in the interval tab.
**Provide logs**
No crash happened
**Environment**
Window native
What GPU are you using?
Nvidia RTX 3090
**Screenshots/Config**
This is config.json file for both training got the error describe above:
![image](https://user-images.githubusercontent.com/112873279/206624802-1b25b75f-a548-487b-b85e-0712ad68a5c6.png)
![image](https://user-images.githubusercontent.com/112873279/206624868-8046439f-402f-4abe-ac2c-a100da3adbd2.png)

**Comment by d8ahazard** [comment]
This is resolved.
