### ISSUE TITLE
VRAM does not clear after failed attempted to train + 10gb vram issues

### ISSUE THREAD

**Issue by Kylescher1** [d8ahazard/sd_dreambooth_extension#46]
My 3080FE has max vram usage, after failing. To clear the vram I need to restart the webui.

On a side note, I cannot get this to run on 10gbs

**Comment by AmmBe** [comment]
With the maximum optimization that is here now, I was able to run with 10.8 GB. But the model was not saved as a .ckpt file

**Comment by d8ahazard** [comment]
So, I believe people are now able to train on 10GB GPUs. 

Feel free to open a new issue with the proper template and I'll be happy to help further.

**Comment by Kylescher1** [comment]
Will do thanks
