### ISSUE TITLE
Invalid VAE path

### ISSUE THREAD

**Issue by notchrisb** [d8ahazard/sd_dreambooth_extension#460]
The function sanitize_filename_part() from the images.py module is used in the db_config.py file on the pretrained_vae_name_or_path variable (line 126). Looks like this is causing the string to convert from

C:\\Users\me\Documents\git\stable-diffusion-webui\models\VAE

to

C__Users_me_Documents_git_stable-diffusion-webui_models_VAE

This script also shows what I am referring to.

```
  #!/usr/bin/env` python
  sname = "C:\\Users\\me\\Documents\\git\\stable-diffusion-webui\\models\\VAE"
  
  
  invalid_filename_chars = '<>:"/\\|?*\n'
  invalid_filename_prefix = ' '
  invalid_filename_postfix = ' .'
  max_filename_part_length = 128
  
  
  def sanitize_filename_part(text, replace_spaces=True):
      if text is None:
          return None
  
      if replace_spaces:
          text = text.replace(' ', '_')
  
      text = text.translate({ord(x): '_' for x in invalid_filename_chars})
      text = text.lstrip(invalid_filename_prefix)[:max_filename_part_length]
      text = text.rstrip(invalid_filename_postfix)
      return text
  
  print(sanitize_filename_part(sname))
```

**Comment by antorio** [comment]
commenting line 126 in db_config.py solved the problem for me.
`# pretrained_vae_name_or_path = images.sanitize_filename_part(pretrained_vae_name_or_path, True)`

Thanks for giving the right direction before in discussion @notchrisb

**Comment by notchrisb** [comment]
@d8ahazard Thank you very much
