### ISSUE TITLE
ERROR creating model after update

### ISSUE THREAD

**Issue by antorio** [d8ahazard/sd_dreambooth_extension#461]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

Dreambooth revision is 88cc50a
SD webui revision is 44c46f0
`
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)? 
YES

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI? 
YES

**Have you updated Dreambooth to the latest revision? 
YES

**Have you updated the Stable-Diffusion-WebUI to the latest version? 
YES

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.
OK

**Describe the bug**

Can't create model with some .ckpt of mine as base model. Fine if with base sd 1.5 model or some other. **It was OK few days ago**, no error when creating the model, until update to the latest.

Suspecting the custom checkpoint now can't be extracted to diffuser because of new parameter 'resolution' at sd_to_diff.py update in Dec 6 (9f57852)

**Provide logs**
Traceback (most recent call last):
File "/workspace/stable-diffusion-webui/modules/call_queue.py", line 45, in f
     res = list(func(*args, **kwargs))
File "/workspace/stable-diffusion-webui/modules/call_queue.py", line 28, in f
     res = func(*args, **kwargs)
**File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 962, in extract_checkpoint
     db_config.resolution, \
AttributeError: 'NoneType' object has no attribute 'resolution'**

**Environment**

Debian 10
RTX 3090

**Comment by antorio** [comment]
just checking, tried changing line 962 of sd_to_diff.py just to a hard straight 512.
Its error now showing: 
Exception loading config: [Errno 2] No such file or directory: 'C:\stable-diffusion-webui\models\dreambooth\[training models's name]\db_config.json

**Comment by antorio** [comment]
last working commit hash successfully creating model: c2fc683ebcf4db23cfce22626aa6a7b565994c96 (nov 30)

**Comment by d8ahazard** [comment]
Is there a db_config.json file in that location?

**Comment by syan2018** [comment]
ohhh, i have a same problem😭

**Comment by antorio** [comment]
> ohhh, i have a same problem😭

@syan2018 have u tried last update?

**Comment by syan2018** [comment]
saw that was fixed by v21！
