### ISSUE TITLE
Error starting Training Wizard

### ISSUE THREAD

**Issue by botoxparty** [d8ahazard/sd_dreambooth_extension#465]
`
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0]
Dreambooth revision: 88cc50ace470580842b519115545b9a08ebe115e
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[!] diffusers[torch] version 0.10.0 installed.
[+] transformers version 4.25.1 installed.
[!] xformers NOT installed.

The weird thing here is that torch is installed, so is torchvision, to both venv and main env in the correct versions.

[ ] torch version 1.12.1+cu113 installed.
[ ] torchvision version 0.13.1+cu113 installed.
#######################################################################################################
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

Yes

**Have you updated Dreambooth to the latest revision?**

Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

OK

**Describe the bug**

Cannot start the Training Wizard

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

Traceback (most recent call last):
  File "/home/adam/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "/home/adam/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/adam/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

And i get 502 errors in my Network tab when trying to open the Training Wizard.

**Environment**

What OS? Ubuntu 22.04

If Windows - WSL or native? native

What GPU are you using? 3090 24GB

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by mykeehu** [comment]
Ok, here are the steps: 
- First create a model 
- On the Concepts -> Concept 1 tab, in the dataset directory, enter the path to the sample images folder 
- ONLY THEN press one of the Training buttons!

**Comment by DenkingOfficial** [comment]
> Ok, here are the steps:
> 
> * First create a model
> * On the Concepts -> Concept 1 tab, in the dataset directory, enter the path to the sample images folder
> * ONLY THEN press one of the Training buttons!

The issue is about Training Wizard, not actually just train button

**Comment by mykeehu** [comment]
We are talking about the same thing. Before using the Training Wizard, you need to specify the folder of images to calculate the parameters based on the samples.

**Comment by d8ahazard** [comment]
Closed, PEBCAK.
