### ISSUE TITLE
Exception training model: argument of type 'ValueError' is not iterable

### ISSUE THREAD

**Issue by bitk0der** [d8ahazard/sd_dreambooth_extension#467]
```
Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)]
Dreambooth revision: 88cc50ace470580842b519115545b9a08ebe115e
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[!] diffusers[torch] version 0.10.0 installed.
[+] transformers version 4.25.1 installed.
[!] xformers NOT installed.
[ ] torch version 1.12.1 installed.
[ ] torchvision version 0.13.1 installed.
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
ok

**Describe the bug**

Training stopped immediatly after start with error: Returning result: Exception training model: argument of type 'ValueError' is not iterable

**Provide logs**

```
Starting Dreambooth training...
 Cleanup completed. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

Initializing dreambooth training...
Patching transformers to fix kwargs errors.
/Users/*****/Documents/PycharmProjects/stable-diffusion-webui-automatic1111/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/generation_utils.py:24: FutureWarning: Importing `GenerationMixin` from `src/transformers/generation_utils.py` is deprecated and will be removed in Transformers v5. Import as `from transformers import GenerationMixin` instead.
  warnings.warn(
Replace CrossAttention.forward to use default
 Training completed, reloading SD Model. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

Memory output: {}
 Restored system models. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

Returning result: Exception training model: argument of type 'ValueError' is not iterable
```

**Environment**

What OS?
macOS Monterey 12.6

What GPU are you using?
Apple M1 Max, 64gb

**Comment by mykeehu** [comment]
Interesting... I use xformers and I train with an RTX 3060 12 GB card without any problems.

**Comment by danielpdykes** [comment]
Performed an uninstall and reinstall within Automatic111 using the Extensions panel and now it seems to have progressed past this point. @bitk0der you may wish to try the same to see if you get different results to the issue you reported here.

**Comment by axonaxis** [comment]
![SnapshotI](https://user-images.githubusercontent.com/30280846/206872640-dace744a-180e-4478-b6f6-837163186149.png)
The same Problem
Ubuntu 20
Python 3.10.8
Tesla V100, 32GB VRAM

**Comment by d8ahazard** [comment]
Fixed with the latest release.
