### ISSUE TITLE
error Converting text encoder... ^C

### ISSUE THREAD

**Issue by wilzamguerrero** [d8ahazard/sd_dreambooth_extension#480]
Hi everyone i hope can help me i have this problem ever that i press for create. um working on free colab.

Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
Commit hash: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Cloning Stable Diffusion into repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories/taming-transformers...
Cloning K-diffusion into repositories/k-diffusion...
Cloning CodeFormer into repositories/CodeFormer...
Cloning BLIP into repositories/BLIP...
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
Dreambooth revision: c12079eae4d00b6fa8aa8e2c4ef370f557151fa9
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.15.dev343+git.1b1fd8a installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
#######################################################################################################

Cloning midas into repositories/midas...

Launching Web UI with arguments: --share --api --force-enable-xformers --ckpt-dir= --ckpt=/content/drive/Shareddrives/Data13/ModelzZz/modelz_base/v1-5.ckpt --cors-allow-origins=https://www.painthua.com/ --theme=dark
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [81761151] from /content/drive/Shareddrives/Data13/ModelzZz/modelz_base/v1-5.ckpt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://b70dee199db8c1a4.gradio.app/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Loading model from checkpoint.
Loading checkpoint...
v1 model loaded.
Creating scheduler...
Converting unet...
Converting vae...
Converting text encoder...
^C

**Comment by wilzamguerrero** [comment]
> You are low on (video?) memory. I got this interruption on Colab when I wanted to comb three models together.

yes is tis the problem, now i used fp16 model for train and its working, maybe something can be done to use the larger models, for now i used the fp16 for train.

**Comment by d8ahazard** [comment]
You can use the --ckptfix commandline arg on startup to use CPU only for extraction.
