### ISSUE TITLE
Where is lora ?

### ISSUE THREAD

**Issue by alexfredo** [d8ahazard/sd_dreambooth_extension#486]
Hi I have installed your extension on automatic1111 but I don't see where is lora, how activate it ? thanks

**Comment by Janca** [comment]
You can add `--test-lora` to your `COMMANDLINE_ARGS=` in your `webui-user.bat/sh` to enable the new LORA option in the `Advanced` section, under `Tuning`

**Comment by SomeKay** [comment]
> You can add `--test-lora` to your `COMMANDLINE_ARGS=` in your `webui-user.bat/sh` to enable the new LORA option in the `Advanced` section, under `Tuning`

Thank you for the information. I've added the `test-lora` flag, but don't know how to create a Lora Model. In the "Create Model" dialog, there is no option to make it a Lora Model.

What I tried is using a regular model and under "Advanced" in "Parameters" turning on LORA, but I still get the Out of Memory error on my 3060TI with 8GB VRAM and 32GB RAM. Wasn't the point of LORA that we could train Dreambooth on 8GB VRAM? And if yes, what else would I need to do?

**Comment by Naegles** [comment]
> Thank you for the information. I've added the `test-lora` flag, but don't know how to create a Lora Model. In the "Create Model" dialog, there is no option to make it a Lora Model.

Just using a regular model is correct, just activate the option under "Advanced". Then make sure to activate "Use 8bit Adam", select "fp16" for "mixed precision" and "xformers" for "memory attention". Also turn on "Gradient Checkpointing".  I didn't have to turn on "Don't cache latents" on my end, which gives a decent speed increase, but if you still have VRAM issues turn that on too.

However, there currently appears to be a bug that causes a spike in VRAM usage while saving. This is fixed with the Pull Request #484 . Without this change I've always gotten an OOM while saving.

On another note, it seems like LORA may need a higher learning rate then you're used to. Haven't experimented enough yet to figure it out for sure though.

**Comment by SomeKay** [comment]
Beautiful! It worked! Thank you! :)

**Comment by alexfredo** [comment]
I have train a lora model with "style" settings and it's crash (a cuda out of memory) when he create the checkpoint file after 2 hours of waiting :( I have 6go of vram and I have follow the instructions above, do someone know why it's crash when he create checkpoint after 100% ?

**Comment by Thomas-MMJ** [comment]
> I have train a lora model with "style" settings and it's crash (a cuda out of memory) when he create the checkpoint file after 2 hours of waiting :( I have 6go of vram and I have follow the instructions above, do someone know why it's crash when he create checkpoint after 100% ?

Read the above comment there is a patch that fixes this, but it isn't committed yet. See 

> However, there currently appears to be a bug that causes a spike in VRAM usage while saving. This is fixed with the Pull Request https://github.com/d8ahazard/sd_dreambooth_extension/pull/484 . Without this change I've always gotten an OOM while saving.

You might want to wait till the patch is committed before trying to use it.

**Comment by alexfredo** [comment]
Ok thanks for the answer Thomas-MMJ !

**Comment by d8ahazard** [comment]
Lora is still WIP, and has been pointed out, is hidden behind the --test-lora command line arg.

OOM issue fix has been merged,

**Comment by Kahldris** [comment]
> Yes LORA needs 1e-4 vs 1e-6 for normal dreambooth.

Just to add to this I tried LORA at 1e-4 for an SD2 model and results were absolutely awful compared to my normal SD1 1e-6 training. Trying 1e-6 now and it's looking more promising...

**Comment by Thomas-MMJ** [comment]
I was basing my statement on the original lora.  The lora in original implementation needed 1e-4, looks like this one needs a different learning rate, not sure what the differences are in implementation.
