### ISSUE TITLE
Error when training/preview images

### ISSUE THREAD

**Issue by demosch** [d8ahazard/sd_dreambooth_extension#49]
<img width="1440" alt="Bildschirmfoto 2022-11-09 um 00 53 49" src="https://user-images.githubusercontent.com/92346072/200701620-af7555c8-a5bd-45af-b703-6d4922e42331.png">
@d8ahazard

**Comment by psdwizzard** [comment]
If you turn off preview it will go no crash

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
> If you turn off preview it will go no crash

what do u mean by this? I disabled "Generate a preview image every N steps" but it still gives same error as above

**Comment by demosch** [comment]
@d8ahazard

**Comment by psdwizzard** [comment]
> > If you turn off preview it will go no crash
> 
> what do u mean by this? I disabled "Generate a preview image every N steps" but it still gives same error as above

you make the number either 0 or above how many steps you are doing (IE if you are training at 1000 steps set your to 1001)

**Comment by demosch** [comment]
@d8ahazard

**Comment by d8ahazard** [comment]
This is now resolved.
