### ISSUE TITLE
OOM Errors on RTX 3090 24GB VRAM

### ISSUE THREAD

**Issue by c-1869** [d8ahazard/sd_dreambooth_extension#491]
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: dd2ce44c9a26240551413756cd2b98a32f2ea3c2
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
#######################################################################################################

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

Yes

**Have you updated Dreambooth to the latest revision?**

Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

OK

**Describe the bug**

I have been trying everything for over a week now to get this to run on my RTX 3090, however haven't had any luck. I've used every Google search, YouTube video, GitHub discussion resource I can find by now and simply am out of ideas. Can you please assist?

**Provide logs**

Launching Web UI with arguments:
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [44bf0551] from C:\Users\~\webui\stable-diffusion-webui\models\Stable-diffusion\f222.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'equal_height': True}
  warnings.warn(
C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py:763: UserWarning: Expected 1 arguments for function <function update_generation_info at 0x000001FF65E393F0>, received 2.
  warnings.warn(
C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py:771: UserWarning: Expected maximum 1 arguments for function <function update_generation_info at 0x000001FF65E393F0>, received 2.
  warnings.warn(
C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Column, please remove them: {'varint': 'panel'}
  warnings.warn(
C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Number, please remove them: {'max': 12, 'min': 1}
  warnings.warn(
C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Number, please remove them: {'min': 10, 'max': 200}
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860
`
Returning [0.9, 0.999, 1e-08, 0.01, 'default', False, '', 0.0, 60.0, 1, True, False, True, 1e-06, 'constant', 500, 75, 4300, 'fp16', True, 1, True, '', 1, 512, 1, True, 0, 0, True, False, False, False, 1, True, True, False, False, False, False, '', 7.5, 40, '', 'photo of a person', '', 'C:\\Users\\~\\Temp1\\ZZ_1\\Resized\\512x512', 'photo of a ZZ4 person', '', -1, 1, 430, -1, 7.5, 40, '', '', '', '', 7.5, 60, '', '', '', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', '', 7.5, 60, '', '', '', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', 'Loaded config.']
Concept 0 class dir is C:\Users\~\webui\stable-diffusion-webui\models\dreambooth\ZZ4\classifiers_0
Starting Dreambooth training...
 Allocated 0.0/2.0GB
 Reserved: 0.0/2.0GB

Initializing dreambooth training...
Patching transformers to fix kwargs errors.
C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\transformers\generation_utils.py:24: FutureWarning: Importing `GenerationMixin` from `src/transformers/generation_utils.py` is deprecated and will be removed in Transformers v5. Import as `from transformers import GenerationMixin` instead.
  warnings.warn(
Replace CrossAttention.forward to use default
Checking concept: {'max_steps': -1, 'instance_data_dir': 'C:\\Users\\~\\Temp1\\ZZ_1\\Resized\\512x512', 'class_data_dir': '', 'instance_prompt': 'photo of a ZZ4 person', 'class_prompt': 'photo of a person', 'save_sample_prompt': '', 'save_sample_template': '', 'instance_token': '', 'class_token': '', 'num_class_images': 430, 'class_negative_prompt': '', 'class_guidance_scale': 7.5, 'class_infer_steps': 40, 'save_sample_negative_prompt': '', 'n_save_sample': 1, 'sample_seed': -1, 'save_guidance_scale': 7.5, 'save_infer_steps': 40}
Concept requires 430 images.
Class image dir is not set, defaulting to C:\Users\~\webui\stable-diffusion-webui\models\dreambooth\ZZ4\classifiers_0
Class dir C:\Users\~\webui\stable-diffusion-webui\models\dreambooth\ZZ4\classifiers_0 has 0 images.
  0%|                                                                                          | 0/430 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\~\webui\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 356, in start_training
    config, mem_record, msg = main(config, mem_record, use_subdir=use_subdir, lora_model=lora_model_name,
  File "C:\Users\~\webui\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 474, in main
    images = concept_pipeline(example["prompt"], num_inference_steps=concept.class_infer_steps,
  File "C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 517, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 381, in forward
    sample, res_samples = downsample_block(
  File "C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 611, in forward
    hidden_states = resnet(hidden_states, temb)
  File "C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\resnet.py", line 464, in forward
    hidden_states = self.conv1(hidden_states)
  File "C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\~\webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 12.78 GiB (GPU 0; 24.00 GiB total capacity; 2.04 GiB already allocated; 19.29 GiB free; 2.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|                                                                                          | 0/430 [00:05<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Memory output: {}
 Restored system models.
 Allocated: 2.0GB
 Reserved: 2.0GB

Returning result: Exception training model: CUDA out of memory. Tried to allocate 12.78 GiB (GPU 0; 24.00 GiB total capacity; 2.04 GiB already allocated; 19.29 GiB free; 2.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Environment**

Windows 10, RTX 3090 24 GB VRAM, Ryzen 7 3800X, 16 GB RAM

**Screenshots/Config**

{
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_epsilon": 1e-08,
    "adam_weight_decay": 0.01,
    "attention": "default",
    "center_crop": false,
    "concepts_path": "",
    "epoch_pause_frequency": 0.0,
    "epoch_pause_time": 60.0,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "half_model": false,
    "hflip": true,
    "learning_rate": 1e-06,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 500,
    "max_token_length": 75,
    "max_train_steps": 4300,
    "mixed_precision": "fp16",
    "model_dir": "C:\\Users\\~~\\webui\\stable-diffusion-webui\\models\\dreambooth\\ZZ4",
    "model_name": "ZZ4",
    "not_cache_latents": true,
    "num_train_epochs": 1,
    "pad_tokens": true,
    "pretrained_model_name_or_path": "C:\\Users\\~~\\webui\\stable-diffusion-webui\\models\\dreambooth\\ZZ4\\working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_weight": 1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 1,
    "save_class_txt": true,
    "save_embedding_every": 0,
    "save_preview_every": 0,
    "save_use_global_counts": true,
    "save_use_epochs": false,
    "scale_lr": false,
    "src": "C:\\Users\\~~\\webui\\stable-diffusion-webui\\models\\Stable-diffusion\\v1-5-pruned-emaonly.ckpt",
    "shuffle_tags": false,
    "train_batch_size": 1,
    "train_text_encoder": true,
    "use_8bit_adam": true,
    "use_concepts": false,
    "use_cpu": false,
    "use_ema": false,
    "use_lora": false,
    "scheduler": "ddim",
    "v2": false,
    "has_ema": "True",
    "concepts_list": [
        {
            "max_steps": -1,
            "instance_data_dir": "C:\\Users\\~~\\Temp1\\ZZ_1\\Resized\\512x512",
            "class_data_dir": "",
            "instance_prompt": "photo of a ZZ4 person",
            "class_prompt": "photo of a person",
            "save_sample_prompt": "",
            "save_sample_template": "",
            "instance_token": "",
            "class_token": "",
            "num_class_images": 430,
            "class_negative_prompt": "",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "save_sample_negative_prompt": "",
            "n_save_sample": 1,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 40
        }
    ],
    "lifetime_revision": 0
}

**Comment by JustinLion83** [comment]
@c-1869 Last night I also hit by this weird CUDA out of memory...PYTORCH_CUDA_ALLOC_CONF error, even though I have enough VRAM！
My situation was worse than yours, I couldn't even generate single 512X512 pxs！ 
After hours trying, now I can generate 1024X1024 pxs or higher resolutions with my Windows 10, RTX3060 12GB, 16GB RAM！
The key is "**change virtual memory size on Windows 10**", I don't know why but after I set my virtual memory size from default 812MB to 16384MB (16GB), it worked on me！
You can give it a try, good luck！

**Comment by c-1869** [comment]
All sorted. Installed some additional RAM today and it is working, looks like that was my bottleneck.
