### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by nowtabletsgo** [d8ahazard/sd_dreambooth_extension#501]
Hello.
After updating dreambooth to the latest version, I get the error "ValueError: too many values to unpack (expected 2)" and Train exits.
Do you have any idea how to solve this problem?

I am using A6000 with paprespace.
See below for logs.

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.9.13 (main, May 23 2022, 22:01:06) 
[GCC 9.4.0]
Dreambooth revision: 196a62ba7b86aa2da6bcd0b0dc065f41f24a0865
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[ ] xformers version N/A installed.
[+] torch version 1.12.0+cu116 installed.
[+] torchvision version 0.13.0+cu116 installed.
#######################################################################################################

Starting Dreambooth training...
 Allocated 0.0/4.0GB 
 Reserved: 0.0/4.1GB 

Initializing dreambooth training...
Patching transformers to fix kwargs errors.
/usr/local/lib/python3.9/dist-packages/transformers/generation_utils.py:24: FutureWarning: Importing `GenerationMixin` from `src/transformers/generation_utils.py` is deprecated and will be removed in Transformers v5. Import as `from transformers import GenerationMixin` instead.
  warnings.warn(
Replace CrossAttention.forward to use default
Checking concept: {'max_steps': -1, 'instance_data_dir': '/notebooks/src/arutera512siro', 'class_data_dir': '/notebooks/src/512', 'instance_prompt': 'sts', 'class_prompt': '1girl', 'save_sample_prompt': '', 'save_sample_template': '', 'instance_token': '', 'class_token': '', 'num_class_images': 0, 'class_negative_prompt': '', 'class_guidance_scale': 7.5, 'class_infer_steps': 40, 'save_sample_negative_prompt': '', 'n_save_sample': 1, 'sample_seed': -1, 'save_guidance_scale': 7.5, 'save_infer_steps': 40}
Concept requires 0 images.
 Loaded model. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 356, in start_training
    config, mem_record, msg = main(config, mem_record, use_subdir=use_subdir, lora_model=lora_model_name,
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 758, in main
    train_dataset, train_dataloader = cache_latents(enc_vae=vae, orig_dataset=gen_dataset)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 746, in cache_latents
    text_encoder_cache.append(text_encoder(d_batch["input_ids"])[0])
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 811, in forward
    return self.text_model(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 710, in forward
    bsz, seq_len = input_shape
ValueError: too many values to unpack (expected 2)
 Training completed, reloading SD Model. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

Memory output: {}
 Restored system models. 
 Allocated: 4.0GB 
 Reserved: 4.1GB 

Returning result: Exception training model: too many values to unpack (expected 2)

**Comment by james-things** [comment]
Appears to be caused by this PR https://github.com/d8ahazard/sd_dreambooth_extension/pull/475

**Comment by tsukimiya** [comment]
I ran into the same problem.
I am using A4000, A6000 and A100 with paprespace.

I tried reverting back to one of the previous revisions of PR #475 (Rev:  593e82ca ) and had the same problem, so it appears to have been occurring a bit earlier.

**Comment by rabidcopy** [comment]
Same still happens to me when unchecking Don't Cache Latents.

**Comment by d8ahazard** [comment]
Iz good, checkbox fixed. Da!
