### ISSUE TITLE
Error in Automatic1111 after update | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by shiftyjmusic** [d8ahazard/sd_dreambooth_extension#515]
Traceback (most recent call last):
File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 358, in start_training
mem_record, msg = main(config, mem_record, use_subdir=use_subdir, lora_model=lora_model_name,
"/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 658, in main
train_dataset = SuperDataset(
File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/SuperDataset.py", line 154, in __init__
file_text = self.text_getter.read_text(file)
"/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 31, in read_text
filename_text = file.read()
"/venv/lib/python3.10/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

Even tried it on an A100 with various settings, quadruple checked everything countless times...

**Comment by shiftyjmusic** [comment]
Something was wrong with my input images..

**Comment by Eleven1202** [comment]
you need in extensions\sd_dreambooth_extension\postinstall.py  first line add  # -*- coding: utf-8 -*-
你需要在目录 “extensions\sd_dreambooth_extension\postinstall.py” 的第一行添加代码   # -*- coding: utf-8 -*-

**Comment by CoraAI** [comment]
"...UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte"
mine is almost the same but "position 170" instead of "position 0"

> you need in extensions\sd_dreambooth_extension\postinstall.py first line add # -_- coding: utf-8 -_- 你需要在目录 “extensions\sd_dreambooth_extension\postinstall.py” 的第一行添加代码 # -_- coding: utf-8 -_-

**Comment by stevenvi** [comment]
When I had this happen to me, it turned out that MacOS was leaving some hidden garbage file droppings in the dataset directory.  For example, it would look like this:
```
$ ls -lha
drwxr-xr-x 2 steven steven  12K Aug 26 01:44 .
drwxr-xr-x 9 steven steven 4.0K Aug 25 02:16 ..
-rw-r--r-- 1 steven steven  106 Aug 25 02:16 00040-0-026.txt
-rwx------ 1 steven steven 4.0K Aug 26 01:43 ._00040-1-026.png
-rw-r--r-- 1 steven steven 285K Aug 25 02:16 00040-1-026.png
-rwx------ 1 steven steven 4.0K Aug 26 01:43 ._00040-1-026.txt
```
Removing these files (the ones starting with `._`) from the dataset fixed the issue.
