### ISSUE TITLE
Error no kernel image is available for execution on the device at line 167 in file.

### ISSUE THREAD

**Issue by ZeroCool22** [d8ahazard/sd_dreambooth_extension#52]
![Screenshot_11](https://user-images.githubusercontent.com/13344308/200719767-2e4e582a-8f9b-4fb2-aa3d-c7d3bd075e8c.jpg)

Solution?

**GPU: 1080TI**

Also, dunno why it says something about **"D"**, i have nothing installed in D.

![Screenshot_12](https://user-images.githubusercontent.com/13344308/200722561-4d1bdd0c-a7a8-4d7d-87af-a458d7f67fb6.jpg)

This is the only **CSRC** folder i have and there is not any **ops.cu** file.

**Comment by james-things** [comment]
I am having the same issue, also running a 1080Ti. I found some troubleshooting for this on the bitsandbytes repo which suggests either a CUDA version mismatch or a GPU incompatibility. (https://github.com/TimDettmers/bitsandbytes/blob/main/errors_and_solutions.md#No-kernel-image-available)

I believe I have now resolved all CUDA discrepancies, but I also noticed that to 10 series cards are incompatible with LLM.int8(), perhaps the source of the error is LLM.int8() being called on 1080Tis? We are likely the only people trying to run this on GPU that have that compatibility issue.

More info: https://github.com/TimDettmers/bitsandbytes#requirements--installation

**Comment by tmode-1960** [comment]
I have a Titan X(pascal), same family of GPU

**Comment by d8ahazard** [comment]
Gonna close this and shift it to a discussion, as there are several related issues that all seem to be tied to this GPU family.

https://github.com/d8ahazard/sd_dreambooth_extension/discussions/99

**Comment by ZeroCool22** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/13344308/201505465-0bf86c41-18b8-4839-b00b-df9067e4ce98.jpg)

Still getting same error and CUDA is updated.

**Comment by james-things** [comment]
I started digging into this a bit yesterday; I am totally unfamiliar with cuda so I could be wrong, but it seems as though the dll may need to be compiled for the card family.

This presents a challenge because the Makefile for bitsandbytes is Linux only, and the maintainer has said they do not have access to windows/would need someone else to help in porting it.

There is a user of another project who managed to compile it himself - it is on Github if you search. I am thinking that may be the origin of the cu116 dll we are trying to use now.

I have been through pretty exhaustive troubleshooting on this one already, so I am going to give building the dll a shot when I get the chance. No promises, but I will share the finished result and provide a how-to if it works. Should get around to it within a week, hopefully less. :)

**Comment by ZeroCool22** [comment]
> I started digging into this a bit yesterday; I am totally unfamiliar with cuda so I could be wrong, but it seems as though the dll may need to be compiled for the card family.
> 
> This presents a challenge because the Makefile for bitsandbytes is Linux only, and the maintainer has said they do not have access to windows/would need someone else to help in porting it.
> 
> There is a user of another project who managed to compile it himself - it is on Github if you search. They also posted the changes they had to make - I am sorry for not including the link but if you Google the dll name you will find it. I am thinking that this person's github repo may be the origin of the cu116 dll we are trying to use now.
> 
> I have been through pretty exhaustive troubleshooting on this one already, so I am going to give building the dll a shot when I get the chance. No promises, but I will share the finished result and provide a how-to if it works. Should get around to it within a week, hopefully less. :)
> 
> Edit: posted this on mobile but managed to find the link nevertheless:
> 
> [TimDettmers/bitsandbytes#30 (comment)](https://github.com/TimDettmers/bitsandbytes/issues/30#issuecomment-1257229487)

I replaced the DLL's but still get the error, we need to modify also some code too?

**Comment by james-things** [comment]
Did you compile the dlls yourself, or do you mean you replaced it with the ones from github?

I was saying that I suspect that maybe the dll we already had was that one from github. I didn't see the maintainer of this repo mention where it came from and I couldn't find any others while searching around. Just a guess though.

**Comment by ZeroCool22** [comment]
> Did you compile the dlls yourself, or do you mean you replaced it with the ones from github?
> 
> I was saying that I suspect that maybe the dll we already had was that one from github. I didn't see the maintainer of this repo mention where it came from and I couldn't find any others while searching around. Just a guess though.

Replaced with ones on that repo.
