### ISSUE TITLE
error generating half model

### ISSUE THREAD

**Issue by wilzamguerrero** [d8ahazard/sd_dreambooth_extension#527]
hello everyone i have a problem for create half ckpt when this option is activate i dont have enough vram for create, so why i used this is because i use only colab, and i can create the model normal, but is more than 4gb so when i load this model is not enough memory only i can load model with a half size, i sued ckptfix and try to do other fix but nothing work maybe have an idea for this problem

**Comment by d8ahazard** [comment]
The forms are there for a reason, and I simply don't have time to play guessing games because folks can't follow instructions designed to help me help them.

**Comment by wilzamguerrero** [comment]
yes i have the solution to change the cpu for cuda in the file of share in stable diffusion, i do this maybe for other people help https://colab.research.google.com/github/wilzamguerrero/SDZ/blob/main/SDZ.ipynb
