### ISSUE TITLE
Training without prior preservation

### ISSUE THREAD

**Issue by brandon-garcia-kueski** [d8ahazard/sd_dreambooth_extension#53]
I'm trying to replicate my workflow from [TheLastBen's fast-dreambooth](https://github.com/TheLastBen/fast-stable-diffusion)
It's basically 800 steps with 6 training images without prior loss preservation. 

What would be the settings to accomplish something similar?

**Comment by d8ahazard** [comment]
Set your target instance dir and prompt, leave all settings for classification images blank. 0 Classifier images, no prompt, no directory. Then it will automatically disable "with prior preservation".
