### ISSUE TITLE
Save between epochs is broken

### ISSUE THREAD

**Issue by hdeezy** [d8ahazard/sd_dreambooth_extension#533]
Only getting a save and sample after the first epoch. For the rest of the epochs it only pauses, no save or sample. This applies for dreambooth and lora I believe.

**Comment by Thomas-MMJ** [comment]
You might need to use this patch, the chkpt save or image generation might be exceeding your vram,

https://github.com/d8ahazard/sd_dreambooth_extension/pull/532

**Comment by hdeezy** [comment]
No vram issue with this. I unchecked "Use Lifetime Steps/Epochs When Saving" and "Save Preview/Ckpt Every Epoch", and now it is working with the Save Checkpoint & Preview(s) Frequency that I set in the UI.
