### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by kitoide** [d8ahazard/sd_dreambooth_extension#538]
My configs:

32GB RAM
RTX 3070 TI

I always get this error, can anyone help me with some optimization I can perform to avoid this error?

`RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 8.00 GiB total capacity; 7.09 GiB already allocated; 0 bytes free; 7.23 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by hdeezy** [comment]
What are you trying to do when you're running out of memory?

**Comment by a-l-e-x-d-s-9** [comment]
Are you using LORA?

**Comment by kitoide** [comment]
> Are you using LORA?

I enabled this and now it seems to be flowing, training is in progress, will report back if I succeed

**Comment by kitoide** [comment]
> Are you using LORA?

What exactly does LORA do?

**Comment by hdeezy** [comment]
https://github.com/cloneofsimo/lora
It is a smaller approximation of dreambooth. Doesn't work properly with gradient checkpointing for now, so don't waste time training with that on.

**Comment by a-l-e-x-d-s-9** [comment]
Without LORA you can't train at all with 8GB VRAM card.

**Comment by Thomas-MMJ** [comment]
Note that the reason it 'runs out of memory' is that the windows driver model WDDM2 reserves 8-15% of the VRAM for itself even when the card is dedicated if you have two GPUs (such as integrated graphics and a dedicated card - a common setup in most gaming laptops).  So you can't use all of your VRAM for training.  Also the pytorch memory gets fragmented so even if you have free memory available that isn't reserved by Windows, the ram can't be allocated because a large enough chunk isn't contiguous.

**Comment by james-things** [comment]
Anyone training successfully with 1080Ti on current commit? I am getting OOM every time and can't for the life of me figure it out. Had no issues training 8bit/fp16 before introduction of the lora stuff.

**Comment by hdeezy** [comment]
> 

I have 1080TI and I'm able to train v1.5 512 with or without lora currently

**Comment by james-things** [comment]
> > 
> 
> I have 1080TI and I'm able to train v1.5 512 with or without lora currently

Sorry, deleted my comment which you were replying to, haha. Immediately after writing it I tried to start training for the n-th time and now everything _just works_ so... I'll chalk the 24 hours of intermittent failure up to ghosts in the computer for now.

**Comment by MarcusAdams-v006200** [comment]
@kitoide , I have a 3090 Ti with 24GB of VRAM. I have to turn on "8bit Atom" under Parameters->Advanced. Make sure you leave "Gradient Checkpointing" enabled. These are both memory optimizations, sacrificing speed. Finally, make sure both "Batch Size" and "Class Batch Size" are set to 1. Increasing the batch sizes uses more VRAM.

**Comment by nanafy** [comment]
Something is for sure wrong. I haven't been able to use this extension since the memory attention stuff got implemented. I always get CUDA out of memory, even on older models I successfully trained prior to the memory attention upgrade. I am literally pulling the same parameters from older models and I get CUDA out of memory with the newer versions. Exact same parameters

**Comment by nanafy** [comment]
How much VRAM do you need to train the new SD 2.0 and 2.1 models? I run out of memory with 12GB VRAM. 
I tried all memory attention options. I have all VRAM saving options enabled except Train Text encoder and Use CPU. Still cannot get it to train. Anyone here successfully gotten training to start on 2.x? with  12GB vram?

**Comment by nanafy** [comment]
> Note that the reason it 'runs out of memory' is that the windows driver model WDDM2 reserves 8-15% of the VRAM for itself even when the card is dedicated if you have two GPUs (such as integrated graphics and a dedicated card - a common setup in most gaming laptops). So you can't use all of your VRAM for training. Also the pytorch memory gets fragmented so even if you have free memory available that isn't reserved by Windows, the ram can't be allocated because a large enough chunk isn't contiguous.

I turned off my integrated one.

**Comment by kitoide** [comment]
> @kitoide, eu tenho um 3090 Ti com 24 GB de VRAM. Eu tenho que ativar "8bit Atom" em Parâmetros->Avançado. Certifique-se de deixar "Gradient Checkpointing" ativado. Ambas são otimizações de memória, sacrificando a velocidade. Também estou usando a opção de inicialização "--xformers", mas não tenho certeza se isso é necessário. Por fim, certifique-se de que "Batch Size" e "Class Batch Size" estejam definidos como 1. Aumentar os tamanhos dos lotes usa mais VRAM.

I do all this, to no avail!

**Comment by kitoide** [comment]
There should be some solution for training to be done with what is available, avoiding memory overflow

**Comment by coldasicee** [comment]
I'll be following this thread. I heard people saying they trained using a 1080, there must be something we can do lol.
But at the same time it's still pretty inconsistent, since the people I saw training with 8gb had the same settings as I did.
(I'm running on a rtx3070)

**Comment by Thomas-MMJ** [comment]
Som recent regressions on VRAM usage, was able to train a week ago with LORA, and now I can't train anything.

**Comment by d8ahazard** [comment]
> Som recent regressions on VRAM usage, was able to train a week ago with LORA, and now I can't train anything.

New version out. Give it a go.

**Comment by nonetrix** [comment]
I am unable to train with Lora now again, this is first time I've tried Lora so I don't know if it's related I am on 8GBs as well

Sorry for bothering 

![image](https://user-images.githubusercontent.com/45698918/212261685-5fe37abf-10e8-49ca-b350-740c90c63b42.png)

**Comment by sunyiwk** [comment]
I am unable to train with Lora now again, this is first time I've tried Lora so I don't know if it's related I am on 6GBs as well

Sorry for bothering

![QQ截图20230324175707](https://user-images.githubusercontent.com/38065863/227490013-9f3955fe-e979-466a-a7d5-6742cab521b6.jpg)
