### ISSUE TITLE
Exception with image again

### ISSUE THREAD

**Issue by AmmBe** [d8ahazard/sd_dreambooth_extension#54]
The error appears when generating a preview images. They are not generated, but the training is successful.
```
Steps:  50%|██████████████████████████▌                          | 50/100 [00:46<00:37,  1.34it/s, loss=0.124, lr=5e-6]
Exception with the stupid image again: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```
another error appears if you set generate a preview image to zero
```
Traceback (most recent call last):
  File "D:\Programs\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "D:\Programs\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "D:\Programs\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "D:\Programs\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 871, in main
    save_img = not global_step % args.save_preview_every
ZeroDivisionError: integer division or modulo by zero
```
Otherwise, everything is fine, if anyone is interested, I was finally able to finish the training, It works using 11.3GB, rtx 3060 12GB, pytorch 1.13.0

**Comment by 0xItx** [comment]
Getting something similar: `Exception with the stupid image again: tensors used as indices must be long, byte or bool tensors`

Windows / rtx 3090 / don't cache latents / train text encoder / 8bit adam / gradient checkpoint / fp16
Using a pre-generated classification dataset

**Comment by 0xItx** [comment]
@AmmBe I'm not sure my fix will address your issue. Could you check? Are you doing CPU training?
