### ISSUE TITLE
Learning speed was down

### ISSUE THREAD

**Issue by poko3347** [d8ahazard/sd_dreambooth_extension#541]
`
Dreambooth revision: 9e3584f0edd2e64d284b6aaf9580ade5dcceed9d
SD-WebUI revision: f82c2c5c6300ae99804edb0e49b3aea4eb79b61d

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

yes

**Have you updated Dreambooth to the latest revision?**

yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

**Describe the bug**

The performance was stable at 1.5 it/s.
However, in the latest commit, it has degraded to 1.5s/it.
The parameters of the learing are exactly the same.

We do not know which commit is the cause, but when we reverted to the following commit, the learning speed returned to normal.
196a62ba7b86aa2da6bcd0b0dc065f41f24a0865

**Environment**

What OS?

Windows 11

What GPU are you using?

RTX 4090

**Comment by KodyAG** [comment]
Same was training at 3 it/s yesterday, now it's 1.6 it/s after updating today, exact same training settings

**Comment by leppie** [comment]
Also as you have the ultimate GPU, you can gain some more speed by change the parameter to `False` on this line:

https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/dreambooth/train_dreambooth.py#L1044

Another 4090 user reported training when from 20 minutes down to under 13 minutes with just this single change.

Unfortunately, I am memory limited on a 10GB 3080, and setting it to `False` causes OOM for me.

**Comment by poko3347** [comment]
Thanks, solved.
However, the method to further speed up 4090 was not effective.
