### ISSUE TITLE
[LORA] When generating ckpt file, it always generates only the latest Lora Model, even when other Lora Model selected.

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [d8ahazard/sd_dreambooth_extension#559]
`
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Commit hash: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Dreambooth revision: c678a431b5d79ba7e1c38d7629ca7e0c79166a1f
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**
When generating ckpt file, it always generates only the latest Lora Model, even when other Lora Model selected.

**Environment**
What OS?
Ubuntu 22.04
If Windows - WSL or native?
No
What GPU are you using?
RTX 2080 8GB

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by a-l-e-x-d-s-9** [comment]
It's not planned to be changed?

**Comment by Thomas-MMJ** [comment]
the bot autocloses it and automarks it

**Comment by mysra** [comment]
After selecting the lora model, you have to press "save config" before you press "generate ckpt". It's weird extra step, but that's how it is now.

**Comment by a-l-e-x-d-s-9** [comment]
@mysra
If you press "save settings" before you press "generate ckpt" it generates ckpt with the training as it should?
Is it respect the selected LORA checkpoint selected in the dropdown box and generate the checkpoint for it? Or is it only generating a ckpt to the latest LORA training and ignoring the selected checkpoint in UI?

**Comment by mysra** [comment]
It respects it. The console shows that it's loading the correct lora model if you save settings.
