### ISSUE TITLE
Optimizations do not work properly on AMD GPUs

### ISSUE THREAD

**Issue by Jarfeh** [d8ahazard/sd_dreambooth_extension#56]

**Comment by kryztoval** [comment]
As far as I have seen there is no training support for AMD GPUs. not only it does not work properly, it just doesn't work. You would either have to get an nVidia GPU or use CPU for the training.

**Comment by aungkhant0911** [comment]
Ditch AMD. Pre-order RTX 4090 like the rest of us.

**Comment by d8ahazard** [comment]
Yeeeeah...this is definitely not something that's within the scope of what I'm doing here. Unfortunately, when it comes to machine learning, I'm pretty sure you either need Nvidia or something crazier.

**Comment by Jarfeh** [comment]
Using Shiva's fork of dreambooth, I've been able to utilize DeepSpeed to offload parts of it to my system ram before, but I'm just barely missing the ceiling. 

@aungkhant0911
I didn't exactly purchase AMD Hardware out of want, but because there was no Nvidia options at the time I made the purchase. I can't exactly shell out the amount of cash necessary for that kind of card.
