### ISSUE TITLE
dreambooth model training automation is possible ?

### ISSUE THREAD

**Issue by eUGENE-BNX** [d8ahazard/sd_dreambooth_extension#567]
Is it possible to train a model without using Automatic 1111?

Can I train stable diffusion models only via console that will collect the dataset in a configuration file?

**Comment by d8ahazard** [comment]
Not entirely...yet.

And, there would still be a requirement for Auto1111 as the host, as it's an extension. 

But, Auto1111 has an API, which this has basic support for. I'm currently working on another overhaul of the UI and underlying systems, and one of those will be to improve the API to add all the requisite endpoints to ensure a fully UI-free process.

So, it's still not 100% console, technically, but you'd still be able to script it by using wget or CURL commands...

**Comment by eUGENE-BNX** [comment]
Thank you for fast response. I have an idea, how can I reach you?
