### ISSUE TITLE
Difference between class prompt and class instance?

### ISSUE THREAD

**Issue by nanafy** [d8ahazard/sd_dreambooth_extension#572]
I need some help understanding which one is the one that actually matters for training your model

It used to just be instance prompt, but now there is instance token as well, same for class. Some clarification would be awesome. Thank you

![image](https://user-images.githubusercontent.com/19253644/208268283-d9705119-c15c-424c-9257-25667151e362.png)

**Comment by Thomas-MMJ** [comment]
a token is either a word or piece of a word, representing the 'name' of your object, such as 'sks',

a prompt is a description of the image including your token.

"a photo of sks"

but it can also be just your token

"sks"

if you use a prompt list then each image can have a different prompt

**Comment by nanafy** [comment]
Thanks Thomas, if you don't mind me asking, Here are my questions I am still confused about.

1. In the previous versions of the extension, before the tokens were added, we only specified instance prompt and instance class. Does everything need to be filled out now?

E.g 
![image](https://user-images.githubusercontent.com/19253644/208269611-1f2d6972-8647-4362-ad13-d72648e03439.png)

OR can I just do this ( which is what I am used to from previous version)

![image](https://user-images.githubusercontent.com/19253644/208269623-8e4858cb-9521-44cb-8648-b3266d13127d.png)

**Comment by nanafy** [comment]
I think I just don't understand if filling out Filewords is necessary or optional for training. I read the readme and not really sure how they work or if they are needed for simple training

**Comment by Thomas-MMJ** [comment]
I think you can leave the prompt blank and it will figure it out from the tokens.

**Comment by nanafy** [comment]
Thanks Thomas, will mark this as closed
