### ISSUE TITLE
Strange issue when using "Generate a preview image every n steps"

### ISSUE THREAD

**Issue by vgaggia** [d8ahazard/sd_dreambooth_extension#59]
Whenever i use the above mentioned option, i get an error about switching to fp16, if i train without fp16 i get the error:

CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

I suppose thats no real helpful error message there as that suggests without that option enabled, no idea where I'd even enable that to be honest.

**Comment by Luke2642** [comment]
What args are you using? These work for me:

webui-user.bat

set COMMANDLINE_ARGS=--xformers --no-half --precision full

**Comment by vgaggia** [comment]
I'm using --xformers and --vae-path models/VAE/Laionvae-ft-ema-560000-ema-pruned.ckpt

i will try what you say when i'm done training a model i'm working on now, it's gonna be like 5 hours though, looking forward to finding out if what you say works though!

**Comment by Luke2642** [comment]
So with those options switched on, merge your checkpoint with a 4gb checkpoint of sd1.4 or 1.5 at a low mix rate. That'll give you a normal checkpoint?

**Comment by vgaggia** [comment]
I am training off sd1.5 already ive come to accept that ill just have to not have checkpoints or image previews

**Comment by VeMeth** [comment]
I'm also having the "Attempting to unscale FP16 gradients " error when generating any previews or creating checkpoints. The model trains successfully when I turn off both.
