### ISSUE TITLE
Abnormal Bleeding/Overfitting

### ISSUE THREAD

**Issue by ArrowM** [d8ahazard/sd_dreambooth_extension#605]
```
Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 633ca33e8ca3d55a5a09a98b3ea6975bd8ffec29
SD-WebUI revision: d7d54d5941dab6f53b130f8e8a2d6d2fdc297c10

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
```

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

OK.

**Describe the bug**

I'm getting **a lot** of abnormal bleeding/over-fitting in my models. I thought it might just be me, but there is a [Discussion post](https://github.com/d8ahazard/sd_dreambooth_extension/discussions/579) where multiple people have the same issue. I'm hoping some of them can provide more info.
I trained a couple models about a month ago using this repo without problems, but a lot of code has changed since then.

**Environment**
Windows 11 22H2, RTX 3080ti

**Screenshots/Config**
I checked that I'm setting up my params as described on the repo:
```
Instance prompt=veli style, [filewords]
class prompt=[filewords]`
```
`veli style` is my token. My captions are generated using deepbooru on the Training tab.  

I am using the default parameters except:
Model 1
```
Learning rate = 1.72e-6
Use EMA = ✅
Use 8bit Adam = ✅
Train Text Encoder = ✅
Mixed Precision = bf16
Memory Attention = xformers
```
Model 2
```
Learning rate = 1.72e-6
Use EMA = ✅
Use 8bit Adam = ✅
Train Text Encoder = ❌
Mixed Precision = fp16
Memory Attention = flash_attention
```
both models had the same bleeding.

**Comment by d8ahazard** [comment]
If it was an issue with the extension, it should have been fixed as IB+ was merged today. 

If it's training advice you need, feel free to keep discussing in Discord. ;)
