### ISSUE TITLE
got an unexpected keyword argument 'keep_fp32_wrapper'

### ISSUE THREAD

**Issue by Xelawk** [d8ahazard/sd_dreambooth_extension#607]
```
Traceback (most recent call last):
  File "/app/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1093, in main
    save_weights()
  File "/app/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 851, in save_weights
    text_enc_model = accelerator.unwrap_model(text_encoder, keep_fp32_wrapper=True)
TypeError: Accelerator.unwrap_model() got an unexpected keyword argument 'keep_fp32_wrapper'
```

**Comment by d8ahazard** [comment]
Your diffusers version is out of date. Please update, restart webui entirely, and try again.

**Comment by ziyaxuanyi** [comment]
I still meet the same problem.
my diffusers version is 0.10.2

**Comment by 1475015695** [comment]
> ```
> Traceback (most recent call last):
>   File "/app/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1093, in main
>     save_weights()
>   File "/app/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 851, in save_weights
>     text_enc_model = accelerator.unwrap_model(text_encoder, keep_fp32_wrapper=True)
> TypeError: Accelerator.unwrap_model() got an unexpected keyword argument 'keep_fp32_wrapper'
> ```
Its the matter with accelerate python package, soultion is easy:
1. update your accelerate package: (1)source venv/bin/activate (make sure you are in SD venv enveriment), (2)pip install --upgrade accelerate. finally, my accelerate version is 0.15.0
2. edit your SD webui requirements_versions.txt file(it will use the sure version for each python package): accelerate==0.15.0
3. restart SD

**Comment by 1475015695** [comment]
> I still meet the same problem. my diffusers version is 0.10.2

look above

**Comment by ziyaxuanyi** [comment]
> > I still meet the same problem. my diffusers version is 0.10.2
> 
> look above

thank you very much! that can solve this problem. it works well.
