### ISSUE TITLE
Add Custom Diffusion training support

### ISSUE THREAD

**Issue by DenkingOfficial** [d8ahazard/sd_dreambooth_extension#611]
**WHAT**
Custom Diffusion, a novel method for model training proposed by Adobe Research
https://github.com/adobe-research/custom-diffusion

**WHERE**
https://www.cs.cmu.edu/~custom-diffusion/

**Additional info**
I tried to train a model on my RTX2060S (8 GB) using this method and it caused an OOM error. But it needs just 512mb more than I have, so I think it can be optimised and integrated into this extension. It produces results as good as DreamBooth does and have advantages such as:
1) Faster training 
2) Lower requirements
3) Simple multi-conceptual training
4) It takes only 75MB per concept and can be compressed even more (As I understand it, it works like TI embeddings)

**Comment by 78Alpha** [comment]
They do mention some optimizations used https://github.com/adobe-research/custom-diffusion/issues/1

It seems to use deepspeed, so it would be a Linux only solution again for 8 GB (Other dreambooth implementations that run on 8 GB use the same thing)

You can try following the 8 GB steps https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth and see if Custom-diffusion runs then. If not, then it may be at the end of its optimizations. Outside of some kind of split attention? or 8-bit optimizations?

**Comment by 2kpr** [comment]
I ran custom diffusion fine on Windows with my 3080 Ti 12GB, it used anywhere from 9GB up to 12GB depending on my batch sizes, 2 for 9GB, 6 for 12GB, settings.

Also, If you train with --freeze_model=crossattn it outputs a 172MB delta.bin file vs the 75MB as it uses more vectors in the attention layer.

**Comment by d8ahazard** [comment]
"Accelerate launch" is already supported in native Auto1111, and so by extension, should work with this.

**Comment by DenkingOfficial** [comment]
Is Custom Diffusion implemented now in your extension?

**Comment by DenkingOfficial** [comment]
@d8ahazard sorry for ping
I can't find any mention of Custom Diffusion in commits and can't find any setting in UI. 
So I wonder why this feature request is closed
