### ISSUE TITLE
[Feature request] Honor clip_skip settings.

### ISSUE THREAD

**Issue by sgsdxzy** [d8ahazard/sd_dreambooth_extension#62]
Some models (namely NAI) is trained with clip_skip = 2. So it is better to support clip skip in webui's settings.

need to change occurrences of `text_encoder(batch["input_ids"])[0]` to 
```
enc_out = text_encoder(batch["input_ids"], output_hidden_states=True, return_dict=True)
encoder_hidden_states = enc_out['hidden_states'][-args.clip_skip]
encoder_hidden_states = text_encoder.text_model.final_layer_norm(encoder_hidden_states)
```

**Comment by sgsdxzy** [comment]
Do you accept pull requests? I can implement and test this.

**Comment by d8ahazard** [comment]
> Do you accept pull requests? I can implement and test this.

I'd *love* some pull requests to help squash some of these. I went to sleep and the issue count doubled. :P
