### ISSUE TITLE
Add days to estimated time of training completion

### ISSUE THREAD

**Issue by ye7iaserag** [d8ahazard/sd_dreambooth_extension#622]
**WHAT**
Days added before hours to the progress ETA time estimation.
In my case I'm training a model for more than 130k steps and it's showing 4 hours which I'm sure is not right.
I'm guessing the days are truncated but I can't be sure whether it is one or two days.
At least make it optional to show if remaining days are more than zero.

**WHERE**
The estimation is shown on the progress bar, so there is best place

**HOW**
Just don't truncate it

**WHEN**
Tomorrow :D

**Comment by d8ahazard** [comment]
Implemented with e5908ab.
