### ISSUE TITLE
Request support for training with rectangular pictures.

### ISSUE THREAD

**Issue by 1223334444abc** [d8ahazard/sd_dreambooth_extension#623]
Most anime pictures use rectangular composition to draw characters, Cutting them into squares causes many problems.
I heard that the native training of rectangular images can be supported by some means.
Is there any chance to integrate them into the plug-in and use any image with a side length of the multiple of sixty-four for training?
I don't know whether using rectangular pictures can get better training results, at least in the training set, the characters look more complete.

**Comment by d8ahazard** [comment]
Added with https://github.com/d8ahazard/sd_dreambooth_extension/commit/15244fef18c35864be6f6c2e1c0237dadc5415c1

**Comment by 1223334444abc** [comment]
@d8ahazard Is there a documentation or user guide for new features?
