### ISSUE TITLE
Feature request - Safetensor support

### ISSUE THREAD

**Issue by mediocreatmybest** [d8ahazard/sd_dreambooth_extension#625]
**WHAT**
What is this feature of which you speak??

Support for safetensor model versions when creating a new models from a source checkpoint.

**WHERE**
From whence did you hear this news?? Provide a URL if possible.
https://huggingface.co/stabilityai/stable-diffusion-2-1/tree/main
Safe Tensor models have been made available from huggingface repository

**HOW**
No doubt others exist but this is what I've found.
https://github.com/diStyApps/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI

**WHEN**
Whenever I get to it. Hold your horses...
Yep!

**Comment by mediocreatmybest** [comment]
Just commenting again so it doesn't get deleted :) Thanks again. From reading some of the other posts it looks like this is on the radar but I didn't see any other issues logged etc. So happy if this gets closed due to existing etc. Thanks again.

**Comment by d8ahazard** [comment]
Added!
