### ISSUE TITLE
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> expected   {'safety_checker'

### ISSUE THREAD

**Issue by Luke2642** [d8ahazard/sd_dreambooth_extension#63]
The latest pull broke in so many ways, so I tried to roll back, ran in to this error when saving a checkpoint, I think I have a mismatched diffusers version after the upgrade to 8.0 rc or something.

Fixed by adding:

safety_checker=None

to train_dreambooth.py line 805. It throws a warning instead.

**Comment by d8ahazard** [comment]
I've updated the installer to be more robust and report the versions of diffusers/torch/torchvision, as these are generally the main source of issues. 

Please do an update and let me know if you are still receiving an issue.

**Comment by mykeehu** [comment]
I get the same error now with the latest build (0ff3f7d685a47ce00de8ebf621290e77be99831d) when generating all preview images:
`You have passed `None` for safety_checker to disable its functionality in <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'>. Note that this might lead to problems when using <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> and is not recommended.
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254`

**Comment by d8ahazard** [comment]
That's a warning, not an error, which is (obv) caused by disabling the
safety checker. Shivam's version has this nag message commented out. Not
harmful, just annoying.
