### ISSUE TITLE
Dreambooth Tab does not appear after install

### ISSUE THREAD

**Issue by Primalinc** [d8ahazard/sd_dreambooth_extension#636]
Everything seemed to go well except Dreambooth Tab does not appear after install

**Comment by Primalinc** [comment]
Solved thanks to following [flotos] and [d8ahazard] advice and restarting everything....it didnt work until I shut down my browser so RESTART EVERYTHING after changing bat. file, apply and restart UI.

**Comment by OddFluffyBunny** [comment]
Mind sharing?

**Comment by d8ahazard** [comment]
Remove and re-install the extension, I've just pushed a big update.

https://github.com/d8ahazard/sd_dreambooth_extension/commit/15244fef18c35864be6f6c2e1c0237dadc5415c1
