### ISSUE TITLE
KeyError: 'images' when starting new training

### ISSUE THREAD

**Issue by Arilziem** [d8ahazard/sd_dreambooth_extension#654]
[shortened for brevity, you will know what is up with this one]
Reply 'OK' Below to acknowledge that you did this.**
'OK' 

**Describe the bug**

Starting a training with the new Imagebuilder+ changes (rev. 645e717) fails when not using the "Train Imagic only" option: 
```
File "[...]\dreambooth\train_dreambooth.py", line 866, in inner_loop
    latents = vae.encode(batch["images"].to(dtype=weight_dtype)).latent_dist.sample()
KeyError: 'images'
```

**Environment**

Windows 10, native

[db_config.json.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/10329188/db_config.json.txt)

**Comment by d8ahazard** [comment]
Already fixed with [645e717](https://github.com/d8ahazard/sd_dreambooth_extension/commit/645e71725cfe0de156f60fa524d8957c30340c3c)
