### ISSUE TITLE
like a classic training possibility

### ISSUE THREAD

**Issue by thezveroboy** [d8ahazard/sd_dreambooth_extension#659]
this plugin allows to teach 1 to 3 concepts at the same time. but this does not provide versatility and opportunities like the classic models of stable diffusion 1.4, 1.5 or 2.0

at the same time, it is possible to train any number of images through the list:
https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/dreambooth/concepts_list.json

there is a question about this. if I have several thousands of pictures, and I can theoretically list information about all of them, then I can train my model with all these pictures. however, manually scoring all this is a long job. Is it possible to create a script that allows you to specify a folder with a database of images in the interface, and the computer itself, through CLIP, will create a description for each image and add it to this list for further training?

then this plugin will allow you to train models on any number of concepts and this will not require large clusters of video cards, as is the case with classical model training

**Comment by Zhincore** [comment]
The "Train" tab in WebUI has "Preprocess images" which can label your dataset for you. You will then have to make the concept list yourself or find other solution on that part.

**Comment by d8ahazard** [comment]
There's also my smartprocess extension, which is more or less designed as a companion for dreambooth.

https://github.com/d8ahazard/sd_smartprocess

**Comment by thezveroboy** [comment]
> The "Train" tab in WebUI has "Preprocess images" which can label your dataset for you.
yes i know about this

> You will then have to make the concept list yourself or find other solution on that part.
and i'm looking for script for this because it's impossible to do it manually. it would be great additional function in the dreambooth

**Comment by saunderez** [comment]
> > The "Train" tab in WebUI has "Preprocess images" which can label your dataset for you.
> 
> yes i know about this
> 
> > You will then have to make the concept list yourself or find other solution on that part.
> 
> and i'm looking for script for this because it's impossible to do it manually. it would be great to have this additional function in the dreambooth

I'm lazy so I asked ChatGPT to write a script to do this for me. Given a folder A:\concepts for instance images and A:\reg for class images and each concept in a folder with naming scheme "instancename classname" this script will generate a concepts_list.json for all concepts.

I had to abbreviate the config for each concept so you'll need to put the rest back in.

`import json
import os

# Set the root directories for the instances and classes
instance_root = r'E:\concepts'
class_root = r'E:\reg'

# Check if the instance root directory exists
if not os.path.exists(instance_root):
    print("The instance root directory does not exist: {}".format(instance_root))
    exit(1)

# Initialize an empty list to hold the configurations
configs = []

# Iterate through the instance folders in the instance root directory
for instance_folder in os.listdir(instance_root):
    # Get the full path to the instance folder
    instance_path = os.path.join(instance_root, instance_folder)
    # Check if the path is a directory (skip if not)
    if not os.path.isdir(instance_path):
        continue
    # Split the instance folder name into the instance name and the class name
    instance_name, class_name = instance_folder.split(' ')
    # Create a configuration for the instance and class
    config = {
        'max_steps': 0,
        'instance_data_dir': instance_path,
        'class_data_dir': os.path.join(class_root, class_name),
        'instance_prompt': instance_folder,
        'class_prompt': 'a {}'.format(class_name),
        'save_sample_prompt': instance_folder,
    }
    # Add the configuration to the list
    configs.append(config)
    # Output the configuration
    print(json.dumps(config, indent=4))

# Write the list of configurations to a JSON file
with open('concepts_list.json', 'w', encoding='utf-8') as f:
    json.dump(configs, f, ensure_ascii=False,`

**Comment by d8ahazard** [comment]
> > > The "Train" tab in WebUI has "Preprocess images" which can label your dataset for you.
> > 
> > 
> > yes i know about this
> > > You will then have to make the concept list yourself or find other solution on that part.
> > 
> > 
> > and i'm looking for script for this because it's impossible to do it manually. it would be great to have this additional function in the dreambooth
> 
> I'm lazy so I asked ChatGPT to write a script to do this for me. Given a folder A:\concepts for instance images and A:\reg for class images and each concept in a folder with naming scheme "instancename classname" this script will generate a concepts_list.json for all concepts.
> 
> I had to abbreviate the config for each concept so you'll need to put the rest back in.
> 
> ```
> import json
> import os
> 
> # Set the root directories for the instances and classes
> instance_root = r'E:\concepts'
> class_root = r'E:\reg'
> 
> # Check if the instance root directory exists
> if not os.path.exists(instance_root):
>     print("The instance root directory does not exist: {}".format(instance_root))
>     exit(1)
> 
> # Initialize an empty list to hold the configurations
> configs = []
> 
> # Iterate through the instance folders in the instance root directory
> for instance_folder in os.listdir(instance_root):
>     # Get the full path to the instance folder
>     instance_path = os.path.join(instance_root, instance_folder)
>     # Check if the path is a directory (skip if not)
>     if not os.path.isdir(instance_path):
>         continue
>     # Split the instance folder name into the instance name and the class name
>     instance_name, class_name = instance_folder.split(' ')
>     # Create a configuration for the instance and class
>     config = {
>         'max_steps': 0,
>         'instance_data_dir': instance_path,
>         'class_data_dir': os.path.join(class_root, class_name),
>         'instance_prompt': instance_folder,
>         'class_prompt': 'a {}'.format(class_name),
>         'save_sample_prompt': instance_folder,
>     }
>     # Add the configuration to the list
>     configs.append(config)
>     # Output the configuration
>     print(json.dumps(config, indent=4))
> 
> # Write the list of configurations to a JSON file
> with open('concepts_list.json', 'w', encoding='utf-8') as f:
> with open('concepts_list.json', 'w', encoding='utf-8') as f:
>     json.dump(configs, f, ensure_ascii=False, indent=4)
> ```

LOL, this is pretty cool. I may have to borrow it and slap a button in the "generate" tab that takes this and the pair of directory paths and does the same thing, only populating the "concepts_list" field with the json, which the app should be able to read as an input. I think. :P

**Comment by thezveroboy** [comment]
cool. hope we'll see this in the dreambooth soon :)
