### ISSUE TITLE
[Feature request] Generate checkpoint button

### ISSUE THREAD

**Issue by mykeehu** [d8ahazard/sd_dreambooth_extension#66]
I accidentally deleted one of my checkpoints today, and it would have been nice to have a button handy to regenerate the checkpoint based on the current state.

**Comment by d8ahazard** [comment]
Good one. Let me fix the bajillion bugs I created yesterday first, then I'll look at adding this. For now, the easiest way is to just train it for 1x additional step. ;)

**Comment by mykeehu** [comment]
We were thinking the same thing, because I used the same trick, but I thought I shouldn't step the model if I didn't have to, but I didn't look for the generation in the code anymore. I'm waiting patiently, because it's still like pressing a button to rerun command

**Comment by d8ahazard** [comment]
Implemented with [f9900cc](https://github.com/d8ahazard/sd_dreambooth_extension/commit/f9900ccb3ce7025d1c89334e320a1c3b255bbd07)

**Comment by mykeehu** [comment]
You are fantastic, thank you!
