### ISSUE TITLE
Reduce VRAM usage before generating sample images?

### ISSUE THREAD

**Issue by Arilziem** [d8ahazard/sd_dreambooth_extension#664]
I am currently training on a 10GB 3080 and cannot generate sample images without running into OOM when I don't use LORA.

I am wondering if there would be a way to reduce VRAM usage enough by unloading certain things from VRAM into RAM and then restoring them after samples have been generated? [aria1th/Hypernetwork-MonkeyPatch-Extension](https://github.com/aria1th/Hypernetwork-MonkeyPatch-Extension) is doing this with the optimizer state (although I am not sure if that would be enough since VRAM is completely full rn and inference needs 1+ gig?).

As an aside, it would also be nice if the model saving would happen before sample generation because currently running into an OOM results in the training progress being lost. (Unless that is already happening, it's just something I noticed on my first attempt with the new changes, but the config might have been wrong on my end.)

**Comment by d8ahazard** [comment]
Thanks for the tip. I've implemented this in the BetterBucketing branch, which I'm just testing/cleaning now, and then will merge to main shortly.
