### ISSUE TITLE
Music Sync

### ISSUE THREAD

**Issue by Flonixcorn** [d8ahazard/sd_dreambooth_extension#668]
Music Sync/Easy Keyframe Generation with preview
So my idea is  
Somethin like a Song Analyzer Tab
It takes a song as an input and then you can select what you want to do with it, f.e. extract beat to zoom and select scale, so that at the end something like this is the result:
https://www.youtube.com/watch?v=t76T6KtzE4s&ab_channel=Flonix
here i made everything by hand using these tools at the bottom, i got kinda sloppy and lazy so it doesnt really fit.

first!:
https://github.com/Anjok07/ultimatevocalremovergui to get 4 stems from my music file 

Then Id need a tool that would take my sound stems and generate keyframes for me like this:
https://www.chigozie.co.uk/audio-keyframe-generator/
preferably as functions tho, but thats hard!
 https://github.com/Anjok07/ultimatevocalremovergui to get 4 stems from my music file 

and then i previewed with this here:
https://colab.research.google.com/github/pharmapsychotic/ai-notebooks/blob/main/pharmapsychotic_AnimationPreview.ipynb 
it didnt give me a good preview tho

then for prompts its really hard to get all of the timings right etc, bc when the beat doesnt line up so the changing/denoising per image doesnt ramp up the image changes late, something would be needed to fix there
And for getting all the timing right i normally just did videotime*fps of animation, but there it would be sick if you could just have some analyze song button that either transforms timestams you got from YT into frame promts

So when something like this would be a sick feature!

if this explanation was understandable!

**Comment by DenkingOfficial** [comment]
It is not related to model training
Why you're posting this into DreamBooth repo?

**Comment by Flonixcorn** [comment]
ah my bad i though i was on deforum!
