### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by superag** [d8ahazard/sd_dreambooth_extension#670]
I'm encountering an error while installing from the setting tab, and cmd prompt gave the following error:

assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
AssertionError: extension access disabled because of command line flags

Didn't find any similar error while searching on Google. Anyone might have any suggestion what might be the cause?

**Comment by speedzz** [comment]
Try removing --share from webui-user.bat

**Comment by superag** [comment]
> 

thank speedzz, i just checked my webui-user.bat

set GIT=
set VENV_DIR=
set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.6
set COMMANDLINE_ARGS= --listen --api --no-half
git pull
call webui.bat

i do not have --share in the script. looks like it's some other problem.

**Comment by speedzz** [comment]
Try Removing --listen

**Comment by superag** [comment]
> Try Removing --listen

this did the trick! Thanks speedzz!
