### ISSUE TITLE
Generated images are nothing like - not as used to be?

### ISSUE THREAD

**Issue by FurkanGozukara** [d8ahazard/sd_dreambooth_extension#671]
I have just trained my brother face on base **SD 1.5 model v1-5-pruned-emaonly**. I am recording a tutorial.

**First question what is Sanity Sample Prompt?**

Here let me start by showing training dataset

![image](https://user-images.githubusercontent.com/19240467/210286816-503b3755-c14e-40a5-bda3-ce41e0c878de.png)

Here let me show you sample images

![image](https://user-images.githubusercontent.com/19240467/210286799-4b9c2365-f1ea-407a-b884-bde225ad8c56.png)

I have trained up to 160 epochs 

When I do inference like this the results are nothing like

The prompt : 
portrait photo of my_key_word:1.2, photo of my_key_word,8k,hdr,smooth,sharp focus,cinematic lighting,intricate, highly detailed,fantasy, illustration, intricate,  octane, digital painting, artstation, concept art,illustration, vibrant colors,  cinematic

negative prompt
bad anatomy, bad proportions, blurry, cloned face, deformed, disfigured, duplicate, extra arms, extra fingers, extra limbs, extra legs, fused fingers, gross proportions, long neck, malformed limbs, missing arms, missing legs, mutated hands, mutation, mutilated, morbid, out of frame, poorly drawn hands, poorly drawn face, too many fingers, ugly, ugly, duplicate, morbid, mutilated, out of frame, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, ugly, blurry, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, out of frame, ugly, extra limbs, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck

And the generated output seriously?
![image](https://user-images.githubusercontent.com/19240467/210286890-160ff3a7-2e39-4200-be73-ae5e7265c292.png)

**If I only provide the my_key_word alone, sometimes it generates the face of my brother**

But what is going on seriously? Also I have used 140 generic classification / regularization images.

It is like learned the classification images not the face i teached 

![image](https://user-images.githubusercontent.com/19240467/210286956-24a89531-a578-4fa5-9528-9674521bb656.png)

these are the settings used

![image](https://user-images.githubusercontent.com/19240467/210286991-5bc86484-13a9-43e9-ba3d-cda70990cccc.png)

**Comment by speedzz** [comment]
I'm having the same problem.

**Comment by drhead** [comment]
I am also having this issue.  It almost seems like it is only training off of classification images alone.

**Comment by eadnams22** [comment]
I had this problem anytime I loaded params from the previous build, but if I remade the settings from scratch, that worked.

**Comment by FurkanGozukara** [comment]
> I had this problem anytime I loaded params from the previous build, but if I remade the settings from scratch, that worked.

dmn this is a serious bug if so

**Comment by steffenthomas** [comment]
Same problem here! :-(
Any workaround? I tried to reinstall dreambooth, but it doesn't work for me.

**Comment by FurkanGozukara** [comment]
> Same problem here! :-( Any workaround? I tried to reinstall dreambooth, but it doesn't work for me.

I am trying to find the solution. Hopefully will prepare a full tutorial once I have

**Comment by d8ahazard** [comment]
What are you using for instance/class prompts?

The "sanity prompt" is a sort of generic prompt you can use to validate the overall quality of the model. In your case, you could do "a man", and when generating samples, it would always create the same image of a man with each batch of samples.

Feel free to hop on the discord and ask questions there, I'd be happy to help get you sorted.

**Comment by speedzz** [comment]
> What are you using for instance/class prompts?
> 
> 
> 
> The "sanity prompt" is a sort of generic prompt you can use to validate the overall quality of the model. In your case, you could do "a man", and when generating samples, it would always create the same image of a man with each batch of samples.
> 
> 
> 
> Feel free to hop on the discord and ask questions there, I'd be happy to help get you sorted.

Where can i find the discord url ?

**Comment by d8ahazard** [comment]
https://discord.gg/q8dtpfRD5w

It's also pinned in the discussions section.

**Comment by jsbach-jung** [comment]
Built a new machine recently and I also ran into the issue. I saw someone on Reddit also had the same problem, and they pinpointed the last build of Dec. 11 as working for them, and I can confirm that one trains like before. Haven’t had the cycles to train on a different build. I’ll peek into discord as well.

**Comment by ItsOkayItsOfficial** [comment]
I'm having this same issue. It doesn't help that it seems impossible to line-up what was successful on a previous `db_config.json` and what is required on the current one.

I have also found that it will now auto-populate fields that used to be required for input, key/value pairs have been renamed or moved, and seemingly doesn't respect inputs as given.

Training off the exact same post-processed images using the exact same (as far I we can align them) `db_config.json` key/value pairs, on the exact same base checkpoint is giving very poor results compared to previous gens.

I've also noticed that it is once again not segregating the `token` and `class` properly, where it's actually training on a token of `token class`. So the checkpoint expects `rgb123 a woman` instead of the `rgb123` token as anticipated.

I think a lot of this could be avoided by scaling down on feature/option set. They're abstract at best and seem to effect the newest generations without being clear on how or why they impact it and how to fully utilize them.

**Comment by vongillern** [comment]
<not trying to pile on, I know this is all complicated, but I'm having the same issues>. Also, the ckpt creation after N epochs is not working either. I've got it set to 25 in the settings, and have the checkbox set in the DB save tab.

**Comment by jsbach-jung** [comment]
I reverted to this version for now, which still works for me:
https://github.com/d8ahazard/sd_dreambooth_extension/tree/196a62ba7b86aa2da6bcd0b0dc065f41f24a0865

**Comment by Neltherion** [comment]
Should we update via the UI or get this exact version and overwrite the previous downloaded version from the UI?

**Comment by FurkanGozukara** [comment]
> Should we update via the UI or get this exact version and overwrite the previous downloaded version from the UI?

I made a great tutorial now it works fine

https://youtu.be/Bdl-jWR3Ukc
