### ISSUE TITLE
Exception training model: module 'tensorflow' has no attribute 'io'

### ISSUE THREAD

**Issue by wasd2002** [d8ahazard/sd_dreambooth_extension#679]
venv "C:\sdwebui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 3e22e294135ed0327ce9d9738655ff03c53df3c0
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 4ca69a904f5ddd5651d87032b3dca515eea505ba
SD-WebUI revision: 3e22e294135ed0327ce9d9738655ff03c53df3c0

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.

Custom model name is
Starting Dreambooth training...
Initializing dreambooth training...
Cannot raise token length limit above 75 when pad_tokens=False
Replace CrossAttention.forward to use FlashAttention
CUDA SETUP: Loading binary C:\sdwebui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
prepare train images.
80 train images with repeating.
0 reg images.
prepare dataset
Caching latents with buckets...
100%|██████████████████████████████████████████████████████████████████████████████████| 80/80 [00:25<00:00,  3.15it/s]
Bucket 0: Resolution (144, 512), Count: 0
Bucket 1: Resolution (208, 512), Count: 0
Bucket 2: Resolution (272, 512), Count: 2
Bucket 3: Resolution (336, 512), Count: 36
Bucket 4: Resolution (400, 512), Count: 27
Bucket 5: Resolution (464, 512), Count: 2
Bucket 6: Resolution (512, 144), Count: 0
Bucket 7: Resolution (512, 208), Count: 0
Bucket 8: Resolution (512, 272), Count: 1
Bucket 9: Resolution (512, 336), Count: 6
Bucket 10: Resolution (512, 400), Count: 5
Bucket 11: Resolution (512, 464), Count: 1
Bucket 12: Resolution (512, 512), Count: 0
Sched breakpoint is 4000
Traceback (most recent call last):
  File "C:\sdwebui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 569, in start_training
    result = main(config, use_subdir=use_subdir, lora_model=lora_model_name,
  File "C:\sdwebui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1024, in main
    return inner_loop()
  File "C:\sdwebui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 86, in decorator
    return function(batch_size, grad_size, *args, **kwargs)
  File "C:\sdwebui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 539, in inner_loop
    accelerator.init_trackers("dreambooth")
  File "C:\sdwebui\venv\lib\site-packages\accelerate\accelerator.py", line 466, in wrapper
    return func(self, *args, **kwargs)
  File "C:\sdwebui\venv\lib\site-packages\accelerate\accelerator.py", line 1535, in init_trackers
    tracker_init(project_name, self.logging_dir, **init_kwargs.get(str(tracker), {}))
  File "C:\sdwebui\venv\lib\site-packages\accelerate\tracking.py", line 153, in __init__
    self.writer = tensorboard.SummaryWriter(self.logging_dir, **kwargs)
  File "C:\sdwebui\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 246, in __init__
    self._get_file_writer()
  File "C:\sdwebui\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 276, in _get_file_writer
    self.file_writer = FileWriter(
  File "C:\sdwebui\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 75, in __init__
    self.event_writer = EventFileWriter(
  File "C:\sdwebui\venv\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "C:\sdwebui\venv\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow' has no attribute 'io'
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: module 'tensorflow' has no attribute 'io'

**Comment by NeoAnthropocene** [comment]
> delete tensorboard tensorflow tensorflow-io in venv and restart will fix it

It ruined my setup. I won't recommend to do that.

**Comment by wasd2002** [comment]
> > delete tensorboard tensorflow tensorflow-io in venv and restart will fix it
> 
> It ruined my setup. I won't recommend to do that.

Disable other extensions and restart might help?

**Comment by DuskXi** [comment]
> > delete tensorboard tensorflow tensorflow-io in venv and restart will fix it
> 
> It ruined my setup. I won't recommend to do that.

If your computer cuda env still using cuda113, I think maybe you need to check `extentions/sd_dreambooth_extension/install.py`

make sure there is cuda113 checking and installing script in this file not cuda116.

due to my env have cuda113 only, I direct move env to .env and let sd webui create new one to solve this problem ("module 'tensorflow' has no attribute 'io'"), bug was fixed, but it bring some new shit, when I try to use training auto saving ckpt file to draw the character which I trained, I found the ckpt is complete euqal to the source cpkt, which means not any training change into the saving ckpt.

now I change the code in `extentions/sd_dreambooth_extension/install.py` make sure it work with cuda113, the last training is working correctly now.

**Comment by wasd2002** [comment]
> > > delete tensorboard tensorflow tensorflow-io in venv and restart will fix it
> > 
> > 
> > It ruined my setup. I won't recommend to do that.
> 
> If your computer cuda env still using cuda113, I think maybe you need to check `extentions/sd_dreambooth_extension/install.py`
> 
> make sure there is cuda113 checking and installing script in this file not cuda116.
> 
> due to my env have cuda113 only, I direct move env to .env and let sd webui create new one to solve this problem ("module 'tensorflow' has no attribute 'io'"), bug was fixed, but it bring some new shit, when I try to use training auto saving ckpt file to draw the character which I trained, I found the ckpt is complete euqal to the source cpkt, which means not any training change into the saving ckpt.
> 
> now I change the code in `extentions/sd_dreambooth_extension/install.py` make sure it work with cuda113, the last training is working correctly now.
You can check attention layer similarity with this script 
https://huggingface.co/JosephusCheung/ASimilarityCalculatior/tree/main
New version seem got some problem training with prior preservation

**Comment by DuskXi** [comment]
> > > > delete tensorboard tensorflow tensorflow-io in venv and restart will fix it
> > > 
> > > 
> > > It ruined my setup. I won't recommend to do that.
> > 
> > 
> > If your computer cuda env still using cuda113, I think maybe you need to check `extentions/sd_dreambooth_extension/install.py`
> > make sure there is cuda113 checking and installing script in this file not cuda116.
> > due to my env have cuda113 only, I direct move env to .env and let sd webui create new one to solve this problem ("module 'tensorflow' has no attribute 'io'"), bug was fixed, but it bring some new shit, when I try to use training auto saving ckpt file to draw the character which I trained, I found the ckpt is complete euqal to the source cpkt, which means not any training change into the saving ckpt.
> > now I change the code in `extentions/sd_dreambooth_extension/install.py` make sure it work with cuda113, the last training is working correctly now.
> > You can check attention layer similarity with this script
> > https://huggingface.co/JosephusCheung/ASimilarityCalculatior/tree/main
> > New version seem got some problem training with prior preservation

Yes, now I run sd_dreambooth_extention in commit c2fc683, I execute `git reset --hard c2fc683` rollback to rollback to old version.

Beacuse there are not just one problem I got in new version, include the worse drawing performance of trained model that train in new version.
