### ISSUE TITLE
Use directly captions from txt

### ISSUE THREAD

**Issue by TheForgotten69** [d8ahazard/sd_dreambooth_extension#680]
### Kindly read the entire form below and fill it out with the requested information.

**WHAT**
What is this feature of which you speak??
Using txt captions rather than putting the caption as picture name

**WHERE**
From whence did you hear this news?? Provide a URL if possible.
Thelastben/multiple colabs/StableTuner

**HOW**
I suppose that could be the same as where if you have a URL, but if there's an example, hook me up.
Reading the txt file rather than the png/jpg names
**WHEN**
Whenever I get to it. Hold your horses...
Thanks!

**Comment by d8ahazard** [comment]
This is already implemented.
