### ISSUE TITLE
Major quality issues with the latest update. Reverting to previous version possible?

### ISSUE THREAD

**Issue by itacocat** [d8ahazard/sd_dreambooth_extension#689]
Is there a place to download an earlier version of the Dreambooth extension? 

I updated it yesterday from a version a week or two old and trained 4-5 models, some new and some with the same dataset (and settings?) of previously trained models.  The results from each of these new models look horrible now.  4800 steps with 16 dataset images and a 0.000001 learning rate worked really well before. With this current version, the same settings produce images that barely look anything like the subject in my dataset. 

At this point, I would much prefer to go back to on older version, but the update overwrote it. Are those older versions available somewhere? 

FYI. I did try the current Training Wizard settings and the results are still quite poor.
I'm running a 3060 12gb card if that's relevant.

**Comment by itacocat** [comment]
I haven't used LORA, but it's addition to the extension hasn't been an issue for me. Just the results of the training are bad now. I didn't really need to update dreambooth yesterday. It was working fine for me. I was just curious about the latest features. 

@ExponentialML 
That is exactly what I was looking for. The UI and training process now look like the previous version. I'll find out in an hour or two if the results are better too, but I'm guessing they will be. Thanks!

**Comment by jojuMX** [comment]
Hello friend, do you know where I can find the link of the version that already includes LORA but before the current interface? since the recent version does not work LORA with 8GB GPU and the previous interface does..

> @itacocat @Omegadarling
> 
> The easiest way to go back to a certain commit (without using CLI) is to go through the commit tree on Github and download the repository zip at that point in time.
> 
> I've gone back to the day before LoRA was implemented. Simply go to this link: https://github.com/d8ahazard/sd_dreambooth_extension/tree/196a62ba7b86aa2da6bcd0b0dc065f41f24a0865
> 
> Click the code drop down and "Download Zip"
> 
> Replace the current `sd_dreambooth_extension` that you have in your webui extension directory with the one in the zip file you've downloaded. Everything should then work as you had it before. If not, go [here](https://github.com/d8ahazard/sd_dreambooth_extension/commits/main?before=4ca69a904f5ddd5651d87032b3dca515eea505ba+35&branch=main&qualified_name=refs%2Fheads%2Fmain), look for a commit, click the `<>` button of the commit you wish to view, and repeat the aforementioned steps.

**Comment by d8ahazard** [comment]
Fixed with eb51824.
