### ISSUE TITLE
Compatibility with Lora Extension by kohya-ss for auto1111 webui

### ISSUE THREAD

**Issue by breakcore2** [d8ahazard/sd_dreambooth_extension#695]
**WHAT**
There exists an extension that allows for using LoRA models without generating a .ckpt first.
I would be nice to be able to convert LoRA from this trainer to a format usable by the extension.
I'm not exactly sure what their format is like but given the file size differences, they don't seem to be the same format made in this extension.

**WHERE**
https://github.com/kohya-ss/sd-webui-additional-networks 
Working lora models with the extension: https://mega.nz/folder/ZwFDWa6Z#xJuLqs2QXCDrvZqx7reYfw

**Comment by d8ahazard** [comment]
I mean, I looked at the code for LORA a day or two ago, and nothing there has changed, so the .pt files generated by this extension should already be compatible with it.

**Comment by breakcore2** [comment]
@d8ahazard 
Could you verify if the .pt files generated in the lora folder during training example: https://files.catbox.moe/ik3smn.pt, are the .pt files you are referring to?
The file sizes are much different and when loading using kohya-ss there is an error like 
```
Error running process: stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "stable-diffusion-webui\modules\scripts.py", line 338, in process
    script.process(p, *script_args)
  File "stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 129, in process
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight, text_encoder, unet)
  File "stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 73, in create_network_and_apply_compvis
    size = du_state_dict[list(du_state_dict.keys())[0]].size()          # if conv2d size is like [320,4,1,1]
AttributeError: 'list' object has no attribute 'keys'
```
looking at du_state_dict for the attached .pt file, it is a list of tensors while a working .pt file from the mega link above has a dictionary where there are keys like "lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_ff_net_2.lora_up.weight"
