### ISSUE TITLE
Is it possible to implement Accelerate from Hugging Face?

### ISSUE THREAD

**Issue by Omegadarling** [d8ahazard/sd_dreambooth_extension#700]
**WHAT**
'Accelerate' is for training with multiple GPUs.

**WHERE**
[https://huggingface.co/docs/transformers/accelerate](https://huggingface.co/docs/transformers/accelerate)

**HOW**
I'm just an artist who has a healthy appreciation for coding, but yeah, check the URL.

**WHEN**
Well, I have a 10 x 3090 GPU machine and it might be nice to train models faster.

**Comment by 78Alpha** [comment]
Have you tried setting ACCELERATE=true for the webui?

**Comment by d8ahazard** [comment]
This was implemented quite a while ago...

**Comment by Omegadarling** [comment]
@d8ahazard That's great and I kind of see it "working" after I added set ACCELERATE="True" to my webui-user.bat, but do you know of anywhere that someone explains how to do this with Automatic1111?

**Comment by 78Alpha** [comment]
Accelerate itself has very little online that can be searched up. Here is the pull where it was added, that is the well of info for the time being.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4527

**Comment by 78Alpha** [comment]
For the 007guard, take a look at this for some info https://superuser.com/questions/706729/007guard-what-is-it-is-it-dangerous-and-can-it-be-removed

**Comment by Omegadarling** [comment]
> For the 007guard, take a look at this for some info https://superuser.com/questions/706729/007guard-what-is-it-is-it-dangerous-and-can-it-be-removed

Wow. I do have Spybot running, so that's probably spot on! I'm uncommenting the localhost line, but there is a line above that says `# localhost name resolution is handled within DNS itself.` so I'm hoping this doesn't create a conflict somewhere...

**Comment by 78Alpha** [comment]
And adding in for it not finding GPUs, I noticed `'Torch is not able to use GPU; add --skip-torch-cuda-test` in the log. From my experience, it's an issue with accelerate. Running it from a script or anaconda/env gives it trouble. Running the script directly will work or will at least provide an error to work with. Accelerate tends to spit out a message equal to `An error has occurred because an error has occurred`

You can try running accelerate on something from a test venv or your main interpreter and see if it can find the GPUs.

**Comment by Omegadarling** [comment]
I looked it up and you can run a simple Accelerate test that might do what you mentioned (tell you if Accelerate can see my GPUs). Here's what it outputs:

```
> accelerate env

Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.12.0
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.9
- Numpy version: 1.23.3
- PyTorch version (GPU?): 1.13.1+cpu (False)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - main_process_ip: None
        - main_process_port: None
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - downcast_bf16: no
```

**Comment by Omegadarling** [comment]
Could it be something as simple as how old my Nvidia driver is? I'm using 472.47, which came out on 2021.11.10. I had to use an older driver to use RNDR, but RNDR now works with newer drivers. The only reason I haven't updated is that it takes over an hour for the drivers to install. Something about PCIe enumeration just gets exponentially slower with each additional GPU.

**Comment by 78Alpha** [comment]
I couldn't guarantee. I usually drop ACCELERATE all together when it starts complaining about not being able to find a GPU. Some anaconda environments or envs work, others won't. Seemed hit or miss. I myself used new and old drivers. An RTX card and even a Tesla P40.

All from a windows environment of course. 1 colab as well.

**Comment by Omegadarling** [comment]
> I couldn't guarantee. I usually drop ACCELERATE all together when it starts complaining about not being able to find a GPU.

Are you using a different library for multi-GPU or just living with ONLY one GPU?

**Comment by 78Alpha** [comment]
> > I couldn't guarantee. I usually drop ACCELERATE all together when it starts complaining about not being able to find a GPU.
> 
> Are you using a different library for multi-GPU or just living with ONLY one GPU?

I live with using just the 1 GPU
