### ISSUE TITLE
Error "ValueError: Cannot process this value as an Image" at the start of training

### ISSUE THREAD

**Issue by sashaok123** [d8ahazard/sd_dreambooth_extension#708]
Python: 3.10.9
Commit hash: [01a1fee8](https://gitgud.io/AUTOMATIC1111/stable-diffusion-webui/-/commit/01a1fee874e12eb68d849a31bbf177c69ff4cc22)

Dreambooth revision is ****************************************
Diffusers version is 0.0.14.dev 
Torch version is 1.12.1+cu113 
Torch vision version is *.*.*.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**Describe the bug**
At the beginning of the training, the Dreambooth tries to read the images, but an error occurs. (screenshot)
(A clear and concise description of what the bug is)

And in WebUI error Exception training model: No executable batch size found, reached zero.
**Provide logs**
[events.out.tfevents.1672996972.Kappa.9584.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/10359035/events.out.tfevents.1672996972.Kappa.9584.txt)

**Environment**
Native Windows 11

What GPU are you using?
RTX 3070Ti Notebook 8GB

**Screenshots/Config**
<img width="847" alt="image" src="https://user-images.githubusercontent.com/27728380/210971033-acbaf2e5-b1e3-4f7a-bbf5-b1c89d70dc80.png">

[db_config.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/10359031/db_config.txt)

**Comment by alenknight** [comment]
i get this too sometimes.... i just gave up trusting it to create the class images... i make my own first, then point the directory to that.  i've been getting this error for a while now.

**Comment by sashaok123** [comment]
> i make my own first, then point the directory to that. 

How to do it?

**Comment by d8ahazard** [comment]
This should be fixed as of version eb51824.
