### ISSUE TITLE
Requesting a way to use LoRa without having to merge with model

### ISSUE THREAD

**Issue by trihardseven** [d8ahazard/sd_dreambooth_extension#723]
### Kindly read the entire form below and fill it out with the requested information.

**WHAT**
What is this feature of which you speak??
Being able to use LoRa like a hypernetwork

**WHERE**
From whence did you hear this news?? Provide a URL if possible.
https://github.com/kohya-ss/sd-webui-additional-networks
Unfortunately it doesn't work for LoRa models made with this extension

**HOW**
I suppose that could be the same as where if you have a URL, but if there's an example, hook me up.
https://github.com/kohya-ss/sd-webui-additional-networks

**WHEN**
Whenever I get to it. Hold your horses...
🙏

**Comment by Arilziem** [comment]
That's already a thing, check your models > lora directory. I think you need to have "Generate lora weights ..." checked in "Saving" tab, which should be on by default though.

An extra button "Generate lora" might be nice, although there isn't really a reason to turn off the weight generation during training, the files being that small.

**Comment by trihardseven** [comment]
The dreambooth extension can make LoRa models but you have to merge them with the model to use them. It's not already a thing, unless there was a recent update that lets you use the unmodified LoRa without merging like you would an embed/hypernet.

**Comment by Arilziem** [comment]
Sorry, I missed the part in your post that says the lora files do not work with the "additional networks" webui extension.

Maybe making them compatible would be a reasonable request. I thought they would work already (@d8ahazard said something along those lines recently). Do you have an error message, or are they simply not recognized by the extension?

**Comment by trihardseven** [comment]
Yes it's not compatible. I just checked his repo and it seems d8ahazard already contacted kohya to work something out.

**Comment by d8ahazard** [comment]
Native lora support has been added to the UI, so I'm closing this.
