### ISSUE TITLE
Add adieyal's Dynamic Prompts

### ISSUE THREAD

**Issue by Omegadarling** [d8ahazard/sd_dreambooth_extension#728]
### Kindly read the entire form below and fill it out with the requested information.

**WHAT**
A cool repo for randomizing prompts within parameters

**WHERE**
[https://github.com/adieyal/dynamicprompts](https://github.com/adieyal/dynamicprompts)

**HOW**
I read about this on Discord because he made a Colab fork of Dreambooth with his code

**WHEN**
No rush! It's just cool and it would be fun to play with

**Comment by d8ahazard** [comment]
After much rumination, thought, and work re-building the extension, I'm not sure if this is the right fit for the extension.
