### ISSUE TITLE
How to put lr=2e-6 ?

### ISSUE THREAD

**Issue by ivaxsirc** [d8ahazard/sd_dreambooth_extension#75]
By default is 5e-6 and for faces with my experience it's better 2e-6 

Which spec i have to change?

Thanks

**Comment by NeptuneTQ** [comment]
Where it says "Learning Rate" 0.000005, change it to 0.000002

**Comment by d8ahazard** [comment]
You can literally just paste 2e-6 in the web UI, gradio/python will understand this to be the same as 0.000002.

![image](https://user-images.githubusercontent.com/1633844/200955323-ded30772-be8b-4b5a-8367-ef2d11c8eba3.png)

**Comment by ivaxsirc** [comment]
Yes it works, thanks
And thank you very much for the time you dedicate to this incredible extension :)

**Comment by ivaxsirc** [comment]
> You can literally just paste 2e-6 in the web UI, gradio/python will understand this to be the same as 0.000002.
> 
> ![image](https://user-images.githubusercontent.com/1633844/200955323-ded30772-be8b-4b5a-8367-ef2d11c8eba3.png)

Yes it works, thanks
And thank you very much for the time you dedicate to this incredible extension :)
