### ISSUE TITLE
Enhancement: Option to train unet and text encoder separately

### ISSUE THREAD

**Issue by kernelator** [d8ahazard/sd_dreambooth_extension#774]
A good way to lower VRAM requirements and offer better control of how much each network is trained would be to offer a three way toggle to choose if you want to train the whole model, the unet, or the text encoder.

Currently it is only possible to train either the whole model or just the unet, so the only thing needed to be added is to add an option to only train the text encoder.

**Comment by leppie** [comment]
See #795 and #558

**Comment by kernelator** [comment]
Thank you @leppie. I hope you can get this merged soon.
