### ISSUE TITLE
Exception training model: 'CheckpointInfo' object is not subscriptable'

### ISSUE THREAD

**Issue by DaveScream** [d8ahazard/sd_dreambooth_extension#779]
Getting error if use LORA

`#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 17c3864803ebb50615205271de687be96cfc96e8
SD-WebUI revision: ce9827a7c51a9f69bf62c634e35d34fa75ee1833

[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.16+2166360.d20230112 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.

#######################################################################################################

loading Smart Crop reqs from C:\Software\Stable_Diffusion\stable-diffusion-webui\extensions\sd_smartprocess\requirements.txt
Checking Smart Crop requirements.

Launching Web UI with arguments: --api --listen --administrator --xformers
OMP: Info #269: KMP_ALL_THREADS variable deprecated, please use KMP_DEVICE_THREAD_LIMIT instead.
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton.language'
SD-Webui API layer loaded
Error loading script: daam_script.py
Traceback (most recent call last):
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py", line 21, in <module>
    from scripts.daam import trace, utils
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam\__init__.py", line 6, in <module>
    from .trace import *
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam\trace.py", line 13, in <module>
    import numba
  File "c:\Software\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "c:\Software\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "c:\Software\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception`

`Starting Dreambooth training...
Initializing dreambooth training...
Replace CrossAttention.forward to use xformers
Instance Bucket 0: Resolution (512, 512), Count: 4
Class Bucket 0: Resolution (512, 512), Count: 0
Target Bucket 0: Resolution (512, 512), Count: 16
We need a total of 16 images.
Generating 16 class images for training...
Traceback (most recent call last):
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 561, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 973, in main
    return inner_loop()
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 116, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 229, in inner_loop
    count, instance_paths, class_paths = generate_classifiers(args, use_txt2img=use_txt2img, accelerator=accelerator, ui = False)
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 900, in generate_classifiers
    builder = ImageBuilder(args, use_txt2img=use_txt2img, lora_model=args.lora_model_name, lora_weight=args.lora_weight,
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 521, in __init__
    if new_model_info[0] != current_model[0]:
TypeError: 'CheckpointInfo' object is not subscriptable
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: ''CheckpointInfo' object is not subscriptable'.`

**Comment by MV799** [comment]
I had this using normal checkpoint, not lora

**Comment by MmmmBeer** [comment]
Same error generating class images.

**Comment by BigBlueGX** [comment]
I bypassed this error by restarting the whole webui and making sure Generate Classification Images Using txt2img is not checked.

This is a new error that started appearing recently

**Comment by DaveScream** [comment]
"Generate Classification Images Using txt2img"   use currently selected model, not base model you want to finetune. So I think some error happens when main model loads.

**Comment by MmmmBeer** [comment]
Thank you, I advanced to the next error after unchecking "Generate Classification Images Using txt2img"

**Exception generating concepts: 'NoneType' object has no attribute 'device'**

I looked back at my Settings and Concepts. I'll review some more tutorials.

**Comment by twinklepop** [comment]
> Thank you, I advanced to the next error after unchecking "Generate Classification Images Using txt2img"
> 
> **Exception generating concepts: 'NoneType' object has no attribute 'device'**
> 
> I looked back at my Settings and Concepts. I'll review some more tutorials.

I am in the same situation as you. I'd like to be able to generate classification images using txt2img though. This error is new, I was previously able to use this feature.

**Comment by Cichopek123** [comment]
Same thing.

**Comment by 0xv0idx** [comment]
![image](https://user-images.githubusercontent.com/12444059/212652132-4c28b23a-8780-4bdc-8057-44cf10c4783a.png)
lower this if i use 394 im getting same error if i use 95 not getting error

**Comment by Maki9009** [comment]
yeah when i have generate classification images using txt2img, it breaks and gives the 'CheckpointInfo' object is not subscriptable ERROR. but when i uncheck it. it starts to generate classification images in a folder FILLED with Classification images already... AND IT GENERATES AROUND 2900 images for some reason... even though in my concept i wrote 300. so idk whats going on, ive been using the Commit from almost 2 weeks ago and it was working. but now its broken when i click the create diffuser model.

**Comment by mart-hill** [comment]
I tested this yesterday on a folder with 2000 512x512px classification images already in.

It's the part of "Settings" tab
![image](https://user-images.githubusercontent.com/55754730/212718110-ef30b24a-8f53-4e3d-b7b5-57eb7094e7b9.png)


When I had Resolution at 512 - the script would continue, since I had only 3x175 (175 - the amount of training images, 3 class img per 1 train one) required for training.

When I had that set at 768 - of course the script would need to generate 3x175 of classfication images, since it determined that not one of the 2000 ones was at the required size, which is pretty nice. Well, other, that the trouble with actually generating them.😄 

This "Resolution" is actually the size of image the whole model will be trained on, right? It doesn't allow for rectangular source imagery, like 512x768, or 768x1152?

**Comment by BigBlueGX** [comment]
I just found what causes the Exception generating concepts: 'NoneType' object has no attribute 'device' on my settings

Set it to fp16 and not bf16 in the "mixed precision'

**Comment by udiss** [comment]
> 是的，当我使用 txt2img 生成分类图像时，它会中断并给出“CheckpointInfo”对象不可订阅的错误。但是当我取消选中它时。它开始在一个已经装满分类图像的文件夹中生成分类图像......并且由于某种原因它生成了大约 2900 张图像......即使在我的概念中我写了 300 张。所以我知道发生了什么，我一直在使用 Commit from大约 2 周前，它正在工作。但现在当我点击创建漫射器模型时它坏了。

me too！

**Comment by udiss** [comment]
> yeah when i have generate classification images using txt2img, it breaks and gives the 'CheckpointInfo' object is not subscriptable ERROR. but when i uncheck it. it starts to generate classification images in a folder FILLED with Classification images already... AND IT GENERATES AROUND 2900 images for some reason... even though in my concept i wrote 300. so idk whats going on, ive been using the Commit from almost 2 weeks ago and it was working. but now its broken when i click the create diffuser model.

me too！

**Comment by mart-hill** [comment]
> yeah when i have generate classification images using txt2img, it breaks and gives the 'CheckpointInfo' object is not subscriptable ERROR. but when i uncheck it. it starts to generate classification images in a folder FILLED with Classification images already... AND IT GENERATES AROUND 2900 images for some reason... even though in my concept i wrote 300. so idk whats going on, ive been using the Commit from almost 2 weeks ago and it was working. but now its broken when i click the create diffuser model.

Yeah, because the script cannot "see" any classification images of the given size you're going to train your model at, hence it starts generating the right-sized ones, with the (**training images amount**) x (**class images per instance image** amount).
![image](https://user-images.githubusercontent.com/55754730/212743975-0e7a7d26-bba4-4a39-8916-482ea3af1a90.png)

The training images amount is gathered by the script automatically, from the folder you specifiy.

**Comment by Maki9009** [comment]
But it used to not happen on the older commits 😔. Why why can't it be normal. Why it gotta goof around now

**Comment by mart-hill** [comment]
> But it used to not happen on the older commits 😔. Why why can't it be normal. Why it gotta goof around now

Let's have patience! Dreambooth extension will get to be fully compatible with current WebUI eventually.🙂

**Comment by Luna447** [comment]
Still have this issue. Should I simply wait for a fix? Updated both dreambooth and webui but I don't know what to do at this point.

**Comment by eranmahalu** [comment]
I still have this error, can anybody assist?
