### ISSUE TITLE
first time, error sha256

### ISSUE THREAD

**Issue by neosyoshiran** [d8ahazard/sd_dreambooth_extension#789]
not work with, click in train

Restored system models.
Returning result: Exception training model: ''CheckpointInfo' object has no attribute 'sha256''.

because?

**Comment by Marcophono2** [comment]
Same here after updating today. Problem occures when trying to generate class images. I hoped the update would have fixed the other issues with using more than one concept. May be it's fixed. May be not. This new issue prevents me from checking that point. :smile: 
Coming from the Windows world I meanwhile understand the fascination in Linux: IF every incompatibilities among python, pandas, numpy, transformers, xformers, accelerate and so on and so on, are cleared, seeing the code working is like a drug punch! :smile:

**Comment by paulxinzhou** [comment]
Same error here with Ubuntu.

**Comment by rakataprime** [comment]
reverting to commit 17c3864803ebb50615205271de687be96cfc96e8 fixes this

**Comment by jianjian-101** [comment]
Maybe, you used the "Generate Classification Images Using txt2img" in Settings (General module). Thus, you can either enter the prompt to generate class images in txt2img, or close the option.
