### ISSUE TITLE
Keep xformers optimization in training.

### ISSUE THREAD

**Issue by sgsdxzy** [d8ahazard/sd_dreambooth_extension#8]
In the latest webui, it is possible to keep the xformers optimization in TI to allow TI on 6GB, and after the xformers attention block fix the results are no longer bad. 
I did a quick test training keeping xformers, and the results are still good, but further experiments are required, as to:
1. whether xformers would affect the training result (if in a bad way);
2. can xformers actually save VRAM, and by how much, and the performance impact.

**Comment by d8ahazard** [comment]
Yes, I believe if you pass the xformers command-line options, then it should install and be used with this.

I don't know if it will negatively impact training results - but it should definitely save VRAM. My motto is "try and find out!". :D

**Comment by sgsdxzy** [comment]
> Yes, I believe if you pass the xformers command-line options, then it should install and be used with this.
> 
> I don't know if it will negatively impact training results - but it should definitely save VRAM. My motto is "try and find out!". :D

You write an unconditional `sd_hijack.undo_optimization()`, so I have to comment it out.  Maybe adding an option to not undo optimizations?

**Comment by sgsdxzy** [comment]
It seems not to be the case, the optimization in ldm does not affect those used by diffuser, finguring out another way.

**Comment by d8ahazard** [comment]
![image](https://user-images.githubusercontent.com/1633844/200672428-93216ad4-e6e4-40af-ae68-9689b2dcd076.png)
