### ISSUE TITLE
[doc] Hows the API work? (or does it..?)

### ISSUE THREAD

**Issue by arpowers** [d8ahazard/sd_dreambooth_extension#805]
**WHAT**
API docs are missing. They should not be missing.

**WHERE**
check out the readme. 

**HOW**
By writing the docs; or even briefly mentioning them. 

**WHEN**
yesterday... please. 

Note. 
I really like your code though @d8ahazard; you do some excellent python wrangling...

**Comment by d8ahazard** [comment]
Use the /docs endpoint
