### ISSUE TITLE
integer division or modulo by zero

### ISSUE THREAD

**Issue by YakuzaSuske** [d8ahazard/sd_dreambooth_extension#81]
Trying to resume training on a model to continue from 4000 steps to 8000 steps results in this error, fixable by increasing the:
`Save a checkpoint every N steps, 0 to disable`
`Generate a preview image every N steps, 0 to disable`
Higher than 0.

Error completing request
Arguments: ('Itou2', 'C:\\Users\\Hector\\Downloads\\New folder (4)', 'C:\\SUPER_SD_2.0\\stable-diffusion-webui-master\\models\\dreambooth\\New folder', 'ItouAmazon, 1girl', '1girl', '', '', 1.0, 7.5, 40.0, 432, 512, False, True, 1, 1, 18, 4000, 1, True, 1e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 0, 4000, 'fp16', True, "[{'instance_prompt': 'ItouAmazon, 1girl', 'class_prompt': '1girl', 'instance_data_dir': 'C:\\\\Users\\\\Hector\\\\Downloads\\\\New folder (4)', 'class_data_dir': 'C:\\\\SUPER_SD_2.0\\\\stable-diffusion-webui-master\\\\models\\\\dreambooth\\\\New folder'}]", False, True, True) {}
Traceback (most recent call last):
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 871, in main
    save_img = not global_step % args.save_preview_every
ZeroDivisionError: integer division or modulo by zero

**Comment by d8ahazard** [comment]
Please use the issue template to submit issues - this helps me better diagnose the problem, and you to troubleshoot some things yourself - like running into a bug that should have already been fixed. Happy to help, just need to keep it efficient. ;)

**Comment by d8ahazard** [comment]
I'm dumb, this should really be fixed now: 4684f0f
