### ISSUE TITLE
Warning: Bad ui setting value: txt2img/Styles/value: []; Default value "[]" will be used instead.

### ISSUE THREAD

**Issue by ZeroCool22** [d8ahazard/sd_dreambooth_extension#812]
`
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 65d5a78abe8a132d40c88360d77670a6d9b7294e
SD-WebUI revision: 889b851a5260ce869a3286ad15d17d1bbb1da0a7

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
`
![Screenshot_8](https://user-images.githubusercontent.com/13344308/213841180-3d55b2e0-2dcd-43f6-a869-905043cbd2ed.jpg)

Styles can't by applied unless i deactivate the extension:

https://user-images.githubusercontent.com/13344308/213841194-31963176-0055-4183-863a-2e90f4abd6d7.mp4

Can someone tell me how to fix it?

💡 **I need to use this specific version, so upgrade is not an option.**

**Comment by d8ahazard** [comment]
Pretty sure this isn't be, but a setting in your uiconfig.json being changed in the app. Find that line and delete it.
