### ISSUE TITLE
Stuck on "Installing requirements for Web UI"

### ISSUE THREAD

**Issue by YakuzaSuske** [d8ahazard/sd_dreambooth_extension#83]
**Have you read the Readme?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**
Won't load so i can't provide lines.

**Describe the bug**
Yesterday Dreambooth worked fine, however a few minutes ago after i git pulled to get the latest version, the Webui no longer starts with the Dreambooth extension, it's stuck on installing requirements for ui. All of this happened after updating Dreambooth to the latest version. By removing dreambooth from extensions, the UI starts as normal.

**Provide logs**
No crash, failure to start.

**Environment**
Windows, 3080Ti

![image](https://user-images.githubusercontent.com/63294141/200977530-31b3da3e-7a65-46c5-9642-62cc2cf6af72.png)

if opening first and then adding Dreambooth manually and restarting extensions this happens.
![image](https://user-images.githubusercontent.com/63294141/200977736-9eb7dc2c-3d40-4bf9-8010-b560497a881d.png)
it just gets stuck on "Checking Dreambooth torch version".

**Comment by YakuzaSuske** [comment]
Reverting to commit https://github.com/d8ahazard/sd_dreambooth_extension/tree/6f81b3b5be180123efabf1f2780aacf5ba16c95c
works as normal, so for now ill use this commit instead of updated master branch

**Comment by qingweia** [comment]
I have the same problem as you

**Comment by seihoukei** [comment]
It's downloading. Had 5mbps usage for a few minutes, then it installed a TON of libraries.

**Comment by YakuzaSuske** [comment]
> It's downloading. Had 5mbps usage for a few minutes, then it installed a TON of libraries.

Weird because I checked and it wasn't downloading anything. In saw no internet usage being used in task manager and I have fiber with 150mbps.

**Comment by ozzymuppet** [comment]
I had same issue. I only knew it was downloading because my 'net connection was maxing out at 10Mbps

There are so many other issues after you get past this though...

**Comment by YakuzaSuske** [comment]
I'll give it another try but just in case i'll make a backup of my current working Dreambooth extension.

**Comment by mykeehu** [comment]
@YakuzaSuske same here:
https://github.com/d8ahazard/sd_dreambooth_extension/issues/86

I switched back to the https://github.com/d8ahazard/sd_dreambooth_extension/commit/182c76fcfd80e58f11aac2e3a6e220c46363758d build to train.

**Comment by YakuzaSuske** [comment]
> @YakuzaSuske same here: #86
> 
> I switched back to the [182c76f](https://github.com/d8ahazard/sd_dreambooth_extension/commit/182c76fcfd80e58f11aac2e3a6e220c46363758d) build to train.

i just switched to this https://github.com/d8ahazard/sd_dreambooth_extension/tree/6f81b3b5be180123efabf1f2780aacf5ba16c95c
itt works so i'll just stay with it for like a few days till it get resolved.

**Comment by d8ahazard** [comment]
Installer issues are now fixed...

**Comment by alinabel** [comment]
after deleting dreambooth extension works fine

**Comment by imtaha** [comment]
> after deleting dreambooth extension works fine

thank you

**Comment by 15220977645** [comment]
![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/82204041/d732c872-b80a-41ae-9412-8e5ea21bb51c)
I wait a long time
