### ISSUE TITLE
Generate ckpt from LoRA checkpoints are not working

### ISSUE THREAD

**Issue by FurkanGozukara** [d8ahazard/sd_dreambooth_extension#831]
I have reported numerous times but no solution yet

Latest version of automatic1111 and sd_dreambooth_extension

![image](https://user-images.githubusercontent.com/19240467/214073190-96020f73-445d-4332-ab50-f58bce055e6c.png)

![image](https://user-images.githubusercontent.com/19240467/214073250-1b592ef5-ecdc-4e1f-900f-fb8bb268c6a7.png)

**Comment by Plkm160** [comment]
I update [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) and [sd_dreambooth_extension](https://github.com/d8ahazard/sd_dreambooth_extension) to the newest version, and I also encounter the same error. In my situation, the Use LORA option is not enabled, but the error message seems the same.

**Comment by FurkanGozukara** [comment]
> I update [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) and [sd_dreambooth_extension](https://github.com/d8ahazard/sd_dreambooth_extension) to the latest version, and I also encounter the same error. In my situation, the Use LORA option is not enabled, but the error message seems the same.

I made a video it is now fixed

: https://youtu.be/O01BrQwOd-Q

**Comment by Plkm160** [comment]
Thank you for your help! I tried your solution after watching video (runing commands to downgrade CUDA) but the problem remains. Maybe there's something wrong with my Stable Diffusion or DreamBooth environment, but still thank you very much.

**Comment by HanJammer** [comment]
> Thank you for your help! I tried your solution after watching video (runing commands to downgrade CUDA) but the problem remains. Maybe there's something wrong with my Stable Diffusion or DreamBooth environment, but still thank you very much.

It solved the issue for me (but make sure to load the settings once the Model is selected!). However generating ckpt-s should no longer be required in A1111 (it makes little sense, as the whole idea is to cut down the model size plus you can use Lora "embedding" with pretty much every other model). A1111 since 21.01.2023  can work directly with the small LoRA "embeddings" saved in the \A1111\models\Lora directory so generating large ckpts is no longer necessary (!). However it won't work with the small (~5MB .pt files saved there during training for some reason, but works flawlessly with the larger ~144MB models downloaded from CIVITAI - anybody knows how to generate them from the small Dreabooth trained Lora models?).

**Comment by FurkanGozukara** [comment]
> > Thank you for your help! I tried your solution after watching video (runing commands to downgrade CUDA) but the problem remains. Maybe there's something wrong with my Stable Diffusion or DreamBooth environment, but still thank you very much.
> 
> It solved the issue for me (but make sure to load the settings once the Model is selected!). However generating ckpt-s should no longer be required in A1111 (it makes little sense, as the whole idea is to cut down the model size plus you can use Lora "embedding" with pretty much every other model). A1111 since 21.01.2023 can work directly with the small LoRA "embeddings" saved in the \A1111\models\Lora directory so generating large ckpts is no longer necessary (!). However it won't work with the small (~5MB .pt files saved there during training for some reason, but works flawlessly with the larger ~144MB models downloaded from CIVITAI - anybody knows how to generate them from the small Dreabooth trained Lora models?).

it is another script generation as far as i know. not yet with Dreambooth extension i think

**Comment by HanJammer** [comment]
> it is another script generation as far as i know. not yet with Dreambooth extension i think

I already figured it out - by using https://github.com/bmaltais/kohya_ss toolset you can extract the LoRA from .ckpt generated by Dreambooth Extension and this extracted LoRA works fine using the "extra networks" in A1111. It's quick and easy workaround until a proper function is added in the DB Extension.
