### ISSUE TITLE
IndexError: list index out of range.

### ISSUE THREAD

**Issue by ZeroCool22** [d8ahazard/sd_dreambooth_extension#845]
Error when try to create model.

`
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: c544ee11aee0085a7fbb7fdda65898dea2145f0c
SD-WebUI revision: 602a1864b05075ca4283986e6f5c7d5bce864e11

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.16rc425 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes.

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes.

**Have you updated Dreambooth to the latest revision?**
Yes.

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes.

What OS?
Windows 10 x64.

If Windows - WSL or native?
Windows 10 native.

What GPU are you using?
1080 TI.

**Screenshots/Config**

![Screenshot_3](https://user-images.githubusercontent.com/13344308/214334523-00e14467-465a-4ba6-9b0e-c57eb4edcb43.jpg)

**Comment by dsully** [comment]
Something in dc8d1f4f8beb546089abd107db3432e03339c9c0 caused this error.

**Comment by 1NoobPlayer** [comment]
Same problem here! How to fix?

**Comment by goodguygregg-dev** [comment]
Commented line 527 in train_dreambooth.py and now it works

`        #print(f"  Freeze CLIP Normalization Layers: {args.freeze_clip_normalization}")`

**Comment by geocine** [comment]
Refresh browser CTRL+F5 https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7102

**Comment by DarkAlchy** [comment]
I did the hard reset and even restarted everything but this bug is there (along with a shit ton more).  Pretty much this extension is just not working for me with all these bugs in 2.x.  I fell back to 1.5 to have the same bugs.

**Comment by Flonixcorn** [comment]
Same error here:
Traceback (most recent call last):
  File "X:\AI\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "X:\AI\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "X:\AI\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range

**Comment by ZeroCool22** [comment]
> Hard Reload browser CTRL+F5 [AUTOMATIC1111/stable-diffusion-webui#7102](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7102)

Worked!

**Comment by DarkAlchy** [comment]
Glad it worked for you but sure as shit didn't me.

**Comment by sebaxakerhtc** [comment]
> Glad it worked for you but sure as shit didn't me.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7071#issuecomment-1399871630

**Comment by DarkAlchy** [comment]
> > Glad it worked for you but sure as shit didn't me.
> 
> [AUTOMATIC1111/stable-diffusion-webui#7071 (comment)](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7071#issuecomment-1399871630)

Thank you.  I guess this dev is out of control, and while I understand his hatred, and frustration, of Auto for his non caring of the extension devs, the attitude towards us is VERY unwarranted.

**Comment by Flonixcorn** [comment]
ctrl f5 worked thx
