### ISSUE TITLE
OutOfMemoryError: CUDA out of memory with RTX 2080 Ti 

### ISSUE THREAD

**Issue by mebelz** [d8ahazard/sd_dreambooth_extension#846]
Hello all,

I've followed all the recent videos of @SECourses and still I'm getting errors such as these, on both Lora and Dreambooth:

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 10.73 GiB total capacity; 9.05 GiB already allocated; 252.44 MiB free; 9.20 GiB reserved in total by PyTorch)

The latest failures with the following configuration:

[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.13.1+cu116 installed.
[+] torchvision version 0.14.1+cu116 installed.

(I'm on Linux). VRAM is 11GB on the RTX 2080 Ti.

nvidia-smi returns 2888MiB used *before* training, I guess by the currently loaded model.
Is that to be expected? Is it unloaded before Dreambooth training starts?

Would love any ideas I could try or ways to debug this.

Thanks!

**Comment by subpanic** [comment]
Would like to say I'm also running into CUDA OOM with configurations that worked previously even on a 3090. Using typical optimizations (xformers, 8bitadam, gradient checkpointing, mixed fp16 or bf16, etc.) anytime transitioning from checkpoint save/sample generation back to training steps,

**Comment by ye7iaserag** [comment]
This is happening with me too on 3080ti so the extra 1GB of VRAM is not doing me any favor
