### ISSUE TITLE
Can't load tokenizer error while training

### ISSUE THREAD

**Issue by People-11** [d8ahazard/sd_dreambooth_extension#87]
**Have you read the Readme?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
No because latest version of extension [can't launch](https://github.com/d8ahazard/sd_dreambooth_extension/issues/83)

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**
Installing Requirements for Dreambooth
Diffusers version is 0.8.0.dev0.
Copying 8Bit Adam files for Windows.

**Describe the bug**
After clicking Train, I got this error:

Error completing request
Arguments: ('testneko', 'C:\\Users\\People11\\Desktop\\594317380prod', '', 'a cute loli chibi catgirl with grey hair and cyan eyes', '', '', '', 1.0, 7.5, 40.0, 0, 512, False, True, 2, 1, 1, 2000, 1, True, 2e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 500, 500, 'no', True, '', False, True, True) {}
Traceback (most recent call last):
  File "C:\Users\People11\Desktop\stable-diffusion-webui-master\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\People11\Desktop\stable-diffusion-webui-master\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\Users\People11\Desktop\stable-diffusion-webui-master\extensions\sd_dreambooth_extension-6f81b3b5be180123efabf1f2780aacf5ba16c95c\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "C:\Users\People11\Desktop\stable-diffusion-webui-master\extensions\sd_dreambooth_extension-6f81b3b5be180123efabf1f2780aacf5ba16c95c\dreambooth\train_dreambooth.py", line 551, in main
    tokenizer = CLIPTokenizer.from_pretrained(os.path.join(args.working_dir, "tokenizer"))
  File "C:\Users\People11\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1768, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'C:\Users\People11\Desktop\stable-diffusion-webui-master\models\dreambooth\testneko\working\tokenizer'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'C:\Users\People11\Desktop\stable-diffusion-webui-master\models\dreambooth\testneko\working\tokenizer' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
<img width="735" alt="Snipaste_2022-11-10_19-04-38" src="https://user-images.githubusercontent.com/41558215/201037713-1eaefc4c-2ef0-4cc7-9cfb-508970a57f1f.png">

**Environment**
Windows
Native
RTX 3080Ti Laptop 16G

**Comment by xiaolxl** [comment]
请检查一下下方的条目：
1.大模型是否是7g的，目前7g的模型不支持，4g的可以
2.大模型的名字是否有特殊符号或空格
3.webui和db插件是否更新到了最新版本

Please check the following entries:
1. Whether the large model is 7g. Currently, 7g models do not support it, but 4g models can
2. Whether the name of the large model has special symbols or spaces
3. Whether the webui and db plug-ins are updated to the latest version

**Comment by People-11** [comment]
> 请检查一下下方的条目： 1.大模型是否是7g的，目前7g的模型不支持，4g的可以 2.大模型的名字是否有特殊符号或空格 3.webui和db插件是否更新到了最新版本
> 
> Please check the following entries:
> 
> 1. Whether the large model is 7g. Currently, 7g models do not support it, but 4g models can
> 2. Whether the name of the large model has special symbols or spaces
> 3. Whether the webui and db plug-ins are updated to the latest version

是7G模型，看来是不支持了
