### ISSUE TITLE
TypeError: Accelerator.unwrap_model() got an unexpected keyword argument 'keep_fp32_wrapper'

### ISSUE THREAD

**Issue by seoeaa** [d8ahazard/sd_dreambooth_extension#874]
When changing epochs during training, an rtx error 4090 

TypeError: Accelerator.unwrap_model() got an unexpected keyword argument 'keep_fp32_wrapper'

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 645f4e7ef8c9d59deea7091a22373b2da2b780f2
Installing requirements for Web UI
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 9f4d931a319056c537d24669cb950d146d1537b0
SD-WebUI revision: 645f4e7ef8c9d59deea7091a22373b2da2b780f2

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.16rc425 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.

#######################################################################################################

Launching Web UI with arguments: --xformers
SD-Webui API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
`

Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 26
  Num Epochs = 100
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 100
  Total optimization steps = 2600
  Total training steps = 2600
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Adam: False, Prec: fp16
  Gradient Checkpointing: True
  EMA: False
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 2e-06
  V2: True
####################################################
Solution helped  train_dreambooth.py 627 line, I really don't understand if this is correct. 
later I found out that the file  yaml was wrong, probably it was because of this

            with torch.autocast("cuda"):
                s_pipeline = DiffusionPipeline.from_pretrained(
                    args.pretrained_model_name_or_path,
                    unet=accelerator.unwrap_model(unet, keep_fp32_wrapper=True),
                    text_encoder=accelerator.unwrap_model(text_encoder, keep_fp32_wrapper=True),
                    vae=vae,
                    scheduler=scheduler,
                    torch_dtype=weight_dtype,
                    revision=args.revision,
                    safety_checker=None,
                    requires_safety_checker=None
                )

**Comment by tbell85** [comment]
What was the solution?

**Comment by seoeaa** [comment]
> with torch.autocast("cuda"):

Wrapped the function in with torch.autocast("cuda"): above is the sample code

**Comment by ShunsukeYamamoto** [comment]
I met this error, and I can't solve this with the wrapper code @seoeaa suggested.
Is there other solution?

## error code
``` shell
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 20
  Num Epochs = 100
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 100
  Total optimization steps = 2000
  Total training steps = 2000
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Adam: False, Prec: no
  Gradient Checkpointing: True
  EMA: False
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 2e-06
  V2: True
Steps:   5%|▌         | 100/2000 [00:39<12:39,  2.50it/s, loss=0.218, loss_avg=0.305, lr=2e-6, vram_usage=19.7]Traceback (most recent call last):
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 455, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 989, in main
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 121, in decorator
    return function(batch_size, grad_size, prof, log_file, *args, **kwargs)
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 951, in inner_loop
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 589, in check_save
    save_weights(save_image, save_model, save_snapshot, save_checkpoint, save_lora, pbar)
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 630, in save_weights
    args.pretrained_model_name_or_path,
TypeError: Accelerator.unwrap_model() got an unexpected keyword argument 'keep_fp32_wrapper'
Steps:   5%|▌         | 100/2000 [00:42<13:36,  2.33it/s, loss=0.218, loss_avg=0.305, lr=2e-6, vram_usage=19.7]
Restored system models.
```

## environment
OS: Ubuntu 20.04.5 LTS
CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
GPU: GeForce RTX3090

diffusers==0.10.2
transformers==4.25.1
xformers==0.0.16rc421
