### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by kyle215ps3** [d8ahazard/sd_dreambooth_extension#895]
N/A

**Comment by kyle215ps3** [comment]
concepts tab as well
![image](https://user-images.githubusercontent.com/87888660/216612455-529e4e1d-058b-409e-b01e-500078c4e0e2.png)

**Comment by d8ahazard** [comment]
This button right here is your friend:

![image](https://user-images.githubusercontent.com/1633844/216729027-0d729daa-5903-47e9-957c-97bf3a1d74c3.png)
