### ISSUE TITLE
Training has no effect on inference result

### ISSUE THREAD

**Issue by ye7iaserag** [d8ahazard/sd_dreambooth_extension#897]
Been refining a 1.5 model for the last week for a specific style on a 5k sample images dataset,
I'm now at step 750k and I see very little to none difference on the output of the model 
Of course I'm training only one epoch at a time since https://github.com/d8ahazard/sd_dreambooth_extension/issues/835 is still affecting me, and it would crash if I set it to train for more than one epoch after the first one finishes.

Something else I've noticed is that training now is way faster than before (one or two months ago), not sure why...

The commit I'm using is https://github.com/d8ahazard/sd_dreambooth_extension/commit/9f4d931a319056c537d24669cb950d146d1537b0

Here is my config

```
{
    "adamw_weight_decay": 0.01,
    "attention": "xformers",
    "cache_latents": false,
    "center_crop": false,
    "freeze_clip_normalization": false,
    "clip_skip": 1,
    "concepts_list": [
        {
            "class_data_dir": "/app/models/dreambooth/animepencilconcept/classifiers_0",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "class_negative_prompt": "",
            "class_prompt": "illustration style",
            "class_token": "",
            "instance_data_dir": "/app/user/training-data",
            "instance_prompt": "animepencilconcept style",
            "instance_token": "",
            "is_valid": true,
            "n_save_sample": 1,
            "num_class_images": 0,
            "num_class_images_per": 0,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 40,
            "save_sample_negative_prompt": "",
            "save_sample_prompt": "animepencilconcept style",
            "save_sample_template": ""
        }
    ],
    "concepts_path": "",
    "custom_model_name": "",
    "epoch": 150,
    "epoch_pause_frequency": 0.0,
    "epoch_pause_time": 60.0,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "gradient_set_to_none": true,
    "graph_smoothing": 50.0,
    "half_model": false,
    "train_unfrozen": false,
    "has_ema": false,
    "hflip": false,
    "initial_revision": 0,
    "learning_rate": 1e-06,
    "learning_rate_min": 1e-06,
    "lifetime_revision": 0,
    "lora_learning_rate": 0.0002,
    "lora_model_name": [],
    "lora_rank": 4,
    "lora_txt_learning_rate": 0.0002,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant_with_warmup",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "mixed_precision": "bf16",
    "model_name": "animepencilconcept",
    "model_dir": "/app/models/dreambooth/animepencilconcept",
    "model_path": "/app/models/dreambooth/animepencilconcept",
    "num_train_epochs": 1,
    "pad_tokens": true,
    "pretrained_model_name_or_path": "/app/models/dreambooth/animepencilconcept/working",
    "pretrained_vae_name_or_path": null,
    "prior_loss_scale": false,
    "prior_loss_target": 100.0,
    "prior_loss_weight": 0.75,
    "prior_loss_weight_min": 0.1,
    "resolution": 512,
    "revision": 750000,
    "sample_batch_size": 1,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": false,
    "save_embedding_every": 1,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": false,
    "save_preview_every": 1,
    "save_safetensors": false,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "scheduler": "ddim",
    "shuffle_tags": true,
    "snapshot": [],
    "src": "/app/models/Stable-diffusion/stable-diffusion-v1.5-pruned-emaonly.ckpt",
    "stop_text_encoder": 0.75,
    "train_batch_size": 1,
    "train_imagic": false,
    "train_unet": true,
    "use_8bit_adam": true,
    "use_concepts": false,
    "use_ema": false,
    "use_lora": false,
    "use_subdir": true,
    "v2": false
}
```

**Comment by Kahldris** [comment]
Glad I'm not the only one, on recent updates training does absolutely nothing - it produces no errors but also just produces random crap from the instance prompt during samples, and also when testing the model after. It's not learning anything no matter what settings I try. I haven't had time to test previous commits to find the exact one that breaks.

This guy too - https://github.com/d8ahazard/sd_dreambooth_extension/discussions/892#discussioncomment-4865392

**Comment by ye7iaserag** [comment]
Not sure if we should use an older version as recommended here https://www.youtube.com/watch?v=usgqmQ0Mq7g
Or just wait for a fix...

**Comment by Kahldris** [comment]
I did git checkout on both the webui and db extension commits as suggested here and oddly training still isn't having any effect: https://youtu.be/KwxNcGhHuLY

**Comment by ye7iaserag** [comment]
@Kahldris which xformers version are you using because I think we both are using 0.0.16rc425
and according to https://github.com/d8ahazard/sd_dreambooth_extension/discussions/857 it's not working

**Comment by Kahldris** [comment]
> 

Ohh... okay yeah that would be why.  xformers: 0.0.16rc425 :/

**Comment by ye7iaserag** [comment]
Check this https://github.com/huggingface/diffusers/issues/1954#issuecomment-1414020609
This guy got it working with xformers==0.0.17.dev441

**Comment by Shankyoz** [comment]
For the time being before the fix gets pushed, I'm using "flash_attention"  under Settings > Advanced in dream booth,
if you have started to train a model with xformers, it seems not to work when you switch to "flash_attention" so I had to recreate the model and start again, speed isn't too bad not as fast as xformers but still decent, I'm just glad I can train again.

**Comment by ye7iaserag** [comment]
Ok I tested with xformers==0.0.17.dev441 and it is working now
For anyone coming from the future: DO NOT USE xformers: 0.0.16rc425

Closing
