### ISSUE TITLE
xformers is incompatible

### ISSUE THREAD

**Issue by mike4llison** [d8ahazard/sd_dreambooth_extension#90]
Causes multiple errors including the unable to install pytorch and accelerator module not found. After having about five fresh instances to troubleshoot what happened to my original install, I concluded finally that xformers was the culprit. It was running perfectly when I first installed the extension then I heard that xformers would give a performance increase. low and behold I got a crap load of errors and dreambooth no longer runs from the webui tab. I'll post more after further testing. I am using an RTX 3090 with 46GB ram, everything else runs perfectly. I don't know how to uninstall xformers from the A1111 folder structure.

**Comment by d8ahazard** [comment]
Installing and using xformers (especially on Windoze) is a bit outside the scope of this project.
