### ISSUE TITLE
invalid header value

### ISSUE THREAD

**Issue by chengyjonathan** [d8ahazard/sd_dreambooth_extension#917]
### Kindly read the entire form below and fill it out with the requested information.

Python revision: 3.9.5 (default, Jun  4 2021, 12:28:51) 
[GCC 7.5.0]
Dreambooth revision: 21ddebabb47274255d516e655f997d9ddadc0fe4
SD-WebUI revision: 226d840e84c5f306350b0681945989b86760e616

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**
Try to create model dir, code tries to download models from huggingface_hub, returns "Invalid header value b'Bearer xxxxxx\n"

(A clear and concise description of what the bug is)

**Provide logs**

ValueError: Invalid header value b'Bearer hf_XX\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 1249, in extract_checkpoint
    text_model = convert_ldm_clip_checkpoint(checkpoint)
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 651, in convert_ldm_clip_checkpoint
    text_model = CLIPTextModel.from_pretrained(
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2012, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.9/site-packages/transformers/models/clip/configuration_clip.py", line 135, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.9/site-packages/transformers/configuration_utils.py", line 559, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.9/site-packages/transformers/configuration_utils.py", line 635, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing a config.json file
Pipeline or config is not set, unable to continue.
Restored system models.
^CInterrupted with signal 2 in <frame at 0x7fc7d002bb60, file '/home/ubuntu/stable-diffusion-webui/webui.py', line 173, code wait_on_server>

**Environment**

What OS?

Linux

What GPU are you using?
V100

**Comment by chengyjonathan** [comment]
Tried removing the extension and reloading, didn't help.

I've seen this error before, and in the past usually means some incompatibility between pytorch and transformers. But it's possible I've made some error during the setup.

**Comment by selalipop** [comment]
Just ran into this and it was caused by my local credentials for hugging face containing a newline character

To fix it you can either manually correct the file in ~/.cache, or run `huggingface-cli login`
