### ISSUE TITLE
After installation sd_dreambooth_extension ScuNET is missing (not visible)

### ISSUE THREAD

**Issue by sra-tatata** [d8ahazard/sd_dreambooth_extension#924]
`
Python 3.9.12 3.9.2 (default, Feb 28 2021, 17:03:44)
Commit hash: ea9bd9fc7409109adcd61b897abc2c8881161256
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is 21ddebabb47274255d516e655f997d9ddadc0fe4
Diffusers version is 0.10.2
Torch version is 1.13.1+cu117 
Torch vision version is 0.14.1+cu117
`

**After installation with Extensions->Available->sd_dreambooth_extension, ScuNET is not visible in the Extras->Upscaler tab**

**Environment**
What OS? Debian 11
![Zrzut ekranu z 2023-02-08 21-12-11](https://user-images.githubusercontent.com/124823149/217641311-1a28ac18-5c6a-422d-9ed2-2845b2f53c60.png)

**Comment by d8ahazard** [comment]
Please use the templates when submitting an issue, including providing full logs on startup showing any issues. AFAIK, I've done nothing that would affect SKUNet.
