### ISSUE TITLE
Errors upon first installation

### ISSUE THREAD

**Issue by gmaciocci** [d8ahazard/sd_dreambooth_extension#93]
**Have you read the Readme?**

Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

Yes

**Have you updated Dreambooth to the latest revision?**

Yes

**Describe the bug**

Upon first run:

`venv "E:\stable-diffusion\stable-diffusion-Automatic\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: ac085628540d0ec6a988fad93f5b8f2154209571
Installing requirements for Web UI
Error running install.py for extension sd_dreambooth_extension.
Command: "E:\stable-diffusion\stable-diffusion-Automatic\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: Requirement already satisfied: basicsr in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 1)) (1.4.2)
Requirement already satisfied: diffusers in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 2)) (0.3.0)
Collecting fairscale==0.4.4
  Using cached fairscale-0.4.4-py3-none-any.whl
Requirement already satisfied: fonts in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 4)) (0.0.3)
Requirement already satisfied: font-roboto in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 5)) (0.0.1)
Requirement already satisfied: gfpgan in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 6)) (1.3.8)
Requirement already satisfied: gradio==3.9 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 7)) (3.9)
Requirement already satisfied: invisible-watermark in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 8)) (0.1.5)
Requirement already satisfied: numpy in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 9)) (1.23.3)
Requirement already satisfied: omegaconf in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 10)) (2.2.3)
Requirement already satisfied: opencv-python in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 11)) (4.6.0.66)
Requirement already satisfied: requests in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 12)) (2.25.1)
Requirement already satisfied: piexif in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 13)) (1.1.3)
Requirement already satisfied: Pillow in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 14)) (9.2.0)
Collecting pytorch_lightning==1.7.7
  Using cached pytorch_lightning-1.7.7-py3-none-any.whl (708 kB)
Requirement already satisfied: realesrgan in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 16)) (0.3.0)
Requirement already satisfied: scikit-image>=0.19 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 17)) (0.19.2)
Collecting timm==0.4.12
  Using cached timm-0.4.12-py3-none-any.whl (376 kB)
Requirement already satisfied: transformers==4.19.2 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 19)) (4.19.2)
Requirement already satisfied: torch in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 20)) (1.12.1+cu116)
Requirement already satisfied: einops in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 21)) (0.4.1)
Requirement already satisfied: jsonmerge in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 22)) (1.8.0)
Requirement already satisfied: clean-fid in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 23)) (0.1.29)
Requirement already satisfied: resize-right in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 24)) (0.0.2)
Requirement already satisfied: torchdiffeq in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 25)) (0.2.3)
Requirement already satisfied: kornia in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 26)) (0.6.7)
Requirement already satisfied: lark in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 27)) (1.1.2)
Requirement already satisfied: inflection in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 28)) (0.5.1)
Requirement already satisfied: GitPython in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from -r requirements.txt (line 29)) (3.1.27)
Requirement already satisfied: fastapi in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.85.0)
Requirement already satisfied: markdown-it-py[linkify,plugins] in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (2.1.0)
Requirement already satisfied: matplotlib in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (3.6.1)
Requirement already satisfied: paramiko in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (2.11.0)
Requirement already satisfied: pydantic in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (1.10.2)
Requirement already satisfied: jinja2 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (3.1.2)
Requirement already satisfied: fsspec in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (2022.8.2)
Requirement already satisfied: h11<0.13,>=0.11 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.12.0)
Requirement already satisfied: pandas in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (1.5.0)
Requirement already satisfied: pyyaml in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (6.0)
Requirement already satisfied: python-multipart in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.0.4)
Requirement already satisfied: ffmpy in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.3.0)
Requirement already satisfied: orjson in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (3.8.0)
Requirement already satisfied: pydub in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.25.1)
Requirement already satisfied: websockets in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (10.3)
Requirement already satisfied: aiohttp in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (3.8.3)
Requirement already satisfied: pycryptodome in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (3.15.0)
Requirement already satisfied: uvicorn in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.18.3)
Requirement already satisfied: httpx in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.23.0)
Requirement already satisfied: typing-extensions>=4.0.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (4.4.0)
Requirement already satisfied: torchmetrics>=0.7.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.10.0)
Requirement already satisfied: pyDeprecate>=0.3.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.3.2)
Requirement already satisfied: tqdm>=4.57.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (4.64.1)
Requirement already satisfied: tensorboard>=2.9.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (2.10.1)
Requirement already satisfied: packaging>=17.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (21.3)
Requirement already satisfied: torchvision in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from timm==0.4.12->-r requirements.txt (line 18)) (0.13.1+cu116)
Requirement already satisfied: filelock in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from transformers==4.19.2->-r requirements.txt (line 19)) (3.8.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.13,>=0.11.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from transformers==4.19.2->-r requirements.txt (line 19)) (0.12.1)
Requirement already satisfied: regex!=2019.12.17 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from transformers==4.19.2->-r requirements.txt (line 19)) (2022.9.13)
Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from transformers==4.19.2->-r requirements.txt (line 19)) (0.10.1)
Requirement already satisfied: yapf in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from basicsr->-r requirements.txt (line 1)) (0.32.0)
Requirement already satisfied: scipy in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from basicsr->-r requirements.txt (line 1)) (1.9.2)
Requirement already satisfied: lmdb in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from basicsr->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: tb-nightly in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from basicsr->-r requirements.txt (line 1)) (2.11.0a20221011)
Requirement already satisfied: future in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from basicsr->-r requirements.txt (line 1)) (0.18.2)
Requirement already satisfied: addict in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from basicsr->-r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: importlib-metadata in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from diffusers->-r requirements.txt (line 2)) (5.0.0)
Requirement already satisfied: facexlib>=0.2.5 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gfpgan->-r requirements.txt (line 6)) (0.2.5)
Requirement already satisfied: onnxruntime in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from invisible-watermark->-r requirements.txt (line 8)) (1.13.1)
Requirement already satisfied: onnx in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from invisible-watermark->-r requirements.txt (line 8)) (1.12.0)
Requirement already satisfied: PyWavelets>=1.1.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from invisible-watermark->-r requirements.txt (line 8)) (1.4.1)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from omegaconf->-r requirements.txt (line 10)) (4.9.3)
Requirement already satisfied: idna<3,>=2.5 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from requests->-r requirements.txt (line 12)) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from requests->-r requirements.txt (line 12)) (1.26.12)
Requirement already satisfied: chardet<5,>=3.0.2 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from requests->-r requirements.txt (line 12)) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from requests->-r requirements.txt (line 12)) (2022.9.24)
Requirement already satisfied: imageio>=2.4.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from scikit-image>=0.19->-r requirements.txt (line 17)) (2.22.1)
Requirement already satisfied: networkx>=2.2 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from scikit-image>=0.19->-r requirements.txt (line 17)) (2.8.7)
Requirement already satisfied: tifffile>=2019.7.26 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from scikit-image>=0.19->-r requirements.txt (line 17)) (2022.10.10)
Requirement already satisfied: jsonschema in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from jsonmerge->-r requirements.txt (line 22)) (4.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from GitPython->-r requirements.txt (line 29)) (4.0.9)
Requirement already satisfied: numba in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from facexlib>=0.2.5->gfpgan->-r requirements.txt (line 6)) (0.56.2)
Requirement already satisfied: filterpy in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from facexlib>=0.2.5->gfpgan->-r requirements.txt (line 6)) (1.4.5)
Requirement already satisfied: frozenlist>=1.1.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (1.3.1)
Requirement already satisfied: yarl<2.0,>=1.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (1.8.1)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (2.1.1)
Requirement already satisfied: attrs>=17.3.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (22.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (1.2.0)
Requirement already satisfied: smmap<6,>=3.0.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from gitdb<5,>=4.0.1->GitPython->-r requirements.txt (line 29)) (5.0.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from packaging>=17.0->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (3.0.9)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.4.6)
Requirement already satisfied: wheel>=0.26 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.37.1)
Requirement already satisfied: absl-py>=0.4 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (1.2.0)
Requirement already satisfied: setuptools>=41.0.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (59.8.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (2.12.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (1.8.1)
Requirement already satisfied: grpcio>=1.24.3 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (1.49.1)
Requirement already satisfied: werkzeug>=1.0.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (2.2.2)
Requirement already satisfied: markdown>=2.6.8 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (3.4.1)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (3.19.6)
Requirement already satisfied: colorama in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from tqdm>=4.57.0->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.4.5)
Requirement already satisfied: starlette==0.20.4 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from fastapi->gradio==3.9->-r requirements.txt (line 7)) (0.20.4)
Requirement already satisfied: anyio<5,>=3.4.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from starlette==0.20.4->fastapi->gradio==3.9->-r requirements.txt (line 7)) (3.6.1)
Requirement already satisfied: httpcore<0.16.0,>=0.15.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from httpx->gradio==3.9->-r requirements.txt (line 7)) (0.15.0)
Requirement already satisfied: sniffio in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from httpx->gradio==3.9->-r requirements.txt (line 7)) (1.3.0)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from httpx->gradio==3.9->-r requirements.txt (line 7)) (1.5.0)
Requirement already satisfied: zipp>=0.5 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from importlib-metadata->diffusers->-r requirements.txt (line 2)) (3.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from jinja2->gradio==3.9->-r requirements.txt (line 7)) (2.1.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from jsonschema->jsonmerge->-r requirements.txt (line 22)) (0.18.1)
Requirement already satisfied: mdurl~=0.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from markdown-it-py[linkify,plugins]->gradio==3.9->-r requirements.txt (line 7)) (0.1.2)
Requirement already satisfied: mdit-py-plugins in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from markdown-it-py[linkify,plugins]->gradio==3.9->-r requirements.txt (line 7)) (0.3.1)
Requirement already satisfied: linkify-it-py~=1.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from markdown-it-py[linkify,plugins]->gradio==3.9->-r requirements.txt (line 7)) (1.0.3)
Requirement already satisfied: fonttools>=4.22.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from matplotlib->gradio==3.9->-r requirements.txt (line 7)) (4.37.4)
Requirement already satisfied: contourpy>=1.0.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from matplotlib->gradio==3.9->-r requirements.txt (line 7)) (1.0.5)
Requirement already satisfied: python-dateutil>=2.7 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from matplotlib->gradio==3.9->-r requirements.txt (line 7)) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from matplotlib->gradio==3.9->-r requirements.txt (line 7)) (1.4.4)
Requirement already satisfied: cycler>=0.10 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from matplotlib->gradio==3.9->-r requirements.txt (line 7)) (0.11.0)
Requirement already satisfied: flatbuffers in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from onnxruntime->invisible-watermark->-r requirements.txt (line 8)) (22.9.24)
Requirement already satisfied: sympy in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from onnxruntime->invisible-watermark->-r requirements.txt (line 8)) (1.11.1)
Requirement already satisfied: coloredlogs in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from onnxruntime->invisible-watermark->-r requirements.txt (line 8)) (15.0.1)
Requirement already satisfied: pytz>=2020.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from pandas->gradio==3.9->-r requirements.txt (line 7)) (2022.4)
Requirement already satisfied: bcrypt>=3.1.3 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from paramiko->gradio==3.9->-r requirements.txt (line 7)) (4.0.1)
Requirement already satisfied: six in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from paramiko->gradio==3.9->-r requirements.txt (line 7)) (1.16.0)
Requirement already satisfied: pynacl>=1.0.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from paramiko->gradio==3.9->-r requirements.txt (line 7)) (1.5.0)
Requirement already satisfied: cryptography>=2.5 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from paramiko->gradio==3.9->-r requirements.txt (line 7)) (38.0.2)
Requirement already satisfied: click>=7.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from uvicorn->gradio==3.9->-r requirements.txt (line 7)) (8.1.3)
Requirement already satisfied: cffi>=1.12 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from cryptography>=2.5->paramiko->gradio==3.9->-r requirements.txt (line 7)) (1.15.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (5.2.0)
Requirement already satisfied: rsa<5,>=3.1.4 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (1.3.1)
Requirement already satisfied: uc-micro-py in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from linkify-it-py~=1.0->markdown-it-py[linkify,plugins]->gradio==3.9->-r requirements.txt (line 7)) (1.0.1)
Requirement already satisfied: humanfriendly>=9.1 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from coloredlogs->onnxruntime->invisible-watermark->-r requirements.txt (line 8)) (10.0)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from numba->facexlib>=0.2.5->gfpgan->-r requirements.txt (line 6)) (0.39.1)
Requirement already satisfied: mpmath>=0.19 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from sympy->onnxruntime->invisible-watermark->-r requirements.txt (line 8)) (1.2.1)
Requirement already satisfied: pycparser in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from cffi>=1.12->cryptography>=2.5->paramiko->gradio==3.9->-r requirements.txt (line 7)) (2.21)
Requirement already satisfied: pyreadline3 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime->invisible-watermark->-r requirements.txt (line 8)) (3.4.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in e:\stable-diffusion\stable-diffusion-automatic\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (3.2.1)
Installing collected packages: fairscale, timm, pytorch_lightning
  Attempting uninstall: fairscale
    Found existing installation: fairscale 0.4.9
    Uninstalling fairscale-0.4.9:
      Successfully uninstalled fairscale-0.4.9
  Attempting uninstall: timm
    Found existing installation: timm 0.6.7
    Uninstalling timm-0.6.7:
      Successfully uninstalled timm-0.6.7
  Attempting uninstall: pytorch_lightning
    Found existing installation: pytorch-lightning 1.7.6
    Uninstalling pytorch-lightning-1.7.6:
      Successfully uninstalled pytorch-lightning-1.7.6
Successfully installed fairscale-0.4.4 pytorch_lightning-1.7.7 timm-0.4.12

stderr: E:\stable-diffusion\stable-diffusion-Automatic\venv\Scripts\python.exe: Error while finding module specification for 'pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 ' (ModuleNotFoundError: No module named 'pip install torch==1')
Traceback (most recent call last):
  File "E:\stable-diffusion\stable-diffusion-Automatic\extensions\sd_dreambooth_extension\install.py", line 14, in <module>
    subprocess.check_call([sys.executable, '-m', torch_cmd])
  File "C:\Users\Giuliano\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['E:\\stable-diffusion\\stable-diffusion-Automatic\\venv\\Scripts\\python.exe', '-m', 'pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 ']' returned non-zero exit status 1.`

**Environment**
What OS? Windows 11
If Windows - WSL or native? Native
What GPU are you using? 2080Ti

**Comment by sspofy** [comment]
same here

**Comment by d8ahazard** [comment]
Installer routine should now be fixed. Please try again.
