### ISSUE TITLE
dreambooth extension forces requirements install without user consent and causes mess

### ISSUE THREAD

**Issue by vladmandic** [d8ahazard/sd_dreambooth_extension#931]
This extension ships with its own `requirements.txt` and silently installs all of them even if specific versions are already present on the system. If extension is *NOT* compatible with some already installed libraries, it should say so, not silently overwrite them.

Basically, extension as it is ruins my Automatic1111 install until I remove it and reinstall correct system libraries.
This is a really bad behavior from an extension as it should never require different system libraries than the parent app it is supposed to be running in!

    Initializing Dreambooth
    If submitting an issue on github, please provide the below text for debugging purposes:
    
    Python revision: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
    Dreambooth revision: 21ddebabb47274255d516e655f997d9ddadc0fe4
    SD-WebUI revision: 0ec6ded0cb44224a42b6b1ee32b1a56f5e8ed9fd
    
    Checking Dreambooth requirements...
    [+] bitsandbytes version 0.35.0 installed.
    [+] diffusers version 0.10.2 installed.
    [+] transformers version 4.25.1 installed.
    [+] xformers version 0.0.17+7f4fdce.d20230205 installed.
    [+] torch version 2.0.0.dev20230205+cu118 installed.
    [+] torchvision version 0.15.0.dev20230205+cu118 installed.

In my case, I'm running custom compiled `accelerate` and this extension downgraded it without even ever saying anything!
Equally, `diffusers`, `fastapi` and `transformers` are **CORE** libraries used by parent app, extension should never touch them.

**Comment by d8ahazard** [comment]
Diffusers isn't used by the base app at all, and the rest should be kept up to date. If they're not, that's not my concern.

Welcome to the wonderful world of open source, where the rules are made up and points don't matter.

The installation of requirements is a feature provided by the base app. If you dislike this behavior, then my suggestion would be to submit a pull request to the main app and see how far that gets you.

My primary concern is ensuring the extension works properly until I finish making it a stand alone application, at which point, I won't have to deal with these headaches any more.

As such, while I understand your frustration, there isn't a lot I can do aside from work to separate this project from Auto1111, which I've slowly been doing.
