### ISSUE TITLE
multi-gpu training

### ISSUE THREAD

**Issue by yggdrasil75** [d8ahazard/sd_dreambooth_extension#935]
### Kindly read the entire form below and fill it out with the requested information.

**WHAT**
I have 2 different gpus in my computer. they are not nvlinked and I can use automatic1111 to generate simultaneously with them using --device-id x and launching it twice on 2 different ports. however, training only uses the vram of 0, so when everything is running, I cant use my secondary gpu to train, only my primary. the second instance basically just sits there cycling through, saying not enough vram over and over and over again. the only things I would put in the other sections is a link to automatics wiki on commandline params, so… not adding that. 

as an alternative, can shared gpu memory or total gpu memory be used instead of device specific memory? cause my total is 58 gb, shared is 47 gb… though I think this is limited by pytorch probably.

**Comment by 78Alpha** [comment]
Have you tried using Accelerate and configuring it for multiple GPU training? It was added a long time ago but is hit or miss.

**Comment by minienglish1** [comment]
If my understanding is correct, you won't be able to use shared gpu memory or total gpu memory.  However, you should be able to split the batches between the devices, which would increase training speed.  There was some mention of needing deepspeed to enable multi-gpu training.  Accelerate should automatically configure it, if it will work.

I'm considering buying a second rtx 3090 if I can figure out how to make it work.  So, let me know how it works out for you.

Good luck.

**Comment by yggdrasil75** [comment]
> Have you tried using Accelerate and configuring it for multiple GPU training? It was added a long time ago but is hit or miss.

how do I do this? accelerate as far as I know is a programming library for python, not an actual standalone program. is that correct?

**Comment by minienglish1** [comment]
I'm not qualified to be teaching how to use it, but here is some info:

link: https://github.com/huggingface/accelerate/

Accelerate modifies the code to enable multiple gpu use, and some other things.

To enable, modify webui-user-dreambooth.bat, changing ":: set ACCELERATE="True"" to "set ACCELERATE="True""

Then activate the venv and run accelerate config
answer the questions and save the configuration.

When I have time I'll try it because I want to test deepspeed to see if I can get some more free vram.

Good luck

**Comment by SavvaI** [comment]
> I'm not qualified to be teaching how to use it, but here is some info:
> 
> link: https://github.com/huggingface/accelerate/
> 
> Accelerate modifies the code to enable multiple gpu use, and some other things.
> 
> To enable, modify webui-user-dreambooth.bat, changing ":: set ACCELERATE="True"" to "set ACCELERATE="True""
> 
> Then activate the venv and run accelerate config answer the questions and save the configuration.
> 
> When I have time I'll try it because I want to test deepspeed to see if I can get some more free vram.
> 
> Good luck

I tried exactly what you have described on my two cards. The script spawned two processes and even two webgui servers. Then, when I went to the dream booth and started my training it get stalled on the initializing dream booth training and finally filled with

**Comment by minienglish1** [comment]
> I tried exactly what you have described on my two cards. The script spawned two processes and even two webgui servers. Then, when I went to the dream booth and started my training it get stalled on the initializing dream booth training and finally falled with
> 
> ```
> Initializing dreambooth training...
> Exception initializing accelerator: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=2, worker_count=1, timeout=0:30:00)
> No training was completed, deleting log: /home/root/stable-diffusion-webui/models/dreambooth/dndpathfindercharacterrpg_lrx4/logging/dreambooth/events.out.tfevents.1678384269.3bd1fbbfa40e.2987.0
> Restored system models.
> ```


Sorry, I can't directly help you with that.  I don't think it it should spawn two webgui servers, that sounds strange.  Multi-gpu essentially splits a batch across gpus, so I wouldn't think it should spawn two webgui servers.  Maybe check the accelerate config file to see how the gpus are configured.

I currently only have 1 gpu.  I'm waiting for anyone to confirm they successfully trained with a multi-gpu setup before I buy a second card.  As soon as I can confirm multi-gpu works, I'll immediately buy a second card and start testing.
