### ISSUE TITLE
CPU Training Option Missing

### ISSUE THREAD

**Issue by BlidBear** [d8ahazard/sd_dreambooth_extension#936]
### **The issue:**
I don't know if the change for removing the CPU Only training option was accidental or deliberate, as the option description is still on the `readme.md` on here, yet the checkbox to use it is missing since around December the 20th 2022.

### **My argument:**
I request for the option to be re-added, as it is a powerful alternative for people choosing to stay away from renting servers/dedicated and complex cloud services, falling on the claws of Google Colab and Jupyter Notebooks, or not being able to afford hardware that costs an arm and a leg.

### **My failed attempts at solving:**
I tried to use _multiple_ older versions of the extension (from October to December) and it was inviable. The main issue I was having is that model saving in the middle of training didn't work, but other dealbreakers were that the GUI was a confusing mess and options were missing (Like LoRA, safetensors saving and graph generation among many others) while others were buggy or straight up didn't work. I recall a version without all of these caveats existing, but I just can't seem to find it. _(I have the hypothesis that it could be two versions merged in a folder, but I'm not too sure)_

### **What methods I propose to fix it:**
As a temporary fix, it would be nice if someone specified the date of a version that both worked and wasn't a mess in the comments.
For long-term solutions, I propose the following:
1.  @d8ahazard re-adding the feature.
2.  Someone savvy making a dedicated fork based on an older version that works, and cleaning the GUI up (or testing the hypothesis above).
3.  Suggestions for alternative methods that support CPU model training (and a GUI if possible, as doing it through CLI is painful).
4.  An omnipotent coding god that can make the awesome tool that is Dreambooth work on 4GB of VRAM.

Thank you in advance for the help. Cheers.

**Comment by d8ahazard** [comment]
There's a command-line argument to enable forcing CPU... --force-cpu. ;)

**Comment by econundrum** [comment]
--force-cpu doesn't seem to be working for me I still get this

 return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 4.00 GiB total capacity; 3.48 GiB already allocated; 0 bytes free; 3.53 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):

Which suggests it still tries to allocate vRAM
