### ISSUE TITLE
TypeError: CLIPTextModel.forward() got an unexpected keyword argument 'images'

### ISSUE THREAD

**Issue by mogu86** [d8ahazard/sd_dreambooth_extension#94]
What i did wrong ?

You have passed a non-standard module None. We cannot verify whether it has the correct type
Number of class images to sample: 1500.
Generating class images:   0%|                                                                | 0/1500 [00:05<?, ?it/s]
Error completing request
Arguments: ('queeniessc', 'D:\\Stable Diffusion\\stable-diffusion-webui\\Training images\\qq', '', 'photo of QQ94 person', 'photo of a person', '', '', 1, 7.5, 40, 1500, 512, False, True, 1, 1, 1, 1000, 1, True, 1e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 500, 500, 'fp16', True, '', False, True, True) {}
Traceback (most recent call last):
  File "D:\Stable Diffusion\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "D:\Stable Diffusion\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 585, in main
    images = pipeline(example["prompt"]).images
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 271, in __call__
    image, has_nsfw_concept = self.safety_checker(images=image, clip_input=safety_cheker_input.pixel_values)
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: CLIPTextModel.forward() got an unexpected keyword argument 'images'

**Environment**
What OS?
Windows 11

What GPU are you using?
RTX 4090

**Comment by sandropaganotti** [comment]
I've the same issue on my setup too. Will submit an issue

**Comment by Yugaoyao** [comment]
> What i did wrong ?
> 
> You have passed a non-standard module None. We cannot verify whether it has the correct type Number of class images to sample: 1500. Generating class images: 0%| | 0/1500 [00:05<?, ?it/s] Error completing request Arguments: ('queeniessc', 'D:\Stable Diffusion\stable-diffusion-webui\Training images\qq', '', 'photo of QQ94 person', 'photo of a person', '', '', 1, 7.5, 40, 1500, 512, False, True, 1, 1, 1, 1000, 1, True, 1e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 500, 500, 'fp16', True, '', False, True, True) {} Traceback (most recent call last): File "D:\Stable Diffusion\stable-diffusion-webui\modules\ui.py", line 185, in f res = list(func(*args, **kwargs)) File "D:\Stable Diffusion\stable-diffusion-webui\webui.py", line 54, in f res = func(*args, **kwargs) File "D:\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training trained_steps = main(config) File "D:\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 585, in main images = pipeline(example["prompt"]).images File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 271, in **call** image, has_nsfw_concept = self.safety_checker(images=image, clip_input=safety_cheker_input.pixel_values) File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) TypeError: CLIPTextModel.forward() got an unexpected keyword argument 'images'
> 
> **Environment** What OS? Windows 11
> 
> What GPU are you using? RTX 4090

I have solve this problem. you should use clip_processor to get the input but clip_model.
