### ISSUE TITLE
TypeError: 'CheckpointInfo' object is not subscriptable

### ISSUE THREAD

**Issue by eranmahalu** [d8ahazard/sd_dreambooth_extension#952]
Hi, I get this when trying to create a new model:
 if checkpoint_file is None or not os.path.exists(checkpoint_file[0]):
TypeError: 'CheckpointInfo' object is not subscriptable

Please help, thanks

**Comment by d8ahazard** [comment]
This should be resolved with https://github.com/d8ahazard/sd_dreambooth_extension/releases/tag/1.0.11

Feel free to open a new issue if you're still having problems.
