### ISSUE TITLE
Google Colab (free): Crash when creating model because of low RAM (not VRAM) 

### ISSUE THREAD

**Issue by Miraculix200** [d8ahazard/sd_dreambooth_extension#96]
I'm trying to get the extension to run on Google Colab, but it always crashes when I try to create a model (when clicking the "Create" button), because there's only 12GB RAM (not VRAM) available on the free Colab. I'm trying it with the 4GB version 1.5 model.

Is it possible to do something about it?

Alternatively I would try to create the model before launching the webui. So there is a little more RAM free. But from looking at the source it's hard to figure out how to create the model using the commandline.

**Comment by d8ahazard** [comment]
The conversion and extraction are just implementations of [https://github.com/ShivamShrirao/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py](this) and [https://github.com/ShivamShrirao/diffusers/blob/main/scripts/convert_diffusers_to_original_stable_diffusion.py](this).

The directory structure should be:

/SD_DIR/models/dreambooth/MODEL_NAME/working/

Use the first script to extract your checkpoint to diffusers format (or just download them directly from huggingface). You'll also need a config file, which I always just download from here:

https://raw.githubusercontent.com/CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml

Unfortunately, I don't think there's much else I can do to help with RAM usage.

**Comment by d8ahazard** [comment]
Closing, because there's really not much else I can do. Feel free to ask any questions you need regarding manual extraction, I'm happy to help you sort them.

**Comment by Miraculix200** [comment]
Alright. I created a thread about it here:
https://github.com/d8ahazard/sd_dreambooth_extension/discussions/102

Let me know your suggestions when you have time.
