### ISSUE TITLE
422 Unprocessable Entity  value is not a valid dict

### ISSUE THREAD

**Issue by LeonTing1010** [d8ahazard/sd_dreambooth_extension#967]
https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/scripts/api.py#L315
In a path operation, you can declare multiple Form parameters, but you cannot also declare Body fields that you expect to receive as JSON. This is because the request will have the body encoded using application/x-www-form-urlencoded instead of application/json. It's  a part of the HTTP protocol.

**Comment by d8ahazard** [comment]
This should be resolved with https://github.com/d8ahazard/sd_dreambooth_extension/releases/tag/1.0.11

Feel free to open a new issue if you're still having problems.

Also, for future reference, please use the issue templates when submitting issues.
