### ISSUE TITLE
New error after updating dreambooth: TypeError: type str doesn't define __round__ method

### ISSUE THREAD

**Issue by vgaggia** [d8ahazard/sd_dreambooth_extension#991]
`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is d4e2f7d5dc5c67cc6292c8b8137b688a43247c35
Diffusers version is 0.13.1
Torch version is 1.13.1+cu117
Torch vision version is 0.14.1+cu117
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
I even reinstalled Auto completely 
**Have you updated Dreambooth to the latest revision?**
Thats what caused it
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**

**Describe the bug**
I'm simply getting the error: Exception training model: 'type str doesn't define __round__ method'.
After reinstalling dreambooth as it wouldn't let me update it for some reason.

**Provide logs**
Bucket 0 (384, 768, 0) - Instance Images:  97 | Class Images: 0 | Max Examples/batch:   97
Bucket 1 (576, 768, 0) - Instance Images: 145 | Class Images: 0 | Max Examples/batch:  145
Bucket 2 (768, 384, 0) - Instance Images:  68 | Class Images: 0 | Max Examples/batch:   68
Bucket 3 (768, 576, 0) - Instance Images: 164 | Class Images: 0 | Max Examples/batch:  164
Bucket 4 (768, 768, 0) - Instance Images:  82 | Class Images: 0 | Max Examples/batch:   82
Total Buckets 5 - Instance Images: 556 | Class Images: 0 | Max Examples/batch: 556
Caching latents...: 100%|███████████████████████████████████████████████████████████| 556/556 [00:01<00:00, 515.02it/s]
Total images / batch: 556, total examples: 556
Caching latents...: 100%|███████████████████████████████████████████████████████████| 556/556 [00:01<00:00, 337.47it/s]
Total dataset length (steps): 556
Initializing bucket counter!
Traceback (most recent call last):
  File "G:\Auto\auto2\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 555, in start_training
    result = main(use_txt2img=use_txt2img)
  File "G:\Auto\auto2\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1133, in main
    return inner_loop()
  File "G:\Auto\auto2\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 123, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "G:\Auto\auto2\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 564, in inner_loop
    text_encoder_epochs = round(args.num_train_epochs * stop_text_percentage)
TypeError: type str doesn't define __round__ method
Restored system models.

**Environment**
Windows 11 native

What GPU are you using?
3090 24gb

**Screenshots/Config**
CONFIG BELOW
{
    "adamw_weight_decay": 0.01,
    "attention": "xformers",
    "cache_latents": true,
    "clip_skip": 1,
    "concepts_list": [
        {
            "class_data_dir": "G:\\Datasets\\EeveeClass",
            "class_guidance_scale": 5.5,
            "class_infer_steps": 10,
            "class_negative_prompt": "",
            "class_prompt": "[filewords]",
            "class_token": "[filewords]",
            "instance_data_dir": "F:\\EveryDream2\\EveryDream2trainer\\input",
            "instance_prompt": "[filewords]",
            "instance_token": "[filewords]",
            "is_valid": true,
            "n_save_sample": 0,
            "num_class_images_per": 0,
            "sample_seed": -1,
            "save_guidance_scale": 1,
            "save_infer_steps": 10,
            "save_sample_negative_prompt": "",
            "save_sample_prompt": "[filewords]",
            "save_sample_template": ""
        }
    ],
    "concepts_path": "",
    "custom_model_name": "",
    "deis_train_scheduler": false,
    "deterministic": false,
    "ema_predict": false,
    "epoch": 0,
    "epoch_pause_frequency": 0,
    "epoch_pause_time": 0,
    "freeze_clip_normalization": false,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "gradient_set_to_none": true,
    "graph_smoothing": 50,
    "half_model": false,
    "train_unfrozen": true,
    "has_ema": false,
    "hflip": false,
    "infer_ema": true,
    "initial_revision": 0,
    "learning_rate": 7e-07,
    "learning_rate_min": 1e-06,
    "lifetime_revision": 0,
    "lora_learning_rate": 0.0001,
    "lora_model_name": "",
    "lora_unet_rank": 4,
    "lora_txt_rank": 4,
    "lora_txt_learning_rate": 5e-05,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant_with_warmup",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "mixed_precision": "bf16",
    "model_name": "Sylveon3",
    "model_dir": "G:\\Auto\\auto2\\models\\dreambooth\\Sylveon3",
    "model_path": "G:\\Auto\\auto2\\models\\dreambooth\\Sylveon3",
    "num_train_epochs": 100,
    "offset_noise": 0,
    "optimizer": "Lion",
    "pad_tokens": true,
    "pretrained_model_name_or_path": "G:\\Auto\\auto2\\models\\dreambooth\\Sylveon3\\working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_scale": false,
    "prior_loss_target": 100.0,
    "prior_loss_weight": 1,
    "prior_loss_weight_min": 0.1,
    "resolution": 768,
    "revision": 0,
    "sample_batch_size": 5,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": true,
    "save_ckpt_during": true,
    "save_ema": true,
    "save_embedding_every": 25,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": true,
    "save_preview_every": 5,
    "save_safetensors": false,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "scheduler": "DDIM",
    "shuffle_tags": false,
    "snapshot": "",
    "split_loss": true,
    "src": "G:\\Auto\\auto2\\models\\Stable-diffusion\\bkp\\wd-1-3-penultimate-ucg-cont.ckpt",
    "stop_text_encoder": "8Bit Adam",
    "strict_tokens": false,
    "tf32_enable": false,
    "train_batch_size": 3,
    "train_imagic": false,
    "train_unet": true,
    "use_concepts": false,
    "use_ema": true,
    "use_lora": true,
    "use_lora_extended": true,
    "use_subdir": false,
    "v2": false
}

**Comment by gammagoat** [comment]
There is something wrong with gradio there. In the UI, explicitly set stop_text_encoder and save and it will resolve.

**Comment by ArrowM** [comment]
^ that should fix it. Or you can manually change the value of the `stop_text_encoder` in the db_config.json file. I can see it's value was somehow set to "8Bit Adam", when it should be a Float.

**Comment by Grayfaux** [comment]
> There is something wrong with gradio there. In the UI, explicitly set stop_text_encoder and save and it will resolve.

Where is this located because I can't seem to find it. Thanks

**Comment by gammagoat** [comment]
It is under Settings tab, in the Advanced section at the bottom. There is a slider under the Train UNET checkbox with a number box. Setting this any value will resolve the error.

**Comment by Steppr** [comment]
I just had the exact same Issue. It also put "8Bit Adam" in the stop_text_encoder field whenever saving my settings. I replaced it with "0.0" manually and that fixed it. No idea what that setting does though, I hope 0 is an ok value. I couldn't find the setting in the UI, had to edit the settings file. 
I had also just reinstalled dreambooth because refused to update for me - so that's a pattern.

**Comment by Connor9994** [comment]
> It is under Settings tab, in the Advanced section at the bottom. There is a slider under the Train UNET checkbox with a number box. Setting this any value will resolve the error.

Been looking around to fix this for ages! Thanks a ton. My slider was set to .5 but the box didn't have numbers in it. When I moved it slightly it displayed a number (.51) and now trains!

**Comment by BaronVonNFt33** [comment]
For some reason, I have no "Advanced" section;   when i do "show all pages" and Ctrl-F for "train" cannot find.   Search for UNET...zero instances.

**Comment by ArrowM** [comment]
It's within the Dreambooth tab (not the A1111 settings)
